cloudquery/cloudquery

example.aws_cis.policy.yml
CIS 1.10 is titled `Ensure IAM password policy prevents password reuse` and the benchmark from AWS should pass as long as there are fewer than 24 remembered passwords.
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-1.10
=> fix name and logic for AWS CIS 1.10

cmd/policy.go
See #13
This also fixes the `gen policy` command for `aws_cis`
=> Fixing policy generation for CIS 1.10

cloudqueryclient/client.go
Prior to this fix, functional options were dropped in the constructor `NewLogger`.  Now they are applied to the logger post-configuration.  Note that verbose could be implemented as a zap.Option to create a uniform interface.
=> Apply ...zapcore.Option during logger creation

providers/aws/ecr/images.go
Hi,
There's three fixes here, firstly adding the constraint on delete cascade to resolve when deleting the existing data;
```
2021/01/09 01:40:13 /go/pkg/mod/github.com/cloudquery/cloudquery@v0.7.7/database/database.go:97 pq: update or delete on table "aws_ecr_repositories" violates foreign key constraint "fk_aws_ecr_repositories_images" on table "aws_ecr_images"
```
Secondly, refactoring the processing loop so that `c.db.InsertOne(tRepo)` is only called once per repository.  Previously, if there were multiple pages of images, this would create a new repository entry in the database.
Finally, resetting `describeImagesInput.NextToken = nil` as the NextToken for the next repo used the previous repositories images last token which would cause a `InvalidParameterException`.
=> Fix AWS/ECR Repository duplicate entries

cmd/fetch.go, cmd/query.go, cmd/root.go, go.mod
This adds support for environment variables with `CQ_` prefix to cloudquery.
Currently supports:
```
CQ_DSN
CQ_DRIVER
CQ_CONFIG_PATH
CQ_QUERY_PATH
```
=> Add support for CQ_ env variable via viper

README.md
It's `gcp_storage_bucket_policy_binding_members` not `gcp_storage_bucket_policy_bindings_members`.
=> fix table name in sample code

cloudqueryclient/client.go
Instead of writing each query result as an individual object line by line, write the whole thing at once as a list.
Previously the output would have been written to look like:
```
{}
{}
```
which isn't valid JSON. Now it will be written as:
```
[
{},
{}
]
```
This should fix #48
=> fix: query --output should write file as list of json objects

providers/aws/iam/policies.go, providers/aws/iam/roles.go
I wanted to fetch the actual policy documents so that I can query the contents of them, for example filter on all policies that have AssumeRole in them. Since we have 17k+ policies in our accounts doing a call for each of them is probably not practical.
The solution for this the `get-account-authorization-details` call that allows you to fetch all the users, groups, roles and policies of an account in a single call. (https://docs.aws.amazon.com/cli/latest/reference/iam/get-account-authorization-details.html)
I've implemented this in this PR for just the policies call, since all the fields matched perfectly, but of course it can be used to replace (parts of) the users, groups and roles implementations too. It will probably make it faster. The issue is there are slight differences in the …
=> Use account authorization details to fetch policy documents

providers/aws/provider.go
I wanted to be able to fetch all my accounts at the same time with such config.yml :
```
providers:
- name: aws
accounts: # Optional. if you want to assume role to multiple account and fetch data from them
- id: production
- id: sharedstorage
- id: test-us
- id: test-eu
- id: test-rds
- id: prod-kms
- id: uballot
- id: mmkpm
```
Working like a charm, however with sqlite when fetching the eighth account I've encountered io limits or concurrency issue. I will open a proper issue for this.
=> add AWS multi account.id fetch capability

providers/aws/ecs/services.go
Before this change, the `NextToken` field is not reset for each cluster which can cause `ListServices` to return incomplete results. This change resets the `NextToken` field for each cluster.
=> Fix ECS list services call

cmd/root.go, plugin/hub/hub.go, plugin/plugin.go
It may be desirable in some environments to use a different directory for plugins. This change adds an environment variable `CQ_PLUGIN_DIR` that if present will be used as the directory for plugins.
If the environment variable is not set, the default behavior of using the current script directory is preserved.
=> Optionally read in provider dir from environment

config/config.go, config/config_test.go
Currently the native Json unmarshaling will not parse out the `Rest` portion of each of the providers. 
`encoding/json` does not have an `inline` struct tag similar to `yaml` so there is no way to parse the extra data from json without a custom unmarshaler.
I'm proposing an implementation of a custom json unmarshaler here, also added some basic tests.
=> bugFix: Add custom unmarshaler for json config

deploy/aws/terraform/bucket.tf, deploy/aws/terraform/cloudwatch.tf, deploy/aws/terraform/database.tf, deploy/aws/terraform/function.tf, deploy/aws/terraform/tasks/us-east-1/input.json, deploy/aws/terraform/vpc.tf, deploy/lambda.go
This PR includes three changes to the AWS Lambda deployment.
1. Adds a cloudwatch trigger
_This shows an example of how one can schedule and run multiple Cloudquery configs in parallel on Lambda_
2. Migrates the Aurora database to Postgres
3. Uses the new `CQ_PLUGIN_DIR` environment variable to allow the plugin architecture to work in Lambda
It also adds an S3 bucket in terraform for use with the lambda function deployment
=> Lambda: add cloud watch trigger, migrate to postgres, allow plugins

.goreleaser.yaml
This change updates the GoReleaser configuration file adding support for installing a completion script automatically for either Bash, ZSH or FIsh shells. This will improve the user experience a little bit for anyone who uses shell completion and also installed CloudQuery using Homebrew.
Additionally, correct indentation of the Go ldflags, and disable Go's garbage collection during build for a potential savings in the overall build time.
=> Add support for installing completion scripts for supported shells using Homebrew recipe

pkg/plugin/registry/hub.go
Without checking the HTTP code, an empty file is always created. And only the next time the CQ is launched, the provider's validation error occurs (the file of the same name is on the disk, but of zero length).
=> Fail provider download on Not Found http error

README.md
Most of the documentation now exists at https://hub.cloudquery.io per provider. Thus no need to duplicate it and maintain it in the main readme anymore apart from maybe one basic example.
=> Update docs to reflect hub.cloudquery.io

internal/file/file.go, pkg/config/convert/converter.go, pkg/config/convert/stdlib.go, pkg/config/convert/stdlib_test.go, pkg/config/policy_parser.go, pkg/config/policy_parser_test.go, pkg/policy/manager.go, pkg/policy/manager_test.go
This PR implements the `file` function into the HCL parser that allows policies to specify an external path.
It also fixes two small issues with the policy execution that I noticed (error output malformed and repository path is evaluated before repository checkout).
=> Implement file HCL function

README.md
Fix link to `New Provider` documentation
=> Update Doc link

cmd/completion.go, cmd/drift.go, cmd/fetch.go, cmd/options.go, cmd/policy_download.go, cmd/policy_run.go, cmd/provider.go, cmd/util.go
IMHO the `SilenceUsage` option isn't the real solution to this kind of problem as it bringt other drawbacks.
=> Fixes #250 - Do not print unrelated help string on cmd error

go.mod, go.sum, modules/configs/drift.hcl, pkg/module/drift/config.go, pkg/module/drift/config_parser.go, pkg/module/drift/drift.go, pkg/module/drift/terraform.go
Subresources are (often multiple) related resources contained in a terraform.Instance as attributes, under an array-typed key.
Issues:
- Some arrays are in fact "sets", ie. the order doesn't matter. We currently can't include them as PKs (identifiers) ~and can't reliably match them in deep mode either~. To fix this I tried sorting them handling TF values, but Postgres returns them unsorted so that didn't help... Looked for a function to sort an `ARRAY` type in PG, but what's recommended is to use `UNNEST()` and then do a subquery to order and `ARRAY_AGG`, which seemed to be too much. (`aws_cloudfront_distribution_cache_behaviours`)
- "root." syntax and handling in `parseTerraformInstance` is not very nice, need better handling/jsonpath to do this for us ideally...
- ~Some type issues (int …
=> Handle subresources

cmd/drift.go, pkg/client/client.go, pkg/config/config_parser.go, pkg/module/drift/drift.go, pkg/module/drift/drift.hcl, pkg/module/drift/model.go, pkg/module/manager.go, pkg/module/types.go, pkg/ui/console/client.go, pkg/ui/console/model.go
`--profile` and profile selection is now done by the console client. (Still, we don't load/parse it unless we're invoking a module)
=> Clean up module profile handling

pkg/config/parser.go, pkg/module/drift/config_parser.go, pkg/module/drift/config_parser_test.go
ie. set `CQ_VAR_ACCOUNT_ID=123` and use `ACCOUNT_ID` in the `aws` block as the variable.
=> Enable environment variables in drift config

pkg/module/drift/drift.go, pkg/module/drift/drift_test.go
It's in the docs but we forgot to actually implement it
=> drift: Fix for wild resource on wild provider application for user supplied config

README.md
Added 
```
?sslmode=disable
```
to fetch command to make the Quick Start process easier to complete for a new person because the process currently errors out saying 
```
pq: SSL is not enabled on the server
```
=> Update Quick Start

pkg/module/drift/drift.go, pkg/module/drift/s3object.go, pkg/module/drift/s3object_test.go
To keep things simple, only partial support (`*` and `**`) in the S3 backend (no character ranges with `[` and `]`)
Local filesystem glob matching is done using `afero.Glob`, which still uses `filepath.Match` underneath so it should be compatible with `filepath.Glob`.
Implements #281.
=> drift: Glob support in source configuration

pkg/client/client.go, pkg/policy/execute.go
Addresses #304 
Addresses #318 
Before fix:
``` bash
% go run main.go policy run --enable-console-log
11:31AM INF logging configured consoleLog=true fileLogging=true fileName=cloudquery.log jsonLogOutput=false logDirectory=. maxAgeInDays=3 maxBackups=3 maxSizeMB=30 verbose=false
11:31AM INF Policies to run policies=[{"Name":"public-ips","Source":"../aws/foundational_security/policy.hcl","SubPath":"","Type":"local","Version":"latest"}]
11:31AM INF Starting policies run...
11:31AM INF Loading policy args={"Name":"public-ips","Source":"../aws/foundational_security/policy.hcl","SubPath":"","Type":"local","Version":"latest"}
11:31AM INF Finished policies run...
```
after fix:
``` bash
% go run main.go policy run --enable-console-log
11:31AM INF logging configured consoleLog=true …
```
=> Improve Logging For Errors

pkg/module/drift/drift.hcl
Required to merge before the new release...
* Renamed columns of `aws_cloudfront_distributions` behaviour -> behavior.
=> Drift config: aws_cloudfront_distribution_cache_behaviours

cmd/root.go, cmd/telemetry.go, internal/telemetry/context.go, internal/telemetry/error.go, internal/telemetry/telemetry.go, pkg/client/client.go
~Keeping `--debug-telemetry` to not break any defaults, could also remove that.~
Remove error redaction from telemetry, count fixes. `--debug-telemetry` now just changes the log level for the OTEL SDK.
=> Always debug telemetry

cmd/root.go, cmd/sentry.go, cmd/util.go, internal/telemetry/error.go, pkg/client/client.go
To keep the panic in the console (`sentry.Recover()` swallows it) needed to take custom recovery actions.
Switched to Sentry's sync HTTP transport in the meantime to get rid of `flushSentry` nuances.
Closes #345.
Oh also added fingerprinting (traceID from otel) so that fetch errors are hopefully grouped.
=> Report panics to Sentry

cmd/init.go
The cloudquery init supports:
cloudquery aws
cloudquery aws gcp
though in one of the examples is:
cloudquery aws,gcp,azure which will result an error
=> Improve a bit misleading help message for cloudquery init

go.mod, pkg/client/client.go, pkg/ui/console/client.go
Closes: #364 
Output:
```
cloudquery % go run main.go fetch
Initializing CloudQuery Providers...
✓ cq-provider-aws@v0.8.4 verified    0s  100 %
Finished provider initialization...
Upgrading CloudQuery providers [aws]
✓ Upgraded provider aws to v0.8.4 successfully.
Finished upgrading providers...
Starting provider fetch...
⚠️ cq-provider-aws@latest diagnostics: 18    3s [===========>--------------------------------------------------|  Finished Resources: 23/120
^C2021/12/27 12:26:22 28 Ctrl-c
⚠️ cq-provider-aws@latest diagnostics: 47    3s [============================>---------------------------------|  Finished Resources: 57/120
Fetch Diagnostics for provider aws:
Resource: emr.clusters Type: Access Severity: Warning
Summary: EMR: ListClusters - User: …
```
=> Exclude context Cancelled

cmd/util.go, internal/telemetry/context.go, internal/telemetry/error.go
Once in end of span (with `spanEnder` business) and the other in the cli handler.
=> Prevent reporting of errors to Sentry twice

deploy/lambda.go, pkg/config/config_parser.go, pkg/config/parser.go
Description is still wip:
As we removed the jsonconverter we didn't update the lambda correctly yet.
Related to https://github.com/cloudquery/terraform-aws-cloudquery/pull/9
Also relates to this - https://github.com/hashicorp/hcl/issues/294
Supporting both json and HCL is possible but it's a real hassle and room for edge-cases so I suggest dropping this for not completly sticking to HCL unless in the future this will be requested somehow again.
=> fix lambda json conversion

pkg/policy/source_test.go
Since the `policy_v3` branch is no more the tests were failing.
=> Fix policy source tests using existing tag

cmd/policy_run.go, deploy/lambda.go, pkg/client/client.go, pkg/ui/console/client.go, pkg/ui/console/model.go
Remove confusing and unused flags:
stop-on-failure
fail-on-violations
Reasoning:
If there is an internal error such as incorrect version, missing tables, there is no reason really to not stop, so this just creates additional documentation and not-intuitive default behaviour (such as not returning 1 on internal error)
`stop-on-failure` - policies run very fast so I would eliminate that flag as well, just have a default behaviour that shows all the results.
Why I started it:
In the CI we always had to add special flags to detect errors and sometimes we missed errors because the CI didn't fail on internal errors.
=> fix: Exit with 1 on policy error

internal/persistentdata/persistentdata.go, pkg/plugin/registry/hub.go
Downgrade "failed to read plugin directory" message to debug level.
Create directories when saving persistent data files.
Closes #410
=> feat: Adjust log messages when .cq dir is absent

pkg/client/client.go, pkg/config/provider.go
expose max_parallel_resource_fetch_limit to allow users to limit amount of concurrent resources fetched by provider, if 0 is provider or attribute is not defined it acts as if no limit is set
=> feat: Expose max_parallel_resource_fetch_limit

cmd/root.go, cmd/ulimit_unix.go, cmd/util.go
The ulimit in Unix environment will be increased automatically.
Currently, we fail a lot of runs due to low limits.
In case of an error, we just log and continue.
=> feat: Increase ulimit in unix environment

go.mod, go.sum, pkg/module/drift/drift.hcl, pkg/module/drift/terraform.go
`billing_groups`, `ca_certificates` and `streams` aren't supported (as we don't have data for them in the tfstate I received)
Looks like those resources aren't supported in TF yet
=> feat: Update drift for AWS IOT resources

pkg/client/client.go, pkg/client/database/database.go, pkg/client/database/postgres/executor.go
=> fix: DB version validation shouldn't block on vanilla PG

cmd/root.go, deploy/lambda.go, internal/persistentdata/persistentdata.go, internal/persistentdata/persistentdata_test.go, pkg/client/version_test.go, pkg/config/config_parser.go, pkg/config/parser_test.go
Implements #446.
```
rootCmd.PersistentFlags().String("data-dir", "./.cq", "Directory to save and load CloudQuery persistent data to (env: CQ_DATA_DIR)")
rootCmd.PersistentFlags().String("plugin-dir", "./.cq/providers", "Directory to save and load CloudQuery plugins from (env: CQ_PLUGIN_DIR)")
rootCmd.PersistentFlags().String("policy-dir", "./.cq/policies", "Directory to save and load CloudQuery policies from (env: CQ_POLICY_DIR)")
```
Little bit too much. Maybe migrate away from plugin-dir and policy-dir in the future
=> feat: Configurable data folder

pkg/client/client.go, pkg/client/client_test.go, pkg/plugin/registry/hub.go, pkg/plugin/registry/hub_test.go, pkg/plugin/registry/organization.go, pkg/ui/console/client.go
* Remove double import of a package
* Rewrite Client.CheckForProviderUpdates test
Rewrite the test so that it does not depend on database availability
and network access to a git repo.
* Add a unit test for Hub.CheckProviderUpdate
* A few cleanups
* introduce ProviderRepoName function
* drop unused Hub.getLatestReleaseVersion
=> feat: Small improvements

cmd/sentry.go, pkg/client/client.go
The commented part will be removed once we finalize on a convention
=> feat: Use provider name/version as exception type when reporting diagnostics to Sentry

cmd/init.go, pkg/ui/console/fixtures/config.yaml
easier to switch to `tsdb://` etc.
Also https://github.com/cloudquery/docs/pull/92
=> fix: Use URI DSNs

pkg/client/client.go, pkg/client/fetch.go
if we have many diagnostics in the fetch summary it will cause an OOM memory insert failure, we remove the diagnostics from the summary, as they are logged regardless.
=> fix: Fetch summary SQL state 54000

pkg/policy/execute.go, pkg/policy/execute_test.go
Also removed the "multilayer policies with invalid selector" test (since now,
the "executor" won't actually return an error in the "invalid selector" case - it
will be up to the "manager").
=> fix: Don't return an error if encountering an empty subpolicy

.github/workflows/history_test.yml, internal/test/test_history_config_oldversion.hcl, pkg/client/database/timescale/ddlmanager.go, pkg/client/database/timescale/timescale.go, pkg/module/manager.go
Views need to be dropped before any migrations can be applied (except creating new tables)
=> fix: Upgrade schema in history mode

cmd/init.go, go.mod, go.sum, pkg/config/parser.go, pkg/module/drift/drift.go, pkg/module/manager.go, pkg/module/types.go, pkg/plugin/registry/hub.go, pkg/plugin/registry/organization.go
=> fix: Init command cleanup

pkg/client/client.go, pkg/policy/snapshots.go
When restoring a snapshot prior to copying the data drop all FK requirements
=> fix: Foreign Keys in Snapshots

.github/workflows/lint_golang.yml, cmd/drift.go, internal/sort/sort.go, internal/sort/sort_test.go, pkg/module/drift/combination.go, pkg/module/drift/combination_test.go, pkg/module/drift/config.go, pkg/module/drift/config_test.go, pkg/module/drift/drift.go, pkg/module/drift/model.go, pkg/module/drift/model_test.go, pkg/module/drift/terraform.go, pkg/module/drift/terraform/state.go, pkg/module/drift/terraform_test.go
- Turns out the "combination feature" was kind of doable with the `path` statement but I still wanted to leave it in for now.
- Added @if to GJSON `value|@if:this,that` (if value is `this` it will be replaced with `that`. if not, it will be left as-is)
- Added @split to GJSON to split a string into an array: `value1,value2|@split:,` => `[ value1, value2 ]`
- Added ability to run GJSON filters in the cloud provider attributes (in the attribute map) and updated drift protocol to v2
- Added ability to define a single cloud resource multiple times (explicitly, using a 'hash' syntax, so that it doesn't get confused/lost in the map accesses) to be able to cover a blanket resource (think `iam.accounts` or `ec2.regional_config`) using multiple TF resources.
- Removed `-tf-mode` cli param (which …
=> feat: Drift: Improvements

pkg/module/drift/config.go, pkg/module/drift/config_parser.go, pkg/module/drift/config_test.go, pkg/module/drift/drift.go
- Version constraints are not needed since HCL is bundled with the provider now
- Second commit fixes the issue about not being able to filter two resources down, using check_resources:
This would fail:
```hcl
check_resources = [
// "codepipeline.pipelines:*",
// "aws_codepipeline_pipeline_stages:*",
"aws_codepipeline_pipeline_stage_actions:*"
]
```
but this would work:
```hcl
check_resources = [
// "codepipeline.pipelines:*",
"aws_codepipeline_pipeline_stages:*",
"aws_codepipeline_pipeline_stage_actions:*"
]
```
(now the former also works)
=> fix: Drift: Remove version constraints, always include all parents

go.mod, internal/telemetry/telemetry.go, pkg/policy/manager.go, pkg/ui/progress.go
Hi!
The satori/go.uuid library isn't longer supported, and contains security [issues](https://github.com/satori/go.uuid/issues/115). So I've replaced this with google/uuid.
=> fix: Replace non-supported satori/go.uuid with google/uuid

go.mod, go.sum
This command is what failed:
```
CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o bin/app-amd64.exe
```
After this fix all of these now work:
```
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bin/app-amd64.exe
CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o bin/app-amd64.exe
```
=> fix: Go Dependencies for `go-fsimpl`

internal/getter/getter.go
Related to https://github.com/cloudquery/cloudquery-issues/issues/324 (internal issue).
To reproduce the issue run: `cloudquery policy run github::github.com/cloudquery-policies/aws`, and see that it fails with `Failed to run policies: failed to get source github::github.com/cloudquery-policies/aws: download not supported for scheme 'github'.`
=> fix(policy): Add missing GitHub policy getter

.gitignore
While running the tests I noticed some files that are generated by the tests are not `git` ignored.
This PR fixes it
=> chore(test): Ignore files generated during tests

internal/firebase/client.go, internal/getter/github.go, internal/getter/github_test.go, pkg/client/client.go, pkg/client/purge_test.go, pkg/client/schema_test.go, pkg/plugin/registry/hub.go
Fixes https://github.com/cloudquery/cloudquery-issues/issues/324 (internal issue).
This PR gets the policy latest version from Firebase instead of GitHub to avoid hitting rate limits.
To reproduce run `cloudquery policy run github::github.com/cloudquery-policies/aws` multiple times.
This is the smallest change I could think of to fix the issue.
Example data  https://firestore.googleapis.com/v1/projects/hub-cloudquery/databases/(default)/documents/orgs/cloudquery/policies/aws/versions?mask.fieldPaths=policy.Name
=> fix(policy): Use firebase instead of GitHub to get latest version

pkg/policy/source_test.go
When I ran `go test -timeout 30s -run ^TestLoadSource$ github.com/cloudquery/cloudquery/pkg/policy` on my machine it prompted for a GitHub username and password.
The reason is that `git` tries to authenticate using `user/pass` when the scheme is `https` (I think `go-getter` tries it when it doesn't find a repo)
It doesn't prompt in CI/non interactive environment as `git` won't prompt in those, and will simply fail (see error [here](https://stackoverflow.com/questions/40274484/fatal-could-not-read-username-for-https-github-com-device-not-configured)).
This PR forces a `user:pass` (invalid, but that's ok as the test expects an error anyway).
=> test(policy): Don't prompt for GitHub user:pass when running the test

pkg/ui/console/client.go
fix support optional providers for sync commands
Closes #634
=> fix: Sync support optional provider args

cmd/init.go, deploy/lambda.go, pkg/config/config.go, pkg/config/config_parser.go, pkg/config/config_parser_test.go, pkg/config/parser_test.go, pkg/ui/console/client.go
Introduce all DSN parts separately in connection block.
Old DSN syntax (URL or non-URL) can still be used, but the two types can't be combined.
Closes #600.
Fixes #612.
=> feat: DSN credentials

pkg/ui/console/client.go
Extracted from https://github.com/cloudquery/cloudquery/pull/684 to a dedicated PR
=> fix: Handle `nil` policy run response

internal/getter/getter.go
Extracted from https://github.com/cloudquery/cloudquery/pull/684.
Specifically https://github.com/cloudquery/cloudquery/pull/684#discussion_r869393112.
Using an array to iterate over the detectors (instead of a map) ensures we run them in order and provide a deterministic result
=> fix: Run policy detectors in order

pkg/policy/source.go
Fixes https://github.com/cloudquery/cloudquery-issues/issues/333 (internal issue).
To reproduce:
`cloudquery policy run empty-dir` when `empty-dir` is an empty directory.
https://github.com/cloudquery/cloudquery/pull/697 actually fixed a related issue when running `cloudquery policy run non-existing-dir`
=> fix: Handle empty policy directory

pkg/policy/source.go
Fixes https://github.com/cloudquery/cloudquery-issues/issues/334 (internal issue).
I could not reproduce this (probably needs a Windows machine). However the error is descriptive enough for the user to take action, so we should probably just filter it from our analytics.
The reported error is:
```
*errors.errorString: subdir "<redacted>" not found
*fmt.wrapError: failed to get source file://C://<redacted>: subdir "<redacted>" not found
```
=> fix: Classify subdir not found error

go.mod, go.sum
Follow up on https://github.com/cloudquery/cloudquery/pull/710 (this PR is the output of running `go mod tidy`)
=> fix: Remove unused lambda dependency

internal/analytics/client.go, pkg/ui/console/client_test.go
Fixes an issue that on each run of `cloudquery` a telemetry id file is created in the current dir
---
=> fix: Don't generate telemetry-random-id in current dir

pkg/policy/execute.go
Currently you cannot output results of a policy to a file if you use a selector as we do not ensure the entire directory structure is created
This is a valid command and should be supported:
`cloudquery policy run gcp//cis_v1.2.0  --output-dir cloudquery-gcp/`
---
=> fix: Handle Outputting Policies With Selectors

pkg/core/diagnostics.go, pkg/core/fetch.go, pkg/core/fetch_test.go, pkg/errors/cancel.go, pkg/errors/error.go, pkg/errors/sentry.go
- pkg/errors can be imported from anywhere now (doesn't import core)
- new methods from https://github.com/cloudquery/cloudquery/pull/741 moved to errors pkg
- ~~tried importing pkg/errors as `cqerrors` (to leave stdlib errors as `errors`) which didn't work in the workflow, had to switch around (`errors` and `stderrors` respectively)~~ my bad
=> fix: Diag import clean up

pkg/policy/policy.go, pkg/policy/policy_test.go, pkg/policy/run.go
Added an inheritance of root policy to selected subpolicy to make fetch checks work if policy run targets subpolicy or section.
closes #626
=> fix: Added root policy config inheritance to selected subpolicy

pkg/config/config.go, pkg/config/config_parser.go
Another lint related issue. I don't think it's a "real" issue as we update the DSN outside of `BuildFromConnParams`.
However it might be a bit confusing that the DNS is updated and the port and type aren't.
A smaller fix would be to only change `c Connection` to `c *Connection`
---
=> refactor: Use pointer for connection receiver

pkg/ui/output.go
Fixes #785.
Could also make it so that nothing is printed below Info level (only for Warning and Error would have its own log level here)
=> fix: Console log log level

pkg/errors/error.go
Some issues from sentry.
The context canceled error is reproduced by hitting CTRL+C as soon as seeing the `INF All regions specified in config.yml. Assuming all regions` message in log, during `cloudquery fetch --enable-console-log`.
=> fix: Error classifier improvements

pkg/policy/parser.go, pkg/policy/parser_test.go, pkg/policy/run.go
The reason is DecodePolicy does not actually return error diag when there
is parse error. But the returned policy is nil leading to panic.
=> fix: Panic in loadPolicyFromSource

pkg/ui/output.go
Fixes https://github.com/cloudquery/cloudquery/issues/852
When console logging is enabled we dump all log messages to `stderr`:
https://github.com/cloudquery/cloudquery/blob/b5af06b570558612c95407dceb4200f92640f335/internal/logging/logger.go#L66
We also redirect all `ui.ColorizedOutput` prints to the log instead of `stdout`. This is a bit confusing as in other places we print to `stdout`, for example when printing policy run table results (search `tablewriter.NewWriter` for all relevant places).
This PR fixes the issue for non terminal (non interactive) environments by printing `ui.ColorizedOutput` to both.
In terminal environments, `stdout` and `stderr` are interleaved so we still need the `return` to avoid printing the same …
=> fix(console): Output to console when console log is enabled in non terminal envs

pkg/ui/console/client.go
It would print fail although there isn't any error diags, moreover the diags are not printed in the end of the execution.
Closes #805
---
=> fix: Purge command failure

pkg/config/config_parser.go
A user with policy in config block doesn't necessarily need to write their own local policy.
If they were using the "source" feature, they might just need the link to how to run them from CLI.
---
=> fix: Small fix in deprecation warning for "policy in config"

cmd/sentry.go, pkg/core/diagnostics.go
Reports provider version as the release, if we're reporting a provider-generated diagnostic.
=> feat: Sentry: Report provider version as release

pkg/core/sync.go
Fixes https://github.com/cloudquery/cloudquery-issues/issues/387 (internal issue)
To reproduce:
1. `cloudquery init aws`
2. `git clone https://github.com/cloudquery/cq-provider-aws`
3. `make build` in the repo ⬆️ 
4. Copy complied provider to `.cq/providers/cloudquery/aws` and replace the existing one.
5. Run `cloudquery fetch --no-verify`
---
=> fix: Improve invalid provider version error

go.mod, go.sum, pkg/core/sync.go, pkg/ui/output.go
Follow up to https://github.com/cloudquery/cloudquery/pull/879.
Makes the link to the docs clickable on supporting terminals (Please note the MacOS `zsh` terminal doesn't support this)
---
=> feat: Add clickable links support

pkg/ui/console/client.go
Added a space after the -> symbol
Before:
After:
---
=> fix: Add missing space when printing provider update message

cmd/root.go, pkg/config/config_parser.go
Extracted from https://github.com/cloudquery/cloudquery/pull/898
Follow up to https://github.com/cloudquery/cloudquery/pull/855
Removes the `plugin-dir` and `data-dir` flags from the CLI. Shouldn't be a breaking change as those flags are hidden.
---
=> fix: Remove plugin-dir and data-dir CLI flags

cmd/root.go, cmd/sentry.go
Noticed this while doing https://github.com/cloudquery/docs/pull/198. I think we can hide these debug flags from users (e.g. when running `cloudquery options`
---
=> fix(command-options): Hide internal debug flags

pkg/ui/console/client.go
Currently we always print `@latest` on fetch progress. This is a bit confusing (see with alias):
Since we currently don't have that information in the code, I removed it for now, see:
---
=> fix(console): Don't print @latest when fetching

pkg/config/config_parser.go
Fixes YAML parsing as we expect provider alias to default to name
---
=> fix: Default alias to name

cmd/init.go, go.mod, go.sum, pkg/config/config.go, pkg/config/config_parser.go, pkg/core/fetch.go, pkg/core/provider.go, pkg/ui/console/client.go
Otherwise ConfigureProvider is called with no format, which would default to HCL.
init/config providers format also moved from map to list of providers.
=> fix: Request correct config format (YAML) from provider

cmd/init.go, cmd/init_test.go, pkg/plugin/registry/organization.go, pkg/plugin/registry/organization_test.go
Related to https://github.com/cloudquery/cloudquery/issues/908
This PR does a bit of refactoring around the code that parses the arguments passed to the `init` command, and add tests
---
=> refactor: Rename ParseProviderNameWithVersion, move to relevant file, add test

cmd/policy.go, pkg/ui/console/client.go
`cloudquery policy run` shouldn't allow running without db (panics on c.Storage access later on)
=> fix: Disallow running of db-using policy operations without config

pkg/ui/console/policy.go
In policy run output identifer values were not shown correctly because
`cast.ToStringSlice(row.Identifiers)` cannot handle
`map[string]interface{}` type and always returns empty slice.
=> fix: Show identifiers values correctly

pkg/ui/console/policy.go
table.Render will panic if len(footer) < len(header or data row)
This at least should fix the panic.
=> fix: Work around the panic in createOutputTable

pkg/core/fetch.go
Handle warning diags created during provider configure
You can see here not all accounts were fully configured, but with the fix the warnings still were printed
```
Fetch Diagnostics:
Type: Access Severity: Warning
Summary: failed to refresh cached credentials, operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: REDACTED, api error AccessDenied: User: arn:aws:sts::REDACTED:assumed-role/REDACTED is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::REDACTED:role/OrganizationAccountAccessRole2
Detail: ensure that arn:aws:sts::REDACTED:assumed-role/REDACTED has access to be able perform `sts:AssumeRole` on arn:aws:iam::REDACTED:role/REDACTED 
Provider aws fetch summary: ✓ Total Resources fetched: 1         ⚠️ Warnings: 0   ❌ Errors: 0
```
--- …
=> fix: Handle Diags

pkg/config/config_parser.go
Pass Contents of Provider Configuration
Prior to this pr this is what would be passed:
```
"configuration:\n    accounts:\n        cq-playground:\n            local_profile: playground\n        cq-provider-aws:\n            local_profile: provider\n"
```
After this pr:
```
"accounts:\n    - cq-playground: null\n      local_profile: playground\n    - cq-provider-aws: null\n      local_profile: provider\n"
```
---
=> fix: Configure Provider Yml

cmd/ulimit_unix.go
1. We should never decrease ulimit, if it's big enough.
2. The logs can definitely be 'info', since this is only logged once per 'cloudquery' invocation. Will also assist in debugging when we get customer logs.
---
=> fix: Don't decrease ulimit. Change ulimit logs from 'debug' to 'info'

.gitignore, cmd/init.go, scripts/test-sanity.sh
=> chore!: Remove support for cq init HCL

cmd/policy.go, pkg/ui/console/client.go, scripts/test-sanity.sh
The 'policy run' command already supports running both from local or remote sources.
'policy run' also caches policies in '.cq' directory.
The benefits of 'policy download' (that just caches a remote policy in '.cq' internal directory) is dubious.
---
=> feat!: Remove 'policy download' feature

pkg/config/config_parser.go, pkg/config/fixtures/config_with_alias.hcl, pkg/config/fixtures/duplicate_provider_alias.hcl, pkg/config/fixtures/duplicate_provider_name.hcl, pkg/config/fixtures/env_vars.hcl, pkg/config/fixtures/env_vars.yml, pkg/config/fixtures/no_source.hcl, pkg/config/fixtures/valid_config.hcl, pkg/config/loader.go, pkg/config/loader_test.go, pkg/core/core_test.go
Apparently this wasn't ported over...
=> fix: Support env var substitution in YAML config

cmd/init.go
Cobra already prints the received error.
To reproduce run `cloudquery init gcp --config config.yml` twice
---
=> fix: Don't print duplicate error during init

cmd/root.go
Removes the auto generated tag from the docs
---
=> fix(cmd-doc): Don't add autogenerated tag

cmd/doc.go
Follow up to https://github.com/cloudquery/cloudquery/pull/1068.
Docs are not generated for the completion command and this PR fixes it.
The reason is that the default completion command is added to the root command after calling `Execute`:
https://github.com/cloudquery/cloudquery/blob/dc558d1521cdacc7be9bf7fff741f86015d65e7c/cmd/root.go#L136
https://github.com/spf13/cobra/blob/b9ca5949e2f58373e8e4c3823c213401f7d9d0e3/command.go#L949
so we can't create a new root command and need to reference the parent that the `completion` command was added to.
Exposed by https://github.com/cloudquery/docs/pull/256/files
---
=> fix(cmd-doc): Generate docs for completion command

cmd/init/init.go, pkg/config/config_parser.go, pkg/config/config_parser_test.go, pkg/config/fixtures/bad_version.yml, pkg/config/loader_test.go
Builds on top of https://github.com/cloudquery/cloudquery/pull/913.
Correct diff available in https://github.com/erezrokah/cloudquery/compare/refactor/config_parsing...erezrokah:fix/version_validation?expand=1
When someone runs `init <provider>@<version>`, `version` can be `latest` or a valid loose Semver version (e.g. `0.10`, `v0.10`, etc.).
However the logic to validate the configuration file is a bit different and we allow `latest` and strings starting with `v`.
This PR align the logic so validating the configuration is loose SemVer compliant.
---
=> fix(config): Align provider version validation

cmd/ulimit_unix.go, cmd/ulimit_unix_test.go
Ulimit has a 'soft'(current) value and 'hard'(maximum) value. 'soft' can always be increased up to the 'hard' limit.
But, increasing the 'hard' limit requires some very arcane permissions (often even root is not enough).
Before this fix, we did just one 'setrlimit' call for increasing both 'hard' and 'soft' limit. But, since increasing
the 'hard' fails on EPERM, the soft limit is also not increased.. This PR fixes this by splitting the 'set hard limit' and 'set soft limit' into two different invocations.
---
=> fix: Ulimit bug

go.mod, go.sum, pkg/ui/output.go
Previously, in pull request #882, the library `termlink` had been introduced to the code in order to add clickable link support. The PR also contained a "workaround" to fix a specific bug which existed in a previous version of the package, which would add an extra space before the url i.e., `text ( url)`:
```go
func Link(text string, url string) string {
if termlink.SupportsHyperlinks() {
return termlink.Link(text, url)
}
// termlink has default behavior for terminals that don't support hyperlinks but it adds an extra space before the link, e.g. `text ( link)`
// so we use our own formatting
return fmt.Sprintf("%s (%s)", text, url)
}
```
This error has now been fixed in the latest version of `termlink` and the workaround is no longer required. As such, I have removed it and refactored the …
=> chore: Refactor Link function code

.github/workflows/release-pr.yml, release-please-config.json
This should tell release please to generate the diff from the `a19c572b7c8dac79dd63b5e84414fc9dd36b1fb3` commit instead of the entire history
=> chore: Set bootstap sha

.release-please-manifest.json, cli/.goreleaser.prerelease.yaml, cli/.goreleaser.yaml, plugins/.goreleaser.yaml, plugins/aws/.goreleaser.yaml, plugins/azure/.goreleaser.yaml, plugins/cloudflare/.goreleaser.yaml, plugins/digitalocean/.goreleaser.yaml, plugins/fuzz/.goreleaser.yaml, plugins/gcp/.goreleaser.yaml, plugins/github/.goreleaser.yaml, plugins/k8s/.goreleaser.yaml, plugins/okta/.goreleaser.yaml, plugins/terraform/.goreleaser.yaml
Looks like variables don't work for `project_name` and `monorepo` configurations.
Also global hooks run from the CWD and not from the project directory.
=> chore: Fix Go Releaser configs

cli/.goreleaser.prerelease.yaml, plugins/.goreleaser.yaml
This is the way to set a directory for global build hooks, see https://goreleaser.com/customization/hooks/?h=hooks
=> chore(release): Set dir for projects

.release-please-manifest.json
Brings back the AWS plugin version to the latest released (It was bumped as a part of my tests)
=> chore: Sync aws release version

release-please-config.json
Disables https://github.com/cloudquery/cloudquery/pull/1194 but keeps the workflow that adds labels to PRs.
Using the GitHub style release notes fails at the moment as it relies on PR labels (instead of commits like the default one).
Since we imported commits from providers repos, but can't import their linked PRs this creates a bit of a mess.
Once we make the switch we can re-enable it, but we should still keep the workflow that adds labels, so once we switch the correct changelog will be generated.
=> chore(release): Disable GitHub release notes

plugins/source/fuzz/go.mod, plugins/source/fuzz/main.go
Same as https://github.com/cloudquery/cloudquery/pull/1199 for the fuzz source
=> chore: Rename plugin/source/fuzz module and imports

plugins/.goreleaser.yaml, plugins/source/aws/.goreleaser.yaml, plugins/source/azure/.goreleaser.yaml, plugins/source/cloudflare/.goreleaser.yaml, plugins/source/digitalocean/.goreleaser.yaml, plugins/source/fuzz/.goreleaser.yaml, plugins/source/gcp/.goreleaser.yaml, plugins/source/github/.goreleaser.yaml, plugins/source/k8s/.goreleaser.yaml, plugins/source/okta/.goreleaser.yaml, plugins/source/terraform/.goreleaser.yaml
Leftovers from moving to `source` directory
=> chore: Fix Go releaser

.github/workflows/check_generated_code_drift.yml
This workflow uses `${{ github.base_ref }}` that is only available on pull request events.
We can use `${{ github.ref }}` (I think) for push events, but I'm not sure we even want to run this test on the default branch
=> chore(ci-drift-generated): Don't run on push events

.gitignore
For now each developer can chose to opt-in to Go workspaces via `go work init`
=> chore: Ignore go work files

cli/pkg/plugin/registry/hub.go
`getPluginBinaryName` prepends `cq-provider-` to the binary name
---
=> fix(cli): Don't prepend cq-provider to monorepo binary name

plugins/source/aws/views/resources.sql, plugins/source/azure/views/resource.sql, plugins/source/gcp/views/resource.sql, plugins/source/k8s/views/resource.sql
Give more informative message when there are no tables created yet and
an attempt is made to create the resources view.
Closes https://github.com/cloudquery/cloudquery/issues/1347
=> chore: Handle no tables in resource view

website/components/BlogHeader.tsx
Blog titles and og-images now use `useConfig` hook instead of unstable internal implementation
---
=> fix: Blog titles and og:image from config hook

README.md
Add the missing path 'cli' for compiled binary file.
---
=> fix(docs): Add the missing path 'cli' for compiled bin

Makefile, README.md
This ensures the output path of the`build-cli` command is the same as for the `build` command.
=> fix: Fix output path of build-cli make command

website/public/images/hero/section1.svg
Fixes the position of the bottom block of section1.svg, which I calculated slightly incorrectly in the previous PR.
=> fix(website): Fix position of corner in top image

cli/internal/versions/versions.go, cli/internal/versions/versions_test.go, cli/pkg/core/provider_test.go, cli/pkg/core/version.go, cli/pkg/core/version_test.go
This updates the CLI to use https://versions.cloudquery.io/v1/cli.json when checking for newer versions, rather than Github releases (which now uses a different tag format).
=> fix(cli): Fix cli version checking to work with monorepo

.github/workflows/approve_vercel.yml
`ouzi-dev/commit-status-updater` doesn't support `pull_request_target`
---
=> chore: Fix approve Vercel workflow

cli/pkg/core/download_test.go, cli/pkg/plugin/registry/hub.go
This is a P1 bug removing dependency on deprecated firebase which prevents downloading plugins.
---
=> fix: Remove deprecated firebase

release-please-config.json
This reverts commit 4d6d2b974e47fda003b352389f8f6283318172ed.
Still doesn't work. We need at least 1 release of each component for this to work as GitHub API compares to a previous tag. We don't have previous tags for Okta and Terraform so the API call fails:
https://github.com/cloudquery/cloudquery/runs/8057536451?check_suite_focus=true#step:2:265
---
=> chore: Revert "chore: Use GitHub changelog format (#1571)"

.github/workflows/approve_vercel.yml, .github/workflows/release_cli.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/1595.
Updates the CLI version in the docs to the latest version after a release was published
---
=> chore: Update CLI version in docs after release

plugins/.goreleaser.yaml
Im adding zip format to goreleaser (in the future we will move just to zip to save bandwidth/storage etc...). Also the new cli will only support zip formats as no reason to support non-zip releases (brew also supports just zip). we will deprecate the other release gradually. 
---
=> chore: Support zip for plugins

.github/repo_settings.yml, .github/workflows/release_pr.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/1618.
Document adding a new plugin to the monorepo, then automate what we can
---
=> chore: Mark test plugin as pre-release until binaries are uploaded

cli/pkg/plugin/registry/hub.go, cli/pkg/plugin/registry/validate.go
With the release of the test plugin our tests have started failing on `main`. The reason is that we use `strings.Contains` to match the binary to the checksum in the checksums file, and the zipped entries also match by OS and Arch:
```bash
44d95de58751bb726f17a79c42e33faed7dad2210b9faf5ebbcf08a5079e41eb  test_linux_amd64.zip
46f587c64821a807ea12d43d08a20e7258452acc3b7e12887b176a14a12d0dc4  test_linux_amd64 
556cc5ae71b261a86c6951ee6bfb9ba5d01492babc31fb8d5b0e58abd23142c5  test_darwin_arm64
9b0796dac187339ae74c765cbdc81924149df3c7aab695e4b010011494cf079f  test_linux_arm64.zip
a2ac8ddeed89ca68a11f7f68e564244d1fcc04d05300cb7c62f8277de9e7ce18  test_darwin_amd64.zip
c2c8f2d10319100f465b7c1c354eb300611e81929c1315c624d30bddc15991ab  test_darwin_arm64.zip …
```
=> fix: Checksum validation

.github/repo_settings.yml, .github/workflows/lint_doc.yml, .github/workflows/lint_golang.yml, .github/workflows/test_build.yml, .github/workflows/test_policy_sql.yml, .github/workflows/test_unit.yml
Seems wasteful to re-run the same workflows again on `main`. If we keep PR branches up to date before merging we can skip testing on `main`
---
=> chore: Don't re-run workflows on main

.github/workflows/broken_links.yml
This workflow is quite slow (takes 10-20 minutes) and seems wasteful to run on each Website PR.
Also links can be broken regardless of code changes we make (for example we link to something external that was changed).
---
=> chore: Run broken links check periodically

plugins/source/aws/resources/services/sns/subscriptions.go
When a Subscription has not been confirmed, it doesn't have a valid ARN so CloudQuery is not able to make nested call. This PR does two things:
1. If a single call fails it will still try all other calls rather than ending early
2. It will not make a call if the ARN is equal to `PendingConfirmation`
---
=> fix: Handle SNS Subscriptions in Pending State

.github/workflows/approve_vercel.yml, .github/workflows/lint_doc.yml, .github/workflows/lint_golang.yml, .github/workflows/release_cli.yml, .github/workflows/release_plugin.yml, .github/workflows/test_build.yml, .github/workflows/test_policy_sql.yml, .github/workflows/test_unit.yml, .github/workflows/validate_release.yml
Some CI improvments:
1. `fetch-depth: 0` fetches all branches, tags, history etc. For diffing `fetch-depth: 2` should be fine
2. Remove dead code - `github.event_name != 'pull_request'` checks are not needed anymore
3.  Remove hard coded components in SQL and Docs CI as we can check if the relevant files for the tests exist
---
=> chore(ci): Use fetch-depth: 2, remove hard coded modules

plugins/source/github/docs/index.md
GitHub and CloudQuery have inconsistent casing.
A few grammar fixes.
=> doc: GitHub Plugin Grammar fixes

.github/workflows/broken_links.yml
We don't run this workflow that often now due to https://github.com/cloudquery/cloudquery/pull/1699 so no need for the concurrency group as it cancels in progress workflows, see https://github.com/cloudquery/cloudquery/actions/runs/2992996017
---
=> chore(ci): Remove broken links workflow concurrency group

.github/repo_settings.yml
Until we bring back doc generation
---
=> chore: Remove GCP lint provider doc rule

plugins/source/test/client/client.go, plugins/source/test/go.mod, plugins/source/test/go.sum, plugins/source/test/plugin/plugin.go
The test plugin complication fails. This PR fixes it. Related to https://github.com/cloudquery/plugin-sdk/releases/tag/v0.1.0
---
=> fix(plugin-test): Update for new SDK version

cli/cmd/generate.go, cli/cmd/generate_test.go, cli/cmd/templates/destination.go.tpl, cli/cmd/templates/source.go.tpl, cli/internal/plugins/plugins.go, plugins/source/gcp/resources/plugin/plugin.go, plugins/source/heroku/plugin/plugin.go
Adds auto-filled config to the `generate` command. Both `source` and `destination` plugins are supported. Plugins should now only return the part of the config relevant to their own configuration. This PR already updates the GCP and Heroku plugins to do this.
Follow-up to https://github.com/cloudquery/cloudquery/pull/1746 that only updates the CLI, no SDK changes.
=> feat: Generate auto-filled config

cli/pkg/plugin/registry/validate.go
In latest v1 of the CLI checksum verification on Windows is broken due to https://github.com/cloudquery/cloudquery/pull/1637.
This PR targets a branch that should allow us to back-port fixes to v1.
Current workaround should be to run the CLI with the `--no-verify` flag on Windows
---
=> fix(cli): Windows verification check

plugins/source/gcp/resources/services/kms/keyrings_mock_test.go
The tests on GCP started failing and I believe https://github.com/cloudquery/plugin-sdk/pull/85 is the reason.
This should fix it
---
=> test: Fix GCP mock test

cli/cmd/generate_test.go, cli/cmd/templates/destination.go.tpl, cli/cmd/templates/source.go.tpl
I noticed all strings are quoted except the `kind` property
---
=> fix: Quote kind string in generated yml files

website/package.json, website/scripts/generate-hub.js, website/yarn.lock
Enables docs generation for all plugins during build. Done in a way that supports old v1 plugins too.
Build is failing due to an issue with Nextra, see https://www.notion.so/cloudquery/v2-Created-ed27199b013c4f6b82131afdcd6087fc#8a540579265a499f8f5647584470e7c3 (internal link)
---
=> chore(wesbite): Enable docs for all plugins

cli/cmd/generate.go, cli/cmd/generate_test.go, cli/cmd/sync.go, cli/internal/plugins/plugin_test.go, cli/internal/plugins/plugins.go
This PR fixes https://github.com/cloudquery/docs/issues/216 which is still present in v2 and causing failures in https://github.com/cloudquery/cloudquery/pull/1848. Also somehow related to https://github.com/cloudquery/cloudquery/issues/908
If you try:
1. `gen source test`
2. `gen destination postgresql`
3. `gen sync .`
you'll get the follow error:
```
Loading specs from directory:  .
Downloading plugin from: https://github.com/cloudquery/cloudquery/releases/download/plugins/source/test/development/test_darwin_arm64.zip to: .cq/plugins/github/cloudquery/test/development/cq-source-test_darwin_arm64.zip 
Error: failed to sync source test: failed to get source plugin client for test: failed to download plugin: bad status: 404 Not Found. downloading …
```
=> fix: Resolve plugin version from GitHub registry instead of gRPC call

cli/cmd/generate_test.go, cli/cmd/templates/source.go.tpl
Fixes https://github.com/cloudquery/cloudquery/issues/1808
=> feat: Generate `postgresql` as default destination in `gen` command

cli/.goreleaser.prerelease.yaml, cli/cmd/root.go
In plugins we use `development` so we should have the same in the CLI (instead of `dev`).
Also I think we need only `Version` as we can get the other values from the Version tag
---
=> fix: CLI dev version

plugins/source/aws/codegen/recipes/iam.go
There is an edge case where ARN should not be used as the primary key: if a user gets deleted and then a new user gets created, the same ARN may get assigned. Instead, we should use account_id + id
=> fix: IAM users PK should be account_id + id, not ARN

plugins/source/aws/codegen/recipes/iam.go, plugins/source/aws/resources/services/iam/credential_reports.go, plugins/source/aws/resources/services/iam/user_access_keys.go, plugins/source/aws/resources/services/iam/user_attached_policies.go, plugins/source/aws/resources/services/iam/user_groups.go, plugins/source/aws/resources/services/iam/user_policies.go, plugins/source/aws/resources/services/iam/users.go
I neglected to regenerate the code before merging https://github.com/cloudquery/cloudquery/pull/1876 😮‍💨 (I will add back the automated check for codegen drift soon). This fixes it and changes the `user_id` column on the `users` table to be `id`.
=> fix: Regenerate iam users + some fixes

plugins/source/test/.goreleaser.yaml
Apparently the issue with versions not being embedded is smaller than I thought. It was only related to the `test` plugin I was testing with
---
=> fix: Version not embedded in test plugin

.release-please-manifest.json
Sets the initial version for Heroku so it doesn't start from `v1.0.0`
---
=> chore(release): Set Heroku initial version

cli/cmd/generate.go
`gen` With a specific plugin version doesn't work, which means we can't test pre-releases.
e.g. `gen source heroku@v0.1.0-pre.0` fails.
This PR fixes it
---
=> fix: Can't gen with specific version

plugins/source/aws/codegen/recipes/s3.go, plugins/source/aws/resources/services/s3/accounts.go, plugins/source/aws/resources/services/s3/accounts_fetch.go
Closes https://github.com/cloudquery/cloudquery/issues/1925
=> fix: Add config_exists field back to aws_s3_accounts (v2)

.github/workflows/lint_markdown.yml
Currently the linting is triggered only on files in the root directory
---
=> chore(ci): Trigger markdown linting on all md files

.github/workflows/validate_release.yml
We changed the component names to use `-` instead of `/` so we can't use them directly as directories anymore
---
=> chore(ci-release): Get component dir from name

cli/cmd/generate_test.go, cli/internal/plugins/plugins.go, cli/internal/versions/versions.go, cli/internal/versions/versions_test.go
Updates the CLI to take plugins versions from the `v2` versions site which has a different structure for tags.
It still tries to download using the old format too to not break existing configurations.
Once we release all plugins under the v2 site we can remove the fallback code
---
=> feat: Use new tag format to download plugins

plugins/source/github/docs/tables/github_action_billing.md, plugins/source/github/docs/tables/github_external_group_members.md, plugins/source/github/docs/tables/github_external_group_teams.md, plugins/source/github/docs/tables/github_external_groups.md, plugins/source/github/docs/tables/github_hook_deliveries.md, plugins/source/github/docs/tables/github_hooks.md, plugins/source/github/docs/tables/github_installations.md, plugins/source/github/docs/tables/github_issue_assignees.md, plugins/source/github/docs/tables/github_issue_labels.md, plugins/source/github/docs/tables/github_issues.md, plugins/source/github/docs/tables/github_organization_member_membership.md, plugins/source/github/docs/tables/github_organization_members.md, plugins/source/github/docs/tables/github_organizations.md, plugins/source/github/docs/tables/github_package_billing.md, plugins/source/github/docs/tables/github_repositories.md, plugins/source/github/docs/tables/github_storage_billing.md, plugins/source/github/docs/tables/github_team_members.md, plugins/source/github/docs/tables/github_team_repositories.md, plugins/source/github/docs/tables/github_teams.md
We should keep this so that the links from the website are not broken until we release v2. 
Added back by running:
```
git checkout 12643fe403f65061621ddea115486ad19ef0b274 -- plugins/source/github/docs/
tables
```
=> fix: Add Github table docs back

plugins/source/aws/codegen/recipes/iam.go, plugins/source/aws/resources/services/iam/policies.go
This adds `policy_version_list` as a JSON column (it was a separate table before). 
Closes https://github.com/cloudquery/cloudquery/issues/1980
=> fix: Add missing fields to aws_iam_policies

README.md
The url for plugins doesn't existed(https://www.cloudquery.io/plugins) and shows 404. 
I update the links from `https://www.cloudquery.io/plugins` to `https://www.cloudquery.io/docs/plugins/source`
=> fix: Url for plugins in README.md file under root folder doesn't existed

plugins/source/aws/codegen/recipes/ec2.go
=> fix: AWS EBS Snapshots attributes column type

plugins/source/aws/resources/services/ec2/ebs_snapshots.go
fix for https://github.com/cloudquery/cloudquery/pull/2075 ... run codegen 🙄
=> fix: AWS EBS Snapshots attributes column type (take two)

sites/versions/v2/cli.json
This updates `sites/versions/v2/cli.json` to `cli-v1.1.0-pre.1`, which is a pre-release. Normally we wouldn't use pre-releases here, but having this would be better than having an empty string as we can then test the flow of end-to-end (related: https://github.com/cloudquery/cloudquery/issues/2076). It will be updated automatically as soon as we do a real v1 release.
=> chore: Update cli latest v2 version to pre-release

plugins/source/aws/codegen/recipes/autoscaling.go, plugins/source/aws/codegen/recipes/backup.go, plugins/source/aws/codegen/recipes/ecs.go, plugins/source/aws/codegen/recipes/elasticbeanstalk.go, plugins/source/aws/codegen/recipes/lambda.go, plugins/source/aws/codegen/recipes/resourcegroups.go, plugins/source/aws/codegen/recipes/xray.go, plugins/source/aws/resources/services/autoscaling/group_scaling_policies.go, plugins/source/aws/resources/services/backup/vault_recovery_points.go, plugins/source/aws/resources/services/ecs/task_definitions.go, plugins/source/aws/resources/services/elasticbeanstalk/environments.go, plugins/source/aws/resources/services/lambda/function_aliases.go, plugins/source/aws/resources/services/resourcegroups/resource_groups.go, plugins/source/aws/resources/services/xray/sampling_rules.go
(...or had them under a non-standard name). For AWS resources, we use the column name `arn` if the resource has a unique ARN.
Closes https://github.com/cloudquery/cloudquery/issues/2029
=> fix: Add ARNs to resources that were missing them

plugins/destination/postgresql/client/postgresql.go, plugins/destination/postgresql/client/postgresql_test.go
The previous upsert query just replaced the values with the values that were already in the table... i.e. the query was:
DO UPDATE SET
"column"=table."column"
which of course does nothing.
The new query is:
"column"=excluded."column",
which does what we want.
See https://www.postgresql.org/docs/current/sql-insert.html
=> fix(postgresql): Upsert in postgresql

.github/workflows/wait_for_required_workflows.yml
It seems the API call for `listForRef` always returns an empty array (even for non forked PRs, see https://github.com/cloudquery/cloudquery/actions/runs/3151802511/jobs/5126220370)
This PR fixes it for non forked PRs by using the correct `sha` and also fixes the workflow to exit early once we finished waiting
=> chore(ci-wait-for-all): Use correct sha when listing checks, exit early when done

.github/workflows/wait_for_required_workflows.yml
https://github.com/cloudquery/cloudquery/pull/2093 updated the action we use to diff files, which seems to use the wrong `sha` in the latest version, see https://github.com/cloudquery/cloudquery/actions/runs/3153783624/jobs/5130648152#step:3:496.
This PR should fix it
=> chore(ci): Fix files diff

.github/workflows/wait_for_required_workflows.yml
Not sure what's the bug, but the latest version of this action seems to be broken https://github.com/cloudquery/cloudquery/actions/runs/3154103905/jobs/5131328774#step:3:531
=> chore(ci): Use v28 of change-files action

website/pages/docs/plugins/source-plugin-release-stages.md, website/pages/docs/plugins/source.md
The `Source Plugin Release Stages` file was named with underscores, causing it to appear as such in the sidebar and URL path
=> chore(docs): Fix filename of source plugins release stages (V1)

.github/workflows/wait_for_required_workflows.yml
Currently this workflows prints on each polling iteration the entire `checkRuns` array which is very spammy. This changes it so we only print `name` and `conclusion`. It also simplifies the logic.
=> chore(ci-wait-for-all): Don't print entire checkRuns array, simplify logic

.github/workflows/wait_for_required_workflows.yml
At the moment if someone changes `cli.yml` (for example) our CI won't wait for that workflow to finish. This fixes it
=> chore(ci): Wait for changes in workflow files

CODEOWNERS
Since we auto merge most updates, having code owners for `go.*` files create quite a lot of noise for developers.
I think we can handle reviews (if needed) for dep updates manually for now
=> chore: Set empty code owners for dependencies updates

website/pages/_meta.json
The following link 
is broken. This PR fixes it
=> chore: Fix plugins link in header tab

cli/cmd/sync.go, cli/cmd/sync_test.go
This fixes an issue where plugin logs were not being streamed to `cloudquery.log`. It also adds a test for this to catch future regressions.
=> fix: Add back missing plugin logs

plugins/source/aws/codegen/recipes/base.go
Add a special case for EC2 so that it doesn't get converted to `e_c2` by the caser. I re-ran codegen using this and it resulted in no changes (as expected).
=> fix: AWS codegen: fix ec2 naming

plugins/source/aws/client/resolvers.go, plugins/source/aws/client/resolvers_test.go, plugins/source/aws/resources/services/sns/subscriptions_mock_test.go
MarshaledJsonResolver  was not able to handle nil fields
=> fix: Fixed crashes when json field is nil

cli/cmd/sync.go
source_name should contain the source_name, not the source_path
=> fix: SourceName

cli/cmd/sync.go
old look:
> Summary: resources: 22029, errors: 100, panic: 0 failed_writes: 0
new look:
> Summary: resources: 25660, errors: 100, panic: 0, failed_writes: 0, time: 2m42s
=> fix: Show sync time

website/vercel.json
If you Google `CloudQuery getting started` the top results are broken. This redirects those links to the quick start guide
=> chore: Redirect getting started links

website/pages/docs/_meta.json, website/pages/docs/recipes/_meta.json, website/pages/docs/recipes/aws-postgresql.md, website/pages/docs/recipes/azure-postgresql.md, website/pages/docs/recipes/gcp-postgresql.md, website/pages/docs/recipes/overview.md
This adds section of useful configs for most used source/destination plugins that users can just copy paste (with auto-update pinned versions as part of CI).
Closes: https://github.com/cloudquery/cloudquery/issues/2047
=> chore(website): Add recipes section

cli/cmd/sync.go
Seems like this bug was hanging there but now when we started using batch in our postgresql plugin we were hit by this.
=> fix: Flush destination plugins when sync finish

plugins/source/aws/codegen/recipes/organizations.go, plugins/source/aws/resources/services/organizations/accounts.go
The organizations resource was using (what seems like) the incorrect multiplexer. Previously, in v0, this resource was using an account multiplexer: https://github.com/cloudquery/cq-provider-aws/blob/main/resources/services/organizations/accounts.go#L22 and I think changing the multiplexer was a mistake during the migration of resources from v0 to v1.
=> fix: Fix multiplexer for AWS Organizations

plugins/source/gcp/policies_v1/queries/iam/service_account_admin_priv.sql
Currently, the query returns Google internal service accounts. These accounts can not be controlled by end users. This query only returns IAM service accounts now.
=> fix(gcp-policy): Only show user defined service accounts in service accounts with admin privileges query

plugins/source/gcp/codegen/recipes/functions.go, plugins/source/gcp/docs/tables/gcp_functions_functions.md, plugins/source/gcp/resources/services/functions/functions.go
The 'TypeInterval' type is broken right now.
Because of the new batching functionality, this failure completely breaks the GCP plugin (any failure in an INSERT causes all other INSERTS to also fail due to the batch).
=> fix!: Rollback: Remove the 'functions.Timeout' column

.github/workflows/dest_postgresql.yml, .github/workflows/dest_test.yml, .github/workflows/source_aws.yml, .github/workflows/source_azure.yml, .github/workflows/source_cloudflare.yml, .github/workflows/source_digitalocean.yml, .github/workflows/source_gcp.yml, .github/workflows/source_github.yml, .github/workflows/source_heroku.yml, .github/workflows/source_k8s.yml, .github/workflows/source_okta.yml, .github/workflows/source_terraform.yml, .github/workflows/source_test.yml
This is a follow up to https://github.com/cloudquery/cloudquery/pull/2949. [GitHub actions caching works like this](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache):
1. PRs can use cache saved on `main`
2. PRs can use cache saved on the PR brach
3. `main` Can't use cache saved on PRs branches
This PRs re-runs our lint, build and tests workflows on `main` to prime the cache so it can be used for follow up PRs.
Once merged I'll verify caching does help in a significant enough way to justify this way.
This seems counter intuitive but might also save us build minutes, as now we are leveraging caching only for re-runs of the same PR.
=> chore(ci): Run lint,built,test on `main` to prime cache

plugins/source/aws/dashboards/grafana/aws_ec2_public_private.json
Fix Name column in Grafana AWS Dashboard ec2_public_private.json
Previous context :
aws_ec2_instances.tags format :
{"Name": "test-cloudinventory"}
New context :
aws_ec2_instances.tags format :
[{"Key": "Name", "Value": "test-cloudinventory"}]
=> fix(aws-grafana-ec2_public_private): Fix Name column

.github/workflows/cli.yml, .github/workflows/dest_postgresql.yml, .github/workflows/dest_test.yml, .github/workflows/source_aws.yml, .github/workflows/source_azure.yml, .github/workflows/source_cloudflare.yml, .github/workflows/source_digitalocean.yml, .github/workflows/source_gcp.yml, .github/workflows/source_github.yml, .github/workflows/source_heroku.yml, .github/workflows/source_k8s.yml, .github/workflows/source_okta.yml, .github/workflows/source_terraform.yml, .github/workflows/source_test.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/3059. Go releaser needs to run from the repo root, so this moves the setting for a default working directory to the specific job that requires it
=> chore(ci): Don't set default working directory for validate-release

.github/workflows/release_cli.yml, .github/workflows/release_plugin.yml
Last part of https://github.com/cloudquery/cloudquery/pull/3059. Now that we got the cache working for `validate-release` workflow, the next step is to use it in the actual release workflows
=> chore(ci): Use release-cache in release workflows

.github/workflows/cli.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/3059. I missed the `push` event for the CLI (all others workflows have it, I double checked)
=> chore(ci): Trigger CLI validate-release on push event

.github/workflows/cli.yml, .github/workflows/dest_postgresql.yml, .github/workflows/dest_test.yml, .github/workflows/source_aws.yml, .github/workflows/source_azure.yml, .github/workflows/source_cloudflare.yml, .github/workflows/source_digitalocean.yml, .github/workflows/source_gcp.yml, .github/workflows/source_github.yml, .github/workflows/source_heroku.yml, .github/workflows/source_k8s.yml, .github/workflows/source_okta.yml, .github/workflows/source_terraform.yml, .github/workflows/source_test.yml
We use `CGO_ENABLED: 0` in our release workflows, so we should do the same with `validate-release`
=> chore(ci-release): Add 'CGO_ENABLED: 0' to validate-release

.github/workflows/wait_for_required_workflows.yml
~~It seems this action fails to use the correct `sha` of the PR if the PR branch is not up to date. This should fix it~~
Use an action that uses the GitHub API as we need a three dots diff
=> chore(ci-wait-for-all): Use `Ana06/get-changed-files` to compare PRs with `main`

plugins/source/gcp/client/client.go, plugins/source/gcp/client/client_test.go, plugins/source/gcp/client/spec.go, plugins/source/gcp/docs/configuration.md
See individual commits for easier reviewing.
1) Fixes two previous bugs in the folder feature [forgotten recursion, forgotten set-union].
2) Adds support for the project-filter feature.
The project-filter is mutually exclusive with `folder_ids`, but `project_ids` that are specified will be added to the projects from the filter. More explicitly:
=> feat: Project filter

contributing/adding_a_new_resource.md
I took a look on the `adding_a_new_resource.md` in `contributing` folder and found out that links in specific guides section are broken and resulted in 404. 
After go around the repo, I think the correct link should be as following for `AWS`, `Azure` and `GCP`.
- AWS -> `../plugins/source/aws/CONTRIBUTING.md`
- Azure -> `../plugins/source/azure/CONTRIBUTING.md`
- GCP -> `../plugins/source/azure/CONTRIBUTING.md`
=> fix: Fix broken links for specific guides section in adding_a_new_resource.md

.github/workflows/greetings.yml
This PR is based on the issue #3161
=> feat: Add a workflow for greetings when users first interactive with repo

.github/workflows/release_cli.yml
This is a follow up to https://github.com/cloudquery/cloudquery/pull/3080 and https://github.com/cloudquery/cloudquery/pull/3188.
Sine we have [2 latest links ](https://github.com/cloudquery/cloudquery/blob/f16542afe1f45809c793afa7631a69bc13bf7ea2/sites/versions/vercel.json#L5)in our `vercel.json` file, and we only want to [update the latest one](https://github.com/cloudquery/cloudquery/blob/f16542afe1f45809c793afa7631a69bc13bf7ea2/sites/versions/vercel.json#L9), we need the `/:binary` to be a part of the replace string
=> chore(release-cli): Fix latest link regex

website/pages/docs/recipes/gcp-postgresql.md
Version string was missing the "v"; and referenced an older version
=> chore(docs): Update GCP version

.github/workflows/source_test.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/3322.
Looks like we can't use large runners on PRs in a safe way.
I configured the following access rules:
But only the one on `main` works as PRs refs are based on the PR number, e.g. `refs/pull/<pr_number>/merge`.
This PR keeps the large runners only on `push` events. I'm hoping that should be sufficient to improve performance by priming the cache for all other PRs
=> chore: Use large runners only on `push`

plugins/destination/postgresql/client/client.go, plugins/destination/postgresql/client/migrate.go
This adds a `unique not null` contraint on the internal `_cq_id` column, both when migrating an existing database and when creating a new database. 
It also fixes a bug where we didn't check if constraints changed before, if the column was new or if the column type changed.
=> feat: Add unique constraint on _cq_id column

.github/workflows/broken_links.yml
This host seems to be causing flakiness for our broken links checker:
https://github.com/cloudquery/cloudquery/actions/runs/3372003263/jobs/5602743373#step:5:263
=> chore(ci): Exclude work-bench from broken links checks

plugins/source/aws/policies_v1/queries/s3/s3_cross_region_replication.sql
Fixes https://github.com/cloudquery/cloudquery/issues/3563
There is a wider question here about whether we should be placing null values in the column at all--maybe they should be empty arrays instead. But for now this change fixes this specific policy.
=> fix: Fix bug in s3_cross_region_replication policy

cli/cmd/testdata/dest.test.yml, cli/cmd/testdata/source.test.yml, cli/go.mod, cli/go.sum
This SDK upgrade to the CLI adds the code in https://github.com/cloudquery/plugin-sdk/pull/371, and as such will make `path` a required config parameter. We consider this a breaking change, so the CLI version will be bumped to 2.0.0. 
As context, we are making `path` required (and not inferred from `name`) because there has been some confusion around these settings. Previously `path` could have been inferred from `name` in some circumstances, but when using multiple configs, this was not always possible, causing confusion.
From now on, `path` is a required parameter. It will usually take the form of `cloudquery/aws`, where `aws` is the source plugin name in this example. For the postgresql destination, it will be `cloudquery/postgresql`.
- `name` should be thought of as the unique …
=> fix!: Make path a required config parameter

website/theme.config.tsx
Changes the Github logo in the top bar to a shield from shields.io:
=> chore(website): Use Github shield in top bar

cli/cmd/testdata/dest.test.yml, cli/cmd/testdata/source.test.yml, plugins/destination/test/client/client.go
As best I can tell, the test destination plugin wasn't reading from the channel, causing a deadlock.
=> fix: Fix test destination plugin hang

.github/workflows/cli.yml
It's useful to see all OS fail and not exit early
=> chore(ci): Add fail-fast: false to CLI matrix

cli/cmd/sync2.go
I also found  error handling omissions in `cli/cmd/sync2.go` !
ref: https://github.com/cloudquery/cloudquery/pull/4486
=> fix: Error handling omissions in sync2

plugins/destination/postgresql/go.mod, plugins/destination/postgresql/go.sum
This reverts commit f4f73a4959af7d437038057c057045c3dee83c13.
Related to https://github.com/cloudquery/cloudquery/issues/4489. I confirmed reverting the SDK update fixes the issue
=> fix: Revert "fix(deps): Update plugin-sdk for postgresql to v1.5.0 (#4396)

.github/workflows/source_aws.yml, .github/workflows/wait_for_required_workflows.yml
AWS CI time can reach ~30 minutes which is the current timeout if uncached see https://github.com/cloudquery/cloudquery/actions/runs/3455334439/jobs/5767283053
=> chore(ci-aws): Increase CI timeout

plugins/source/aws/dashboards/grafana/aws_ec2_public_private.json
When using the AWS grafana dashboard for that displays public and prviate EC2 instances the 'name' column wouldn't populate with the query provided so after playing around a bit I found an 'easier' way to get the name to appear in the column successfully.
**Current Dashboard Example:**
---
**After applying this PR:**
=> fix: Fix Name tag reference in grafana dashboard

plugins/source/aws/policies/queries/apigateway/api_gw_publicly_accessible.sql
Fixed typo in JSON key in  plugins/source/aws/policies/queries/apigateway/api_gw_publicly_accessible.sql
Fixing #4837
=> fix(aws): Fixed typo in JSON key

plugins/source/aws/policies/queries/lambda/functions_with_public_egress.sql
Replaced "ec2 instances" with "lambda functions" in plugins/source/aws/policies/queries/lambda/functions_with_public_egress.sql
Just to make it clear to the receivers of the data.
=> fix(aws): Typo in lambda query

plugins/destination/snowflake/.goreleaser.yaml
This should fix the releaser to compile snowflake for windows amd64 successfully
=> chore: More fun stuff with goreleaser

plugins/destination/snowflake/README.md, plugins/destination/snowflake/client/client.go, plugins/destination/snowflake/client/client_test.go, plugins/destination/snowflake/client/spec.go, website/pages/docs/plugins/destinations.mdx, website/pages/docs/recipes/destinations/_meta.json, website/pages/docs/recipes/destinations/snowflake.md
I realised the `dsn` in snowflake spec is inconsistent with other plugins so changed it to `connection_string` and added a recipe + docs. Blog will come after that in a separate PR.
=> fix: Update Snowflake spec and docs

website/pages/docs/plugins/sources/aws/_meta.json, website/pages/docs/plugins/sources/azure/_meta.json, website/pages/docs/plugins/sources/cloudflare/_meta.json, website/pages/docs/plugins/sources/digitalocean/_meta.json, website/pages/docs/plugins/sources/gcp/_meta.json, website/pages/docs/plugins/sources/github/_meta.json, website/pages/docs/plugins/sources/heroku/_meta.json, website/pages/docs/plugins/sources/k8s/_meta.json, website/pages/docs/plugins/sources/okta/_meta.json, website/pages/docs/plugins/sources/terraform/_meta.json
The `Tables ↗` pagination link at the bottom of each source plugin page doesn't work, for example in AWS:
https://www.cloudquery.io/docs/plugins/sources/aws/multi_account
The fix is similar to https://github.com/cloudquery/cloudquery/pull/3207, however I couldn't find a way to make the pagination link open in a new tab so this is only a partial fix.
=> fix(website): Fix source plugins tables pagination link

website/pages/docs/recipes/destinations/csv.md, website/pages/docs/recipes/destinations/postgresql.md, website/pages/docs/recipes/destinations/snowflake.md, website/pages/docs/recipes/destinations/sqlite.md, website/pages/docs/recipes/sources/aws.md, website/pages/docs/recipes/sources/azure.md, website/pages/docs/recipes/sources/gcp.md
The GitHub docs are deprecated and link back to our website
=> fix(website): Link directly to docs in recipes instead of GitHub

website/pages/docs/plugins/destinations/postgresql/overview.md
We support versions v10 and v20.2 (inclusive)
=> fix(website): Use `>=` instead of `>` for database versions

.github/workflows/dest_csv.yml
Don't think we need PostgreSQL for the CSV plugin
=> chore(ci): Remove postgres service from CSV plugin workflow

README.md
Since the reader is probably already on this page, it doesn't seem necessary to link to our Github repo from the word "open-source". 
The link is still included in the "Links" section lower down.
=> doc: Remove link to Github repo from word "open source"

cli/cmd/sync2.go
This fixes a hanging bug in recent versions of the CLI and some destination plugins (e.g. BigQuery, Snowflake). The actual bug is in the `GetTablesForSpec` SDK function, which should not return a flattened list of tables, but this fix for the CLI means the CLI will work with any version of `GetTablesForSpec` (even versions with the bug). 
I will follow up shortly with a fix for the SDK.
=> fix: Filter results of getTablesForSpec to top-level tables in CLI

.github/workflows/dest_csv.yml, .github/workflows/dest_postgresql.yml, .github/workflows/dest_sqlite.yml, .github/workflows/dest_test.yml, .github/workflows/source_cloudflare.yml, .github/workflows/source_datadog.yml, .github/workflows/source_digitalocean.yml, .github/workflows/source_gandi.yml, .github/workflows/source_github.yml, .github/workflows/source_heroku.yml, .github/workflows/source_okta.yml, .github/workflows/source_terraform.yml, .github/workflows/source_test.yml
Remove large runners from small plugins. I looked at the build times, and removed large runners from plugins that their build time is under 5m without the large runner
=> chore(ci): Remove large runners from small plugins

plugins/source/aws/policies/queries/ec2/eips_unused.sql
The unused EIP policy check is generating a lot of false positives because it only checks for association to an EC2 instance. this misses various other valid associations (e.g. NAT Gateways, AWS Transfer servers).
=> fix(aws): Unused EIP policy - check associations not instance_ids

website/pages/docs/recipes/destinations/bigquery.md
Left over from when the BigQuery plugin still (tried to) support `overwrite-delete-stale` mode. It now only supports `append` mode.
=> chore(website): Use append mode in BigQuery recipe

plugins/source/gcp/codegen/recipes/serviceusage.go, plugins/source/gcp/resources/services/serviceusage/services.go
Default pageSize is 50... This PR raises it to the maximum allowed, which is 200
[Docs here](https://pkg.go.dev/cloud.google.com/go/serviceusage/apiv1/serviceusagepb#ListServicesRequest)
=> feat(gcp): Increase PageSize for ServiceUsage

website/versions/source-aws.json
Reverts cloudquery/cloudquery#5479
Looks like there's a bug with this version
=> fix: Revert "chore: Update plugin `source-aws` version to v7.3.1"

plugins/source/aws/client/helpers.go, plugins/source/aws/resources/services/lambda/functions_fetch.go
Fixes https://github.com/cloudquery/cloudquery/issues/5525
I kept the `IsNotFoundError` as that seems to be the pattern for everything in AWS. Also not sure if we should return `nil` or set the `Item`. I think since it's a pre resource resolver we have to?
=> fix(aws-functions): Return error in case of access denied

.github/workflows/wait_for_required_workflows.yml
Otherwise `plugins/source/azure` matches `plugins/source/azuredevops` files, see https://github.com/cloudquery/cloudquery/pull/5558
=> chore(ci): Add slash when matching actions to files

website/pages/docs/plugins/sources/aws/multi_account.md
Get Session Token referenced IAM Roles.  Get-Session-Token is a call used for either IAM Users or AWS Account (root), not IAM Roles.
This is a quick fix, eventually may move this block somewhere else or remove it if it's not necessary.
=> fix: Documentation for AWS: Get Session Token Language

plugins/source/aws/codegen/services/generate.go
This error was not being checked and could be hiding errors from the codegen user.
=> fix(aws-codegen): Check error returned by formatAndWriteFile

scripts/table_diff/changes/changes.go, scripts/table_diff/changes/changes_test.go
This improves the table diff comment for primary keys. From the current comment:
It can be understood that the column was removed, but actually the primary key was removed
=> fix(table-diff): Improve primary keys comments

plugins/source/aws/CONTRIBUTING.md, plugins/source/aws/Makefile, plugins/source/aws/codegen/recipes/elasticsearch.go, plugins/source/aws/docs/tables/aws_elasticsearch_domains.md, plugins/source/aws/resources/services/elasticsearch/domains.go, plugins/source/aws/resources/services/elasticsearch/domains_fetch.go, plugins/source/aws/resources/services/elasticsearch/domains_mock_test.go, plugins/source/aws/resources/services/elasticsearch/tags_fetch.go, plugins/source/aws/resources/services/elasticsearch/tags_fetch_mock_test.go
feat(aws): Make `arn` primary key of `aws_elasticsearch_domains`. Rename `id` column to `domain_id`
BREAKING CHANGE: Rename `id` column to `domain_id` for `aws_elasticsearch_domains`
=> fix(aws)!: Fix PK in `aws_elasticsearch_domains`

.github/workflows/broken_links.yml
This uses the latest version of `wait-for-vercel`, specifically with:
1. New deps https://github.com/patrickedqvist/wait-for-vercel-preview/pull/44
2. Better error messages on network errors https://github.com/patrickedqvist/wait-for-vercel-preview/pull/36
I'm hoping 2. will help us debug the failing broken links CI failures
=> fix(ci-broken-links): Update `wait-for-vercel` to latest commit sha

.github/workflows/release_plugin.yml, .github/workflows/source_aws.yml
Default Go Releaser timeout is `30m`, apparently not good enough for the AWS plugin:
https://github.com/cloudquery/cloudquery/actions/runs/3742575350/jobs/6353695699#step:6:45
=> chore(release): Increase Go releaser timeout

website/pages/docs/plugins/sources/aws/configuration.md
Fix a typo introduced in https://github.com/cloudquery/cloudquery/pull/5942
=> fix(website): Fix aws config

website/components/Footer.tsx
Adds a link to the latest blog post from the footer of our pages. This is a simple change that is intended to make our new blog posts a bit more visible from the website, serendipitously driving more readers to new blog posts.
Before: 
After:
=> chore(website): Add latest blog post to footer

.github/workflows/broken_links.yml
A workaround to https://github.com/patrickedqvist/wait-for-vercel-preview/issues/45.
This should fix the broken links CI workflow when a build is ignored on Vercel.
I'm using negated logic `!= false` as we also run this check on a schedule and manually. Otherwise we need to set multiple outputs (`skip-for-pr`, `skip-for-schedule`)
=> fix(ci): Skip broken links checks if build is ignored on Vercel

plugins/source/gcp/codegen/recipes/run.go, plugins/source/gcp/docs/tables/gcp_run_locations.md, plugins/source/gcp/resources/services/run/locations.go
Follow up to https://github.com/cloudquery/cloudquery/pull/5919. Fixes the description link for the `run_locations` table
=> fix(gcp_run_locations): Use correct description link

plugins/destination/bigquery/client/migrate.go, plugins/destination/bigquery/client/read.go
BigQuery migrations should not fail if there are extra columns present in the table. As long as the columns are not required, it should ignore those columns and add any extra ones required by CloudQuery table schemas. This allows users to add additional columns of their own, and it means that you can upgrade to a new minor version of a source plugin and roll back later without issues.
This is tested in the new tests added in https://github.com/cloudquery/plugin-sdk/pull/574
- Fixes https://github.com/cloudquery/cloudquery/issues/6364
=> fix(bigquery): Migrations: ignore extra columns in the table

plugins/destination/postgresql/client/read.go
The PostgreSQL read test should only read and return the columns defined in our schema. This will allow https://github.com/cloudquery/plugin-sdk/pull/574/files to pass.
=> fix(tests): Postgresql: Read only columns defined in the schema

plugins/destination/sqlite/client/migrate.go, plugins/destination/sqlite/client/read.go
There was a bug in the query that checks whether a table exists - it always found the table to not exist because `?` was being quoted. We also now select only the columns defined in the table schema, rather than all columns.
This will allow https://github.com/cloudquery/plugin-sdk/pull/574/files to pass.
=> fix: Fix SQLite migration logic

plugins/destination/snowflake/client/read.go
This changes the Read query to only select the columns defined in the table schema, so that user-defined columns are ignored. Since Read is only used in tests, this only affects testing right now.
This change should allow the new test in https://github.com/cloudquery/plugin-sdk/pull/574 to pass
=> fix(tests): Fix Snowflake read test

plugins/source/k8s/views/resource.sql
The column name "cq_table" of k8s_resources view created by source/k8s/views/resource.sql 
is inconsistent with the dashboard config in source/k8s/grafana/asset_inventory.json which use column "_cq_table"
Fix a typo by change: cq_table -> _cq_table in source/k8s/views/resource.sql
=> fix(k8s): Fix a typo in source/k8s/views/resource.sql: cq_table -> _cq_table

plugins/destination/mongodb/client/transformer.go, plugins/destination/neo4j/client/transformer.go, plugins/destination/postgresql/client/transformer.go
Looks like we didn't handle `nulls` well in all cases.
This should close https://github.com/cloudquery/cloudquery/issues/6333 and also the recent pg report that we got.
Side note: There is some boilerplate code here but I don't think there is a way to avoid it because we do want to give destinations an opportunity to decide what to do on `null` value which might not always be just send null as it can be empty `string` like in CSV or some other value.
=> fix(destinations): Handle nulls in JSONs

scripts/table_diff/changes/changes.go
While we [auto migrate type changes](https://github.com/cloudquery/cloudquery/blob/a4987ae191b9f5e660d29ca4a99f1469dd9e1fe7/plugins/destination/postgresql/client/migrate.go#LL110C8-L110C8) I believe those should still be considered breaking as they can impact how the data is queried
=> fix(table-diff): Mark type changes as breaking

website/pages/docs/plugins/sources/overview.mdx
We need to set the id where we can't easily use the name to link to the overview.
Another option is to update the login in https://github.com/cloudquery/cloudquery/blob/d089745836f4d6a3e862ea7a98e57fd5054fa970/website/components/PluginsTable.tsx#L65
to strip whitespaces when defaulting to `name`
=> fix(website): Set Id for Hacker News source plugin in overview table

plugins/source/gcp/docs/tables/gcp_resourcemanager_folders.md, plugins/source/gcp/resources/services/resourcemanager/folders.go
Looks like `organization_id` can be `nil`. `name` should be good enough:
https://github.com/cloudquery/cloudquery/blob/d90410764f8d3e3c0bed82db0a143885e0c90190/plugins/source/gcp/resources/services/resourcemanager/folders_fetch.go#L44
=> fix: Revert "fix(gcp-resources): Add `organization_id` and `name` as PK of `gcp_resourcemanager_folders`

website/pages/docs/plugins/sources/snyk/configuration.md
=> chore(docs): Remove reference to `SNYK_API_KEY` env variable

website/pages/_app.tsx
Add plausible analytics for two reasons:
1) I need that to work on the plausible plugin
2) we can check this out and we can keep it if we like it or remove later on if simple analytics is good enough for us (we don't need to add cookie consent to this analytics as well).
=> chore(website): Add plausible analytics

website/pages/docs/plugins/sources/_meta.json, website/pages/docs/plugins/sources/overview.mdx
I think the plugin needs to be in the `meta.json` as a route, otherwise our versions find replace logic doesn't work
=> fix(website): Add Plausible Analytics to meta.json

plugins/source/pagerduty/resources/services/incidents/incidents_fetch.go, website/pages/docs/plugins/sources/pagerduty/overview.md
This fixes an issue where only the last month of incidents were fetched (see `since` parameter in https://developer.pagerduty.com/api-reference/9d0b4b12e36f9-list-incidents#Query-Parameters).
Also copied some query examples from blog to docs.
=> fix: Fetch incidents with `dateRange="all"`, and add query examples to docs

website/pages/docs/advanced-topics/performance-tuning.mdx
Absolutely a nit, but using wildcard-matching to limit tables synced may be more effective than tuning concurrency settings.
=> doc: Reorder the points on the performance tuning page

plugins/source/azure/docs/tables/azure_security_secure_score_control_definitions.md, plugins/source/azure/resources/services/security/secure_score_control_definitions.go
=> fix(azure)!: Add `subscription_id` to `azure_security_secure_score_control_definitions` PK

cli/cmd/migrate.go, cli/cmd/sync.go
The error conditions were checking the wrong `err` variable, which can be an issue for v0 plugins.
=> fix: Fix discovery error check

plugins/source/k8s/client/client.go, website/pages/docs/plugins/sources/k8s/overview.mdx
Support running cloudquery k8s plugin in k8s cluster using serviceaccount.
We are using argo workflow(https://argoproj.github.io/argo-workflows/) to schedule the cloudquery k8s resource syncing every day in the k8s pod.  Currently the client in k8s plugin only support kubeconfig env,  so we need the pack the kubeconfig into the docker image or put it in a configmap, which is not the k8s-way. 
So we want to add the support to create the client  in k8s plugin  using k8s serviceaccount.
The changes in the PR is a little hack. Suggestions are welcomed. Thanks~
=> feat(k8s): Support running cloudquery k8s plugin in k8s cluster using serviceaccount

plugins/source/azure/docs/tables/azure_authorization_provider_operations_metadata.md, plugins/source/azure/resources/services/authorization/provider_operations_metadata.go
Related to #7269.
Fixes #7241.
=> fix(azure)!: Drop `subscription_id` from `azure_authorization_provider_operations_metadata`

plugins/source/azure/docs/tables/azure_cdn_edge_nodes.md, plugins/source/azure/resources/services/cdn/edge_nodes.go
=> fix(azure)!: Drop `subscription_id` from `azure_cdn_edge_nodes`

plugins/source/azure/docs/tables/azure_eventgrid_topic_types.md, plugins/source/azure/resources/services/eventgrid/topic_types.go
Fixes #7246.
Related to #7275.
=> fix(azure)!: Drop `subscription_id` from `azure_eventgrid_topic_types`

plugins/source/azure/docs/tables/azure_policy_data_policy_manifests.md, plugins/source/azure/resources/services/policy/data_policy_manifests.go
Fixes #7251.
Related to #7263.
=> fix(azure)!: Drop `subscription_id` from `azure_policy_data_policy_manifests`

plugins/source/aws/docs/tables/aws_cloudtrail_trails.md, plugins/source/aws/resources/services/cloudtrail/trails.go
Org wide Cloudtrails can span an account. ARN + region isn't enough for uniqueness as each trail would only show up once per region, rather than once per account per region...
=> fix(aws)!: PK for `aws_cloudtrail_trails`

plugins/source/github/client/mocks/mock_orgs.go, plugins/source/github/client/services.go, plugins/source/github/docs/tables/github_hook_deliveries.md, plugins/source/github/resources/services/hooks/deliveries.go, plugins/source/github/resources/services/hooks/deliveries_fetch.go, plugins/source/github/resources/services/hooks/hooks_test.go
Fixes https://github.com/cloudquery/cloudquery-issues/issues/468.
We need to `Get` the hook to resolve the request and response
fix(github-resources): Resolver Org Hooks request/response using GetHookDelivery
BREAKING-CHANGE: The `request` and `response` columns for `github_hook_deliveries` are now of type `JSON` instead of `String`.
=> fix(github-resources)!: Resolver Org Hooks request/response using GetHookDelivery

plugins/source/aws/docs/tables/README.md, plugins/source/aws/docs/tables/aws_ec2_ebs_volume_statuses.md, plugins/source/aws/resources/plugin/tables.go, plugins/source/aws/resources/services/ec2/ebs_volume_statuses.go, plugins/source/aws/resources/services/ec2/ebs_volume_statuses_fetch.go, plugins/source/aws/resources/services/ec2/ebs_volume_statuses_mock_test.go, plugins/source/aws/resources/services/ec2/ebs_volumes_fetch.go, website/pages/docs/plugins/sources/aws/tables.md
Fixes https://github.com/cloudquery/cloudquery/issues/7637.
To get status events, we need `DescribeVolumeStatus`.
I tested syncing statues, but events is a bit hard as those are created by AWS, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-volume-status.html?icmpid=docs_ec2_console#monitoring-vol-events
=> feat(aws-resources): Add EC2 EBS Volume Statuses

plugins/source/aws/docs/tables/aws_cloudformation_stacks.md, plugins/source/aws/docs/tables/aws_codebuild_projects.md, plugins/source/aws/docs/tables/aws_directconnect_connections.md, plugins/source/aws/docs/tables/aws_ec2_customer_gateways.md, plugins/source/aws/docs/tables/aws_redshift_clusters.md, plugins/source/aws/resources/services/cloudformation/stacks.go, plugins/source/aws/resources/services/codebuild/projects.go, plugins/source/aws/resources/services/directconnect/connections.go, plugins/source/aws/resources/services/ec2/customer_gateways.go, plugins/source/aws/resources/services/redshift/clusters.go
Copied from https://github.com/cloudquery/cloudquery/pull/7651
These resources use a list instead of our convention of map[string] for tags:
- aws_cloudformation_stacks
- aws_codebuild_projects
- aws_ec2_customer_gateways
- aws_redshift_clusters
This update fixes it.
=> fix(aws): Turn tags into maps

plugins/source/azure/policies/queries/security/default_policy_disabled.sql, plugins/source/azure/policies/views/policy_assignment_parameters.sql
I found a bug in the logic of CIS Azure Benchmark v1.3.0 Section 2.12 (`policy_assignment_parameters.sql` and `default_policy_disabled.sql`).
The current query takes json keys in the `property` column of the `azure_policy_assignments` table to make a view. But, an actual value of the column is below.
```json
{
"scope": "/subscriptions/cc9a41f6-4e32-4f28-8326-a3c49e7036a3",
"metadata": {
"createdBy": "ae1999e6-b000-4f94-8e1c-ece7b864e35b",
"createdOn": "2022-08-19T01:36:48.5129096Z",
"updatedBy": "64fd25ee-36e3-44e9-bf7a-96e411ae909f",
"updatedOn": "2023-02-08T03:00:27.2551198Z",
"assignedBy": "Security Center",
"parameterScopes": {},
"excludedOutOfTheBoxStandards": [
"PCI DSS 3.2.1",
"ISO 27001",
"SOC TSP"
]
},
"notScopes": [],
"parameters": {
"sqlServerAuditingMonitoringEffect": { …
```
=> fix(azure): Fix detecting logic for CIS Azure Benchmark v1.3.0 - 2.12

plugins/source/aws/docs/tables/aws_rds_certificates.md, plugins/source/aws/resources/services/rds/certificates.go
CLI Docs show that `arn` has no account in it:
```
{
"Certificates": [
{
"Thumbprint": "34478a908a83ae45dcb61676d235ece975c62c63",
"ValidFrom": "2015-02-05T21:54:04Z",
"CertificateIdentifier": "rds-ca-2015",
"ValidTill": "2020-03-05T21:54:04Z",
"CertificateType": "CA",
"CertificateArn": "arn:aws:rds:us-east-1::cert:rds-ca-2015"
}
]
}
```
=> fix(aws)!: Fix PK  for `aws_rds_certificates`

cli/cmd/analytics.go
This should fix so `brew install cloudquery` will install latest version and not a hotfix to a year old version 😆
=> fix(cli): Fix brew latest

plugins/destination/snowflake/client/transformer.go
Because of the way writing to snowflake works (i.e. via a JSON file), for text arrays, strings with nulls become screwed up a little (which fails our tests..).
["abc", "def\x00"] becomes, in snowflake, [`abc`, `def\u0000`] i.e. a string of length 4 becomes a string of length 9).
This fix does exactly the same thing we do in postgresql.
=> fix(snowflake): Strip nulls

plugins/destination/postgresql/client/transformer.go
because underlyting postgresql type is `timestamp without timezone`, we need to change it to UTC (otherwise we jsut strip TZ information, making the data bad).
=> fix: Postgresql timestamps

plugins/destination/snowflake/client/migrate.go, plugins/destination/snowflake/client/types.go
- Fix SQL queries (unnecessary '' and "").
- change snowflake types to their actual snowflake types (rather than aliases) https://docs.snowflake.com/en/sql-reference/data-types.html.
- convert "yes"/"no" strings to bool.
=> fix: Snowflake migrations

website/pages/docs/core-concepts/configuration.md, website/pages/docs/plugins/sources/aws/overview.mdx, website/pages/how-to-guides/how-to-load-infrastructure-data-into-athena.mdx
Fixes https://github.com/cloudquery/cloudquery/issues/7302
Brings back https://github.com/cloudquery/cloudquery/pull/7236 and https://github.com/cloudquery/cloudquery/pull/7238.
We need to use `filename` see https://github.com/cloudquery/cloudquery/issues/7302#issuecomment-1427051349
=> feat(website): Bring back code block titles

plugins/source/aws/views/athena/README.md, plugins/source/aws/views/athena/resources.sql
This adds a standalone SQL script that can be used to create an aws_resources view in Athena, similar to the Postgres one.
Provides an alternative option for https://github.com/cloudquery/cloudquery/issues/4383
=> doc: Athena Resource View Standalone SQL Script

plugins/source/aws/docs/tables/aws_quicksight_analyses.md, plugins/source/aws/docs/tables/aws_quicksight_dashboards.md, plugins/source/aws/docs/tables/aws_quicksight_data_sets.md, plugins/source/aws/docs/tables/aws_quicksight_data_sources.md, plugins/source/aws/docs/tables/aws_quicksight_folders.md, plugins/source/aws/docs/tables/aws_quicksight_group_members.md, plugins/source/aws/docs/tables/aws_quicksight_groups.md, plugins/source/aws/docs/tables/aws_quicksight_ingestions.md, plugins/source/aws/docs/tables/aws_quicksight_templates.md, plugins/source/aws/docs/tables/aws_quicksight_users.md, plugins/source/aws/resources/services/quicksight/analyses.go, plugins/source/aws/resources/services/quicksight/dashboards.go, plugins/source/aws/resources/services/quicksight/data_sets.go, plugins/source/aws/resources/services/quicksight/data_sources.go, plugins/source/aws/resources/services/quicksight/folders.go, plugins/source/aws/resources/services/quicksight/group_members.go, plugins/source/aws/resources/services/quicksight/groups.go, plugins/source/aws/resources/services/quicksight/ingestions.go, plugins/source/aws/resources/services/quicksight/tag_fetch.go, plugins/source/aws/resources/services/quicksight/templates.go, plugins/source/aws/resources/services/quicksight/users.go
closes https://github.com/cloudquery/cloudquery-issues/issues/488
fix(aws): Add `account_id` and region to `aws_quicksight_*` resources
BREAKING-CHANGE: fix(aws): Add `account_id` and region to `aws_quicksight_*` resources
fix(aws): Rename `user_arn` field to `arn` in `aws_quicksight_group_members`
BREAKING-CHANGE: Rename `user_arn` field to `arn` in `aws_quicksight_group_members`
=> fix(aws)!: Add `account_id` and `region` to `aws_quicksight_*` resources

website/pages/docs/reference/destination-spec.md, website/pages/docs/reference/source-spec.md
`{/**/}` is only needed for MDX files as that how comments work for that format.
For markdown files we need only ``
=> fix(website): Fix vale comments

plugins/source/aws/views/athena/README.md, plugins/source/aws/views/athena/main.go
This adds support for adding extra columns to the `aws_resources` view created for Athena. This is useful if you are using e.g. `year`, `month`, `day` partitioning and want this to be included in the view.
=> chore: Add support for extra columns in Athena aws_resources view

plugins/destination/mongodb/client/client_test.go, plugins/destination/mongodb/client/read.go, plugins/destination/mongodb/client/write.go, plugins/destination/mongodb/go.mod, plugins/destination/mongodb/go.sum
Updates MongoDB to the new SDK with the following issues discovered in the tests:
- In overwrite mode, for a table with no PKs we used an empty filter always overwriting. The fix is similar to https://github.com/cloudquery/cloudquery/pull/8259 to use all columns as the filter
- When reading timestamp the Go lib uses local timezone. We want to read it as UTC (assuming it's written as UTC).
=> feat(deps): Update MongoDB plugin-sdk to v1.38.2

plugins/destination/postgresql/client/migrate.go
Hot fix for Postgres. The real fix should be to add this option to the SDK, set it for the CQId column and use it in the destination
=> fix(migrate): Make `_cq_id` unique

.github/workflows/dest_clickhouse.yml, plugins/destination/clickhouse/queries/tables.go, plugins/destination/clickhouse/queries/testdata/create_table.sql, website/pages/docs/plugins/destinations/clickhouse/overview.mdx
Fixes https://github.com/cloudquery/cloudquery/issues/8400.
`22.1.2` is the minimal 22 version I could find
=> fix(migration): Don't add trailing comma to create table

website/pages/_meta.json
Same as https://github.com/cloudquery/cloudquery/pull/3207, to fix that plugins are always highlighted:
=> fix(website): Add route to plugins _meta.json

website/pages/_meta.json
Reverts cloudquery/cloudquery#8555
Looks like this has an unwanted side effect on not having the sidebar for plugins:
=> fix: Revert "fix(website): Add route to plugins _meta.json"

.github/workflows/broken_links.yml
The exclude patterns on our scheduled broken links check don't work since we prefix the URL with `/`, see https://github.com/cloudquery/cloudquery/actions/runs/4343157121/jobs/7584850108#step:7:6
This issue does not exist on pull requests, as the Vercel deploy URL does not end with a `/`
> On the scheduled workflow we don't wait for a deployment and check https://www.cloudquery.io
=> fix(ci): Remove trailing slash from URL on scheduled broken links check

.github/workflows/pr_labeler.yml
GitHub does not support more than 100 labels per PR, so the PR labeler action fails when that happens. There's ongoing work to fix it, see https://github.com/actions/labeler/pull/497, but I think we can ignore the action failures for now.
=> chore(ci): Ignore PR labeler errors

website/components/_app.tsx, website/package.json
I noticed that Google has been indexing some pages under different domains, e.g. `docs.cloudquery.io`, `v1.cloudquery.io` - this adds canonical links to point search engines to the main `www.` version of every page. I made use of the advice on this page https://rishimohan.me/blog/nextjs-canonical-tag to make sure it also works for ISR pages.
=> fix(website): Add canonical links

.github/renovate.json5
We have a few files that reference a specific Go Releaser version. This ensures those get updated.
See https://github.com/cloudquery/cloudquery/pull/8758/files#diff-abcfa13367f012b18849cd3068dab27b53c00480c8bc1dc164ad92d545880452
=> chore(ci-deps): Update Go Releaser version in Docker files

plugins/destination/s3/client/client.go, plugins/destination/s3/client/client_test.go, plugins/destination/s3/client/spec.go, plugins/destination/s3/client/spec_test.go, website/pages/docs/plugins/destinations/s3/_authentication.mdx, website/pages/docs/plugins/destinations/s3/_configuration.mdx, website/pages/docs/plugins/destinations/s3/overview.mdx
This causes consistent confusion to our users and also don't follow least privilege. This now should require only PutObject. The user anyway always knows where the bucket is located.
https://discord.com/channels/872925471417962546/873606591335759872/1083080462936838245
=> fix(dest-s3)!: Make region required and don't make getbucketlocation

website/components/_app.tsx, website/package-lock.json
~~Still testing this (hence the log message).~~
Deploy previews are not indexed by default, so we don't need the canonical. See https://vercel.com/guides/are-vercel-preview-deployment-indexed-by-search-engines.
If we keep the canonical, every time we add a new page to the Website our broken link check fails on the PR since the link uses the main domain, which doesn't have that page deployed yet
=> chore: Don't set canonical on non production builds

plugins/source/azure/resources/services/compute/virtual_machine_scale_set_vms.go
We need to explicitly set the `expand` option to get the scale set VM instance view
=> fix(azure-resources): Retrieve instance view when sync `azure_compute_virtual_machine_scale_set_vms`

website/components/pages/IntegrationSourceDestination.tsx, website/scripts/prebuild.tsx
Fixes an edge case in our integrations pages where someone selects a source and destination with the same id (e.g. MySQL->MySQL or Postgres->Postgres)
=> fix(website): Handle source -> dest integration with the same id

plugins/destination/mysql/client/migrate.go
This fixes a bug in the MySQL destination migration where it always required a forced migration since we didn't set the `NotNull` value for primary keys. See original comment https://github.com/cloudquery/cloudquery/pull/8438#discussion_r1118470405
=> fix(mysql-migrate): Properly set `NotNull` when a column is a primary Key

website/pages/docs/cq-vs-others/_meta.json
Fixes title of the `CloudQuery vs CloudSploit` page in the sidebar
=> chore(website): Update meta.json for CQ comparison pages

plugins/destination/s3/client/client.go
When using the S3 destination plugin, cloudquery failed with an Access Denied error around the test file despite correct permissions.
Beforehand the code used the plugins path (i.e. cloudquery/s3). That means it doesn't actually test the correct permissions. It should use the output path that is provided by the user.
=> fix: Use the correct path for test file

plugins/source/aws/docs/tables/README.md, plugins/source/aws/resources/plugin/tables.go, plugins/source/aws/resources/services/ec2/account_attributes.go, plugins/source/aws/resources/services/ec2/account_attributes_mock_test.go, website/pages/docs/plugins/sources/aws/tables.md, website/tables/aws/aws_ec2_account_attributes.md
Adds support for grabbing data from `Ec2.DescribeAccountAttributes`. Puts data into a new table `aws_ec2_account_attributes`
=> feat(aws): Add AWS EC2 AccountAttributes

website/components/mdx/_configure-authenticate-provider.mdx, website/components/mdx/_configure-destination.mdx, website/components/mdx/_configure-done.mdx, website/components/mdx/_configure-linux.mdx, website/components/mdx/_configure-source.mdx, website/components/mdx/_configure-start-syncing.mdx, website/components/mdx/_configure-sync-command-unix-precompiled.mdx, website/components/mdx/_configure-sync-command.mdx, website/pages/docs/quickstart/linux.mdx
Fixes https://github.com/cloudquery/cloudquery/issues/8943.
This seems like a lot of changes, but it mostly breaks `_configure.mdx` into multiple components so we can have `_configure.mdx` and `_configure-linux.mdx`. The latter uses a different sync command component that has `./cloudquery sync` instead of `cloudquery sync` (notice the `./` prefix).
There's some follow up to do here for MacOS quick start (and also for the integrations page), to switch from `cloudquery` to `./cloudquery` and back when someone clicks the corresponding table (i.e. `cloudquery` for Homebrew and `./cloudquery` for precompiled binary).
=> fix(linux-quickstart): Update sync command to use local binary

plugins/source/azure/resources/services/billing/accounts.go, plugins/source/azure/resources/services/billing/enrollment_accounts.go, website/tables/azure/azure_billing_accounts.md, website/tables/azure/azure_billing_enrollment_accounts.md
Related to https://github.com/cloudquery/cloudquery/issues/8929 (as to list consumption data we need to use a billing account ID as a scope).
Billing and enrollment accounts are not tied to a subscription so we shouldn't multiplex over those, and also remove the subscription ID column (hence the breaking change).
fix(resources): Don't list billing and enrollment accounts per subscription
BREAKING-CHANGE: Remove `subscription_id` column from `azure_billing_enrollment_accounts` and `azure_billing_accounts` tables.
=> fix(resources)!: Don't list billing and enrollment accounts per subscription

plugins/destination/postgresql/client/migrate.go, plugins/destination/postgresql/client/types.go
Fixes https://github.com/cloudquery/cloudquery/issues/9141. This will allow CloudQuery to sync to tables that had their schemas created by some external process, as long as the column can be normalized to a CloudQuery type. This is mostly useful for Postgres -> Postgres sync use cases right now. As we improve the internal type system, we should be able to do away with these training wheels and create the same column types on the destination as we find on the source for such cases.
The type normalization is copied from the [Postgres source](https://github.com/cloudquery/cloudquery/blob/main/plugins/source/postgresql/client/types.go)
=> fix(postgresql): Normalize types in Postgres destination

plugins/destination/file/client/client.go, plugins/destination/file/client/client_test.go, plugins/destination/file/client/read.go, plugins/destination/file/client/spec.go, plugins/destination/file/client/write.go, plugins/destination/file/go.mod, plugins/destination/file/go.sum, website/pages/docs/plugins/destinations/file/overview.mdx
Users can now use the following options to change the destination behavior:
1. `skip_header`: default is `false` which will mean the the first row will be the column headers
2. `delimiter`: default value is `,` but user can specify any single character
The underlying implementation for CSV and JSON is also being changed to Apache Arrow through the updated import of the `filetypes` library.
=> feat!: Add ability to override CSV File options (headers and delimiters)

plugins/destination/azblob/go.mod, plugins/destination/azblob/go.sum
Updates the filetypes library to v1.6.0, which now uses Apache Arrow as the underlying CSV implementation.
=> feat(azblob): Update to filetypes v1.6.0

plugins/destination/gcs/go.mod, plugins/destination/gcs/go.sum
Updates the filetypes library to v1.6.0, which now uses Apache Arrow as the underlying CSV implementation.
=> feat(gcs): Update to filetypes v1.6.0

plugins/source/azure/docs/tables/README.md, plugins/source/azure/resources/services/compute/virtual_machine_scale_set_vm_network_interfaces.go, plugins/source/azure/resources/services/compute/virtual_machine_scale_set_vm_network_interfaces_test.go, plugins/source/azure/resources/services/compute/virtual_machine_scale_sets.go, plugins/source/azure/resources/services/compute/virtual_machine_scale_sets_mock_test.go, website/pages/docs/plugins/sources/azure/tables.md, website/tables/azure/azure_compute_virtual_machine_scale_set_network_interfaces.md, website/tables/azure/azure_compute_virtual_machine_scale_sets.md
Fixes https://github.com/cloudquery/cloudquery/issues/9258.
The API to list VM Scale Set Network Interfaces is on the `armnetwork` module and not on the `armcompute` module
=> feat(azure-resources): VM Scale Set Network Interfaces

.github/workflows/release_summary.yml
This is required so the new commit triggers workflow runs (using the default GitHub token won't do that)
=> fix(ci-release-summary): Set `cq-bot` as commit author

.github/ISSUE_TEMPLATE/bug_report.yml
`cloudquery --version` is the correct command
=> fix(issue-templates): Use `cloudquery --version` instead of `cloudquery version`

.github/workflows/release_summary.yml
My previous fix in https://github.com/cloudquery/cloudquery/pull/9340 was wrong as we need to set the token on the checkout action, see https://github.com/cloudquery/cloudquery/blob/main/.github/workflows/manual_commands_triggers.yml#L30
=> fix(ci): Release summary token v2

plugins/source/aws/resources/services/ec2/image_attributes.go
Verified that it seems like you can only make this call for images that you own:
``` bash
% aws ec2 describe-images --image-ids ami-0f54834d636a9e96f  --region us-east-1 --query "Images[0].OwnerId"       
"286198878708"
% aws ec2 describe-image-attribute --image-id ami-0f54834d636a9e96f --attribute launchPermission --region us-east-1
An error occurred (AuthFailure) when calling the DescribeImageAttribute operation: Not authorized for image:ami-0f54834d636a9e96f
```
Note `286198878708` is not an account that we own (based on google searches it seems to be an account owned by an AWS Service team
=> fix(aws): Only resolve ec2 image launch permissions when the image is owned by the AWS Account

.github/workflows/release_summary.yml
https://github.com/cloudquery/cloudquery/pull/9260 broken the logic that detects if we already added a summary to a PR to avoid a recursive workflow.
This PR fixes the logic and makes it more robust by looking at number of commits instead of the content of the PR
=> fix(release-summary): Only run the summary workflow if the PR has 1 commits

website/pages/docs/plugins/sources/azure/_configuration.mdx
A follow up to https://github.com/cloudquery/cloudquery/pull/9355, and related to https://github.com/cloudquery/cloudquery/issues/9269#issuecomment-1482441047.
Since we recommend the env variables auth method we can remove the `concurrency` setting from the docs, as with variables auth it should not be needed, unless syncing the `["azure_compute_skus", "azure_*_definitions","azure_authorization_role_assignments"]`, which this PR adds to `skip_tables`.
=> feat(website-azure): Update Azure docs to skip some tables, remove concurrency

plugins/source/stripe/codegen/recipes/all.go, plugins/source/stripe/codegen/recipes/recipes.go, plugins/source/stripe/codegen/templates/list.go.tpl, plugins/source/stripe/resources/services/prices/prices.go
Use the [expand parameter](https://stripe.com/docs/api/expanding_objects) to include fields on the `stripe_prices` table.
Other tables might also be affected, it might be worth considering exposing a config option.
=> fix(stripe): Expand fields on prices

plugins/destination/clickhouse/client/spec.go, website/pages/docs/plugins/destinations/clickhouse/overview.mdx
feat(clickhouse)!: Read only plain `ca_cert` value
BREAKING-CHANGE: Stop reading `ca_cert` value as file path. See [file variable substitution](/docs/advanced-topics/environment-variable-substitution#file-variable-substitution-example) for how to read this value from a file.
=> feat(clickhouse)!: Read only plain `ca_cert`

website/pages/docs/plugins/sources/mysql/overview.mdx
The title should be `MySQL` and not `PostgreSQL`
=> fix(website): Use correct title for MySQL source plugin

website/components/pluginData.tsx, website/scripts/prebuild.tsx
I got bit by this in https://github.com/cloudquery/cloudquery/pull/9511, and apparently also `MySQL` but didn't notice.
If we have duplicate IDs the last one takes.
See current integration for MySQL:
https://www.cloudquery.io/integrations/mysql/file
It should show the example configuration, but it doesn't as it takes the values on the `unpublished` kind.
=> chore(website): Fail prebuild script on duplicate plugin ids

plugins/source/aws/policies/queries/iam/hardware_mfa_enabled_for_root.sql
The MFA policy isn't linking any MFA devices to the root user because the case of the Arn attribute is incorrect.
Note that this query doesn't strictly enforce the hardware MFA policy, as it only checks virtual MFA devices. I don't believe there is anyway for CloudQuery to detect hardware MFA devices that are associated with the root user, as the AWS API requires you to be logged in as root to do that.
=> fix: Fix case on arn attribute

.github/workflows/wait_for_required_workflows.yml
Related to https://github.com/cloudquery/cloudquery/pull/9736#issuecomment-1501606356. We've seen cases were apparently the GitHub JS SDK returns duplicate check runs, so adding a log for the ID to see what's up.
=> chore(ci): Log check run ID to detect duplicates

plugins/source/aws/resources/services/iot/thing_groups.go
Use `PreResourceResolver` to call `DescribeThingGroup` rather than calling sequentially
=> feat(aws): Parallelize resolution of `aws_iot_thing_groups`

plugins/source/aws/resources/services/iot/policies.go
Use `PreResourceResolver` to call `GetPolicy` rather than calling sequentially
=> feat(aws): Parallelize resolution of `aws_iot_policies`

plugins/source/aws/resources/services/iot/billing_groups.go
Use `PreResourceResolver` to call `DescribeBillingGroup` rather than calling sequentially
=> feat(aws): Parallelize resolution of  `aws_iot_billing_groups`

.github/workflows/source_aws.yml, .github/workflows/source_azure.yml, .github/workflows/source_gcp.yml, .github/workflows/source_k8s.yml
Short way instead of #9656.
Closes #9388
=> fix(workflows): Properly use caches in AWS, Azure, GCP, K8s workflows

website/pages/docs/plugins/destinations/clickhouse/_configuration.mdx, website/pages/docs/plugins/destinations/meilisearch/_configuration.mdx, website/pages/docs/plugins/destinations/mssql/_configuration.mdx, website/pages/docs/plugins/destinations/mysql/_configuration.mdx, website/pages/docs/plugins/sources/tailscale/_configuration.mdx
Removes some extra spacing present in a few plugin configs, bringing all configs into alignment.
=> chore(docs): Consolidate formatting for configs

.github/workflows/scripts/required_actions.js, .github/workflows/scripts/wait_for_required_workflows.js, .github/workflows/wait_for_required_workflows.yml
Split the logic into 2 distinct parts:
1. Define what actions are required to wait for
2. Actual waiting
Extends #10072
Tested by #10119
=> chore(ci): Splitting `wait-for-required-workflows` code

.github/workflows/broken_links.yml, website/pages/docs/plugins/sources/plausible/_authentication.mdx, website/pages/docs/plugins/sources/plausible/overview.mdx
It seems these links not working have been a temporary issue with  `plausible.io` or some kind of bot protection, as they work now:
This PR brings back the links and also excludes them from the broken links check as many external sites have some kind of bot protection
=> fix(website): Bring back plausible.io links

plugins/destination/sqlite/client/write.go, plugins/destination/sqlite/go.mod, plugins/destination/sqlite/go.sum
feat: Update to use arrow type system
BREAKING-CHANGE: This release introduces an internal change to our type system to use [Apache Arrow](https://arrow.apache.org/). This should not have any visible breaking changes, however due to the size of the change we are introducing it under a major version bump to communicate that it might have some bugs that we weren't able to catch during our internal tests. If you encounter an issue during the upgrade, please submit a [bug report](https://github.com/cloudquery/cloudquery/issues/new/choose).
=> fix(sqlite): Fix arrow memory leak

plugins/destination/postgresql/client/read.go
The function returns an error so we could do that instead of panicking (unless there's a specific reason to panic I'm missing)
=> fix: Return error instead of panicking

plugins/destination/sqlite/client/types.go
Related to https://github.com/koltyakov/cq-source-sharepoint/issues/19#issuecomment-1514954567.
SQLite doesn't have an official `timestamp` type but the Go lib takes care of it, see https://github.com/mattn/go-sqlite3/issues/748.
We had this type in `v1`, see https://github.com/cloudquery/cloudquery/blob/plugins-destination-sqlite-v1.3.6/plugins/destination/sqlite/client/types.go#L58
=> fix: Add timestamp type

plugins/source/aws/resources/services/s3/bucket_grants.go, plugins/source/aws/resources/services/s3/buckets.go
Was trying to look into an issue with S3 ACL Pks and removed this refactor from my investigation code. Removed all custom/resource specific parallelization to rely solely on the SDK provided parallelization
=> fix(aws): Remove Resource Specific Parallelization For S3 to use only the SDK parallelization 

plugins/source/aws/policies/queries/cloudtrail/enabled_in_all_regions.sql
This PR addresses inadequate criteria in the inner join of the policy query that checks whether AWS CloudTrail is enabled in all regions, [enabled_in_all_regions.sql](https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/policies/queries/cloudtrail/enabled_in_all_regions.sql)
Specifically, the fix handles the situation of a single global CloudTrail in a target AWS account by adding `region` criteria to the `inner join`. It also corrects the results when an Organization-wide CloudTrail is in place, by adding `account_id` criteria to the `inner join`.
This bug is identified in #10245.
=> fix: Add region criteria to inner join

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/new_destination_plugin.yml, .github/ISSUE_TEMPLATE/new_resource.yml, .github/ISSUE_TEMPLATE/new_source_plugin.yml
We already have a triage view that is based on an issue status, so we don't need the labels, see https://github.com/orgs/cloudquery/projects/7/views/11
=> chore(issue-templates): Remove `needs-triage` label from issue templates

plugins/source/aws/client/client.go, plugins/source/aws/client/testing.go, plugins/source/aws/resources/services/iam/credential_reports_mock_test.go
As a precursor to exposing table level options, the Spec will need to be accessible to the resolvers now in each resolver it can access it via 
```
cl := meta.(*client.Client)
cl.Spec.
```
=> feat(aws): Store Spec in Client

plugins/source/azure/resources/services/consumption/subscription_price_sheets.go
There was a bug in the original pagination code I wrote. See https://github.com/Azure/azure-sdk-for-go/issues/20671#issuecomment-1521307978
=> fix(azure-consumption): Update Price Sheets next link on new response when paginating

.github/workflows/broken_links.yml
Looks like Twitter started failing our broken links checker https://github.com/cloudquery/cloudquery/actions/runs/4795606927/jobs/8530378774#step:7:42
=> fix(ci-broken-links): Exclude twitter

plugins/source/snyk/client/client.go, plugins/source/snyk/client/multiplexer.go, plugins/source/snyk/client/organizations.go, plugins/source/snyk/client/testing.go, plugins/source/snyk/docs/tables/README.md, plugins/source/snyk/go.mod, plugins/source/snyk/go.sum, plugins/source/snyk/resources/plugin/plugin.go, plugins/source/snyk/resources/services/group/group_members.go, plugins/source/snyk/resources/services/group/groups.go, plugins/source/snyk/resources/services/group/groups_mock_test.go, plugins/source/snyk/resources/services/organization/members.go, plugins/source/snyk/resources/services/organization/organizations.go, plugins/source/snyk/resources/services/organization/organizations_mock_test.go, plugins/source/snyk/resources/services/organization/provisions.go, website/pages/docs/plugins/sources/snyk/tables.md, website/tables/snyk/snyk_group_members.md, website/tables/snyk/snyk_groups.md, website/tables/snyk/snyk_organization_members.md, website/tables/snyk/snyk_organization_provisions.md
Adds 4 new tables to the Snyk plugin: `snyk_groups`, `snyk_group_members`, `snyk_organization_members` and `snyk_organization_provisions`.
- Closes https://github.com/cloudquery/cloudquery/issues/10172
- Closes https://github.com/cloudquery/cloudquery/issues/10173
- Closes https://github.com/cloudquery/cloudquery/issues/10174
=> feat(snyk): Add Groups, Group Members, Organization Members and Pending User Provisions

website/pages/docs/plugins/sources/aws/configuration.md
The old link seems to have moved and is now returning 404.
=> doc: Fix AWS profile link

plugins/source/postgresql/client/cdc.go, plugins/source/postgresql/resources/plugin/plugin_test.go
user reported unable to sync postgresql table named `user` (which is a pg reserved word). This PR adds sanitization to table names to ensure all identifiers are properly handled
=> fix(postgresql): Ensure all table names are escaped

plugins/source/aws/resources/services/wafregional/rule_groups.go, plugins/source/aws/resources/services/wafregional/rule_groups_mock_test.go, website/tables/aws/aws_wafregional_rule_groups.md
SSIA
The implementation is almost same as `waf` one
https://github.com/cloudquery/cloudquery/blob/4d76c37eed0502821f7490a7fe310407b0ef0e4c/plugins/source/aws/resources/services/waf/rule_groups.go#L87-L112
=> feat(aws): Add rule_ids to wafregional rule_group

cli/cmd/sync_v0.go, cli/cmd/sync_v1.go, cli/internal/plugin/manageddestination/plugin.go, cli/internal/plugin/manageddestination/unix.go, cli/internal/plugin/manageddestination/windows.go
- Change text in output message from `with for` to `for`
- Change `source` to `destination` in `manageddestination` package
=> fix: Fix typos in CLI output text and logs

plugins/destination/s3/client/client.go, plugins/destination/s3/client/write.go, plugins/destination/s3/client/write_test.go, website/pages/docs/plugins/destinations/s3/overview.mdx
file plugin supports `{{FORMAT}}` but looks like we were missing it here.
=> feat(s3): Support `{{FORMAT}}` placeholder

plugins/source/aws/client/account.go, plugins/source/aws/client/client.go, plugins/source/aws/client/multiplexers.go
When syncing `aws-cn` the cloudfront region should be set to `cn-north-1`  when partition is `aws-gov` then there is no cloudfront so no reason to set the multiplexer
=> fix(aws): Handle Cloudfront Regions in different partitions

plugins/source/aws/policies/queries/ecs/ecs_services_with_public_ips.sql
When I run the query of ECS.2 in foundational policies, I have noticed that resource_id became null if there is no ECS service in a ECS cluster.
Thus, we don't have to use `left join` to detect the rule. Only just seek `aws_ecs_cluster_services` table.
=> fix(aws): Fix the case where resrouce_id is null in ECS.2 of foundational policy

plugins/source/github/client/client.go, plugins/source/github/client/spec.go, website/pages/docs/plugins/sources/github/_configuration.mdx
Implements: https://github.com/cloudquery/cloudquery/issues/10696
Adding support for GHE based on the request found [here](https://github.com/cloudquery/cloudquery/issues/10696)
Didn't increase the coverage cause the GitHubEnterpriseClient from go-github is basically a duck-type githubClient.
=> feat: Add GitHub Enterprise support on GitHub source

plugins/destination/gremlin/client/spec.go, plugins/destination/gremlin/client/transformer.go, plugins/destination/gremlin/client/write.go, website/pages/docs/plugins/destinations/gremlin/overview.mdx
Neptune doesn't support list types ([among other things](https://docs.aws.amazon.com/neptune/latest/userguide/access-graph-gremlin-differences.html)) so we need to represent lists as strings.
The option defaults to `false` (assuming we have more Neptune users than Apache TinkerPop users it was worded as such)
Fixes #10839
=> feat(gremlin): Add `complete_types` option

plugins/source/okta/client/client.go, plugins/source/okta/client/spec.go, website/pages/docs/plugins/sources/okta/overview.mdx
Users have no visibility into the requests that CQ is making, which makes debugging nearly impossible. This PR allows users to see all of the requests being made
=> feat(okta): Enable SDK Debug Logs

website/pages/docs/plugins/destinations/gremlin/_meta.json, website/pages/docs/plugins/destinations/gremlin/types.md
gremlin is one of those funny destinations where we persist almost everything as string.
https://cloudquery-890gp0r69-cloudquery.vercel.app/docs/plugins/destinations/gremlin/types
tinkerpop types [doc](https://tinkerpop.apache.org/docs/current/reference/#_data_types) wasn't very ~good~ clear so I purposefully didn't link it.
=> doc(gremlin): Document supported types

plugins/source/firestore/client/list_tables.go, plugins/source/firestore/client/sync.go
=> fix(timestamp): Use `time.Time` in `__created_at` & `__updated_at` resolvers

plugins/destination/mongodb/client/client.go, plugins/destination/mongodb/client/uint64.go, plugins/destination/mongodb/client/write.go, plugins/destination/mongodb/go.mod, plugins/destination/mongodb/go.sum
Extracted from https://github.com/cloudquery/cloudquery/pull/11150 as MongoDB failed when trying to insert `unit64` that overflows `int64`, see https://github.com/cloudquery/cloudquery/actions/runs/5176150331/jobs/9324604882#step:8:14.
The solution is to use a custom encoder to save the value as `int64`. When the value is read, if you cast it back to `unit64` you'd get the original value, so there's no dataloss.
=> fix(deps): Update module github.com/cloudquery/plugin-sdk/v3 to v3.10.3

website/pages/how-to-guides.mdx
=> fix(website): Grammar fix on how-to-guide main page

plugins/source/aws/resources/services/ec2/instances.go, plugins/source/aws/resources/services/wafv2/web_acls.go, plugins/source/aws/resources/services/wafv2/web_acls_mock_test.go
Prior to fix resolver only grabs ALB resources which is the default value. WebACL can also be attached to Cognito, AppSync and API Gateway resources.
=> fix(aws): Resolve All types of attached Resources in `aws_wafv2_web_acls`

plugins/destination/mysql/client/schema.go
This is a follow up to https://github.com/cloudquery/cloudquery/pull/11360 to ensure `blob/text` SQL types have their PK configured correctly.
It also has another PK fix related to the arrow migration to avoid creating a duplicate index for columns that have all `Unique,NotNull,PrimaryKey` flags set
=> fix(dest-mysql): Set key prefix for `blob/text` PK columns

plugins/source/firestore/resources/plugin/plugin.go
Reverts cloudquery/cloudquery#11429
This doesn't work, as while it adds the internal columns those are not populated with values so the destination writes fail
=> chore: Revert "fix: Add internal columns"

plugins/source/oracledb/client/list_tables.go, plugins/source/oracledb/client/types.go, plugins/source/oracledb/client/types_test.go
Fixes https://github.com/cloudquery/cloudquery/issues/11538. This is a breaking change since now if a `number` has precision it will create a float type column at the destination.
Parsing the precision and scale is take from https://github.com/cloudquery/cloudquery/pull/11115/files#diff-619acf691639d4d0288b58b3814d54d67a93f4774f22d61dc5812348ef099b4c and I'll port the query update from this PR to https://github.com/cloudquery/cloudquery/pull/11115
feat: Support number type with precision and scale
BREAKING-CHANGE: Support for parsing `number` type precision and scale was added. As a result number columns with scale that is different than `0`, e.g. `number(6,2)` will be converted to `float` type at the destination instead of `int`. You might need to either run with …
=> feat!: Support number type with precision and scale

plugins/destination/duckdb/client/write.go
Follow-up for https://github.com/cloudquery/filetypes/issues/137
=> fix: Write buffered parquet files

cli/cmd/sync.go, cli/cmd/testdata/multiple-sources-destinations.yml
This fixes the case where different sources are specified in one config, syncing to their own destinations. Previously the code incorrectly assumed that all sources should sync to all destinations.
Tested with the following config:
```yaml
kind: source
spec:
name: xkcd1
path: hermanschaaf/xkcd
version: v2.0.0
destinations: ["postgresql_schema1"]
tables: ["*"]
spec:
---
kind: source
spec:
name: xkcd2
path: hermanschaaf/xkcd
version: v2.0.0
destinations: ["postgresql_schema2"]
tables: ["*"]
spec:
---
spec:
name: postgresql_schema1
registry: "github"
path: cloudquery/postgresql
version: "v4.2.1"
spec:
connection_string: "postgresql://postgres:pass@localhost:5432/cloudquery?sslmode=disable&search_path=test1"
---
spec:
name: postgresql_schema2
registry: …
```
=> fix: Fix syncing multiple sources to multiple non-overlapping destinations

plugins/source/aws/resources/services/s3/buckets.go, plugins/source/aws/resources/services/s3/buckets_mock_test.go, plugins/source/aws/resources/services/s3/models/s3.go, website/tables/aws/aws_s3_buckets.md
Thank you for implementing this amazing project.
I added ~`is_public_by_policy`~ `policy_status` to `WrappedBucket`.
Though AWS shows the criteria ([criteria](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html#access-control-block-public-access-policy-status)), It is difficult for me to conclude whether a s3 bucket which uses bucket policy is public or not.
so I suggest the way using `GetBucketPolicyStatus` API in this PR.
=> feat(aws): Add PolicyStatus to WrappedBucket

website/pages/docs/plugins/sources/heroku/_meta.json
Closes https://github.com/cloudquery/cloudquery/issues/11681
=> doc(website): Remove broken Configuration link from Heroku docs

plugins/source/gcp/codegen/client/discover.go
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16
=> refactor: Remove refs to deprecated io/ioutil

plugins/destination/mysql/client/schema.go
Currently when CQ is syncing to MySQL the query to get all tables returns tables in ALL schemas, not just the schema that the user specified in the connection string. This means that if a user is syncing data from the same plugin multiple times to different schemas the finding tables function will never be able to tell the difference between the same table name in different schemas...
The fix is to only return tables from the current database if it is selected... Users that do not specify a default database in their DSN/connection string will continue to have issues though... In a following PR we should add in validation that will require a default DB `select database()` should return a value that is not null...
=> fix(mysql): Handle Multiple Schemas

plugins/source/aws/docs/tables/README.md, plugins/source/aws/resources/services/codebuild/source_credentials.go, website/pages/docs/plugins/sources/aws/tables.md, website/tables/aws/aws_codebuild_builds.md, website/tables/aws/aws_codebuild_source_credentials.md
`builds()` in two different, (looks like unrelated) resources.
Fixes https://github.com/cloudquery/cloudquery-issues/issues/580
=> fix(aws): Codebuild builds

.github/styles/Vocab/Base/accept.txt, website/pages/docs/plugins/sources/jira/_authentication.mdx, website/pages/docs/plugins/sources/jira/_configuration.mdx, website/pages/docs/plugins/sources/jira/_meta.json, website/pages/docs/plugins/sources/jira/overview.mdx, website/pages/docs/plugins/sources/jira/tables.md, website/pages/docs/plugins/sources/jira/tables/jira_boards.md, website/pages/docs/plugins/sources/jira/tables/jira_fields.md, website/pages/docs/plugins/sources/jira/tables/jira_issues.md, website/pages/docs/plugins/sources/jira/tables/jira_priorities.md, website/pages/docs/plugins/sources/jira/tables/jira_projects.md, website/vercel.json
This is a very draft version for documentation for our first premium plugin - Jira.
Some more fine tuning might be needed but this should be a good start and a buy link is available at `https://cloudquery.io/buy/jira` (after this PR is merged)
=> chore(website): Add Jira premium plugin

website/pages/docs/plugins/sources/gandi/_configuration.mdx, website/pages/docs/plugins/sources/gandi/overview.mdx, website/pages/docs/plugins/sources/googleads/_configuration.mdx, website/pages/docs/plugins/sources/googleads/overview.mdx, website/pages/docs/plugins/sources/heroku/_configuration.mdx, website/pages/docs/plugins/sources/heroku/overview.mdx, website/pages/docs/plugins/sources/launchdarkly/_configuration.mdx, website/pages/docs/plugins/sources/launchdarkly/overview.mdx, website/pages/docs/plugins/sources/mixpanel/_configuration.mdx, website/pages/docs/plugins/sources/mixpanel/overview.mdx, website/pages/docs/plugins/sources/plausible/_configuration.mdx, website/pages/docs/plugins/sources/plausible/overview.mdx, website/pages/docs/plugins/sources/slack/_configuration.mdx, website/pages/docs/plugins/sources/slack/overview.mdx, website/pages/docs/plugins/sources/tailscale/_configuration.mdx, website/pages/docs/plugins/sources/tailscale/overview.mdx, website/pages/docs/plugins/sources/vercel/_configuration.mdx, website/pages/docs/plugins/sources/vercel/overview.mdx, website/vercel.json
Instead of https://github.com/cloudquery/cloudquery/pull/12026.
Some more fine tuning is needed and still missing redirect for vercel but should be good for first version.
=> chore(website): Add premium plugins

plugins/source/aws/client/testing.go
Currently we are only validating that the top level table has no empty columns... This change ensures we validate all relations as well
=> fix(aws): Validate table relations not just top level table

.github/workflows/source_aws.yml
Current workflow uses cq cli `v3.5` to run a sync, which fails because new protocol requires at least v3.6
=> chore(aws): Fix AWS release workflow

.github/workflows/broken_links.yml, website/pages/blog/proto-v3.mdx
The link to `incremental syncs` was broken so I fixed it. Also excluded the links to `mongodb.com` as it seems they have some kind of bot protection.
Finally, changed all the links in the blog to absolute ones so it's easier to understand to what they resolve
=> chore(website): Fix broken link in `proto-v3` blog

website/utils/integrations.js
Fixes the static integration paths for premium plugins that don't have directories in the prebuilt location anymore
=> fix: Fix paths for premium plugins

plugins/source/aws/resources/services/s3/buckets.go
closes #12163 
Now that we are using go v1.20 we can use the `err.join` that allows us to group errors together. 
S3 columns are resolved sequentially by grouping errors we can try each one and return all of the errors at once
=> fix(aws): Make S3 column resolvers non-blocking

.github/renovate.json5
This should reduce the noise of PRs such as https://github.com/cloudquery/cloudquery/pull/12166 by not updating `plugin-pb-go` in plugins. `plugin-pb-go` is an indirect dependency for plugins and should be updated via the SDK anyways.
=> chore(deps): Disable `plugin-pb-go` dep updates in plugins

.github/workflows/broken_links.yml, website/pages/how-to-guides/update-plugins-using-renovate.mdx
The regex101 site has been down on and off for at least a week now and it affects our broken links checker. I think let's exclude it from the checks for the time being. Time will tell whether regex101 will come back online or not
=> chore(website): Exclude Regex101 from broken links check

plugins/source/oracledb/client/client.go
I missed this in https://github.com/cloudquery/cloudquery/pull/11711.
Without this fix we will always migrate all tables. The sync still works on the filtered tables, so this only impacts migration
=> fix: Filter tables in Tables function

.github/workflows/broken_links.yml
Our broken links checker considers redirects as broken links, so we need to exclude them.
=> fix(broken-links-checker): Exclude `register_for_cloud`

plugins/source/aws/resources/services/lambda/function_versions.go, website/tables/aws/aws_lambda_function_versions.md
This PR is aimed to address #12391 by creating a composite primary key on `aws_lambda_function_versions` table comprising `function_arn` and `version`.
Since `function_arn` will always be unique, `account_id` or `region` are not required to be part of the primary key.
This is my first PR against the codebase, extra pair of eyes are highly recommended!
=> feat(aws)!: Define composite primary key for lambda_function_versions

plugins/source/aws/resources/services/dynamodb/table_continuous_backups.go, website/tables/aws/aws_dynamodb_table_continuous_backups.md
This PR is aimed to address #12395 by creating a primary key (`table_arn`) on `aws_dynamodb_table_continuous_backups` table.
=> feat(aws)!: Define primary key for dynamodb_table_continuous_backups

plugins/source/aws/resources/services/s3/bucket_encryption_rules.go, website/tables/aws/aws_s3_bucket_encryption_rules.md
This PR is aimed to address #12392 by creating a primary key (`bucket_arn`) on `aws_s3_bucket_encryption_rules` table.
=> feat(aws)!: Define primary key for s3_bucket_encryption_rules

plugins/destination/snowflake/client/deletestale.go, plugins/destination/snowflake/client/migrate.go, plugins/destination/snowflake/client/read.go, plugins/destination/snowflake/client/write.go
In Snowflake, quoted uppercase column names are treated as case insensitive as opposed to quoted lowercase names. Lowercase ("cased") column names need to be quoted every time they are referred, uppercase column names don't need to be.
- This PR updates every column from `"column_name"` to be `"COLUMN_NAME"` so they can be queried without quotes.
- Migration improvements:
- Table listing is limited to current schema (instead of whole database) and it will list the tables just once per migrate batch, instead of running that query for each table separately.
- If multiple-cased versions of the same column exist (for instance because of running the older Snowflake plugin again, after the migration by this PR) it will auto-correct by dropping the mismatching columns if `migrate_mode: forced` …
=> fix(snowflake)!: Make all quoted column names uppercase to support unquoted queries

plugins/source/aws/resources/services/ec2/regions.go, website/tables/aws/aws_regions.md
This PR is aimed to address #12414 by creating a composite primary key on `aws_regions` table comprising `account_id` and `region`.
With this key there will be one set of regions (27) per discovered AWS Account.
The reason why we're not limiting them to only one set of regions for all accounts is that different AWS Accounts can have different `opt_in_status` / `enabled` values for different regions.
=> feat(aws)!: Define composite primary key for regions

plugins/destination/snowflake/client/migrate.go, plugins/destination/snowflake/client/spec.go, website/pages/docs/plugins/destinations/snowflake/_configuration.mdx, website/pages/docs/plugins/destinations/snowflake/overview.mdx
With no limit (negative value) I get on latest AWS:
```
go run main.go migrate examples/aws-to-snowflake.yml  1.14s user 0.73s system 4% cpu 45.335 total
```
With the default (1 table at the time):
```
go run main.go migrate examples/aws-to-snowflake.yml  1.33s user 0.83s system 0% cpu 11:42.94 total
```
I made the default 1 to avoid what could be considered a breaking change. We can change it later if we need to
=> feat(migrate): Add `migrate_concurrency`

plugins/source/alicloud/client/spec.go, plugins/source/alicloud/client/testing.go
`deterministic_cq_id` should not be a part of the plugin spec. Marking as a `refactor` as it was never documented nor used
=> refactor(spec): Remove plugin level `deterministic_cq_id`

plugins/source/homebrew/internal/homebrew/analytics_test.go
The Homebrew plugin tests started failing due to an issue with the Homebrew analytics.
See several issues:
https://github.com/Homebrew/formulae.brew.sh/issues/830
https://github.com/Homebrew/brew/issues/13211
Looks like they are migrating to a new system 🤷 
It's broken on [their Website too](https://formulae.brew.sh/analytics/cask-install/30d/):
I simplified the test for now, otherwise this plugin blocks SDK and Arrow updates for all other plugins. See https://github.com/cloudquery/cloudquery/actions/runs/5642450454/job/15282353013
=> test(homebrew): Relax cask installs validation

plugins/source/gcp/resources/services/bigquery/datasets.go, plugins/source/gcp/resources/services/bigquery/datasets_fetch.go, plugins/source/gcp/resources/services/bigquery/datasets_mock_test.go, plugins/source/gcp/resources/services/bigquery/tables_fetch.go
Seems like we've been creating one extra client per dataset and then one extra client per table.
This PR changes it so that we're creating a single client for all datasets ~~, and another client for all tables per dataset~~ per multiplexer. Should help with the [429 errors](https://discord.com/channels/872925471417962546/873606591335759872/1132870724667834439) as each client authenticates again.
The PreResourceResolver pattern is only used in bigquery resources.
=> fix(bigquery): Create less clients per dataset/table

plugins/source/postgresql/client/sync.go
Discovered this while working on https://github.com/cloudquery/cloudquery/issues/12524.
If the table has a single column the PostgreSQL source fails to sync it
=> fix: Support syncing tables with a single column

plugins/destination/duckdb/client/client_test.go, plugins/destination/duckdb/client/read.go, plugins/destination/duckdb/client/transform.go, plugins/destination/duckdb/client/types.go
Fixes https://github.com/cloudquery/cloudquery/issues/12524
When reading `parquet` files, DuckDB seems to be failing to identify `date` types, thinks those are `timestamp without timezone` and fails since it doesn't know how to convert a timestamp to date. Found https://github.com/duckdb/duckdb/issues/1291 and other `parquet` related issues:
https://github.com/duckdb/duckdb/issues?q=is%3Aissue+is%3Aopen+parquet+
https://github.com/marcboeker/go-duckdb/issues?q=is%3Aissue+parquet+is%3Aclosed
The solution I found is to use `timestamp` to store date types when writing/reading to/from the temporary `parquet` file. It might take up a bit more space in the `parquet` file but it works.
We might want to look into skipping the temporary file if it's not a huge effort to do
=> feat: Support date types

plugins/destination/mssql/queries/values.go
Fixes https://github.com/cloudquery/cloudquery/issues/12577 (can also be reproduces by syncing only `azure_compute_skus`)
It was a bit hard to for me to understand the code, but it seems we use `NewTableFromRecords` to map an array of records with length of `batch_size` to a single Arrow table. This means the resulting table will have `batch_size` number of rows, with each column having `number_of_schema_columns` chunks, where each chunk of arrays is of `batch_size` length. Each array that is a part of the chunk of arrays has the underlying data from the source (think of a chunk of a way to manage a collection of arrays).
See
https://github.com/cloudquery/arrow/blob/b7ee35bf784acdf7af50f7776ce8b9dd8117a4c2/go/arrow/array/table.go#L177 …
=> fix: Don't use row index for accessing chunk data

scaffold/cmd/source.go, scaffold/cmd/templates/source/client/client.go.tpl, scaffold/cmd/templates/source/main.go.tpl, scaffold/cmd/templates/source/resources/plugin/client.go.tpl, scaffold/cmd/templates/source/resources/plugin/plugin.go.tpl, scaffold/cmd/templates/source/resources/services/table.go.tpl
Fixes https://github.com/cloudquery/cloudquery/issues/12643
Had to refactor the templating engine code a bit as now we have different template files with the same name (`client.go.tpl` under `client` and under `resources/plugin`.
Go templating engine doesn't load templates recursively so I used `fs.WalkDir` to avoid having to manually map template files to output files.
=> fix: Create separate plugin client package

plugins/source/aws/resources/services/codecommit/repositories.go
In initial version we made an erroneous assumption about ListRepos not returning more than BatchGetRepos could handle. It turns out if more than 100 repos are returned by ListRepositories, then BatchGetRepos will fail...
=> fix(resources): Handle Pagination for AWS Code Commit Repositories

website/pages/_meta.json
Policies menu item is always bolded, this fixes it.
I also moved CSPM to the bottom of the menu because I think this makes it look a bit better (the long text stands out against the other text otherwise)
=> fix(website): Fix bold policies menu

cli/cmd/sync_v3.go
Before this change, an error in this part of the code obscures the name of the destination that failed, and can make it seem like it was actually the source inititialization that failed.
Related to https://github.com/cloudquery/cloudquery/issues/12656
=> fix: Add name of destination to error on init

website/pages/docs/plugins/sources/fastly/_configuration.mdx
Fixing something I noticed while browsing plugin docs. Without this, the integration pages will all show `postgresql` regardless of the destination being synced to.
=> doc: Use DESTINATION_NAME in Fastly configuration docs

plugins/source/pagerduty/resources/services/incidents/incidents_fetch.go
PagerDuty incidents listing API will fail when trying to retrieve more than 10 000 incidents.
```
HTTP response failed with status code 400, message: Arguments Caused Error (code: 2002): Offset+limit exceeds maximum allowed value of 10000. Please try to refine your search to reduce the returned set of records below this number, like adding a date range.
```
This PR update `fetchIncidents` to fetch incidents in increments of 90 days and workaround this limitation.
=> fix: Workaround 10k fetch incident limit in PagerDuty

plugins/source/datadog/resources/plugin/plugin.go, plugins/source/datadog/resources/plugin/plugin_test.go
The last versions of Datadog plugin do not work and generate the following message:
>  plugin not initialized. call Init() first
The `newClient` function return `nil,nil` if the configuration is good. It should return the client initialized.
I wrote also some extra tests to prevent regression.
=> fix: Return a datadog client instance instead of nil

website/pages/docs/plugins/sources/aws/configuration.md
Use correct markdown format for links
=> chore: Fix link to plugin versioning in AWS config docs

plugins/destination/postgresql/client/client.go, plugins/destination/postgresql/client/list_tables.go, plugins/destination/postgresql/client/migrate.go, plugins/destination/postgresql/client/types.go, plugins/destination/postgresql/pgarrow/to_arrow.go, plugins/destination/postgresql/pgarrow/to_arrow_test.go
Based on the findings from #12765 & #12870:
1. Handle `numeric(20,0)` as `uint64` from the database schema
2. Fix `numeric(20,0)[]` reported as `numeric[]` from CockroachDB
3. Always perform normalization even for the new tables
=> fix: Normalization logic for new & existing tables differences

plugins/source/test/Dockerfile.goreleaser
The test plugin release workflow [started failing](https://github.com/cloudquery/cloudquery/actions/runs/5821978644/job/15785571460#step:7:54) with the latest version of Go Releaser (released yesterday).
I believe the change that broke it is this https://github.com/goreleaser/goreleaser/pull/4218.
This PR updates the docker file to match the fix
=> chore: Fix test plugin docker configuration

plugins/destination/snowflake/client/client.go, plugins/destination/snowflake/client/spec.go, plugins/destination/snowflake/client/spec_test.go, website/pages/docs/plugins/destinations/snowflake/overview.mdx
A new `private_key` option for connecting to Snowflake using a keypair. Takes care of properly formatting the key, allowing the user to specify their private key using a `${file:priv.key}` substitution from a raw PEM file.
This change supersedes https://github.com/cloudquery/cloudquery/pull/12965 which attempted to let the user specify [gosnowflake.Config](https://pkg.go.dev/github.com/snowflakedb/gosnowflake#Config) but this proved unwieldy.
Closes  #12598
=> feat: Snowflake private_key config option.

.github/workflows/release_cli.yml, .github/workflows/release_scaffold.yml
Doing this as a part of cleaning up some of the secrets in this repo. I gave the GitHub open source team access to `cloudquery/homebrew-tap`  so now we can use the `GH_CQ_BOT` token to publish to that repo instead of a dedicated token (I'll delete it after the PR is merged)
=> chore: Use GH_CQ_BOT token for publishing to Homebrew

plugins/source/postgresql/client/cdc.go, plugins/source/postgresql/client/sync.go, plugins/source/postgresql/client/transform.go
1. Instead of performing type switch for every row for every column, just remember it once for the value transformation
2. reuse the record builder (per `NewRecord` resetting the record builder for reuse)
=> feat: Simplify value transformation

plugins/source/gcp/resources/services/storage/buckets.go, website/tables/gcp/gcp_storage_buckets.md
Context in https://discord.com/channels/872925471417962546/1141351009545879612/1141361426284425246.
The GO SDK for buckets doesn't mimic the JSON API, they have a different object struct for some reason, see https://github.com/googleapis/google-cloud-go/blob/fbe78a28e01043b059e86c6e960d092b299ac9a4/storage/bucket.go#L753
Not sure why they wrap is and normalize some properties instead of retuning the raw bucket (which they have).
This PR links to the Go docs instead of the JSON API docs so it's easier to understand the data CloudQuery sync
=> fix(resources): Link to Go docs in `gcp_storage_buckets`

plugins/source/airtable/src/spec.ts
The Airtable JS SDK calls it API key, but the official term is access token
=> fix: Rename spec option from `api_key` to `access_token`

plugins/source/airtable/src/airtable.ts, plugins/source/airtable/src/plugin.ts, plugins/source/airtable/src/tables.ts
Fixes detecting and parsing of Airtable `dateTime` type. Also adds a log message when getting the tables
=> fix: Airtable `dateTime` type handling

plugins/source/github/client/client.go
Fixes https://github.com/cloudquery/cloudquery/issues/13163. We were re-using the list options (hence the pagination page) between organizations
=> fix: Re-init `RepositoryListByOrgOptions` for each organization when listing repositories

plugins/source/typeform/plugin/plugin.py
Fix JSON login by instantiating a logger and passing it in to the scheduler.
Closes https://github.com/cloudquery/plugin-sdk-python/issues/44
=> fix: Fix JSON logging

plugins/source/github/client/client.go, plugins/source/github/client/spec.go, website/pages/docs/plugins/sources/github/_configuration.mdx, website/pages/docs/plugins/sources/github/overview.mdx
Related to https://github.com/cloudquery/cloudquery/issues/13163. Adds `discovery_concurrency` like other plugins to improve discovery speed (currently defaults to `1` as can be considered breaking).
Using the following config I saw a `25%` improvement (Google has ~2.5k repositories and Microsoft has ~5.8K`):
```yaml
kind: source
spec:
...
tables:
- github_repositories
skip_dependent_tables: true
spec:
discovery_concurrency: -1
orgs:
- microsoft
- google
destinations:
- postgresql
```
=> feat: Add `discovery_concurrency` sync option

cli/cmd/migrate.go, cli/cmd/migrate_v2.go, cli/cmd/sync.go, cli/cmd/sync_v2.go
Fixes https://github.com/justmiles/cq-source-crowdstrike/issues/5.
We should apply the schema and record transformations when the source is v2 and the destination is v3, otherwise pks are not removed in `append` mode, sync time and source name columns are not added, etc.
**This probably impacts all community/partners plugins as I believe those haven't upgraded to SDK v4.**
Tried to do this the less possible ugly way I could think of.
Tested with:
```yaml
kind: source
spec:
name: azure
path: cloudquery/azure
version: v8.3.0 # v2 source
destinations: ["bigquery", "postgresql"]
tables: ["azure_storage_*"]
---
spec:
name: bigquery
path: cloudquery/bigquery
version: "v3.3.0" # v3 destination
write_mode: "append"
spec:
project_id: ****
dataset_id: ****
--- …
```
=> fix: Apply schema and record transformations for v2 sources with v3 destinations

plugins/source/aws/client/client.go
In original implementation service could be recreated and service would end up being nil when actually used
=> fix: Race condition in Initializing services

cli/cmd/migrate_v2.go, cli/cmd/sync_v2.go
Follow up to https://github.com/cloudquery/cloudquery/pull/13291.
Fixes https://github.com/justmiles/cq-source-crowdstrike/issues/5.
v2 sources already add these columns so we shouldn't duplicate them. I didn't catch this during my tests since I already had the tables in the database so the destination skipped creating them.
=> fix: Don't add source name and sync time columns for v2 sources and v3 destinations

plugins/destination/postgresql/client/client.go, plugins/destination/postgresql/client/insert.go, plugins/destination/postgresql/client/list_tables.go, plugins/destination/postgresql/client/migrate.go
Extracted from https://github.com/cloudquery/cloudquery/pull/13318. Witnessed the bottleneck using `pprof`.
With default batch settings I'm getting `2m29s` sync time instead of ~`11m`,
With `batch_size_bytes: 100000000` and `batch_timeout: 60s` I'm getting `1m40s`. (Fixed in https://github.com/cloudquery/cloudquery/pull/13324)
Used spec:
```yaml
kind: source
spec:
name: aws
path: "cloudquery/aws"
version: "v19.0.0"
tables:
- "*"
skip_tables:
- "aws_cloudtrail_*"
- "aws_iam_*"
- "aws_servicequotas_*"
destinations:
- postgresql
---
spec:
name: "postgresql"
registry: "grpc"
path: localhost:8888
spec:
connection_string: "postgresql://postgres:pass@localhost:5432/postgres?sslmode=disable"
```
=> fix: Don't list Postgres tables during insert

website/versions/destination-postgresql.json
Reverts cloudquery/cloudquery#13325
So I can fix https://github.com/cloudquery/cloudquery/pull/13323 when `--no-migrate` is used
=> chore: Revert "chore: Update plugin `destination-postgresql` version to v5.0.6"

plugins/destination/postgresql/client/client.go, plugins/destination/postgresql/client/insert.go, plugins/destination/postgresql/client/list_tables.go
Follow up to https://github.com/cloudquery/cloudquery/pull/13323 to handle `--no-migrate`. Thanks @candiduslynx for pointing it out
=> fix: Call list tables once on insert if `--no-migrate` was used

plugins/destination/postgresql/client/insert.go, plugins/destination/postgresql/client/list_tables.go, plugins/destination/postgresql/client/migrate.go
`exclude` was always passed as an empty list. Also we can use `tables.TableNames()`
=> refactor: Clean up list tables method

website/versions/source-aws.json
Due to https://github.com/cloudquery/cloudquery/issues/13389 until https://github.com/cloudquery/cloudquery/pull/13391 is out
=> chore: Revert AWS version in docs to `v22.6.0`

plugins/destination/postgresql/client/insert.go, plugins/destination/postgresql/client/list_tables.go, plugins/destination/postgresql/client/migrate.go
Somehow the change in https://github.com/cloudquery/cloudquery/pull/13332 got reverted, I think unintentionally.
This is however necessary as part of a fix for https://github.com/cloudquery/cloudquery/issues/13412
=> fix: Drop include clause from list tables

plugins/source/hackernews/resources/plugin/client.go
This ensures that the backend state is persisted between syncs
=> fix: Flush state backend so that state is persisted

cli/cmd/sync_v3.go
This fixes a bug introduced with the migration to SDK v4 / Protocol v3; when `overwrite-delete-stale` write mode is used, stale entries should not be removed from incremental tables when a state backend is active.
=> fix: Skip incremental tables when performing delete-stale

plugins/source/alicloud/resources/services/bss/bill_fetch.go
Fix HistoryBillingCycles. when data is 28~31,month without 02 or another without 31 month.
=> fix!: Fix Bill without Feb

.release-please-manifest.json, plugins/source/bitbucket/CHANGELOG.md
This reverts commit 45af1c9abf7cba031831fcf494e53873a4a94d7b.
So we can re-release v1.0.0 after fixing the CI
=> chore: Revert "chore(main): Release plugins-source-bitbucket v1.0.0 (#13493)"

.github/workflows/lint_markdown.yml
The version we're using is quite old, as they only pushed changes to the main branch now https://github.com/errata-ai/vale-action. This PR uses the latest commit sha. I'm hoping it can fix some things like
=> chore: Update vale linter

plugins/source/postgresql/client/list_tables.go, plugins/source/postgresql/client/sql/list_tables.sql
A no-op refactoring to move to using an `embed` SQL string ready for https://github.com/cloudquery/cloudquery/pull/13612
relates: https://github.com/cloudquery/cloudquery/pull/13612
=> chore: Refactor SQL query into embed file

plugins/source/postgresql/client/sql/list_tables.sql, plugins/source/postgresql/resources/plugin/plugin_test.go
Duplicate columns can occur if multiple constraints are added to a single column. Adding `group by` terms to remove duplicate constraint columns. Boolean fields in the `group by` are aggregated using `bool_or`, the `constraint_name` resolves to the primary key constraint name or an empty string if there is no named constraint. This is all that is required by [this](https://github.com/cloudquery/cloudquery/blob/51e4d572ec343f2bceefae21f0a16963bd8e1d2a/plugins/source/postgresql/client/list_tables.go#L52-L54) part of the code.
fixes: #13459
=> fix: Duplicate columns when multiple contraints

plugins/source/aws/policies/queries/elb/elbv2_redirect_http_to_https.sql, website/tables/aws/aws_elbv2_listeners.md
Fix a bug in `plugins/source/aws/policies/queries/elb/elbv2_redirect_http_to_https.sql` that tries to match on uppercase "REDIRECT" while the data in `aws_elbv2_listeners` shows the lowercase "redirect" (see issue https://github.com/cloudquery/cloudquery/issues/13433 for detail).  This bug causes false positive matches in the aws policy.
Fixes https://github.com/cloudquery/cloudquery/issues/13433
=> fix: Issue #13433 - match on lowercase "redirect" in aws policy 

plugins/source/aws/client/spec.go, plugins/source/aws/resources/plugin/client.go, website/pages/docs/plugins/sources/aws/configuration.mdx
This wasn't moved into the AWS plugin before because there wasn't a strong need for it, but apparently some APIs (like account contacts) can benefit from this scheduler.
=> feat: Add scheduler option to AWS

website/pages/blog/announcing-cloudquery-aws-event-based-sync-beta.mdx
This is an update to the existing announcement of the AWS event-based sync to highlight that after the release to public, this is going to be a paid feature.
=> doc: Adding a note about a paid feature

website/pages/docs/developers/creating-new-plugin/javascript-source.mdx
So we always use the latest version
=> fix: Use latest SQLite plugin version in JS SDK docs

plugins/source/shopify/client/spec.go, plugins/source/shopify/internal/shopify/shopify.go, plugins/source/shopify/resources/plugin/client.go, plugins/source/shopify/resources/services/customer/customers_mock_test.go, plugins/source/shopify/resources/services/order/orders_mock_test.go, plugins/source/shopify/resources/services/product/products_mock_test.go, website/pages/docs/plugins/sources/shopify/overview.mdx
Fixes https://github.com/cloudquery/cloudquery/issues/13867
Also updates the default version to be `2023-01` (no changes to the APIs the plugin currently uses, according to [release notes](https://shopify.dev/docs/api/release-notes/2023-01)). Shopify API versions are usually supported for 1 year so it needs constant 'bumping'.
=> feat: Configurable API version, default version to 2023-01

plugins/source/gcp/resources/services/compute/osconfig_inventories.go
Should fix https://github.com/cloudquery/cloudquery/issues/13945
=> fix: Fetch all fields for `gcp_compute_osconfig_inventories`

plugins/source/firestore/client/client.go
See https://github.com/cloudquery/cloudquery/actions/runs/6328679225/job/17187394279#step:6:89 I missed this in https://github.com/cloudquery/cloudquery/pull/14102.
If we pass empty tables to `FilterDfs` it fails since there are no matches.
=> fix: Handle NoConnection

website/pages/docs/plugins/destinations/clickhouse/_configuration.mdx
Per the ClickHouse docs only `append` is supported https://www.cloudquery.io/docs/plugins/destinations/clickhouse/overview so we should set it in the config by default
=> chore: Set `write_mode: append` in example configuration

.github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml
We don't need to check the releaser type as we want to always publish these plugins to the Hub. This caused SQLite and DuckDB to be skipped as they have a Dockerfile preset:
https://github.com/cloudquery/cloudquery/actions/runs/6338691053
https://github.com/cloudquery/cloudquery/actions/runs/6339408118
Snowflake worked fine but doesn't need this part either:
https://github.com/cloudquery/cloudquery/actions/runs/6341384187
=> chore: Remove plugin_releaser from Hub CI for SQLite,Snowflake,DuckDB

plugins/source/datadog/client/client.go, plugins/source/datadog/client/spec.go, website/pages/docs/plugins/sources/datadog/_configuration.mdx, website/pages/docs/plugins/sources/datadog/configuration.mdx
Add configurable site to allow other DDog regional sites to be used, if no site is specified the existing behaviour is preserved.
fixes: https://github.com/cloudquery/cloudquery/issues/14265
=> feat: Add configurable site

plugins/source/datadog/resources/services/dashboards/dashboards.go, plugins/source/datadog/resources/services/dashboards/dashboards_mock_test.go, plugins/source/datadog/resources/services/monitors/monitors.go, plugins/source/datadog/resources/services/monitors/monitors_mock_test.go, plugins/source/datadog/resources/services/notebooks/notebooks.go, plugins/source/datadog/resources/services/notebooks/notebooks_mock_test.go, plugins/source/datadog/resources/services/slos/corrections.go, plugins/source/datadog/resources/services/slos/corrections_mock_test.go, plugins/source/datadog/resources/services/slos/slos.go, plugins/source/datadog/resources/services/slos/slos_mock_test.go, plugins/source/datadog/resources/services/synthetics/synthetics.go, plugins/source/datadog/resources/services/synthetics/synthetics_mock_test.go
Following on from https://github.com/cloudquery/cloudquery/issues/14187, adding support for other pagination calls which have been introduced in recent SDK versions.
fixes: https://github.com/cloudquery/cloudquery/issues/14190
=> feat: Add pagination support for endpoints

website/pages/blog/creating-a-new-js-plugin.mdx
We should use relative links so clicking them doesn't open a new tab and also they work on deploy previews.
Some of the links were also `http` which redirected to `https`
=> chore: Use relative links in `creating-a-new-js-plugin.mdx`

.github/workflows/publish_plugin_to_hub.yml, .github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml
Fixes https://github.com/cloudquery/cloudquery/actions/runs/6408182243/job/17396605792#step:6:16
Fixes https://github.com/cloudquery/cloud/issues/508 (internal issue)
Uses https://www.npmjs.com/package/shell-escape as it has ~250,000 weekly downloads (despite the repo latest commit being from 2015)
=> chore(ci): Escape release notes before passing to package command

cli/cmd/migrate.go, cli/cmd/sync.go, cli/cmd/sync_v2.go, cli/internal/specs/v0/source.go, cli/internal/specs/v0/spec_reader.go, plugins/destination/clickhouse/client/migrate.go, plugins/destination/clickhouse/queries/tables.go, plugins/destination/meilisearch/client/index.go, plugins/destination/mssql/client/changes.go, plugins/destination/mssql/client/columns.go, plugins/destination/mssql/queries/columns.go, plugins/destination/postgresql/client/transformer_test.go, plugins/source/aws/client/spec/tableoptions/change_case.go, plugins/source/googleanalytics/client/row.go, plugins/source/pagerduty/client/testing.go
This commit changes the slices to use the standard slices.
Since go1.21, slices package introduced standard library (see more info https://pkg.go.dev/slices@master)
cloudquery use Go 1.21, so I replaced.
=> chore: Replace standard slices package

.github/workflows/docs_changes_summary.yml
We're hitting rate limits with the built-in actions token so this switches to our own token. We can do it only for `pull_request_target` events (not `pull_request`)
=> chore: Use cq-bot token in Summarize changes workflow

.github/workflows/wait_for_required_workflows.yml, scripts/workflows/wait_for_required_workflows.js
Should help with https://github.com/cloudquery/cloudquery/issues/14464 hopefully. This changes our CI to use git based diffing instead of the GitHub API.
Also changes the polling internal to 15s instead of 5s
=> chore: Switch to git based diffing instead of API diffing

.github/workflows/manual_commands.yml
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only
We need slash commands only for PRs
=> chore: Evaluate slash commands only on PR comments

scripts/workflows/wait_for_required_workflows.js
We're still hitting rate limits in this workflow so hopefully this helps
=> chore: Increase polling time in wait for all workflow to avoid rate limits

.github/workflows/docs_changes_summary.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/14463. If we use our own `cq-bot` we need to update the comment author filter when finding an existing comment
=> chore: Fix `comment-author` filter in docs changes workflow

website/pages/docs/deployment/_meta.json, website/pages/docs/deployment/docker-offline.mdx
Adding docs explaining how to use `cloudquery install` to build a container that does not download plugins at runtime.
=> doc: How to build a container with preinstalled plugins

plugins/source/github/client/client.go, plugins/source/github/client/mocks/mock_actions.go, plugins/source/github/client/services.go, plugins/source/github/docs/tables/README.md, plugins/source/github/resources/plugin/tables.go, plugins/source/github/resources/services/actions/workflowJobs.go, plugins/source/github/resources/services/actions/workflowRunUsage.go, plugins/source/github/resources/services/actions/workflowRuns.go, website/pages/docs/plugins/sources/github/_authentication.mdx, website/pages/docs/plugins/sources/github/tables.md, website/tables/github/github_workflow_jobs.md, website/tables/github/github_workflow_run_usage.md, website/tables/github/github_workflow_runs.md
Closes #14311 
Adds tables for github_workflow_runs, github_workflow_run_usage, and github_workflow_jobs allowing to analyze GitHub Actions usage.  
In addition, added URL output to log for rate limiting for easier troubleshooting of secondary rate limits.
=> feat: Adding GitHub Actions workflowRuns, RunUsage, and Jobs

plugins/destination/snowflake/client/write.go
Fix for #14528
Previously PR was essentially a no-op since a migrate message is also passed from client.Write.
~Still needs testing.~
=> fix: Setup write before WriteMessage processing

cli/.goreleaser.yaml
Doesn't look like the [previous PR](https://github.com/cloudquery/cloudquery/pull/14515) worked as it published everything as `amd64` https://github.com/cloudquery/cloudquery/actions/runs/6531867504/job/17733917959#step:10:61
=> fix: Don't use templating in Dockers publish config

.github/workflows/dest_sqlite.yml, plugins/destination/duckdb/.goreleaser.yaml, plugins/destination/snowflake/.goreleaser.yaml, plugins/destination/sqlite/.goreleaser.yaml
In https://github.com/cloudquery/cloudquery/pull/14612 we added static linking to the DuckDB, SQLite and Snowflake plugins, but this broke Darwin buils. As it is only needed for Linux images I have added conditional overrides to the goreleaser yml config.
=> fix: Conditional static linking for linux/amd64 for DuckDB, SQLite and Snowflake

cli/cmd/switch_test.go, cli/go.mod, cli/go.sum
The xdg logic for configuraiton management is now available through the `cloudquery-api-go` dependency and is no longer needed as a direct dependency in the CLI.
=> chore: Removes the xdg (direct) dependency

website/scripts/prebuild.tsx
Follow up to https://github.com/cloudquery/cloudquery/pull/14648. Found out we don't really need the escaping and also it broken some of the content 😅
=> chore: Remove markdown escaping

.github/workflows/broken_links_scheduled.yml
`hub.cloudquery.io` now redirects to https://hub.cloudquery.io/plugins/source (the new Hub). I think we'd like to keep it that way instead of updating links to reference `https://hub.cloudquery.io/plugins/source` directly.
This adds an exclude to our broken links too as it fails on redirects
=> chore: Exclude `hub.cloudquery.io` from broken links check

cli/cmd/install.go
Extracted from https://github.com/cloudquery/cloudquery/pull/15000
Added some missing options to the `install` command.
We could probably also do `managedplugin.WithDirectory(cqDir)` directly without the condition as `cqDir` has a default so the only way it can be an empty string is when someone does `--cq-dir ""` (I tested that and it sets `cqDir` to an empty string).
Not doing the `cqDir` fix as that could be considered a breaking change fix (doing `--cq-dir ""` with the current code will use the default `.cq`)
=> fix: Add missing options to install command

plugins/source/aws/policies/queries/elb/elbv1_https_predefined_policy.sql, website/tables/aws/aws_elbv1_load_balancer_policies.md, website/tables/aws/aws_elbv1_load_balancers.md
`make gen-docs` outputs
```log
2023/10/26 13:53:13 Skipping query "Classic Load Balancers with HTTPS/SSL listeners should use a predefined security policy that has strong configuration" due to error: at or near ":": syntax error
```
=> fix: Change casting

cli/cmd/tables.go
Same as https://github.com/cloudquery/cloudquery/pull/15001 for the tables command
=> fix: Add missing options to tables command

cli/cmd/sync.go
Since the default for `OtelEndpoint` is an empty string we don't need the condition
=> refactor: Simplify sync command options

cli/cmd/migrate.go
Same as https://github.com/cloudquery/cloudquery/pull/15001 for the migrate command
=> fix: Add missing options to migrate command

.github/workflows/source_typeform.yml, plugins/source/typeform/plugin/tables/form_responses.py, plugins/source/typeform/tests/tables/test_forms.py, website/tables/typeform/typeform_form_responses.md, website/tables/typeform/typeform_forms.md
This adds the `tags` column to `typeform_form_responses` table.
Tags are useful for further data analysis of the responses.
=> feat: Add tags column to typeform plugin

plugins/destination/mssql/main.go
MSSQL publishing to the Hub fails since it's missing metadata https://github.com/cloudquery/cloudquery/actions/runs/6615875816/job/17968986032
(noticed since it was a spike on failed downloads in our monitoring).
Did a search and couldn't find other plugins that are missing it
=> fix: Add missing metadata

website/pages/docs/deployment/docker-offline.mdx
This updates the documentation on how to build containers for offline deployment based on the changes to the `cloudquery install` command.
=> doc: Update the docs on offline container

.github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml
We were still using stub docs for these plugins. This PR fixes it
=> chore: Fix docs publishing for DuckDB, Snowflakse, SQLite

.github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml
Seems like `rsync` [doesn't work as expected](https://github.com/cloudquery/cloudquery/actions/runs/6719832688/job/18262200668#step:9:11) on the cross compile image so trying a different approach
=> chore: Fix docs publishing cross-compile image

website/next.config.mjs, website/pages/docs/developers/publishing-a-plugin-to-the-hub.md, website/pages/docs/plugins/sources/file/_configuration.md, website/pages/docs/plugins/sources/file/overview.md, website/pages/docs/plugins/sources/heroku/_configuration.md, website/pages/docs/plugins/sources/heroku/overview.md, website/pages/docs/plugins/sources/slack/_configuration.md, website/pages/docs/plugins/sources/slack/overview.md, website/pages/docs/plugins/sources/tailscale/_configuration.md, website/pages/docs/plugins/sources/tailscale/overview.md
Part of cloudquery/cloudquery-issues#768 (internal issue). Adds the latest versions for the paid public plugins, see https://hub.cloudquery.io/plugins/source?tiers=paid.
I also removed the buy links from the configuration comments as I think the CLI should guide users to login when using these plugins.
Once this PR is merged we can publish new versions of the plugins with the new docs.
**Not in this PR** - latest versions in https://www.cloudquery.io/docs/plugins/sources/overview as it requires a bigger change to get the versions in the React component here https://github.com/cloudquery/cloudquery/blob/0971c8a49c6415eb9330f4d078f5ab7a37bd78ae/website/components/PluginsTable.tsx#L32
=> chore: Add latest version to public paid plugins

cli/cmd/login.go, cli/cmd/switch.go, cli/internal/auth/logout.go
This updates the login logic so that the team context is automatically set if a user is part of only one team. If the user is in multiple teams, a message is printed to indicate that `cloudquery switch <team>` will be needed.
=> fix: Set team context when logging in, and don't clear it when logging out

cli/internal/specs/v0/destination.go, cli/internal/specs/v0/source.go
This makes the error message clearer when you forget to add `v` for a CloudQuery registry plugin.
=> fix: Improve error message if version is specified incorrectly

plugins/source/mysql/docs/overview.md, plugins/source/oracledb/docs/overview.md, plugins/source/postgresql/docs/overview.md, website/components/pluginData.tsx
Adding plugin [documentation directories](https://github.com/cloudquery/cloudquery/blob/9fd925cf06a52c00b0189bf3d0c56f2d9afe0041/website/utils/plugins.js#L24) for plugins recently moved to `cloudquery-private`.
=> chore(website): Add plugin documentation directories

cli/cmd/addon_download.go, cli/cmd/addon_download_test.go, cli/cmd/addon_publish.go, cli/cmd/doc_test.go, cli/cmd/root.go, cli/cmd/testdata/addon-v1/manifest.json, cli/go.mod, cli/go.sum, website/pages/docs/reference/cli/cloudquery_addon_download.md
```
cloudquery addon download addon-team/addon-type/addon-name@v1.0.0
cloudquery addon download addon-team/addon-type/addon-name@v1.0.0 -t /path/to/dest/dir
cloudquery addon download addon-team/addon-type/addon-name@v1.0.0 -t - | jar t
```
(Apparently the regular infozip `unzip` can't read from stdin? but `jar` can...)
=> feat: Add `addon download` command

.github/workflows/wait_for_required_workflows.yml
See https://github.com/marketplace/actions/changed-files#output_all_modified_files for details
Causes odd behavior when there are only removed files for some workflow being run: https://github.com/cloudquery/cloudquery/pull/15188
=> fix(ci): Account for deleted files in CI as well

.github/renovate.json5
Similar to `plugin-pb-go`, `cloudquery-api-go` is an indirect dependency for plugins and will be updated via SDK updates. So no need for https://github.com/cloudquery/cloudquery/pull/15167
=> chore: Disable github.com/cloudquery/cloudquery-api-go updates for plugins

plugins/source/aws/resources/services/costexplorer/cost_custom.go
I suspect this was a copy-paste induced typo, as there's no other place in the `aws_alpha_costexplorer_cost_custom` resolver where we access the `CloudwatchMetrics` member of table options.
=> fix: Check proper table options for `aws_alpha_costexplorer_cost_custom`

cli/cmd/install.go, cli/cmd/migrate.go, cli/cmd/sync.go, cli/cmd/tables.go, cli/internal/auth/team.go, cli/internal/auth/token.go
This adds the team name to the managed plugins configuration, which will use the `/team/*` endpoints to download plugins - allowing plugin downloads to be attributed to the correct team
fixes: https://github.com/cloudquery/cloudquery-issues/issues/835
=> feat: Add teamName to managed plugin configuration

cli/cmd/plugin_docs_download.go, cli/cmd/plugin_docs_upload.go
`chore` because the commands are currently hidden.
=> chore: Update CLI `plugin docs` command help text

.github/workflows/publish_plugin_to_hub.yml, .github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml
Instead of doing version replacement in the UI this does it during publish.
=> chore: Embed latest version in docs during publish

.github/workflows/release_summary.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/15288. Fixes an old bug where trying to get the latest tag for `azure` sometimes gets the tag for `azuredevops`:
https://github.com/cloudquery/cloudquery/actions/runs/6890494479/job/18743654738#step:5:1
=> chore: Fix latest tag step

cli/cmd/addon_publish.go, cli/cmd/addon_publish_test.go, cli/cmd/testdata/addon-v1/manifest-embedded-message.json
=> fix: Addon publish command should take `message` as-is unless prefixed with `@`

plugins/source/gcp/client/transformers.go, plugins/source/gcp/docs/tables/gcp_artifactregistry_locations.md, plugins/source/gcp/docs/tables/gcp_cloudscheduler_locations.md, plugins/source/gcp/docs/tables/gcp_networkconnectivity_locations.md, plugins/source/gcp/docs/tables/gcp_run_locations.md
[`googleapi.RawMessage`](https://pkg.go.dev/google.golang.org/api@v0.151.0/googleapi#RawMessage) is documented as being JSON, but they were being converted to Arrow BINARY type. This was causing `gcp_networkconnectivity_locations.metadata` to not be handled as JSON.
=> fix!: Change `googleapi.RawMessage` column type from binary to JSON

plugins/source/azure/docs/tables/README.md, plugins/source/azure/docs/tables/azure_resources_providers.md, plugins/source/azure/resources/plugin/tables.go, plugins/source/azure/resources/services/resources/providers.go, plugins/source/azure/resources/services/resources/providers_mock_test.go
Added `azure_resources_providers` table, which retrieve azure resource provider information using the following rest api.
https://learn.microsoft.com/en-us/rest/api/resources/providers/list?view=rest-resources-2021-04-01&tabs=HTTP
=> feat: Add `azure_resources_providers` table

plugins/source/aws/docs/tables/aws_s3_bucket_cors_rules.md, plugins/source/aws/docs/tables/aws_s3_bucket_lifecycles.md, plugins/source/aws/docs/tables/aws_s3_bucket_loggings.md, plugins/source/aws/docs/tables/aws_s3_bucket_ownership_controls.md, plugins/source/aws/docs/tables/aws_s3_bucket_policies.md, plugins/source/aws/docs/tables/aws_s3_bucket_public_access_blocks.md, plugins/source/aws/docs/tables/aws_s3_bucket_replications.md, plugins/source/aws/docs/tables/aws_s3_bucket_versionings.md, plugins/source/aws/docs/tables/aws_s3_bucket_websites.md, plugins/source/aws/resources/services/s3/bucket_cors_rules.go, plugins/source/aws/resources/services/s3/bucket_lifecycles.go, plugins/source/aws/resources/services/s3/bucket_logging.go, plugins/source/aws/resources/services/s3/bucket_ownership_controls.go, plugins/source/aws/resources/services/s3/bucket_policies.go, plugins/source/aws/resources/services/s3/bucket_public_access_block.go, plugins/source/aws/resources/services/s3/bucket_replications.go, plugins/source/aws/resources/services/s3/bucket_versioning.go, plugins/source/aws/resources/services/s3/bucket_websites.go
Part of https://github.com/cloudquery/cloudquery/issues/15381
Closes https://github.com/cloudquery/cloudquery/issues/15476
fix: Provide primary keys for tables (S3) (https://github.com/cloudquery/cloudquery/pull/15494)
BREAKING-CHANGE: Provide primary keys for tables (S3) (https://github.com/cloudquery/cloudquery/pull/15494). The following tables are affected:
* `aws_s3_bucket_cors_rules`
* `aws_s3_bucket_lifecycles`
* `aws_s3_bucket_loggings`
* `aws_s3_bucket_ownership_controls`
* `aws_s3_bucket_policies`
* `aws_s3_bucket_public_access_blocks`
* `aws_s3_bucket_replications`
* `aws_s3_bucket_versionings`
* `aws_s3_bucket_websites`
=> fix!: Provide primary keys for tables (S3)

plugins/source/aws/resources/services/identitystore/groups.go, plugins/source/aws/resources/services/identitystore/instance_fetch.go, plugins/source/aws/resources/services/identitystore/users.go
New release by AWS supports multiple instances of AWS Identity Center Instances (formerly SSO Instances)
https://aws.amazon.com/blogs/security/how-to-use-multiple-instances-of-aws-iam-identity-center/
=> feat: Support Multiple Instances of AWS Identity Center Instances

cli/internal/docs/json.go, cli/internal/docs/testdata/TestGeneratePluginDocs-JSON-__tables.json
This should make it easier to add an indication for paid tables in plugins docs (additionally to the per table indication we have). Related to https://github.com/cloudquery/cloudquery-issues/issues/939 (internal issue)
=> feat: Add `isPaid` indication to JSON docs

plugins/destination/s3/docs/_configuration.md
S3 destination supports only append mode
=> chore: Add `write_mode: "append"` to s3 docs

.github/workflows/publish_plugin_to_hub.yml, .github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml
Part of https://github.com/cloudquery/cloudquery-issues/issues/765 (internal issue). This should allow us to push a pre-release tag and have it published to the Hub
=> chore: Handle pre-releases release notes during publishing to the hub

plugins/source/aws/client/service_names.go
This will allow using the proper service name like so
```go
client.ServiceAccountRegionMultiplexer(tableName, client.AWSServiceS3.String())
```
=> fix: Allow using service name from const directly

website/pages/docs/developers/creating-new-plugin/go-source.mdx
The directory scaffold example is outdated. This PR updates it to the current behavior of cq-scaffold. fixes #15645
=> chore: Update scaffold directory tree

cli/cmd/addon_download.go, cli/cmd/addon_publish.go, cli/cmd/plugin_docs_download.go, cli/cmd/plugin_docs_upload.go, cli/cmd/plugin_publish.go, cli/cmd/plugin_publish_test.go, cli/internal/hub/util.go, cli/internal/publish/addons.go, cli/internal/publish/plugins.go, cli/internal/publish/shared.go
Some refactoring to make it easier to support Docker publishing. This PR moves some functions to internal helper packages `publish` and `hub` instead of having all the code under the top level commands implementation.
=> refactor: Move publish helper functions to internal package

plugins/source/aws/resources/services/lambda/functions.go
Fixes https://github.com/cloudquery/cloudquery/issues/15727. Currently Lambda tags don't make it into the table due to a simple bug.
~I haven't tested this, and I'm not really sure how at the moment. There aren't already any unit tests I can leverage and I don't know how to install a custom plugin. Since this is such a simple change, I figured it was worth a shot submitting it anyway.~
I found the docs to test locally and used CloudQuery to write to a local file. The difference between my local plugin and the upstream plugin showed that this change worked as expected!
=> fix: Update lambda functions resolveTags() to use Tags field instead of Concurrency

plugins/source/aws/resources/services/lambda/functions.go, plugins/source/aws/resources/services/lambda/functions_mock_test.go
The happy path of `GetFunction` succeeding means that `ListTags` should not be called. This PR adds tests to ensure all paths are properly implemented
=> chore: Tags for Lambda Functions properly set

plugins/source/aws/resources/services/backup/vault_recovery_points.go
We noticed a lot of errors being thrown when syncing our `aws_backup_vault_recovery_points` table, upon further investigation we noticed that these errors were only being thrown when syncing DynamoDB backup resources. We also discovered this would only happen in an AWS account with [Advanced DynamoDB Backups](https://docs.aws.amazon.com/aws-backup/latest/devguide/advanced-ddb-backup.html) disabled.
[Apparently](https://docs.aws.amazon.com/aws-backup/latest/devguide/API_ListTags.html) the ListTags API can only be used for backups that support "Full Backup Management", which DynamoDB backups do not support without "Advanced DynamoDB Backups" enabled.
It looks like there might have been an attempt to fix this in the past but AWS have since changed their error codes and CloudQuery's fix no …
=> fix: Don't try to ListTags on DynamoDB backups if `Advanced DynamoDB Backups` is disabled

plugins/source/gcp/client/client.go, plugins/source/gcp/client/testing.go
Currently there is no way to test tables where nested tables use a different client type (gRPC vs Rest) as the endpoint is passed in via the `client.Options` ... The "cleanest" way to support this would be to have some sort of reverse proxy in front of the 2 types of test servers that proxies the requests to the correct endpoint.
This PR provides a way for the resolver to override the endpoint at resolve time rather than at plugin configuration time
=> chore: Support Mixed Client For GCP Testing

.github/workflows/source_airtable.yml
Since https://github.com/cloudquery/cloudquery/pull/15721/files#diff-a1b22c80628ca652952e2c245e1e591636ad67549f7b8180b3552faeb83316e1R75 the plugin requires Node.js 20 so the CI should reflect it
=> chore: Use Node.js 20 in source_airtable.yml

cli/internal/publish/plugins.go
The requirement for this header was added recently in the backend to track downloads, so the backend needs to know the team that's downloading the plugin. It's less relevant for the push operation though, but still needed. It's ok to use the team from the manifest - it just has to be any team the user is a part of. During push we already verify the token used to push has access to the team.
=> fix: Add `X-Meta-User-Team-Name` during docker push

cli/.golangci.yml
=> chore: Remove `perfsprint` linter

.github/workflows/publish_plugin_to_hub.yml, .github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml
Publishing to the Hub CI was set up before the backend supported API keys so I used a CLI token. Now that we support API keys this PR switches to use one
=> chore: Switch to API key from `cloudquery login` token

cli/cmd/plugin_publish.go, cli/go.mod, cli/go.sum, cli/internal/publish/plugins.go
Replaces https://github.com/cloudquery/cloudquery/pull/16191
=> fix(deps): Update module github.com/cloudquery/cloudquery-api-go to v1.6.5

plugins/destination/sqlite/client/migrate.go
This will mark unsupported schema changes as non-automigratable rather than panicing
=> feat: Handle All types of Schema Changes

plugins/source/aws/docs/tables/README.md, plugins/source/aws/docs/tables/aws_iam_mfa_devices.md, plugins/source/aws/docs/tables/aws_iam_users.md, plugins/source/aws/resources/services/iam/mfa_devices.go, plugins/source/aws/resources/services/iam/users.go, plugins/source/aws/resources/services/iam/users_mock_test.go
Resolves https://github.com/cloudquery/cloudquery/issues/16199
Add all `mfa_devices` listing for AWS IAM users.
Those ressources need to be fetch per user as the physical MFA devices cannot be retrieved via a list endpoint.
=> feat: Add mfa_devices for AWS IAM users

plugins/destination/mssql/main.go
This prevents this plugin from being published to the Hub.
Not sure when this broke since we have a few versions https://hub.cloudquery.io/plugins/destination/cloudquery/mssql/v4.3.15/versions?search=ms.
I added the wrong metadata in https://github.com/cloudquery/cloudquery/pull/15025/files (I think before it wasn't required and we got it from the CLI)
=> fix: Use team name instead of kind for team

cli/cmd/login.go, cli/internal/team/team.go
Closes https://github.com/cloudquery/cloudquery/issues/16298
The following scenarios have to be taken care of:
1. The user explicitly selects team via `--team` flag
2. The user has previously selected team
1. The team is available after login – use it
2. The team is unavailable – use the opt 3
3. Check that 1 & only 1 team is available for the user – & use it
=> fix: Properly set team on login

cli/.goreleaser.yaml
Reverts the last commit from https://github.com/cloudquery/cloudquery/pull/16231
=> chore: Add `cloudquery:latest` to manifest to support arm64

plugins/source/aws/client/spec/schema.json, plugins/source/aws/client/spec/spec.go, plugins/source/aws/docs/_configuration.md, plugins/source/aws/docs/configuration.md, website/pages/docs/advanced-topics/performance-tuning.mdx
The AWS team pointed out that our documentation has not been updated after the default scheduler was set to `shuffle`. This should correct it.
Instead of https://github.com/cloudquery/cloudquery-private/pull/1039
=> fix: Update `scheduler` doc & JSON schema

plugins/destination/file/client/client.go, plugins/destination/file/client/client_test.go, plugins/destination/file/client/spec.go, plugins/destination/file/client/spec_test.go, plugins/destination/file/docs/_configuration.md, plugins/destination/file/docs/overview.md
Additional changes:
1. Use direct embedding instead of pointer for file spec
2. Validate via file spec as well
=> fix!: Remove deprecated `directory` option

plugins/destination/file/docs/_configuration.md, plugins/destination/gcs/docs/_configuration.md, plugins/destination/kafka/docs/_configuration.md, plugins/destination/s3/docs/_configuration.md
=> fix: Use `write_mode` instead of `write-mode` in docs

plugins/source/okta/README.md, plugins/source/okta/client/spec.go, plugins/source/okta/docs/_authentication.md, plugins/source/okta/docs/_configuration.md, plugins/source/okta/docs/overview.md
Should be merged prior to https://github.com/cloudquery/cloudquery/pull/16493
=> fix!: Remove support for deprecated `OKTA_API_TOKEN` environment variable

.github/workflows/publish_plugin_to_hub.yml
Now that we're publishing to the Hub we shouldn't use the Go Releaser file to detect if this is a Go plugin
=> chore: Fix detection of Go Plugins

plugins/source/aws/docs/tables/aws_route53resolver_resolver_rules.md, plugins/source/aws/docs/tables/aws_s3_bucket_cors_rules.md, plugins/source/aws/resources/services/route53resolver/resolver_rules.go, plugins/source/aws/resources/services/s3/bucket_cors_rules.go
fix: Fix PrimaryKey component for `aws_route53resolver_resolver_rules ` to account for cross account and region sharing
fix: Fix PrimaryKey component for `aws_s3_bucket_cors_rules`
=> fix: Fix Multiple PKs

README.md
Fix the broken hub link in the docs (The www prefix was problematic). Took the liberty to actually mark them as links in markdown.
=> doc: Fix broken hub link

cli/cmd/migrate_v3.go, cli/cmd/specs.go, cli/cmd/sync_v3.go, cli/cmd/tables_v3.go, cli/go.mod
This PR adds spec validation before passing it to the plugin.
It also extracts the init logic into a handy `initPlugin` func.
The decision structure is the following (we allow a bit of leeway here if the schema provided isn't a correct JSON schema: the CLI will **skip validation** _instead of_ failing the sync/init)
```mermaid
flowchart TD
A{No Connection?} ----> |true| S
A{No Connection?} --> |false| G[Get spec schema]
subgraph validate
G --> |non-empty schema| P[parse schema]
G --> |failed call| E[error-out]
P --> |OK| V[validate spec]
V --> |failed| E
end
P --> |failed| S
G --> |unimplemented| S
G --> |empty schema| S
V --> |OK| I[init]
S[Skip validation] --> I  
```
=> feat: Validate plugin spec before init

plugins/source/aws/client/spec/schema.json, plugins/source/aws/client/spec/spec.go
Tried to enable AWS debug logs during working on auth related issues and didn't understand why I didn't see them
=> fix: Clarify that `aws_debug: true` needs debug log level

.github/workflows/broken_links.yml, .github/workflows/broken_links_scheduled.yml, website/vercel.json
Add redirects for the integrations pages
=> chore: Add intergrations redirects

plugins/destination/azblob/client/client.go, plugins/destination/duckdb/client/client.go, plugins/destination/elasticsearch/client/client.go, plugins/destination/file/client/client.go, plugins/destination/gcs/client/client.go, plugins/destination/gremlin/client/client.go, plugins/destination/meilisearch/client/client.go, plugins/destination/mongodb/client/client.go, plugins/destination/neo4j/client/client.go, plugins/destination/s3/client/client.go
Ensure that write errors are captured by passing a logger object to each writer
=> fix: Ensure all writers have a logger

plugins/destination/elasticsearch/client/read.go
If an index has never had data written to it, it will not exist. So if we read from a non-existant index we will get a 404. 
Rather than returning an error when hitting a 404 the `Read` command should just return `nil`.
=> fix: Handle 404 Error for read

cli/cmd/sync.go
Also needed for plugins that track usage (see error in https://github.com/cloudquery/cloudquery-issues/issues/1343 - internal issue)
=> fix: Always pass _CQ_TEAM_NAME to plugins

plugins/destination/bigquery/client/client.go, plugins/destination/clickhouse/client/client.go, plugins/destination/mysql/client/client.go, plugins/destination/snowflake/client/client.go, plugins/destination/sqlite/client/client.go
Prior to this PR, these destinations used the logger that was passed in to the function, this meant that it had the wrong `module` name
=> fix: Use Logger for Client rather than the one that is passed in

plugins/destination/duckdb/client/client.go, plugins/destination/duckdb/client/migrate.go, plugins/destination/duckdb/client/write.go
This was broken in https://github.com/cloudquery/cloudquery/pull/16668
Chore, because it wasn't released.
=> chore: Re-enable no-migrate option for DuckDB

website/next.config.mjs
Fixes https://github.com/cloudquery/cloudquery-issues/issues/1342
This should ensure Hub plugins version takes precedence over GitHub ones in our docs
=> chore: Fix replace versions logic to prioritize the Hub

.github/.kodiak.toml
See https://kodiakhq.com/docs/config-reference#mergemessagestrip_html_comments.
This is a better way to clean up the PR body from any template comments
=> chore: Use `strip_html_comments: true` instead of hard coded strings

plugins/source/github/client/client.go
We should pass the enterprise base URL to the package that handles app installation authentication https://github.com/beatlabs/github-auth?tab=readme-ov-file#enterprise
We do `WithEnterpriseURLs` on the GitHub go client, but we use a different package to handle app installation authentication.
=> fix: Pass enterprise base URL to app auth if needed

website/pages/how-to-guides/update-plugins-using-renovate.mdx
The registry config breaks the regex used to update plugins (see a bit below in the guide `kind:\s(?<kind>.*)\nspec:\n\s{2}name:.*?\w\n\s{2}path:\scloudquery\/(?<plugin>.*)\n\s{2}version:\s\"?v(?<currentValue>.*\d)\"?\n`)
=> chore: Update update-plugins-using-renovate.mdx

plugins/source/github/client/client.go
Reverts cloudquery/cloudquery#16834
This fix didn't work. I retracted the published version
=> chore: Revert "fix: Don't include `/api/v3/` in base URL passed to `inst.NewEnterpriseConfig`"

.release-please-manifest.json, plugins/source/github/CHANGELOG.md
Reverts cloudquery/cloudquery#16835
This fix didn't work so I'm reverting it
=> chore: Revert "chore(main): Release plugins-source-github v8.0.2"

plugins/destination/gremlin/client/client.go, plugins/destination/gremlin/client/schema.json, plugins/destination/gremlin/client/spec.go, plugins/destination/gremlin/client/spec_test.go, plugins/destination/gremlin/docs/_configuration.md, plugins/destination/gremlin/docs/overview.md
Recently tested AWS Neptune IAM auth over HAProxy and it didn't work.
=> feat: Provide `aws_neptune_host` option for Neptune IAM authentication over proxy

plugins/destination/s3/client/write.go, plugins/destination/s3/client/write_test.go
Instead of marshaling the `[]byte` array which obviously results in base64 encoding, pass objects to the `Append` directly.
fix: Properly replace JSON values when using `athena: true` (https://github.com/cloudquery/cloudquery/pull/16942)
BREAKING-CHANGE: Properly replace JSON values when using `athena: true` (https://github.com/cloudquery/cloudquery/pull/16942). Previously, `json` columns would have been sanitized & then marshaled twice, resulting in `base64` encoded bytes value. Now, the `json` columns have a proper object value.
=> fix!: Properly replace JSON values when using `athena: true`

plugins/destination/firehose/client/spec/spec.go, plugins/destination/firehose/docs/_configuration.md
* Set environment variables in configuration
* Fix default `max_retries` - preventing the default from being `0`
=> fix: Adding firehose stream environment variable

plugins/destination/firehose/client/spec/schema.json, plugins/destination/firehose/client/spec/spec.go, plugins/destination/firehose/client/spec/spec_test.go
The frontend was showing the following validation error:
`jsonschema: '/stream_arn' does not validate with https://github.com/cloudquery/cloudquery/plugins/destination/firehose/client/spec/spec#/$ref/properties/stream_arn/pattern: does not match pattern '^arn:[^:]+:firehose:[^:]+:[^:]+:deliverystream/[^:]+$'`
Which I think is down to the `/` needing to be escaped. The `spec_test.go` tests still pass with this, so will give it a go.
=> fix: Remove stream_arn regex validation

scripts/workflows/wait_for_required_workflows.js
If both CLI and Scaffold were changed we should add `validate-release` for each one
=> chore: If both CLI and Scaffold are updated, validate both

cli/cmd/sync.go, cli/cmd/sync_test.go
This replaces dashes in plugin names with underscores, and makes the entire prefix upper case, in order to get valid, consistent environment variables.
=> fix: Clean env prefixes for cloud syncs

cli/internal/transformer/transformer.go
If user syncs CQ data from a data source, the sync will fail because the CLI always adds `cqsynctime` and `cqsource`. This pr only adds the columns if they are not present
=> fix: Ensure not adding duplicate CQ columns

website/pages/docs/deployment/kestra.mdx
Current link is 404, this is the best replacement I found
=> chore: Fix broken link in Kestra guide

plugins/source/hackernews/client/errors.go
Should help address this error:
```
[2024-03-04 15:05:55:000] | ERROR | {"module":"hackernews-src","client":"hackernews","error":"while getting item: Get \"https://hacker-news.firebaseio.com/v0/item/39551242.json\": dial tcp 35.201.97.85:443: i/o timeout","message":"table resolver finished with error","table":"hackernews_items"}
```
=> fix: Retry on network errors

CONTRIBUTING.md
Fixes https://github.com/cloudquery/cloudquery/issues/17010.
I looked for the old content that we could bring back but it's not relevant anymore. The new document we have is fairly similar and more relevant.
=> doc: Fix broken link

website/next.config.mjs
Redirecting from cloud signup form to the actual signup url
=> fix: Redirect to Cloud signup

plugins/source/oracle/client/configProvider.go, plugins/source/oracle/client/oracle_clients.go, plugins/source/oracle/docs/_authentication.md
Allows referencing the private key content directly instead of a path to the key.
Part of https://github.com/cloudquery/cloudquery-issues/issues/1361 (internal issue).
This should allow running the Oracle source plugin in environments when one can't populate the file system with the private key
=> feat: Support `private_key` env variable

plugins/destination/gremlin/client/spec.go
Gremlin should allow not setting `auth_mode` and it will default to `none`, however it doesn't work at the moment.
This PR fixes it
=> fix: Allow empty auth mode

plugins/destination/mssql/client/schema.json, plugins/destination/mssql/client/spec.go, plugins/destination/mssql/docs/_configuration.md, plugins/destination/mssql/docs/configuration.md
Added an example to the JSON schema and the docs using env variables replacement so the managed syncs UI populates the secrets list:
=> fix: Update docs example to use env variable replacement

plugins/source/gitlab/client/client.go
The GitLab source plugin doesn't support `cloudquery test-connection` since it doesn't validate the token on `init`.
This PR fixes that
=> feat: Check token validity on init

cli/cmd/login.go
Fixes https://github.com/cloudquery/cloudquery-issues/issues/1454 (internal issue).
It seems that a recent change in Brave browser causes the login callback to be called multiple times, causing us to panic when we close an already closed channel
=> fix: Ensure login callback is only handled once

.github/workflows/publish_plugin_to_hub.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/17336
=> chore: Add working directory when running Java plugin build

.github/workflows/publish_plugin_to_hub.yml
These are needed for download the Java SDK from GitHub packages
=> chore: Add GITHUB_TOKEN and GITHUB_ACTOR envs to Java package command

.release-please-manifest.json, plugins/source/bitbucket/CHANGELOG.md
This reverts commit 8041438555cbcec32abdb3301095bc0aa5de6bd4.
Should have merged first https://github.com/cloudquery/cloudquery/pull/17359
=> chore: Revert "chore(main): Release plugins-source-bitbucket v1.2.0 (#17360)"

plugins/source/bitbucket/docs/_authentication.md, plugins/source/bitbucket/docs/_configuration.md, plugins/source/bitbucket/docs/overview.md, website/vercel.json
Adds the missing docs for the Bitbucket plugin (see https://hub.cloudquery.io/plugins/source/cloudquery/bitbucket/latest/docs).
Also redirects from the old Website to the Hub
=> fix: Add missing docs

plugins/source/bitbucket/app/src/main/java/bitbucket/BitbucketPlugin.java
Same as https://github.com/cloudquery/plugin-sdk-java/pull/217
This should fix the broken tables page for the Bitbucket plugin here https://hub.cloudquery.io/plugins/source/cloudquery/bitbucket/latest/tables
=> fix: Set parents for child tables

plugins/destination/gcs/client/client.go, plugins/destination/gcs/client/client_test.go, plugins/destination/gcs/client/read.go, plugins/destination/gcs/client/spec/schema.go, plugins/destination/gcs/client/spec/schema.json, plugins/destination/gcs/client/spec/schema_test.go, plugins/destination/gcs/client/spec/spec.go, plugins/destination/gcs/client/spec/spec_test.go, plugins/destination/gcs/client/write.go, plugins/destination/gcs/docs/overview.md, plugins/destination/gcs/go.mod
Fixes #15097 . Since the PR is fairly large, please review it commit by commit along with a read of the commit message descriptions to get a better sense of the changes. 
Add path variable support to GCS destination plugin. **This is a breaking change**. We check if the path string has any of the template variables like {{FORMAT}}, {{TABLE}} and so on. If they do, we follow the behaviour of S3 plugin wherein we replace the template variables and that's it. If there are no such variables, we revert back to the current behaviour in the code block shown above.
Please read the issue comments to check on how the decisions for this PR were made. 
This PR follows similar approach to the S3 plugin. I've added some extra tests for client.read() errors which we should probably copy back to S3 and …
=> feat!: Add path variable support to GCS destination plugin. 

.github/workflows/validate_pr_title.yml
We've been hitting GitHub rate limits quite a lot during releases recently. This is an optimization to skip the PR title validator when the PR is generated from our bot, as the title for such PRs is always valid
=> chore: Don't validate PR title on bot PRs

plugins/source/okta/resources/services/applications/users.go
We can use `500` for app users:
> We're already at `200`
Docs say the default is `10000` but maximum value is 200 🙃 
> Kept it as `200` in our code
Docs say default is `100` for historical reasons and you should use `200` so kept that as in our code:
=> feat: Increase application users limit to 500

plugins/source/okta/go.mod, plugins/source/okta/go.sum, plugins/source/okta/resources/plugin/client.go
This uses our forked version with the PR from https://github.com/okta/okta-sdk-golang/pull/450 (until approved) to prevent hitting Okta rate limits and blocking until the limit has reset (or context was cancelled).
This follows Okta's best practices https://developer.okta.com/docs/reference/rl-best-practices/#check-your-rate-limits-with-okta-s-rate-limit-headers
=> fix: Prevent reaching Okta rate limits

cli/cmd/migrate_v3.go, cli/cmd/sync_v3.go, cli/internal/specs/v0/destination.go, cli/internal/specs/v0/schema.json, cli/internal/specs/v0/spec_reader.go, cli/internal/specs/v0/spec_reader_test.go, cli/internal/specs/v0/testdata/sync_group_id_append.yml, cli/internal/specs/v0/testdata/sync_group_id_default.yml, cli/internal/specs/v0/testdata/sync_group_id_overwrite.yml, cli/internal/specs/v0/testdata/sync_group_id_overwrite_delete_stale.yml, cli/internal/transformer/transformer.go, website/pages/docs/reference/destination-spec.md
Fixes https://github.com/cloudquery/cloudquery/issues/8138. Still needs docs and a bit more testing, opening for feedback.
Using the following configurations (assuming `gcp-1.yml` and `gcp-2.yml` run separately in parallel on a daily basis):
```yaml filename=gcp-1.yml
kind: source
spec:
name: "gcp-cq-playground"
path: "cloudquery/gcp"
version: "v12.3.5"
tables: ["gcp_bigquery_datasets"]
destinations: ["postgresql"]
spec:
project_ids: [cq-playground]
---
spec:
name: "postgresql"
path: "cloudquery/postgresql"
registry: "cloudquery"
version: "v8.0.3"
external_sync_group_id: "{{YEAR}}-{{MONTH}}-{{DAY}}-{{HOUR}}"
write_mode: "overwrite"
spec:
connection_string: "postgresql://postgres:pass@localhost:5432/postgres?sslmode=disable"
```
```yaml filename=gcp-2.yml
kind: source …
```
=> feat: Add sync group ID destination spec configuration

plugins/destination/snowflake/client/write.go
=> fix: Explicitly abort on errors

.github/workflows/broken_links_scheduled.yml
Looks like they added some bot detection https://github.com/cloudquery/cloudquery/actions/runs/8938683008/job/24553300918#step:4:170
=> chore: Exclude `egghead.io` from broken links checks

cli/cmd/sync_v3.go
This fixes a bug where source errors and warnings were a summed with some of the destination errors and warning as well
=> fix: Do not combine source and destination warnings and errors

cli/.golangci.yml, plugins/.golangci.yml
This PR resolve the issue https://github.com/cloudquery/cloudquery/issues/17455  => it removes the deprecated run.skipdir from .golangci.yml 
I used the documentation for golangci-lint here : https://golangci-lint.run/usage/configuration/#issues-configuration
there was only 2 .golangci.yml that needed changes (out of 4) : 
- the one in the cli folder 
- the one in the plugins folder (destination + source)
I did not change theses 2 : 
- plugin-sdk did not have the run.skipdir directive.
- codegen did not have any .golangci.yml file.
I tested  with golangci-lint before and after my modification : 
**Before**:
**After:**
This is my first contribution, I hope I did everything well,
Have a good day
=> chore: Replacing deprecated run.skip-dirs for issues.exclude-dirs in golanci.yml

plugins/destination/duckdb/go.mod, plugins/destination/duckdb/go.sum
This upgrades to the DuckDB driver version v0.10.2.
MotherDuck users upgrading to this version will need to enable v0.10.2-compatibility on their account (this will become the default after today).  For more information, see: https://motherduck.com/docs/key-tasks/upgrading-to-DuckDB-0.10#previewing-duckdb-version-0102-in-motherduck
=> feat: Upgrade DuckDB library to v1.6.4 (DuckDB driver v0.10.2)

cli/cmd/specs.go
Part of https://github.com/cloudquery/cloudquery-issues/issues/1676 (internal issue). We're moving JSON schema validation to only be in the Cloud and use the current validation login in the CLI.
We can't remove it fully at the moment as it's used by the `validate-config` command, so that would come later on
=> fix: Remove JSON schema validation warnings

plugins/source/bitbucket/docs/overview.md, plugins/source/hackernews/docs/overview.md, plugins/source/k8s/docs/overview.md, plugins/source/xkcd/docs/overview.md
Removes some redundant headers in a few plugins' docs.
=> doc: Simplify headers in plugin docs

cli/internal/auth/token.go
This message is outdated and doesn't work well when someone has the plugins pre-downloaded already (e.g. using an offline license).
=> fix: Remove outdated login hint message

plugins/destination/bigquery/docs/_configuration.md, plugins/destination/clickhouse/docs/_configuration.md, plugins/destination/duckdb/docs/_configuration.md, plugins/destination/file/docs/_configuration.md, plugins/destination/meilisearch/docs/_configuration.md, plugins/destination/mysql/docs/_configuration.md, plugins/destination/neo4j/docs/_configuration.md, plugins/destination/postgresql/docs/_configuration.md, plugins/destination/s3/docs/_configuration.md, plugins/destination/snowflake/docs/_configuration.md, plugins/destination/sqlite/docs/_configuration.md, plugins/source/hackernews/docs/_configuration.md, plugins/source/k8s/docs/_configuration.md
Some customers appear to be using our SEO (export) pages as a walkthrough and they miss the fact that there's detailed documentation somewhere else. This is adding a link directly in the example spec to help users getting back to the detailed documentation directly from the code. I am using bitly links on purpose to be able to measure whether this actually had any effect. That is why this change is affecting only a selected subset of plugins.
=> doc: Link to hub from example specs

website/versions/cli.json
Reverts cloudquery/cloudquery#18122
We reverted this version to an regression in `--log-console`
=> chore: Revert "chore: Update CLI version to v5.20.4"

plugins/destination/bigquery/client/client.go, plugins/destination/bigquery/client/client_test.go, plugins/destination/bigquery/client/errors.go, plugins/destination/bigquery/client/migrate.go, plugins/destination/bigquery/client/read.go, plugins/destination/bigquery/client/types.go, plugins/destination/bigquery/client/write.go, plugins/destination/bigquery/docs/types.md
fix: Support Apache Arrow types with non-default options (#18198). Previously some Apache Arrow types (namely, `timestamp` with non-default time zone) would result in plugin failure.
BREAKING-CHANGE: Apache Arrow `timestamp` now always maps to BigQuery `timestamp` type (#18198). Previously, `timestamp` with `nanoseconds` precision was mapped to a `record` type.
Instead of https://github.com/cloudquery/cloudquery/pull/18126
Fixes https://github.com/cloudquery/cloudquery-issues/issues/1786 (internal issue)
=> fix!: Support Apache Arrow types with non-default options

cli/internal/analytics/client.go
Otherwise MarshalJSON gets called on it, which leads to an error for an empty email address:
```
2024/06/11 14:42:52 ERROR: json: error calling MarshalJSON for type types.Email: email: failed to pass regex validation - {track 441f7b51-559a-4f0f-86c9-249528aa85c8 7c7b9a79-2e47-48a1-963d-9be3fd79a5f1 00000000-0000-0000-0000-000000000000 sync_run_started 2024-06-11 14:42:52.280882 +0300 EEST m=+4.534407834 2024-06-11 14:42:52.280882 +0300 EEST m=+4.534407834 0x140008dadc0 map[destination_paths:[cloudquery/postgresql] environment:cli invocation_uuid:58de237a-ceb0-472b-821e-288ea6555062 source_path:cloudquery/aws sync_name:aws sync_run_id:58de237a-ceb0-472b-821e-288ea6555062 team:cloudquery user_email: user_id:00000000-0000-0000-0000-000000000000] map[] server}
```
=> fix: Use plain email string for user email

plugins/destination/bigquery/client/migrate.go
Prior to this version BQ would fail if any table has a primary key. Now if a PK is defined it will just ignore it.
All PKs should be removed by the CLI. In the case of state tables, when versioning is enabled, the SDK will handle duplicates by choosing the latest version
=> fix: Remove Primary Key Validation

cli/internal/analytics/client.go
This adds `groupType` to the team event, as documented [here](https://www.rudderstack.com/docs/destinations/streaming-destinations/posthog/posthog-device-mode/):
> It is mandatory to include groupId and groupType in your group calls to create or update the group details.
> RudderStack removes the groupType field from the traits and passes them to PostHog as the group properties.
=> fix: Add groupType to team Group event

plugins/destination/s3/client/read.go, plugins/destination/s3/go.mod
This should allow using s3 for incremental syncs (assuming `no_rotate: true` and no `UUID` placeholder). Before this fix initializing the state client fails since `read.go` returns an error on non existing object key.
=> fix: Don't fail on non existing key

cli/internal/analytics/client.go
Adds `name` trait to Rudderstack team group
=> fix: Add name property to team group

plugins/destination/s3/client/client.go, plugins/destination/s3/client/read.go, plugins/destination/s3/client/write.go
Speedup memory GC
Testing on multi-row
Pre change:
Post change
=> fix: Don't reuse memory pools between tables

cli/cmd/root.go, cli/internal/analytics/client.go
We're already doing identify and group in the backend so no need for the CLI to do them
=> fix: Remove identify, group events

cli/internal/otel/receiver.go
We were closing the metrics file before the last print was done, so the last values where not printed.
This fixes it. Follow up to https://github.com/cloudquery/cloudquery/pull/18498
=> fix: Don't close metrics file before last print

plugins/destination/s3/client/client.go, plugins/destination/s3/client/write.go
Fixes https://github.com/cloudquery/cloudquery-issues/issues/1999 (hopefully).
While the comment in the code is correct and all messages for the same table are processed sequentially, I don't think there's a guarantee that `WriteTable` is not called from multiple concurrent Go routines
=> fix: Handle concurrent map writes

plugins/destination/mssql/docs/_configuration.md
The current format doesn't work. This PR fixes it, you can see the correct format in https://hub.cloudquery.io/plugins/destination/cloudquery/mssql/latest/docs#example-configure-microsoft-sql-server-destination-plugin
=> fix: Fix user id format in example configuration comment

cli/cmd/install.go
Similar to https://github.com/cloudquery/cloudquery/pull/18542, so you can install a single plugin without linking it to a destination/source
=> fix: Allow `plugin install` command to be run with a single-plugin spec

website/pages/docs/advanced-topics/performance-tuning.mdx
Adds a section to our performance tuning docs about the `--tables-metrics-location` flag
=> chore: Add table metrics flag to performance tuning docs

website/pages/docs/advanced-topics/performance-tuning.md
I noticed the `Improve Performance by Skipping Relations` part of https://docs.cloudquery.io/docs/advanced-topics/performance-tuning is out of date since now the default is to skip by default.
This PR
1. Updates the section with relevant information
2. Moves it to the bottom of the doc as it shouldn't be the first action users do to optimize syncs
3. Renames the file from `mdx` to `md`. Only reason we had `mdx` is the `import { Callout } from 'nextra-theme-docs'` but we support it in `md` files via `:::callout`
=> chore: Update the `skip_dependent_tables` part in our docs

cli/cmd/test_connection.go
Follow-up to https://github.com/cloudquery/cloudquery/pull/18761
=> chore: Handle destination kind separately, noop for default

.github/workflows/broken_links_scheduled.yml
The links added in https://github.com/cloudquery/cloudquery/pull/18867 requires authentication so our broken links checker fails on them https://github.com/cloudquery/cloudquery/actions/runs/10283984123/job/28459044421#step:4:114
=> chore: Exclude `app.datadoghq.com` from broken links check

plugins/destination/postgresql/client/connection_tester.go, plugins/destination/postgresql/client/connection_tester_test.go
Since we're relying on error codes more, we need to provide more than just `UNKNOWN` (which is the default if a non-`TestConnError` error is returned)
Should help with https://github.com/cloudquery/cloudquery-issues/issues/2129 (internal issue)
=> fix: Better connection tester error codes

website/pages/docs/deployment/ecs.md
Adding a missing comma to the json config for AWS ECS setup instructions.
=> doc: Add a missing comma to json config

cli/internal/analytics/client.go
This adds a property `"$groups": {"team": "<team-name>"}` to emitted events so that they are associated with teams properly in posthog
=> fix: Emit event groups in a format that posthog accepts

.github/workflows/broken_links_scheduled.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/18932.
Seems like AWS blocks our bot https://github.com/cloudquery/cloudquery/actions/runs/10403514170/job/28810149647#step:4:144
=> chore: Exclude `aws.amazon.com` from broken links check

website/components/mdx/_cloudquery-sign-in.mdx
I think this paragraph is a bit outdated. Aligned it with https://www.cloudquery.io/download.
`cloudquery login` also handles creating an account (via the browser Window) so we don't need that part either.
Feedback welcomed
=> fix: Clean up sign-in section of quick start guide

cli/internal/analytics/client.go
Passing the error instance doesn't seem to get serialized correctly in our analytics stack, so this PR changes the code to use the error string
=> fix: Use error string for  analytics events

cli/cmd/install.go, cli/cmd/install_test.go, cli/cmd/migrate.go, cli/cmd/sync.go, cli/cmd/tables.go, cli/cmd/test_connection.go, cli/cmd/testdata/transformation.yml, cli/cmd/validate_config.go, cli/internal/auth/token.go
This PR allows for transformer plugins to be downloaded by the `cloudquery install` command
=> feat: Add `install` support for Transformer plugins

plugins/destination/bigquery/client/migrate.go
Moving AWS table options docs to the table description caused some descriptions to trigger the limit on BigQuery,
see internal failure https://github.com/cloudquery/policies/actions/runs/10939828521/job/30370943857#step:10:485:
```
Descriptions can be at most 16384 characters long., invalid
```
=> fix: Truncate table description if over the limit

cli/internal/otel/receiver.go
This fixes an issue with the `--tables-metrics-location` flag, that when you pass it you'd see the following log warnings:
```
2024-09-20T13:28:20Z WRN otel error error="failed to send logs to http://localhost:51875/v1/logs: 404 Not Found" invocation_id=95b765f7-2472-4c7a-b062-c0c799743bf7 module=cli
```
The reason is that now plugins send OTEL logs data as well, but the CLI is not set up to receive them. This was an oversight on my end when adding logs support to plugins.
The PR also cleans up some unused options
=> fix: Add missing OTEL logs component

cli/cmd/sync_v3.go
I accidentally elided certain CLI metrics reporting while fixing Rudderstack event tracking. This PR fixes that issue.
=> fix: Fix incorrect location of metrics calculation.

plugins/destination/postgresql/cloud-config-ui/src/hooks/useConfig.tsx
Small correction to the helper text for the connection string, we should use `user:pass` instead of `jack:secret`.
=> fix: Update the helper text

plugins/destination/postgresql/cloud-config-ui/src/utils/convertConnectionStringToFields.ts, plugins/destination/postgresql/cloud-config-ui/src/utils/tests/convertConnectionStringToFields.test.ts
Catch any strings that can't be parsed - preventing the UI from hanging.
With this approach, the test connection will ultimately report the error state.
=> fix: Catch any unparseable strings

website/pages/docs/billing-and-usage/overview.md
Changed "A row means a resource synced with a source plugin that creates or updates a single row in the destination." to  "We charge when a record is pulled from a source whether a record has changed or not."
Source: https://cloudqueryio.slack.com/archives/C02KCFA5F9R/p1728575812725569
=> chore(main): Updated to make billing Docs more percise

.github/workflows/lint_markdown.yml
Fixes this failure in our CI that started showing up https://github.com/cloudquery/cloudquery/actions/runs/11325041150/job/31491094977?pr=19372#step:3:16
=> chore: Fix vale linter

cli/internal/transformer/transformer.go
This PR fixes an issue with `sync_group_id` in append mode where the PK constraint for it was't removed
=> fix: Remove constraints from internal fields if needed

cli/internal/otel/receiver.go
This PR fixes an issue with the table metrics flag where we would not print the last update of the metrics, since we didn't wait for the Go routine that does it to finish
=> fix: Wait for last print of table metrics before exiting

plugins/destination/postgresql/client/spec/spec.go
If you run a sync with Postgres and don't specify you get this log message:
```
INF Initializing postgresql destination invocation_id=fc72fdc1-96ba-46ea-bf84-cad2a5dd8540 module=pg-dest pgx_log_level="invalid level 0"
```
The log message also hides that we're not setting the log level properly.
This PR fixes that
=> fix: Set default `pgx_log_level` level

cli/cmd/sync_v3.go, cli/internal/transformerpipeline/pipeline.go
Fixes https://github.com/cloudquery/cloudquery-issues/issues/2591 (internal issue)
We have 2 Go routines in play in `sync_v3`, one for the transformer pipeline and one for handling sync messages on the gRPC channel.
Any of those Go routines can return an error, and the error group will report the first one which is not consistent in case the pipelined was closed due to a destination error where `OnOutput` returns the error and closes the pipeline.
In the latter case we should signal the sync Go routine to exit early but not with an error that will get reported from the pipeline Go routine.
=> fix: Return correct error from transformers pipeline

website/pages/docs/deployment/docker-offline.mdx
The command is `cloudquery plugin` not `cloudquery integration` at least until we decide to change it
=> chore: Use `cloudquery plugin` instead of `cloudquery integration` in docs

website/vercel.json
Redirect now goes to the Case Study landing page: https://www.cloudquery.io/case-studies
This solves: https://github.com/cloudquery/cloudquery-issues/issues/2702
=> chore: Updated Case Study redirect to the new landing page.

cli/cmd/sync_v3.go, cli/internal/tablenamechanger/table_name_changer.go
The Basic Transformer introduced the concept of renaming tables.
This works well, but an unfortunate side-effect of it is that sync_v3 had to be aware of the renames, because it does post-processing things to the tables, like delete-stale.
Because of this, a `tableNameChanger` was implemented back then, which is used for all that happens after the sync.
At the time this was implemented, we didn't use to write table names to the sync summary.
When we added this feature, we forgot to replace table names. This PR does just that.
Here's a before/after sync summary row:
=> fix: Renames tables before writing summary.

plugins/transformer/jsonflattener/client/recordupdater/record_updater.go, plugins/transformer/jsonflattener/client/recordupdater/record_updater_test.go
fixes https://github.com/cloudquery/cloudquery-issues/issues/2763
(internal issue)
Normally, the JSON Flattener will attempt to flatten JSON objects to the first level, e.g.:
```json
"type_schema": "[{\"availability_domain\":\"utf8\",\"display_name\":\"utf8\",\"volume_group_replica_id\":\"utf8\"}]"
```
But the TypeSchema notation had a special case that the JSON Flattener wasn't aware of:
```json
{
"name": "freeform_tags",
"type": "json",
"type_schema": "{\"utf8\":\"utf8\"}"
},
```
In this case, the `utf8` key is not a literal string, but a special value that means "any string key". This should be ignored by the flattener, because it's meant to contain different keys on different rows, and table schemas are fixed.
The only way to implement this would be to do a linear pass over all rows …
=> fix: Ignore utf8 keys.

plugins/destination/clickhouse/client/migrate.go, plugins/destination/clickhouse/client/spec/schema.json, plugins/destination/clickhouse/client/spec/spec.go, plugins/destination/clickhouse/client/spec/spec_test.go, plugins/destination/clickhouse/docs/overview.md, plugins/destination/clickhouse/queries/tables.go, plugins/destination/clickhouse/queries/tables_test.go, plugins/destination/clickhouse/queries/testdata/create_table_order_by.sql
This PR implements support for setting custom ORDER BY clauses on any table or group of tables in the ClickHouse destination.
Because tables are defined on the source side and every destination can have different optimal indexing/sorting circumstances, it is not practical to define destination-specific sorting strategies at the source. Therefore, this enables setting it at the destination.
=> feat: Implement custom ORDER BY clause support.

website/components/mdx/_configure.mdx
This PR adds a **call-to-action** (CTA) to the "Authenticate to AWS" step in the Quickstart guide. The CTA encourages users to either **join our community** or **contact us for a demo** if they encounter issues.
- Added a CTA to the "Authenticate to AWS" step with links to:
- Join our community.
- Contact us for a demo.
- Updated the step text to include guidance on seeking help if users get stuck.
- We've observed significant user drop-off at this step due to failed attempts to sync using this plugin.
- Providing clear next steps for support will help reduce frustration and guide users toward resolving their issues.
- This CTA serves as an immediate solution until a video walkthrough of the demo can be added in the future.
- A video walkthrough demo will be created and added to this step …
=> chore(main): Add Call-to-Action to Quickstart AWS Authentication Step

.github/workflows/release_cli.yml, go.mod
This PR tries to make so our latest CLI version shows up in https://pkg.go.dev/github.com/cloudquery/cloudquery
=> chore: Push CLI tag as latest repo tag, add root `go.mod`

.github/workflows/release_cli.yml
This should allow pkg.go.dev to index the CLI subdirectory as a module https://go.dev/ref/mod#glos-module-subdirectory
=> chore: Push CLI tag with directory prefix

cli/cmd/addon_download.go, cli/internal/publish/addons.go
Fixes https://github.com/cloudquery/cloudquery/security/code-scanning/4
Fixes https://github.com/cloudquery/cloudquery/security/code-scanning/3
Fixes https://github.com/cloudquery/cloudquery/security/code-scanning/2
Technically those are all false positives since:
1. The request path is derived from the location [here](https://github.com/cloudquery/cloudquery/blob/83cab0b4b34bfbe33a89b444659087dfa5b4ef7b/cli/cmd/addon_download.go#L94), which is built from the addon parts which are validated [here](https://github.com/cloudquery/cloudquery/blob/83cab0b4b34bfbe33a89b444659087dfa5b4ef7b/cli/cmd/addon_download.go#L67) (though not validated for `..` in the argument)
2. If `/` or `..` are part of the addon name the request to get it will fail so we won't reach the code that downloads it. …
=> refactor: Don't use request URL path to build zip path in addons download

plugins/destination/test/client/client.go, plugins/destination/test/client/schema.json, plugins/destination/test/client/spec.go, plugins/source/test/client/schema.json, plugins/source/test/client/spec.go, plugins/source/test/resources/services/paid_table.go, plugins/source/test/resources/services/test_some_table.go, plugins/source/test/resources/services/test_sub_table.go, plugins/transformer/test/client/client.go, plugins/transformer/test/client/spec/spec.go
This PR adds spec options on all test plugins to cause an `os.Exit(1)` upon syncing, to enable e2e testing in the `cli`.
The spec option is a boolean called `exit_immediately`, except in the destination test plugin which has granular options for erroring already (write, insert, migrate), so in this case I added analogous `exit` versions.
I tested the options by running syncs which each component exiting (source, destination, transformer):
```bash
$ cli sync testdata
Loading spec(s) from testdata
Starting sync for: test (local@./test) -> [test-destination (grpc@localhost:7778)]
source plugin process failed with exit status 1
Error: failed to sync v3 source test: unexpected error from sync client receive: rpc error: code = Unavailable desc = error reading from server: EOF
```
```bash
$ cli …
```
=> feat: Add `exit_immediately` spec option to all test plugins.

plugins/destination/bigquery/cloud-config-ui/package-lock.json, plugins/destination/bigquery/cloud-config-ui/package.json, plugins/destination/clickhouse/cloud-config-ui/package-lock.json, plugins/destination/clickhouse/cloud-config-ui/package.json, plugins/destination/mysql/cloud-config-ui/package-lock.json, plugins/destination/mysql/cloud-config-ui/package.json, plugins/destination/postgresql/cloud-config-ui/package-lock.json, plugins/destination/postgresql/cloud-config-ui/package.json, plugins/destination/s3/cloud-config-ui/package-lock.json, plugins/destination/s3/cloud-config-ui/package.json, plugins/source/hackernews/cloud-config-ui/package-lock.json, plugins/source/hackernews/cloud-config-ui/package.json, plugins/source/xkcd/cloud-config-ui/package-lock.json, plugins/source/xkcd/cloud-config-ui/package.json
Could not get https://github.com/cloudquery/cloudquery/pull/19856 to work, so trying something else for now to fix the security issues.
Looked at the breaking changes in https://github.com/postcss/postcss/releases/tag/8.0.0 and https://github.com/fb55/nth-check/releases/tag/v2.0.0, should not impact `react-scripts` I think
=> chore: Override outdated dependecies in config UI packages

plugins/source/hackernews/cloud-config-ui/package-lock.json, plugins/source/hackernews/cloud-config-ui/package.json, plugins/source/xkcd/cloud-config-ui/package-lock.json, plugins/source/xkcd/cloud-config-ui/package.json
Follow up to https://github.com/cloudquery/cloudquery/pull/19868.
We need to override `css-select` for this to work, not `react-scripts`
Fixes https://github.com/cloudquery/cloudquery/security/dependabot/340
Fixes https://github.com/cloudquery/cloudquery/security/dependabot/338
=> chore: Override nth-check in config UI

cli/cmd/sync_test.go, cli/cmd/testdata/destination-errors.yml, cli/cmd/testdata/destination-exits.yml, cli/cmd/testdata/source-errors.yml, cli/cmd/testdata/source-exits.yml, cli/cmd/testdata/transformer-errors.yml, cli/cmd/testdata/transformer-exits.yml, cli/cmd/testdata/transformer-succeeds.yml
Adds the following E2E tests to CLI:
- Source exits immediately
- Destination exits immediately
- Transformer exits immediately
- Source errors immediately
- Destination errors immediately
Missing: cannot add a test where transformer errors immediately, because there's a bug where this is not causing erroring resources. Will work on that separately.
This PR will allow us to merge an SDK performance improvement for the DFS strategy.
=> chore: Add E2E testing to CLI.

plugins/destination/postgresql/client/client_test.go, plugins/destination/postgresql/client/migrate.go
There are 2 bugs related to performance index creation:
1. We use the same index name for all tables, so it gets created only for a single table across the database
2. We don't create it for new tables, only existing ones
The logic in the test is to handle CockroachDB
=> fix: Create unique index per table, handle non existing tables

plugins/destination/test/client/client.go
The StreamBatchWriter has a slightly different interface for its client, and the mocked method implementations didn't consume their input channels. As a result, in tests, the syncs got stuck, because sends on those channels would never be consumed.
=> fix: Fix hang in test destination plugin.

cli/cmd/sync.go, cli/cmd/sync_test.go
Without this fix, two env vars of the same name would be returned.
=> fix: Allow overriding API key per plugin in isolated env setting

cli/.goreleaser.yaml
Follow up to https://github.com/cloudquery/cloudquery/pull/16989.
While we have Ubuntu CLI images we don't publish them as multi platform ones (see https://github.com/cloudquery/cloudquery/pkgs/container/cloudquery):
making them harder to consume.
This PR adds that feature
=> feat: Publish multiplatform images for Ubuntu

plugins/destination/mssql/client/client_test.go
This PR fixes intermediate CI failures in our tests that started happening when we upgraded to Go 1.23.. See https://github.com/cloudquery/cloudquery/pull/20087#issuecomment-2606728207 and https://github.com/cloudquery/cloudquery/actions/runs/12892739493/job/35947615181?pr=20087#step:11:18 
If we want to support certificates with negative serial numbers we should do:
```go.mod
go 1.23
godebug (
x509negativeserial=1
)
```
In our `go.mod` file, but I don't think we should as it's not RFC compliant
=> test: Set `x509negativeserial=1` in test

plugins/destination/clickhouse/client/migrate.go, plugins/destination/clickhouse/client/spec/schema.json, plugins/destination/clickhouse/client/spec/spec.go, plugins/destination/clickhouse/docs/_licenses.md, plugins/destination/clickhouse/docs/overview.md, plugins/destination/clickhouse/queries/tables.go, plugins/destination/clickhouse/queries/tables_test.go
This PR adds a `skip_incremental_tables` boolean sub-option to the `partition_by` strategies of the ClickHouse destination.
The reasoning is that it is a common use case that incremental/non-incremental changes have to be partitioned differently, but since tables can migrate from being non-incremental to becoming incremental, the "list of incremental tables" can change over time, and so maintaining this list in the spec up to date can be an error-prone operational burden.
By adding the `skip_incremental_tables` options on a partitioning strategy, a partitioning strategy can be applied specifically to non-incremental tables, without needing to list the tables.
=> feat: Add skip_incremental_tables suboption for partition_by.

.github/renovate.json5
This should open Go version update PRs for newer versions than our default (defined in https://github.com/cloudquery/.github/blob/7a408435c94677e30963ea808287a82e0de31bb5/.github/renovate-go-default.json5#L11).
The default is there since some of our Go modules (like the SDK) are publicly consumed so we don't want to force consumers to upgrade their go version
=> chore: Use different Go version update logic for plugins

cli/cmd/sync.go
To go with a certain PR on the private repo.
=> chore: Pass `_CQ_INSTALLATION_ID` env var in plugin isolation mode

cli/cmd/sync.go, cli/cmd/test_connection.go, cli/go.mod, cli/go.sum, cli/internal/analytics/client.go, cli/internal/env/env.go, cli/internal/transformer/transformer.go
Goes with https://github.com/cloudquery/plugin-sdk/pull/2105
For Cloud syncs we should replace the internal columns if exist so we can trace back the synced data to the correct source name, sync time and sync group id (otherwise we'd get the ones of the original sync, e.g. `AWS->S3`)
=> fix: Replace internal columns if exist on Cloud syncs

cli/internal/specs/v0/version.go
=> fix: Only validate version when Cloudquery Registry is used

plugins/destination/clickhouse/client/client_test.go, plugins/destination/clickhouse/client/migrate.go, plugins/destination/clickhouse/queries/tables.go
Fixes a bug in ClickHouse migration where is would require forced migration for new lists and maps columns.
=> fix: Support compound types migrations

plugins/destination/clickhouse/docs/overview.md
A small oversight in https://github.com/cloudquery/cloudquery/pull/20772.
=> chore: Update ClickHouse docs with min supported version

cli/internal/secrets/secrets.go, cli/internal/secrets/secrets_test.go
This PR skips redacting environment variables injected by EKS and some allowed by our plugin isolation logic. Moreso, it also skips redacting environment variables whose values are less than 4 characters in length.
=> fix: Skip redacting environment variables injected by cloud providers or the CLI

plugins/transformer/jsonflattener/client/recordupdater/column_builders.go, plugins/transformer/jsonflattener/client/recordupdater/column_builders_uuid.go, plugins/transformer/jsonflattener/client/recordupdater/record_updater_test.go, plugins/transformer/jsonflattener/client/schemaupdater/schema_updater.go
Adds support for flattening nested UUID types
=> feat: Add UUID type support

plugins/destination/s3/client/write.go
When `write_empty_objects_for_empty_tables` option is used, if migration (writing empty object to the bucket) fails, the method returns early without closing the channel. This produces a hang in [StreamingBatchWriter](https://github.com/cloudquery/plugin-sdk/blob/main/writers/streamingbatchwriter/) (`clientCh <- r`)
=> fix: S3 destination avoid hang on migrate errors

plugins/destination/s3/client/write.go
`errors.Join(errs, err)` doesn't check if `errs` is already a `joinError`, so it ends up creating error pairs with multiple levels of wrapping.
Follow-up to https://github.com/cloudquery/cloudquery/pull/20872
=> fix: Proper error join

plugins/transformer/basic/client/recordupdater/record_updater.go, plugins/transformer/basic/client/recordupdater/record_updater_test.go, plugins/transformer/basic/client/spec/spec.go, plugins/transformer/basic/client/spec/spec_test.go, plugins/transformer/basic/client/transformers/transformers.go, plugins/transformer/basic/client/transformers/transformers_test.go, plugins/transformer/basic/docs/_configuration.md, plugins/transformer/basic/docs/overview.md
Adds two transformations to help users normalize data. Has json path handling like `obfuscate` transformations.
=> feat: Add lower and upper case transformations to basic transformer

plugins/transformer/basic/client/recordupdater/record_updater_test.go, plugins/transformer/basic/go.mod, plugins/transformer/basic/go.sum
This PR fixes remove_column to support removing json arrays with 'foo.#.bar' syntax. It also fixes accessing complex paths starting from '#'  in example '#.env.#.value'
=> fix: Bump sjson library to fix accessing root arrays and complex path

plugins/destination/sqlite/client/delete.go
Following up on https://github.com/cloudquery/cloudquery/pull/21102
There was a leftover from the debugging session that got merged into the release.
This removes a `fmt.Println(...)` left in the `unpackArray` function from the SQLite plugin, used when sending DeleteRecord messages.
=> fix: Remove fmt.Println from sqlite unpackArray

cli/internal/publish/pluginui.go
=> fix: Remove requirement for index.html for plugin UI assets

plugins/destination/mysql/docs/types.md
Small follow up to https://github.com/cloudquery/cloudquery/pull/21220 to remove the duplicated header
=> chore: Remove types header

plugins/source/hackernews/client/schema.json, plugins/source/hackernews/client/spec.go, plugins/source/hackernews/client/spec_test.go, plugins/source/hackernews/client/testing.go, plugins/source/hackernews/docs/_configuration.md, plugins/source/hackernews/docs/_licenses.md, plugins/source/hackernews/docs/overview.md, plugins/source/hackernews/resources/services/items/items_fetch.go
This adds relative time support to the Hackernews plugin, and changes the default behavior to sync the last 24 hours. The default generated config (`cloudquery init`) will use 3 hours, which takes a few minutes to sync on my machine.
I've chosen not to mark this as a breaking change, because:
- the previous timestamp format (RFC3339) is still supported, and
- if a user has been syncing without the start time specified, the state store would make them immune to the default changing
=> feat: Add relative time support to HackerNews plugin

plugins/destination/clickhouse/client/migrate.go
This improves the error message when migrating between plugin versions where sorting key or partition keys have changed. Before, the user was left guessing what changes were needed for certain tables.
```bash
cloudquery sync aws_to_clickhouse.yaml
Loading spec(s) from aws_to_clickhouse.yaml
Starting sync for: aws (cloudquery/aws@v32.37.1) -> [clickhouse (cloudquery/clickhouse@v7.3.1)]
Error: failed to sync v3 source aws: write client returned error (insert): plugin returned error:
Can't migrate tables automatically, migrate manually or consider using 'migrate_mode: forced'. Non auto migratable tables changes:
aws_ec2_instance_types:
- Column "placement_group_info" added with type "utf8"
- Column "test_column" with type "utf8" removed
- Not null constraint removed from column "v_cpu_info" …
```
=> fix: Add more verbose error for when partition and sorting key changes

cli/cmd/ai.go
The `cloudquery-test` tool on AI Onboarding receives a named argument from the server. The argument name didn't coincide between the tool and the function.
=> fix: Fix bug on cloudquery-test argument.

cli/cmd/init.go, cli/cmd/init_test.go
This PR simply removes the clause that limits the AI Onboarding experience to CloudQuery users.
=> chore: Remove @cloudquery.io limitation for init command.

cli/cmd/ai.go
Upon finishing AI Onboarding, the `EndConversation` endpoint is called with a cancelled context.
=> fix: End conversation properly.

cli/cmd/init.go
Currently, if there's an issue with AI Onboarding, we output an error and finish the command.
This PR makes it fall back to the original basic interactive `init` command on error. Also, it elides internal errors from the output which are not useful to users.
=> fix: If there's an issue with AI onboarding, fallback.

cli/cmd/switch.go, cli/internal/auth/team.go, cli/internal/team/team.go
```
CLOUDQUERY_API_KEY=invalidkey ./cli switch
Error: failed to list teams: 401: Invalid authentication token
```
=> fix: Better handling of error messages from API

cli/cmd/login.go, cli/cmd/switch.go, cli/internal/auth/team.go, cli/internal/team/team.go
Fixes a bug whereby the `internal` value in the cached config didn't get updated between login / switch events, meaning that analytics events could get sent (or not sent) incorrectly. 
This was a rare bug that only affected CloudQuery team members doing testing on the analytics system itself.
=> fix: Update team internal metadata upon switch and login

cli/cmd/ai.go, cli/cmd/init.go
When using AI Onboarding with `--resume-message`, rather than `What are you trying to build with CloudQuery?` we should send `Your conversation has been resumed. You can now generate the config or ask questions about your sync.`
=> fix: Send a more adequate message on resume.

.github/workflows/release_cli.yml
This is needed since we publish to GitHub packages docker images
=> chore: Fix permissions to publish CLI

.github/workflows/clean_actions_cache.yml
The workflow to delete PR's cache after they are merged stopped working due to the permissions changes I did.
This PR fixes it and also updates the workflow to use the built in `gh` CLI `cache` command since the `extension` is now deprecated
=> chore: Fix PR cache delete action

plugins/destination/postgresql/client/insert.go
`schema.Column` defines both `PrimaryKey` and `PrimaryKeyComponent` for a column, and certain plugin's tables use one of the two but not the other.
The Postgres destination decides whether to insert or upsert based on the existence of PK columns on the table, but ignores PK components.
This causes tables with PK component only columns to fail with constraint violations on inserts, when the rows already exist on the DB side.
=> fix: Table with PK components should upsert.
