- providers/aws/iam/roles.go
- providers/aws/iam/users.go
Instead of just raising issues I thought it would be nice to try and make a PR. Note that this is my first interaction with Go, so treat this code with caution and feel free to change it.
I experienced an issue where tags are not added to the database for both iam users and roles. Even though the tables  `aws_iam_user_tags` and `aws_iam_role_tags` are created, these tables never get populated.
The code looked correct, and even the API documentation and the aws go sdk specify that tags should be returned when calling `ListRoles` and `ListUsers`, but they never are.
I've found that this is a known issue in the AWS API https://github.com/boto/boto3/issues/1855. The issue has been open for a long time with no end in sight.
I've now implemented another call to `ListUserTags` and `ListRoleTags` …
> Add role and user tags

- cmd/config.go
- database/database.go
- providers/aws/organizations/accounts.go
- providers/aws/organizations/client.go
- providers/aws/provider.go
Continue PR: https://github.com/cloudquery/cloudquery/pull/51
> Add organizations

- cmd/config.go
- providers/aws/provider.go
- providers/aws/sns/client.go
- providers/aws/sns/topics.go
Hello! I am interested in contributing to this project; I decided to add SNS Topics. Please let me know if this looks good!
> Add sns topics

- README.md
Changes
* Added how to quickly load the database after the fetch
* Added basic sqlite schema describes
* Most people aren't building this so I removed the `./` from `./cloudquery` from the quick start commands
> README.md: Add basic sqlite schema describes

- Makefile
- client/client.go
- client/client_test.go
- client/config.go
- cmd/fetch.go
- cmd/init.go
- config/parser.go
- deploy/lambda.go
This is just a rebase of https://github.com/cloudquery/cloudquery/pull/70 on top of main.
@zscholl I'm merging this one - I've just rebased it on top of main as I was exactly working on similar code area. Thank!!
> Lambda config

- cmd/root.go
> fix  rettach providers env to be empty by default

- .github/workflows/release.yml
- .github/workflows/test.yml
- .goreleaser.yaml
- go.mod
> Builde Release binaries for arm64 architecture

- .gitignore
- pkg/plugin/registry/hub.go
Allow verify skip for community providers #106
> Skip verify for community providers

- cmd/init.go
> update incorrect dsn. Closes #140

- pkg/ui/console/client.go
Fixes cloudquery/cloudquery-issues#87
> fixed error message when thre is no config file Closes #87

- cmd/provider.go
- cmd/provider_download.go
This will just verify/download all providers mentioned in the
configuration.
Closes #163
> Implement `provider download` command.

- pkg/plugin/plugin.go
- pkg/ui/console/client.go
- pkg/ui/console/progress.go
> fix unmanaged plugin panic

- deploy/lambda.go
- go.mod
- go.sum
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/config/provider.go
- pkg/ui/console/client.go
- pkg/ui/console/progress.go
- pkg/ui/progress.go
Depends on https://github.com/cloudquery/cq-provider-sdk/pull/76
> Partial Fetch

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Create Bug and Feature Requests Issue Templates
> Adding issue templates

- pkg/ui/console/client.go
Improve fetch summary print to be more understandable
> update fetch summary print

- cmd/options.go
- cmd/root.go
> Help message on subcommand

- modules/configs/drift.hcl
Update resource config, fix cloudwatch alarms
> Update drift resources

- cmd/util.go
- pkg/module/drift/drift.go
- pkg/module/drift/model.go
- pkg/module/drift/terraform.go
- pkg/module/types.go
- pkg/ui/console/client.go
- pkg/ui/console/model.go
Exit with exit code 1 if any of these are detected:
- drifted resources
- extra resources
- missing resources
> drift: Exit with nonzero code if drift detected

- README.md
Sorry for another one, but "powered by" is a better word then backed (seems like financial connection)
> Updated one-liner

- cmd/drift.go
- pkg/module/drift/config.go
- pkg/module/drift/config_parser.go
- pkg/module/drift/drift.go
- pkg/module/drift/model.go
- pkg/module/drift/terraform.go
- pkg/module/drift/terraform/state.go
- pkg/module/drift/terraform/terraform.go
New usage: `cloudquery drift scan /path/to/file.tfstate`
> Drift with tfstate

- README.md
Update old policy documentation. It still needs more work and basically it should point to the right section in the docs which we are still missing but this should be a good first iteration.
> update old policy documentation

- cmd/policy_run.go
- pkg/client/client.go
- pkg/policy/execute.go
- pkg/policy/manager_test.go
- pkg/ui/console/client.go
> added fail-on-violation flag

- pkg/client/client.go
- pkg/policy/execute.go
- pkg/policy/manager_test.go
Otherwise there is a bug where policy result is not saved to output file
on violation.
> Handle --fail-on-violation flag higher up

- pkg/module/drift/model.go
- pkg/ui/console/client.go
This is different from the case of drift module detecting a drift.
> Set nonzero exit code if module returned an error

- internal/logging/logger.go
> auto enable console log on non-terminal consoles

- CHANGELOG.md
- go.mod
- pkg/client/client.go
- pkg/policy/execute.go
- pkg/policy/manager.go
- pkg/policy/parser.go
- pkg/policy/policy.go
- pkg/ui/console/client.go
> add support for policy in policy

- internal/persistentdata/persistentdata.go
- internal/persistentdata/persistentdata_test.go
- internal/telemetry/telemetry.go
Logic should be the same as previous code, I've only added the check-home-dir-for-the-file-first section, had to refactor to suit
> Read persisted telemetry ID if exists

- CHANGELOG.md
- pkg/client/client.go
Fix #325
Fixed bug where total resource count wasn't added up.
> Fix provider failure cancel

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/plugin/registry/hub.go
- pkg/ui/console/client.go
> added provider update available notification

- cmd/sentry.go
> Disable Sentry module reporting

- cmd/util.go
- pkg/ui/console/client.go
We discussed this before, not sure if this is good way to do it...
> Add config hash field

- pkg/client/client.go
Too little or just right? Should I dive into PolicyManager and instrument LoadPolicy/RunPolicy as well?
> telemetry: Instrument runPolicy

- internal/telemetry/telemetry.go
> Fix is_faas misdetection

- cmd/fetch.go
- pkg/client/client.go
- pkg/ui/console/client.go
Do we also want an SDK counterpart removing this from the proto?
> Always disable data delete, remove the option

- cmd/sentry.go
- cmd/util.go
- internal/telemetry/error.go
- internal/telemetry/telemetry.go
- pkg/ui/console/client.go
- Classify context.Canceled, SSL setup and query cancellations 
- Persist the random ID to better identify installations
> Classify more errors

- pkg/client/client_test.go
- pkg/plugin/plugin.go
https://github.com/cloudquery/cloudquery/pull/375
> upgrade to protocol v3 due to #375 PR

- internal/getter/file.go
check if source if absolute file path if it is don't add wd
> respect absolute file path

- pkg/ui/console/client.go
- pkg/ui/console/policy.go
fix: Adjust policy describe message
> fix: Adjust policy describe message

- pkg/module/drift/terraform/terraform.go
> fix: Better drift tfstate error

- pkg/client/client.go
If connection info is not specified we allow the client to get created (missing DSN just logs a line)
But this causes problems the first time we want to access the DB. For fetch this is always in buildProviderMigrator, for drift and policy functions it's just before the respective module executor calls.
> fix: Nil connection

- cmd/fetch.go
- cmd/fetch_test.go
- cmd/util.go
- pkg/ui/console/client.go
- pkg/ui/console/client_test.go
```
Usage:
cloudquery fetch
cloudquery fetch aws
cloudquery fetch aws gcp
cloudquery fetch aws:ec2.instances,s3.buckets gcp
cloudquery fetch aws_2:ec2.instances,s3.buckets
cloudquery fetch aws_2 gcp_2
```
> feat: Fetch only specified providers/resources

- go.mod
- go.sum
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/config/provider.go
This needs https://github.com/cloudquery/cq-provider-sdk/pull/184 first
> feat: Add max_goroutines to providers

- go.mod
- go.sum
- pkg/ui/console/fetch.go
~Needs a new SDK release~
Fixes #473.
> feat: Update SDK and show resource id on diagnostics

- .github/ISSUE_TEMPLATE/bug_report.md
> chore: Remove '--debug' flag from issue template

- pkg/client/client.go
but allow with `--debug-sentry` and development mode (which will go into the 'development' tab)
> fix: Don't report unmanaged provider diags to sentry

- pkg/config/config.go
- pkg/config/parser_test.go
- pkg/ui/console/client.go
Fix messages, don't upgrade/downgrade dupe providers, don't let providers not supporting things block other upgrades... still hide ErrNoChange "error" to avoid ringing alarm bells in CIs...
> fix: Upgrade/downgrade providers cleanup

- go.mod
- go.sum
- internal/telemetry/error.go
- internal/telemetry/error_test.go
- pkg/client/client.go
- pkg/ui/console/fetch.go
Also update SDK to use better sorting
> fix: Diag: Don't report errors we don't care about

- pkg/module/drift/terraform.go
This is used if the specified object may or may not be nil, and we want to extract a bool value from it
> feat: Drift: Add @getbool modifier

- pkg/config/parser.go
- pkg/ui/console/client.go
So one can do `dsn = file("dsn.txt")`
> feat: Add file() func to config parser

- go.mod
- go.sum
- pkg/client/client.go
Implements #520
Requires https://github.com/cloudquery/cq-provider-sdk/pull/200
> feat: Store cq_fetch_id in meta

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/config/config.go
- pkg/plugin/manager.go
- pkg/ui/console/client.go
Closes #496.
This is extra bad, but given the way everything is set up this is what I ended up with.
> fix: Downgrade provider

- go.mod
- go.sum
- pkg/client/client.go
- pkg/config/provider.go
To go with https://github.com/cloudquery/cq-provider-sdk/pull/209
> feat: Support timeouts in fetch

- pkg/client/database/postgres/executor.go
- pkg/client/database/timescale/timescale.go
@bbernays that's what I meant :)
> chore: Clean up db version checks

- .github/dependabot.yml
- .github/release.yml
- .github/workflows/README
- .github/workflows/history_test.yml
- .github/workflows/lint_golang.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- CODEOWNERS
> chore: Update from .github

- cmd/root.go
- pkg/ui/console/client.go
- pkg/ui/console/fetch.go
Requires SDK version != 0.8.12 on the provider
> feat: Ignore ignored diags unless -v is specified

- go.mod
- go.sum
- pkg/ui/console/client.go
> feat: Simplify fetch warning/error counts (unless -v is on)

- cmd/root.go
- internal/logging/logger.go
- pkg/ui/output.go
Allow to disable color formatting in logger
> feat: Add console colour disable

- pkg/ui/console/client.go
fixes nil pointer exception if connection config is not set
> fix: Added error when connection configuration is not set

- cmd/root.go
- cmd/util.go
- internal/logging/logger.go
- pkg/ui/console/client.go
- pkg/ui/console/policy.go
- pkg/ui/console/progress.go
- pkg/ui/output.go
> fix: Include all responses in log, log invocation params

- go.mod
- go.sum
- pkg/client/client.go
- pkg/ui/console/client.go
- pkg/ui/console/fetch.go
Needs https://github.com/cloudquery/cq-provider-sdk/pull/220 tagged to properly work.
> fix: Handle panic level diags

- cmd/util.go
- go.mod
- go.sum
- internal/telemetry/error.go
- internal/test/providertest/provider.go
- pkg/client/client.go
- pkg/ui/console/client.go
goes with https://github.com/cloudquery/cq-provider-sdk/pull/226 and https://github.com/cloudquery/cq-provider-aws/pull/755
~a problem: provider.Configure calls fail with `diag.ACCESS` / `ERROR`. Since it's `ERROR` it's currently reported.~
> feat: Configure to return diagnostics, upgrade SDK

- internal/analytics/client.go
- internal/analytics/env.go
- pkg/core/fetch.go
- pkg/core/fetch_test.go
- pkg/policy/policy.go
- pkg/policy/run.go
- pkg/policy/run_test.go
- pkg/policy/source.go
- pkg/policy/source_test.go
- pkg/ui/console/client.go
- pkg/ui/console/diagnostics.go
- pkg/ui/output.go
- add policy analytics
- fix edges of fetch failed with configure
- improve fetch analytics event
> feat: Add policy analytics

- cmd/root.go
- internal/logging/logger.go
- pkg/config/config_parser.go
- pkg/config/parser_test.go
> fix: Enable logging config through HCL

- internal/firebase/client.go
Follow up on https://github.com/cloudquery/cloudquery/pull/618
> refactor: Rename firebase client type

- .gitignore
- pkg/config/config.go
- pkg/policy/policy.go
- pkg/policy/run.go
- pkg/ui/console/client.go
- pkg/ui/console/policy.go
> fix: Policy selector

- pkg/ui/console/client.go
This was broken in the refactor.
> fix: Validate db version before proceeding

- pkg/ui/console/client.go
> chore: Include db installation id in analytics

- .goreleaser.prerelease.yaml
- .goreleaser.yaml
I'll follow up with the relevant `.github` changes once this is working
> chore: Remove go generate

- pkg/ui/console/policy.go
Replaces https://github.com/cloudquery/cloudquery/pull/684
> fix: Classify not found policies and improve errors

- CHANGELOG.md
- cmd/policy.go
- internal/analytics/env.go
- remove unused changelog lines
- update analytics to not omit false
> fix: Add missing descriptions

- cmd/command.go
> fix: Completion issue

- pkg/policy/parser.go
- pkg/policy/run.go
- pkg/ui/console/client.go
> fix: Classify policy parse errors as User

- cmd/command.go
- cmd/init.go
- cmd/root.go
- cmd/sentry.go
- internal/analytics/client.go
- internal/logging/logger.go
- pkg/core/fetch.go
- pkg/core/fetch_test.go
- pkg/ui/console/client.go
- pkg/ui/console/client_test.go
> feat: Add global log id

- pkg/core/database/postgres/executor.go
- pkg/core/database/timescale/timescale.go
> fix: Set ID For all Versions

- pkg/errors/sentry.go
> fix: Squash redact errors

- pkg/ui/console/client.go
> fix: Panic on nil fetch response

- pkg/ui/console/client.go
> fix: Panic on nil fetch result

- internal/analytics/client.go
> fix: Space trimming in telemetry file

- pkg/core/fetch_test.go
Related to https://github.com/cloudquery/cloudquery/issues/719.
Reports the actual error returned by `plugin.NewManager`
---
> test(fetch): Report error on failure

- pkg/core/fetch.go
- pkg/core/fetch_test.go
Fixes https://github.com/cloudquery/cloudquery/issues/719
The test timeout test expects the fetch to fail at a very specific point in the code, while the `DeadlineExceeded` error can be returned in multiple places (every place that uses the context).
I'm guessing this happens more often in CI as the machines are slower so we reach the deadline before and fail in a different way.
You can reproduce using a debugger and wait more than 4 seconds before stepping into `resp, diags := Fetch(ctx, storage, pManager, &tc.Options)`
---
> fix: Handle DeadlineExceeded errors

- pkg/core/fetch.go
Fix regression introduced in https://github.com/cloudquery/cloudquery/pull/714
> fix: FetchId column regression

- cmd/root.go
- pkg/plugin/manager.go
Fixes https://github.com/cloudquery/cloudquery/issues/746
---
> fix: Don't attempt to download provider in re-attach mode

- go.mod
- go.sum
> chore: Update SDK version

- pkg/policy/execute.go
- pkg/policy/execute_test.go
> fix: Policy output file name

- pkg/policy/execute.go
> fix: Check policy version on it's core version

- go.mod
- go.sum
- pkg/plugin/plugin.go
Should merge after tagging https://github.com/cloudquery/cq-provider-sdk/pull/285
> fix: Upgrade protocol version to V5

- pkg/core/fetch_test.go
Latest test provider release broke the tests. This PR pins the version to get the tests passing until we fix the issue.
---
> test(fetch): Pin test provider version

- pkg/core/fetch_test.go
New test provider reports things a bit differently that we expected (probably due to the SDK upgrade)
---
> test(fetch): Fix assertions to match new test provider

- cmd/fetch.go
Again with the linting.
Reference rule https://staticcheck.io/docs/checks#S1001.
Honestly I can take it or leave it
---
> refactor: Use copy instead of loop

- pkg/policy/execute.go
- pkg/policy/execute_test.go
> fix: Normalize selector

- Dockerfile.goreleaser
> fix: Add Git Binary To Docker

- pkg/core/provider.go
- pkg/plugin/manager.go
- pkg/ui/console/client.go
- pkg/ui/output.go
> fix: Skip reattached provider update checks

- pkg/policy/execute.go
> fix: Panic During Policy Storage

- cmd/sentry.go
- cmd/ulimit_unix.go
Closes https://github.com/cloudquery/cloudquery-issues/issues/372
---
> feat: Add ulimit info to sentry

- pkg/core/diagnostics.go
- pkg/core/diagnostics_test.go
Closes https://github.com/cloudquery/cloudquery-issues/issues/369
> fix: Incorrect diagnostics summary count

- pkg/ui/console/policy.go
Closes: #797 
in Go keys in a dict are random in order, while arrays are ordered
---
> fix: Policy Output Table

- cmd/root.go
disable sending telemetry with special CQ team cookie
> fix: Disable Telemetry with special CQ team cookie

- pkg/core/database/postgres/executor.go
Pending https://github.com/cloudquery-policies/azure/pull/48, all our tests should pass on postgres 10, so we can change the minimum version
---
> feat: Change minimum postgres version to 10

- pkg/policy/source.go
> fix: Improve missing git binary message

- cmd/init.go
- pkg/config/config.go
> fix: Remove deprecated 'policy_directory' and 'plugin_directory' from hcl file

- cmd/command.go
- pkg/core/purge_test.go
> chore: Use SDK sleep

- pkg/policy/execute.go
- pkg/policy/execute_test.go
- pkg/policy/run.go
fixes: https://github.com/cloudquery/cloudquery-issues/issues/378
---
> fix: Classify "failed to open file" as USER diags

- .github/workflows/sanity.yml
- .github/workflows/test.yml
- Makefile
- cmd/fetch.go
- scripts/test-sanity.sh
Remove flag that should be the default behaviour.
If someone wants to override it he should use bash "|| true" mechanism.
This should also help remove bloat of flags that we have right now.
---
> feat!: Remove fail-on-error

- pkg/core/fetch.go
> fix: Progress bar diag count

- cmd/root.go
Fixes https://github.com/cloudquery/cloudquery/issues/954
---
> fix: Silence usage on command errors

- pkg/config/config.go
- pkg/config/config_parser.go
Fixes an issue with old configs.
> fix: Support modules tag in config

- pkg/config/fixtures/bad_version.hcl
- pkg/config/fixtures/config_with_alias.hcl
- pkg/config/fixtures/duplicate_provider_alias.hcl
- pkg/config/fixtures/duplicate_provider_alias.yaml
- pkg/config/fixtures/duplicate_provider_name.hcl
- pkg/config/fixtures/env_vars.hcl
- pkg/config/fixtures/no_source.hcl
- pkg/config/fixtures/valid_config.hcl
- pkg/config/parser_test.go
> test(yaml): Add simple YAML parsing test

- pkg/ui/console/client.go
This code seems redundant as we already check for `nil` and return here https://github.com/cloudquery/cloudquery/blob/bda1476242e2aaf8f1b263055cf0878889adf5a2/pkg/ui/console/client.go#L719
---
> fix: Remove unused console print

- main.go
Fixes https://github.com/cloudquery/cloudquery/issues/953
Errors are already print by Cobra, see https://github.com/spf13/cobra/blob/8380ddd3132bdf8fd77731725b550c181dda0aa8/command.go#L972
---
> fix: Don't print duplicate errors

- pkg/config/loader_test.go
Fixes the name of the test
---
> test: Rename test method to reflect test name

- pkg/core/sync.go
Related to https://github.com/cloudquery/docs/issues/216. Quick fix to improve messaging until we improve the docs
---
> fix(providers-sync): Improve error message

- pkg/ui/console/client.go
- pkg/ui/console/summary.go
Addressing #951:
* Displaying errors, warnings and ignored issues info **only** if there were occurrences of such issues
* Add an extra footer suggesting running `cloudquery` with `--verbose` flag when ignored issues appear
---
> enhancement: More verbose summary

- cmd/doc.go
> feat: Generate metadata for CLI docs

- cmd/completion.go
- cmd/doc.go
> fix: Doc command to generate id meta without space

- cmd/policy.go
> fix: Update 'policy run' help message

- cmd/root.go
The version command is missing information at the moment:
---
> fix(cmd-version): Embded commit and date

- cmd/fetch/fetch.go
- internal/analytics/client.go
- internal/analytics/summary.go
- internal/analytics/summary_test.go
- internal/analytics/telemetry_events.go
- pkg/core/diagnostics.go
- pkg/core/fetch.go
- pkg/ui/console/client.go
Closes cloudquery/cloudquery-issues#374
> feat: Send telemetry about failed COPY FROMs

- pkg/config/config.go
- pkg/config/config_parser.go
- pkg/config/config_parser_test.go
- pkg/config/fixtures/dsn_file.txt
- pkg/config/schema.json
> feat: Add dsn_file connection option

- website/.gitignore
- website/pages/blog/cloudquery-postgrest.md
> chore: Fix blogs build + gitignore for Nextjs project

- .github/workflows/release-pr.yml
Update to the correct name of the workflow job dependency
> chore(release): Fix job name

- .github/workflows/release-pr.yml
- release-please-config.json
The `bootstrap-sha` value is exclusive so we need to take the previous one
> chore: Set bootstap sha

- .github/workflows/release-pr.yml
> chore(release): Fix mark prerelease

- .github/workflows/release-pr.yml
- plugins/aws/.goreleaser.yaml
- plugins/azure/.goreleaser.yaml
- plugins/cloudflare/.goreleaser.yaml
- plugins/digitalocean/.goreleaser.yaml
- plugins/fuzz/.goreleaser.yaml
- plugins/gcp/.goreleaser.yaml
- plugins/github/.goreleaser.yaml
- plugins/k8s/.goreleaser.yaml
- plugins/okta/.goreleaser.yaml
- plugins/terraform/.goreleaser.yaml
I wasn't able to get the matrix code to work, so went with working but a bit duplicated solution for marking releases as pre-releases
> chore: Follow up to monorepo release process

- plugins/aws/.golangci.yml
- plugins/azure/.golangci.yml
- plugins/cloudflare/.golangci.yml
- plugins/digitalocean/.golangci.yml
- plugins/fuzz/.golangci.yml
- plugins/gcp/.golangci.yml
- plugins/github/.golangci.yml
- plugins/k8s/.golangci.yml
- plugins/okta/.golangci.yml
- plugins/terraform/.golangci.yml
Relates to https://github.com/cloudquery/.github/issues/266
> chore: Disable decorder on resource files (monorepo)

- .github/release.yml
- .github/workflows/add_tags.yml
- release-please-config.json
Fixes https://github.com/cloudquery/.github/issues/81
> chore(release): Use GitHub style changelog

- .github/workflows/release-plugin.yml
- .github/workflows/release-pr.yml
- .release-please-manifest.json
- plugins/.goreleaser.yaml
- plugins/source/aws/.goreleaser.yaml
- plugins/source/aws/CHANGELOG.md
- plugins/source/azure/.goreleaser.yaml
- plugins/source/cloudflare/.goreleaser.yaml
- plugins/source/digitalocean/.goreleaser.yaml
- plugins/source/fuzz/.goreleaser.yaml
- plugins/source/gcp/.goreleaser.yaml
- plugins/source/github/.goreleaser.yaml
- plugins/source/k8s/.goreleaser.yaml
- plugins/source/okta/.goreleaser.yaml
- plugins/source/terraform/.gitignore
- plugins/source/terraform/.goreleaser.yaml
- plugins/source/terraform/examples/terraform.tfstate
- release-please-config.json
To be merged after https://github.com/cloudquery/cloudquery/pull/1189
> chore: Update release process to reference plugins/source/<name>

- .release-please-manifest.json
- release-please-config.json
Fixes the release process to take into account old paths
> chore: Fix release process

- plugins/source/okta/docs/docs.go
- plugins/source/okta/go.mod
- plugins/source/okta/main.go
- plugins/source/okta/resources/provider.go
- plugins/source/okta/resources/users.go
Same as https://github.com/cloudquery/cloudquery/pull/1199 for the okta source
> chore: Rename plugin/source/okta module and imports

- plugins/source/terraform/docs/docs.go
- plugins/source/terraform/go.mod
- plugins/source/terraform/main.go
- plugins/source/terraform/resources/provider.go
- plugins/source/terraform/resources/tfdata.go
Same as https://github.com/cloudquery/cloudquery/pull/1199 for the terraform source
> chore: Rename plugin/source/terraform module and imports

- sites/versions/v1/source-aws.json
- sites/versions/v1/source-azure.json
- sites/versions/v1/source-cloudflare.json
- sites/versions/v1/source-digitalocean.json
- sites/versions/v1/source-gcp.json
- sites/versions/v1/source-github.json
- sites/versions/v1/source-k8s.json
- sites/versions/v1/source-okta.json
- sites/versions/v1/source-terraform.json
These versions haven't been published on this repo yet, but the CLI will fetch it from the old provider repos in that case.
> chore: Update plugin versions (monorepo)

- .release-please-manifest.json
- release-please-config.json
- sites/versions/v1/cli.json
- sites/versions/v1/source-fuzz.json
- sites/versions/v1/source-test.json
Syncs the versions with latest of each plugin
> chore: Sync versions

- .release-please-manifest.json
- sites/versions/v1/cli.json
Bring monorepo CLI versions to match latest release
> chore: Sync CLI versions

- release-please-config.json
[To latest released version](https://github.com/cloudquery/cloudquery/commit/cf1b087372561ab338a56a19a0302a9de9d4748f) so our bot knows how to diff changes
> chore: Update bootstrap sha

- cli/docs/index.md
Fixes some typos in our CLI docs
---
> fix(cli-docs): Fix typos in docs/index

- plugins/source/fuzz/index.md
Adds docs to the `fuzz` plugin
---
> feat(plugin-source-docs): Add docs

- .github/workflows/release_cli.yml
- .release-please-manifest.json
- cli/CHANGELOG.md
Use correct token for Go Releaser
---
> chore: Fix CLI release

- .github/workflows/endpoints.yml
Fixes https://github.com/cloudquery/cloudquery/runs/7828105739?check_suite_focus=true#step:5:14
---
> chore(plugin-source-aws): Fix endpoints workflow

- cli/.goreleaser.prerelease.yaml
- cli/.goreleaser.yaml
- plugins/.goreleaser.yaml
Right now all releases are created as pre-releases due to the monorepo switch.
After we test the releases we can merge this PR.
---
> chore(release): Switch to public releases

- .github/workflows/validate_release.yml
Fixes https://github.com/cloudquery/cloudquery-issues/issues/441 (internal issue), validates releases on the release PR
---
> chore: Add validate release workflow

- .github/renovate.json5
Fixes https://github.com/cloudquery/cloudquery-issues/issues/444 (internal issue). Will create updates for our linter and Go version in workflow files
---
> chore(deps): Add renovate config to update Go version and linter

- .github/workflows/validate_release.yml
Fixes https://github.com/cloudquery/cloudquery/runs/7834531842?check_suite_focus=true#step:6:65
---
> chore(release): Pass --snapshot flag for release validation

- cli/Dockerfile.goreleaser
Fixes https://github.com/cloudquery/cloudquery/runs/7834692085?check_suite_focus=true#step:6:104
---
> chore(release): Fix docker release

- plugins/source/cloudflare/go.mod
- plugins/source/cloudflare/go.sum
Updates the Cloudflare provider to Go v1.18 like others
---
> fix(deps): Update to Go 1.18

- cli/Dockerfile.goreleaser
Follow up to https://github.com/cloudquery/cloudquery/pull/1287
---
> fix(cli): Keep docker old entrypoint name

- cli/.goreleaser.yaml
Fixes Hombrew links, see https://github.com/cloudquery/homebrew-tap/commit/ee5a96aeed4e062013f0932a0a275ddb7a1c9694
---
> chore(release): Use PrefixedTag for Homebrew download URLs

- .github/.labeler.yml
- .github/workflows/add_tags.yml
Adds labels to PRs according to the plugin that is updated in the PR.
> chore: Add PR labels for plugins

- .github/renovate.json5
Fixes https://github.com/cloudquery/.github/issues/296
---
> chore(deps): Update to postgres 11 in tests

- cli/.goreleaser.prerelease.yaml
- cli/Dockerfile.goreleaser
> fix(cli): Update binary name

- .github/repo_settings.yml
- .github/workflows/sync_repo_settings.yml
Fixes https://github.com/cloudquery/cloudquery-issues/issues/442 (internal issue).
Migrates https://github.com/cloudquery/.github/blob/accea4c738bd5272a77221f985d1f0cc19c95e36/.github/workflows/sync_repo_settings.yml
---
> chore(ci): Add repo settings sync workflow

- .github/repo_settings.yml
- .github/workflows/test_policy_sql.yml
Related to https://github.com/cloudquery/.github/issues/296
---
> chore(test): Update postgres version to 11 in policy tests

- .release-please-manifest.json
This is a workaround to avoid conflicts between multiple release PRs https://github.com/googleapis/release-please/issues/1502
---
> chore(release): Add fillers to manifest file to avoid conflicts

- Makefile
- README.md
- scripts/build.sh
This also renames the `cli` binary buillt by `scripts/build.sh` to `cloudquery`.
> chore(docs): Update readme and add `build-cli` command

- .github/renovate.json5
To support updating https://github.com/cloudquery/cloudquery/blob/8b887e9f7d1cac9720904be00f102221bc0727d0/.github/workflows/lint_doc.yml#L55
---
> chore(deps): Support updating go version in cache paths

- plugins/source/aws/client/mocks/mock_ec2.go
- plugins/source/aws/client/services.go
- plugins/source/aws/docs/tables/aws_ec2_key_pairs.md
- plugins/source/aws/resources/provider/provider.go
- plugins/source/aws/resources/services/ec2/gen.hcl
- plugins/source/aws/resources/services/ec2/key_pairs.go
- plugins/source/aws/resources/services/ec2/key_pairs_mock_test.go
Brings https://github.com/cloudquery/cq-provider-aws/pull/1404 to the monorepo
---
> feat: Implement EC2 Key Pairs (#1403)

- .github/workflows/sync_repo_settings.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/1315
---
> chore(ci): Sync repo settings only if changed

- .release-please-manifest.json
https://github.com/cloudquery/cloudquery/pull/1329/files broke the version of Azure, looks like a race condition of sort
---
> chore: Fix Azure version in manifest file

- plugins/source/aws/docs/tables/aws_ec2_key_pairs.md
- plugins/source/aws/resources/provider/provider.go
- plugins/source/aws/resources/services/ec2/gen.hcl
- plugins/source/aws/resources/services/ec2/key_pairs.go
- plugins/source/aws/resources/services/ec2/key_pairs_mock_test.go
Follow up to https://github.com/cloudquery/cloudquery/pull/1325. This PR also updates `gen.hcl` to ensure there's no drift between the autogenerated code and the template file.
---
> fix(ec2): Add ARN to key pair

- website/content/features.ts
> fix(website): Fix features cards content on the main page

- plugins/source/aws/client/mocks/mock_ssm.go
- plugins/source/aws/client/services.go
- plugins/source/aws/docs/tables/aws_ssm_parameter_policies.md
- plugins/source/aws/docs/tables/aws_ssm_parameters.md
- plugins/source/aws/resources/provider/provider.go
- plugins/source/aws/resources/services/ssm/parameters.go
- plugins/source/aws/resources/services/ssm/parameters.hcl
- plugins/source/aws/resources/services/ssm/parameters_mock_test.go
Fixes: https://github.com/cloudquery/cloudquery/issues/1363
> feat: Add AWS SSM Parameters resource

- plugins/source/aws/docs/tables/aws_xray_encryption_config.md
- plugins/source/aws/docs/tables/aws_xray_groups.md
- plugins/source/aws/docs/tables/aws_xray_sampling_rules.md
- plugins/source/aws/resources/services/xray/encryption_config.go
- plugins/source/aws/resources/services/xray/gen.hcl
- plugins/source/aws/resources/services/xray/groups.go
- plugins/source/aws/resources/services/xray/sampling_rules.go
- regenerate AWS xray code with cq-gen
- update cq-gen config to fix drift
- update resolvers to use paginators
> chore(aws): Update AWS Xray code

- .github/workflows/pr_title.yml
> chore: Add doc to title

- .github/labeler.yml
> chore: Add website labler

- .github/workflows/add_tags.yml
> chore: Add doc label for titles

- website/components/pages/home.tsx
- website/pages/docs/index.mdx
Some light editing applied to the new website copy
> chore: Website docs fixes

- plugins/source/aws/resources/services/elasticache/clusters.go
- plugins/source/aws/resources/services/elasticache/engine_versions.go
- plugins/source/aws/resources/services/elasticache/global_replication_groups.go
- plugins/source/aws/resources/services/elasticache/parameter_groups.go
- plugins/source/aws/resources/services/elasticache/replication_groups.go
- plugins/source/aws/resources/services/elasticache/reserved_cache_nodes.go
- plugins/source/aws/resources/services/elasticache/reserved_cache_nodes_offerings.go
- plugins/source/aws/resources/services/elasticache/service_updates.go
- plugins/source/aws/resources/services/elasticache/snapshots.go
- plugins/source/aws/resources/services/elasticache/subnet_groups.go
- plugins/source/aws/resources/services/elasticache/user_groups.go
- plugins/source/aws/resources/services/elasticache/users.go
This simplifies the table resolvers for Elasticache a little bit.
> chore(aws): Use paginator for Elasticache pagination

- .github/labeler.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/1439
---
> chore: Fix indentation for labeler config

- website/theme.config.tsx
> chore(docs): Add defaultMenuCollapsed prop to the theme config

- website/components/Footer.tsx
- website/components/pages/home.tsx
> chore(docs): Fix landing page links

- website/pages/docs/faq.md
- website/pages/docs/getting-started/getting-started-with-aws.mdx
- website/pages/docs/getting-started/getting-started-with-azure.mdx
- website/pages/docs/getting-started/getting-started-with-gcp.mdx
- website/pages/docs/troubleshooting.md
> chore(docs): Remove some stale policy stuff

- plugins/source/github/client/client.go
> fix: Validate github config

- website/components/pages/home.tsx
- website/content/features.ts
Updates our landing page to include use-cases. 
---
> chore(docs): Fix landing page

- CONTRIBUTING.md
- issue_reporting.md
Brings our contribution guidelines up to date.
> chore(docs): Update CONTRIBUTING.md and issue_reporting.md

- .github/renovate.json5
Follow up to https://github.com/cloudquery/cloudquery/pull/1323 to catch all the possible locations of go in our workflow files
---
> chore: Update renovate to update go version in workflow files

- website/pages/docs/policies.md
> doc: Fix links

- .github/workflows/test_build.yml
Currently building can take upwards of 3 minutes. Running mock tests have no dependency on compilation. In order to reduce waiting this PR splits the two tests into their own files
---
> chore: Improve Test performance

- README.md
> chore: Build status

- website/next-sitemap.config.js
- website/package.json
- website/yarn.lock
Added autogenerated sitemap
https://cloudquery-om929vcwh-cloudquery.vercel.app/sitemap.xml
---
> feat: Website sitemap

- website/components/Integrations.tsx
- website/components/QueriesExamples.tsx
- website/components/pages/home.tsx
> feat: Add queries examples section to the landing page

- website/components/BlogHeader.tsx
- website/components/HeaderOgImage.tsx
- website/theme.config.tsx
- website/vercel.json
> fix: Website links

- .github/workflows/release_plugin.yml
Fixes a small issue with the version update PRs
---
> chore: Fix version update PR body

- website/components/QueriesExamples.tsx
> chore: Format query examples on the landing page

- plugins/source/aws/docs/tables/aws_acm_certificates.md
- plugins/source/aws/go.mod
- plugins/source/aws/go.sum
- plugins/source/aws/resources/provider/provider.go
- plugins/source/aws/resources/services/acm/certificates.go
- plugins/source/aws/resources/services/acm/certificates.hcl
- plugins/source/aws/resources/services/acm/certificates_mock_test.go
> chore: Add acm certificates cq-gen file

- CODEOWNERS
Add Erez as main reviewer for anything under .github. or maybe also add @yevgenypats @hermanschaaf ? (let me know what you think is best)?
---
> chore: Add Erez as reviewer for .github

- .github/workflows/approve_vercel.yml
- .github/workflows/ignore_vercel.yml
Trying to ignore the Vercel red status check
---
> chore: Set vercel status

- .github/workflows/broken_links.yml
- website/.gitignore
- website/pages/hub/index.mdx
- website/pages/hub/meta.json
- website/pages/meta.json
- website/scripts/generate-hub.js
See https://github.com/shuding/nextra/issues/729 for reasoning.
Nextra fails to build the Hub "edit on GitHub" links. Didn't find a way to customize it. 
---
> chore(website): Rename Hub to Plugins

- .github/workflows/approve_vercel.yml
Follow up to the Vercel workflow
---
> chore: Fix Vercel workflow

- .github/workflows/approve_vercel.yml
I hope this works. Since this is a `pull_request_target` event, the only way to test is to merge to `main`
---
> chore: Vercel workflow fix

- .github/workflows/approve_vercel.yml
Ok I think this should work, visit https://github.com/actions/github-script#download-data-from-a-url
---
> chore: Use payload.pull_request

- .github/workflows/lint_doc.yml
- .github/workflows/lint_golang.yml
- .github/workflows/test_build.yml
- .github/workflows/test_policy_sql.yml
- .github/workflows/test_unit.yml
We don't really need to run these workflows on release PRs as those PRs only update the changelog
---
> chore: Don't run test,build,lint on release PRs

- website/vercel.json
> chore: Hub redirects

- website/components/clients/LogosBlock.tsx
Need permission from legal first.
---
> feat(website): Remove Tempus logo until permission

- website/pages/logo.mdx
> fix: Fix broken links on website

- plugins/source/digitalocean/client/helpers.go
- plugins/source/digitalocean/go.mod
- plugins/source/digitalocean/go.sum
- plugins/source/digitalocean/resources/account.go
> feat: Added throttling for digitalocean API calls

- website/pages/logo.mdx
> chore: Add the Open Graph metadata to the logo page

- release-please-config.json
Re-introduces the GitHub changelog format that was disabled in https://github.com/cloudquery/cloudquery/pull/1195
---
> chore: Use GitHub changelog format

- release-please-config.json
This should work with https://github.com/cloudquery/cloudquery/pull/1576 and https://github.com/cloudquery/cloudquery/pull/1575 merged
---
> chore: Use GitHub changelog type

- plugins/source/aws/client/helpers.go
- plugins/source/aws/client/mocks/mock_iam.go
- plugins/source/aws/client/services.go
- plugins/source/aws/resources/services/iam/users.go
- plugins/source/aws/resources/services/iam/users_mock_test.go
> fix: IAM Users

- website/components/mdx/_getting-started-download-section.mdx
- website/pages/blog/how-to-aws-cis-compliance.md
Fixes https://github.com/cloudquery/cloudquery/issues/1594.
Will do this automatically in a follow up PR
---
> chore: Fix broken links

- website/pages/blog/2022-may-monthly.md
- website/pages/blog/announcing-cloudquery-history.md
- website/pages/blog/announcing-cloudquery-policies.md
- website/pages/blog/aws-improvements-Q1-2022.md
- website/pages/blog/aws-resources-view.md
- website/pages/blog/open-source-cspm.md
- website/pages/blog/our-open-source-journey-building-cloudquery.md
- website/pages/blog/releasing-cloudquery-0.20.0.md
- website/pages/blog/running-aws-foundational-security-best-practices-with-cloudquery-policies.md
- website/pages/blog/running-aws-pci-dss-with-cloudquery-policies.md
- website/pages/blog/running-nsa-and-cisa-kubernetes-hardening-tests-with-cloudquery-policies.md
- website/pages/docs/cli/fetch/configuration.md
- website/pages/docs/cli/rate_limiting.md
- website/pages/docs/faq.md
- website/pages/docs/getting-started/getting-started-with-aws.mdx
- website/pages/docs/getting-started/getting-started-with-azure.mdx
- website/pages/docs/getting-started/getting-started-with-gcp.mdx
Fixes some broken links/redirects in our docs and updates some other sections (e.g. to remove Hub mentions).
Probably needs more follow up
---
> chore: Fix some broken links/redirects in our docs

- plugins/source/aws/resources/services/iam/users.go
> fix: IAM User edge Case

- .github/workflows/test_build.yml
Build tests do not rely on postgres service to run
---
> chore: Update Build Tests

- plugins/source/aws/docs/index.md
> fix: Fix docs and trigger release

- .github/repo_settings.yml
- .github/workflows/endpoints.yml
- .github/workflows/lint_doc.yml
- .github/workflows/test_build.yml
- .github/workflows/test_policy_sql.yml
- .github/workflows/test_unit.yml
1. Ensure cache is per module
2. Align workflows style (remove go version from matrix)
3. Cache only linux paths as we don't run on other OS
---
> chore(ci): Align workflows, cache per module

- .github/renovate.json5
This config was moved to https://github.com/cloudquery/.github/pull/333/files
---
> chore: Cleanup renovate config

- website/components/QueriesExamples.tsx
- website/components/pages/home.tsx
small fix to download go to action and screen sizes
---
> feat(website): Fix code examples for screen size

- release-please-config.json
> chore: Add test to release-please

- plugins/source/test/plugin/plugin.go
> feat(source-test): Add zip release to test plugin

- plugins/.goreleaser.yaml
Forgot to add `id` field to yaml
---
> chore: Fix goreleaser zip

- .github/repo_settings.yml
- .github/workflows/approve_vercel.yml
- website/scripts/generate-hub.js
Instead listing directories, create docs only for pre-defined plugins to avoid failing on the test plugin
---
> chore: Fix website build, add Heroku

- website/scripts/generate-hub.js
> chore: Remove Heroku from website

- .release-please-manifest.json
This ensures we don't have git conflicts between different release PRs (https://github.com/cloudquery/cloudquery/pull/1314)
---
> chore(release): Add test provider version filler

- plugins/.goreleaser.yaml
This allows publishing plugins as zip files without breaking old CLI versions
---
> chore: Remove zips from checksum file

- .gitignore
- cli/cmd/doc_test.go
- cli/cmd/generate_test.go
- cli/cmd/sync_test.go
- cli/internal/destinations/postgresql/postgresql_test.go
Adding more tests. and also moving cmd tests to run via rootCmd so we can get full coverage and know that the basic commands are working. 
---
> test: Add more cmd tests

- plugins/source/aws/resources/services/iam/users.go
fixes the tags for iam_users
---
> fix: Tags in users.go

- .github/workflows/broken_links.yml
When running this workflow on a schedule there's no Vercel deploy preview so we need to wait on the production environment
---
> chore: Fix check broken links on schedule

- contributing/adding_a_new_resource.md
Fixes a small typo in our docs
---
> chore(docs): Update adding_a_new_resource.md

- .github/workflows/broken_links.yml
Follow up on https://github.com/cloudquery/cloudquery/pull/1714. We can't have the same id for a step, so we need an intermediate step to set a default value for an input.
---
> chore: Fix broken links checker

- .github/workflows/release_pr.yml
Not sure how to test this expect merging to `main`. This should avoid the need to manually add new components to this workflow
---
> chore: Make release PR flow generic

- plugins/CONTRIBUTING.md
Fixes https://github.com/cloudquery/cloudquery/issues/1701
---
> chore: Fix plugins contributing docs

- .github/workflows/broken_links.yml
Reduce number of parallel requests to avoid hitting external links rate limits:
https://github.com/cloudquery/cloudquery/runs/8176351681?check_suite_focus=true#step:8:503
---
> chore: Reduce broken links checker requests

- website/components/QueriesExamples.tsx
> fix: Query on Main page

- plugins/source/okta/resources/provider.go
- plugins/source/terraform/resources/provider.go
- website/pages/docs/developers/sdk/provider/overview.md
But it still needs to be set during build.
> fix: Provide `Version` in all providers

- .github/workflows/release_pr.yml
I broke setting releases as pre-releases until the binaries are uploaded in https://github.com/cloudquery/cloudquery/pull/1716.
This should fix it
---
> chore: Fix release please workflow

- plugins/source/gcp/.goreleaser.yaml
Fixes https://github.com/cloudquery/cloudquery/runs/8204004361?check_suite_focus=true#step:6:64
---
> chore(ci-release): Fix GCP Go Releaser

- plugins/.golangci.yml
To accommodate both SDK and new SDK based plugins
---
> chore(lint): Add `errors.WithStack` to `wrapcheck` linter

- plugins/source/gcp/client/client.go
> fix: Enable GCP to find all Active Projects

- plugins/source/heroku/docs/index.md
- plugins/source/heroku/plugin/plugin.go
The configuration section is (still) a bit iffy.
> chore: Update heroku docs, remove backoff from config

- cli/pkg/plugin/registry/validate.go
> fix(cli): Windows verification check

- plugins/source/aws/main.go
> fix: Add Sentry DSN

- .github/issue_labeler.yml
To triage Website and docs issues
---
> chore: Add more labels to issues

- .github/renovate.json5
We handle Website updates once per month, so this PR groups all the update to a single PR to avoid a ton of noise
---
> chore(deps): Group all Website dependencies updates to a single PR

- .github/renovate.json5
Fixes https://github.com/cloudquery/cloudquery/issues/1843
---
> chore: Fix renovate config

- plugins/source/aws/client/client.go
> fix(aws): Nil pointer in config unmarshal

- website/package.json
- website/scripts/generate-hub.js
- website/yarn.lock
We should be committing the docs to GitHub instead of generating during build
---
> chore: Generate plugin docs from GitHub files instead of go command

- cli/internal/plugins/plugins.go
> fix: Use correct binary path on Windows

- plugins/source/cloudflare/main.go
- plugins/source/digitalocean/main.go
- plugins/source/heroku/main.go
> feat: Add Sentry DSN

- .github/workflows/approve_vercel.yml
- .github/workflows/issue_labeler.yml
- .github/workflows/pr_labeler.yml
- .github/workflows/pr_title.yml
- .github/workflows/release_pr.yml
Switches to our bot token where applicable to avoid hitting rate limits with the built-in token.
We can do this only for workflows that have access to GitHub secrets even when triggered on forks PRs
---
> chore(ci): Use cq-bot token where applicable

- plugins/source/aws/codegen/recipes/backup.go
- plugins/source/aws/codegen/recipes/fsx.go
- plugins/source/aws/codegen/recipes/iam.go
- plugins/source/aws/codegen/recipes/ssm.go
- plugins/source/aws/codegen/recipes/wafv2.go
- plugins/source/aws/go.mod
- plugins/source/aws/go.sum
- plugins/source/aws/resources/services/backup/vaults.go
- plugins/source/aws/resources/services/elbv2/load_balancers.go
- plugins/source/aws/resources/services/fsx/file_systems.go
- plugins/source/aws/resources/services/fsx/snapshots.go
- plugins/source/aws/resources/services/fsx/volumes.go
- plugins/source/aws/resources/services/iam/user_access_keys.go
- plugins/source/aws/resources/services/iot/thing_groups.go
- plugins/source/aws/resources/services/iot/things.go
- plugins/source/aws/resources/services/kms/keys.go
- plugins/source/aws/resources/services/ssm/documents.go
- plugins/source/aws/resources/services/ssm/documents_fetch.go
- plugins/source/aws/resources/services/wafv2/managed_rule_groups.go
- plugins/source/aws/resources/services/wafv2/managed_rule_groups_fetch.go
This fixes the unit tests for all AWS resources, except for Cloudtrail, which is handled by https://github.com/cloudquery/cloudquery/pull/1892
> fix: Fix some AWS resources with postResolvers

- plugins/source/aws/go.mod
- plugins/source/aws/go.sum
- plugins/source/aws/resources/services/backup/vaults_fetch.go
- plugins/source/aws/resources/services/iam/roles_fetch.go
- plugins/source/aws/resources/services/kms/keys_fetch.go
- plugins/source/aws/resources/services/lightsail/instances_fetch.go
- plugins/source/aws/resources/services/rds/cluster_snapshots_fetch.go
- plugins/source/aws/resources/services/rds/db_snapshots_fetch.go
- plugins/source/aws/resources/services/wafv2/rule_groups_fetch.go
Fixes issues identified by https://github.com/cloudquery/plugin-sdk/pull/156
> fix: Fix AWS JSON issues found by new SDK check (v2)

- plugins/source/aws/codegen/recipes/s3.go
- plugins/source/aws/resources/services/s3/bucket_cors_rules.go
- plugins/source/aws/resources/services/s3/bucket_encryption_rules.go
- plugins/source/aws/resources/services/s3/bucket_grants.go
- plugins/source/aws/resources/services/s3/bucket_lifecycles.go
- plugins/source/aws/resources/services/s3/buckets.go
- plugins/source/aws/resources/services/s3/buckets_fetch.go
Closes https://github.com/cloudquery/cloudquery/issues/1909
Closes https://github.com/cloudquery/cloudquery/issues/1908
> fix: Fix some issues with AWS S3 resource (v2)

- plugins/source/aws/codegen/recipes/wafv2.go
- plugins/source/aws/resources/services/wafv2/web_acls.go
Closes https://github.com/cloudquery/cloudquery/issues/1926
> fix: Add logging_configuration field to aws_wafv2_web_acls

- plugins/source/azure/codegen/recipes/base.go
- plugins/source/azure/go.mod
- plugins/source/azure/go.sum
- plugins/source/azure/resources/services/datalake/analytics_accounts.go
- plugins/source/azure/resources/services/datalake/store_accounts.go
- plugins/source/azure/resources/services/sql/database_blob_auditing_policies.go
- plugins/source/azure/resources/services/sql/databases.go
- plugins/source/azure/resources/services/sql/server_admins.go
- plugins/source/azure/resources/services/sql/server_blob_auditing_policies.go
- plugins/source/azure/resources/services/sql/server_dev_ops_auditing_settings.go
- plugins/source/azure/resources/services/web/apps.go
Fixes Azure code gen to handle custom types `date.time` and `uuid.UUID` (the changes for `data.time` are included in https://github.com/cloudquery/cloudquery/pull/1885)
---
> fix: Update Azure codegen

- release-please-config.json
Follow up to https://github.com/cloudquery/cloudquery/pull/1957
---
> chore: Update release components

- .github/workflows/validate_release.yml
Woops, forgot to remove my test string
---
> chore: Use branch name in validate release

- .github/workflows/release_plugin.yml
Similar to https://github.com/cloudquery/cloudquery/pull/1971
---
> chore: Fix Go Release plugin dir

- .github/workflows/release_cli.yml
- .github/workflows/release_plugin.yml
This should correct handle pre-release and regular releases
Fixes https://github.com/cloudquery/cloudquery/actions/runs/3105957008/jobs/5032220559
---
> chore: Fix parsing of tags during release

- cli/internal/plugins/download.go
> fix: Use uppercase downloading during progress

- plugins/source/aws/codegen/recipes/applicationautoscaling.go
- plugins/source/aws/resources/services/applicationautoscaling/policies.go
Closes https://github.com/cloudquery/cloudquery/issues/1999
> fix: Fix applicationautoscaling multiplexing (v2)

- website/pages/_meta.json
- website/pages/docs/plugins/_meta.json
- website/pages/docs/plugins/source.md
- website/vercel.json
Fix redirects to plugins, also uses `source` as to be consistent with other routes where the page title matches the route
---
> chore: Fix website redirects

- release-please-config.json
This should make all versions versioned as `v1`
---
> chore(release): Switch to v1

- plugins/destination/postgresql/main.go
The purpose of this PR is to trigger a release PR for the stub postgres plugin
---
> feat: Update log

- website/pages/docs/index.mdx
Small grammar and spelling fixes.
---
> doc: Fix grammar/spelling in intro doc

- cli/cmd/sync.go
- cli/go.mod
- cli/go.sum
- cli/internal/plugins/manager_test.go
Sync CLI supports now reading directories, files and files with multiple yaml objects.
> feat: Update SDK to v0.10.1

- contributing/adding_a_new_resource.md
Fixes some markdown relations issues:
> chore(docs): Fix some markdown related issues

- cli/.golangci.yml
- plugins/.golangci.yml
> chore: Remove GCI from lint

- website/pages/blog/cloudquery-v1-release.md
- website/pages/blog/podcast-software-engineer-daily.md
- website/pages/docs/core-concepts/plugins.md
- website/pages/docs/plugins/source_plugins_release_stages.md
- website/pages/docs/quickstart.mdx
Some of these were found by `misspell`, some by me
> chore(website): Some v1 docs fixes

- .github/workflows/release_cli.yml
- sites/versions/vercel.json
- website/components/mdx/_getting-started-download-section.mdx
- website/pages/blog/how-to-aws-cis-compliance.md
Creates our own latest link for the CLI
> chore(site-versions): Add latest redirect

- .github/workflows/dest_postgresql.yml
- .github/workflows/dest_test.yml
- .github/workflows/source_aws.yml
- .github/workflows/source_cloudflare.yml
- .github/workflows/source_digitalocean.yml
- .github/workflows/source_gcp.yml
- .github/workflows/source_heroku.yml
- .github/workflows/source_k8s.yml
- .github/workflows/source_okta.yml
- .github/workflows/source_terraform.yml
- .github/workflows/source_test.yml
> chore: Disable cache temporary

- .github/workflows/dest_test.yml
- .github/workflows/source_aws.yml
- .github/workflows/source_cloudflare.yml
- .github/workflows/source_digitalocean.yml
- .github/workflows/source_gcp.yml
- .github/workflows/source_heroku.yml
- .github/workflows/source_k8s.yml
- .github/workflows/source_okta.yml
- .github/workflows/source_terraform.yml
- .github/workflows/source_test.yml
We should trigger the workflows if someone changes the workflow file. Otherwise we won't be able to test changes to workflows
> chore(ci): Add missing paths

- .github/workflows/dest_postgresql.yml
- .github/workflows/dest_test.yml
- .github/workflows/source_aws.yml
- .github/workflows/source_cloudflare.yml
- .github/workflows/source_digitalocean.yml
- .github/workflows/source_gcp.yml
- .github/workflows/source_heroku.yml
- .github/workflows/source_k8s.yml
- .github/workflows/source_okta.yml
- .github/workflows/source_terraform.yml
- .github/workflows/source_test.yml
> chore(ci): Fix golangci-lint

- .github/workflows/source_azure.yml
- .github/workflows/source_github.yml
Those are missing from the original PR
> chore(ci): Add missing workflows

- .github/workflows/cli.yml
- .github/workflows/endpoints.yml
This was missed in https://github.com/cloudquery/cloudquery/pull/2140 and currently fails these workflows
> fix: Disable caching for CLI and endpoints workflow

- .github/workflows/cli.yml
Same as https://github.com/cloudquery/cloudquery/pull/2143 for the CLI
> chore: Fix CLI go lint

- .github/workflows/dest_postgresql.yml
- .github/workflows/dest_test.yml
- .github/workflows/source_aws.yml
- .github/workflows/source_azure.yml
- .github/workflows/source_cloudflare.yml
- .github/workflows/source_digitalocean.yml
- .github/workflows/source_gcp.yml
- .github/workflows/source_github.yml
- .github/workflows/source_heroku.yml
- .github/workflows/source_k8s.yml
- .github/workflows/source_okta.yml
- .github/workflows/source_terraform.yml
- .github/workflows/source_test.yml
- plugins/destination/postgresql/README.md
> chore(ci): Add go cache

- .github/workflows/wait_for_required_workflows.yml
Fixes https://github.com/cloudquery/cloudquery/issues/2184
> chore(ci-wait-for-all): Match dirs as array of string, use startsWith

- .github/workflows/cli.yml
- .github/workflows/endpoints.yml
- .github/workflows/release_cli.yml
- .github/workflows/release_plugin.yml
- .github/workflows/validate_release.yml
Fixes https://github.com/cloudquery/cloudquery/issues/2187
> chore(ci): Add missing caching

- .github/workflows/wait_for_required_workflows.yml
> chore(ci-wait-for-all): Add JSON stringify

- .github/workflows/source_okta.yml
Fixes https://github.com/cloudquery/cloudquery/issues/2196
> chore(ci-okta): Fix workflow

- .github/workflows/source_test.yml
Fixes https://github.com/cloudquery/cloudquery/issues/2199
> chore(ci-source-test): Fix workflow

- .github/workflows/cli.yml
- .github/workflows/source_aws.yml
- .github/workflows/source_azure.yml
- .github/workflows/source_cloudflare.yml
- .github/workflows/source_digitalocean.yml
- .github/workflows/source_gcp.yml
- .github/workflows/source_github.yml
- .github/workflows/source_heroku.yml
- .github/workflows/source_k8s.yml
- .github/workflows/source_okta.yml
- .github/workflows/source_terraform.yml
- .github/workflows/source_test.yml
Source plugins workflows had `destination` as the job key
> chore(ci): Fix jobs ids

- .github/workflows/source_aws.yml
- .github/workflows/source_azure.yml
- .github/workflows/source_cloudflare.yml
- .github/workflows/source_digitalocean.yml
- .github/workflows/source_gcp.yml
- .github/workflows/source_github.yml
- .github/workflows/source_heroku.yml
- .github/workflows/source_k8s.yml
- .github/workflows/source_okta.yml
- .github/workflows/source_terraform.yml
- .github/workflows/source_test.yml
- plugins/source/azure/docs/tables/azure_network_route_filters.md
- plugins/source/azure/docs/tables/azure_network_virtual_network_gateway_connections.md
- plugins/source/cloudflare/docs/tables/cloudflare_account_members.md
- plugins/source/cloudflare/docs/tables/cloudflare_waf_groups.md
- plugins/source/cloudflare/docs/tables/cloudflare_waf_rules.md
- plugins/source/cloudflare/docs/tables/cloudflare_worker_cron_triggers.md
- plugins/source/cloudflare/docs/tables/cloudflare_workers_secrets.md
- plugins/source/gcp/docs/tables/README.md
- plugins/source/gcp/docs/tables/gcp_resourcemanager_project_policies.md
- plugins/source/terraform/docs/tables/tf_resource_instances.md
- plugins/source/terraform/docs/tables/tf_resources.md
- plugins/source/test/docs/tables/README.md
- plugins/source/test/docs/tables/test_some_table.md
Fixes https://github.com/cloudquery/cloudquery/issues/2188
> chore(ci): Add missing docs drift check

- .github/workflows/approve_vercel.yml
We don't generate the docs in our Website build so we can drop this requirement
> chore(ci): Approve Vercel status only on Website changes

- .github/pr_labeler.yml
Heroku was missing the PR labeler
> chore(ci): Add missing Heroku labeler configuration

- .github/.kodiak.toml
Sometime we want to bump PRs in the merge queue
> chore: This should allow us to bump PRs in the merge queue

- website/pages/docs/plugins/source-plugin-release-stages.md
Simplifies the doc and removes `Alpha,Beta`
> chore(docs): Update plugin stages doc

- website/vercel.json
The plugins links on our homepage are broken. This should fix it
> chore: Fix redirects

- cli/cmd/root.go
> fix(cli): Dont truncate log (append only)

- plugins/source/aws/codegen/recipes/emr.go
- plugins/source/aws/resources/services/emr/clusters.go
- plugins/source/aws/resources/services/emr/clusters_fetch.go
> feat(aws): EMR Clusters to use PreResourceResolver

- website/pages/blog/migrating-from-v0-to-v1.md
> chore(website): Minor nits to migration blog

- plugins/source/aws/codegen/recipes/cloudtrail.go
- plugins/source/aws/docs/tables/aws_cloudtrail_trails.md
- plugins/source/aws/resources/services/cloudtrail/models/cloudtrail.go
- plugins/source/aws/resources/services/cloudtrail/trails.go
- plugins/source/aws/resources/services/cloudtrail/trails_fetch.go
- plugins/source/aws/resources/services/cloudtrail/trails_mock_test.go
> fix(aws): Re-add Cloudtrail tags

- plugins/source/aws/codegen/recipes/base.go
- plugins/source/aws/codegen/recipes/route53.go
- plugins/source/aws/docs/tables/aws_route53_hosted_zones.md
- plugins/source/aws/resources/services/route53/hosted_zones.go
- plugins/source/aws/resources/services/route53/hosted_zones_fetch.go
- plugins/source/aws/resources/services/route53/hosted_zones_mock_test.go
- plugins/source/aws/resources/services/route53/models/route53.go
> fix(aws): Re-add Route53 hosted zone tags

- website/pages/blog/migrating-from-v0-to-v1.md
When migrating to v1, it is important to start from a clean DB.
> doc: Add section about starting from clean db to migration blog post

- plugins/source/azure/resources/services/web/vnet_connections.go
> fix(azure): Skip resource if SiteConfig is nil

- website/pages/docs/core-concepts/migrations.md
- website/pages/docs/core-concepts/policies.md
- website/pages/docs/cq-vs-others/cspms.md
- website/pages/docs/developers/architecture.md
- website/pages/docs/developers/codegen.md
Closes https://github.com/cloudquery/cloudquery/issues/2307
> chore(website): Remove mention of providers. Use plugins.

- README.md
Remove duplicate bits from readme.
Make it consistent with our main docs and just link to docs instead of having things in both places.
> chore: Update README to be consistent with docs

- website/pages/docs/developers/_meta.json
I think it should be `Creating a New Plugin` and `Generating Resources`
> chore(website): Fix developers sidebar titles

- plugins/destination/postgresql/client/client_test.go
- plugins/destination/postgresql/client/deletestale.go
- plugins/destination/postgresql/client/deletestale_test.go
- plugins/destination/postgresql/go.mod
- plugins/destination/postgresql/go.sum
This will only compile after https://github.com/cloudquery/plugin-sdk/pull/269 is released
> fix: Update postgresql plugin to work with new sdk (deleteStale feature)

- plugins/destination/postgresql/README.md
- plugins/destination/postgresql/client/client.go
- plugins/destination/postgresql/client/deletestale.go
- plugins/destination/postgresql/client/deletestale_test.go
- plugins/destination/postgresql/client/migrate_test.go
- plugins/destination/postgresql/client/spec.go
- plugins/destination/postgresql/client/write.go
- plugins/destination/postgresql/client/write_test.go
Adds batching to improve performance over network + exposing this as configuration.
Closes https://github.com/cloudquery/cloudquery/issues/2462
> feat(pg): Use pgx batch to improve performance

- .github/workflows/source_k8s.yml
- plugins/source/k8s/Makefile
- plugins/source/k8s/docs/tables/k8s_batch_jobs.md
- plugins/source/k8s/docs/tables/k8s_core_pods.md
- plugins/source/k8s/resources/services/batch/jobs.go
- plugins/source/k8s/resources/services/core/pods.go
Related to https://github.com/cloudquery/cloudquery/issues/2189. Added drift detection to find out some columns were missing
> feat(k8s): Add jobs.spec_pod_failure_policy and pods.spec_host_users columns

- .github/workflows/cli.yml
- cli/Makefile
The same we have for plugins, this workflow checks that the CLI docs are up to date
> chore(ci-cli): Check for docs drift

- plugins/source/aws/client/client.go
> fix: Improperly Configured Service Clients

- website/pages/docs/reference/source-spec.md
Adds a note to help developers point to how to configure a specific plugin
> chore(docs): Update source-spec.md

- plugins/source/k8s/go.mod
- plugins/source/k8s/go.sum
- plugins/source/k8s/resources/services/apps/deployments_mock_test.go
- plugins/source/k8s/resources/services/apps/replica_sets_mock_test.go
- plugins/source/k8s/resources/services/apps/stateful_sets_mock_test.go
- plugins/source/k8s/resources/services/batch/cron_jobs_mock_test.go
- plugins/source/k8s/resources/services/batch/jobs_mock_test.go
- plugins/source/k8s/resources/services/core/endpoints_mock_test.go
- plugins/source/k8s/resources/services/core/limit_ranges_mock_test.go
- plugins/source/k8s/resources/services/core/namespaces_mock_test.go
- plugins/source/k8s/resources/services/core/resource_quotas_mock_test.go
- plugins/source/k8s/resources/services/core/service_accounts_mock_test.go
- plugins/source/k8s/resources/services/networking/network_policies_mock_test.go
- plugins/source/k8s/resources/services/rbac/role_bindings_mock_test.go
- plugins/source/k8s/resources/services/rbac/roles_mock_test.go
- plugins/source/k8s/resources/services/testing/data.go
Continuation of https://github.com/cloudquery/cloudquery/pull/2726
~Needs https://github.com/cloudquery/plugin-sdk/pull/287 merged/tagged.~
> chore(k8s): Remove old faker

- website/pages/docs/reference/destination-spec.md
- website/pages/docs/reference/source-spec.md
Add information about `spec` field
> doc: Improve Information about spec

- website/pages/docs/reference/destination-spec.md
- website/pages/docs/reference/source-spec.md
Thank you to @alanjoseuk for pointing this out
> doc: Fix typo

- website/pages/docs/faq.md
- website/pages/docs/quickstart.mdx
- website/pages/docs/reference/destination-spec.md
> doc: Change default write_mode to 'overwrite-delete-stale'

- website/pages/docs/quickstart.mdx
> doc: Add authentication section to quickstart section

- plugins/destination/postgresql/client/write.go
> fix: Improve PG Write Speeds

- website/pages/docs/cq-vs-others/overview.md
Closes https://github.com/cloudquery/cloudquery/issues/2906
> chore(website): Fix broken links in comparison page

- .github/workflows/release_plugin.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/2909 to fix a copy paste typo
> chore(release): Use correct step id in release workflow

- plugins/source/aws/docs/configuration.md
> doc(aws): Fix Source Plugin Configuration Reference

- website/pages/blog/migrating-from-v0-to-v1.md
- website/pages/docs/quickstart.mdx
- website/pages/docs/reference/destination-spec.md
- website/pages/docs/reference/source-spec.md
> doc: Document that path is not optional

- website/pages/_app.tsx
Part of https://www.simpleanalytics.com/ onboarding flow
> chore(website): Add analytics

- cli/.goreleaser.prerelease.yaml
Fixes https://github.com/cloudquery/cloudquery/issues/3072
A follow up PR for the docs is coming soon, we should update the docs only after we release a new CLI
> fix(cli): Update binary names to use Go releaser defaults

- website/components/mdx/_getting-started-download-section.mdx
- website/pages/blog/how-to-aws-cis-compliance.md
To be merged after https://github.com/cloudquery/cloudquery/pull/3080 is released
> chore(docs): Update CLI download links

- .github/workflows/broken_links.yml
- website/pages/confirm.mdx
Fixes the broken links workflow to wait for the correct deployment (we have the Website and our versions site, so we need to wait for the Website deployment)
> chore(ci): Wait for correct deployment

- .github/workflows/release_plugin.yml
Fixes the release plugin workflow I broken with all the cache changes
> chore: Fix release plugin workflow

- sites/versions/vercel.json
I broke our latest CLI link with the binary renames. This should fix it
> chore: Fix Vercel latest link

- website/pages/docs/plugins/sources.md
Add `Cloudflare` plugin links to plugins page for website to solve #2817 
> fix: Add cloudflare to the plugins page for website

- website/pages/docs/advanced-topics/_meta.json
- website/pages/docs/advanced-topics/running-cloudquery-in-parallel.mdx
- website/pages/docs/quickstart.mdx
- website/pages/docs/troubleshooting.md
> doc: Make it clearer that names must be unique

- plugins/source/test/tables/test.go
Small fix to the name of the function used in the test plugin that I had in my local stash.
> chore: Fix function name in test plugin

- plugins/source/aws/docs/configuration.md
- plugins/source/azure/docs/configuration.md
- plugins/source/gcp/docs/configuration.md
- plugins/source/k8s/docs/configuration.md
Docs for the long tail of small providers to follow.
> doc: Add examples to configuration docs for the big plugins

- cli/cmd/analytics.go
- cli/cmd/sync.go
- cli/cmd/sync2.go
- cli/go.mod
- cli/go.sum
This is split from this PR: https://github.com/cloudquery/cloudquery/pull/3323 so we can merge and release CLI first
> feat: Update CLI to SDK v0.13.16 - CQTypes and v2 protocol

- .github/workflows/wait_for_required_workflows.yml
- .release-please-manifest.json
- plugins/destination/csv/Makefile
A few missing bits from the CSV plugin
> chore(plugin-csv): Add missing configurations

- plugins/source/heroku/client/spec.go
> fix: Delete broken spec parameters

- .github/ISSUE_TEMPLATE/bug_report.md
- cli/docs/index.md
- plugins/destination/postgresql/README.md
- plugins/source/terraform/README.md
- website/pages/docs/reference/destination-spec.md
- website/pages/docs/reference/source-spec.md
Working on https://github.com/cloudquery/cloudquery/issues/3191.
- remove references to `cloudquery generate`.
- remove references to `cloudquery init`.
- update flags and commands in issue template.
- Add example to 'Source Spec' and 'Dest Spec' sections (to reduce confusion from nested spec).
- change 'should' to 'must' when talking about unique names.
> doc: Update

- website/pages/docs/reference/destination-spec.md
- website/pages/docs/reference/source-spec.md
> doc: Followup

- .github/workflows/broken_links.yml
Looks like we need the top level host
> chore(ci-broken-links): Exclude work-bench host instead of www

- .github/styles/Vocab/Base/accept.txt
- plugins/destination/csv/README.md
- plugins/destination/postgresql/CONTRIBUTING.md
- plugins/source/aws/codegen/recipes/templates/resolver_and_mock_test/list_resources_1/README.md
- plugins/source/cloudflare/README.md
- plugins/source/cloudflare/docs/configuration.md
- plugins/source/github/README.md
- plugins/source/heroku/docs/configuration.md
- plugins/source/okta/README.md
- website/pages/docs/advanced-topics/rate-limiting.md
- website/pages/docs/advanced-topics/running-cloudquery-in-parallel.mdx
- website/pages/docs/developers/creating-new-plugin.md
- website/pages/docs/quickstart.mdx
- website/pages/docs/reference/source-spec.md
- website/pages/docs/troubleshooting.md
Required for https://github.com/cloudquery/cloudquery/pull/3476
> chore(docs): Fix typos

- website/pages/docs/plugins/destinations.md
The CSV plugin links to the Postgres one
> chore: Fix links to CSV Plugin

- .github/workflows/broken_links.yml
> chore(ci): Exclude `mailchimp.com` from broken links checker

- plugins/source/azure/CHANGELOG.md
Other plugins don't have it (it's an old remain of our old release process)
> chore: Remove deprecated header from Azure changelog

- plugins/source/aws/docs/configuration.md
- sites/versions/v2/source-aws.json
- website/pages/blog/migrating-from-v0-to-v1.md
- website/pages/docs/quickstart.mdx
- website/pages/docs/recipes/aws-csv.md
- website/pages/docs/recipes/aws-postgresql.md
- website/pages/docs/reference/source-spec.md
This reverts commit 7ee9e769994408221479402ce48e966778133919.
> chore: Revert "chore: Update plugin `source-aws` version to v4.2.1 (#3534)

- plugins/source/aws/codegen/recipes/elasticache.go
- plugins/source/aws/docs/tables/aws_elasticache_engine_versions.md
- plugins/source/aws/resources/services/elasticache/engine_versions.go
> fix(aws): Elasticache Engine Versions PK

- plugins/source/aws/docs/configuration.md
> fix: Fix documentation

- .github/workflows/dest_csv.yml
- .github/workflows/dest_postgresql.yml
- .github/workflows/dest_test.yml
- .github/workflows/source_aws.yml
- .github/workflows/source_azure.yml
- .github/workflows/source_cloudflare.yml
- .github/workflows/source_digitalocean.yml
- .github/workflows/source_gcp.yml
- .github/workflows/source_github.yml
- .github/workflows/source_heroku.yml
- .github/workflows/source_k8s.yml
- .github/workflows/source_okta.yml
- .github/workflows/source_terraform.yml
- .github/workflows/source_test.yml
Follow up on https://github.com/cloudquery/cloudquery/pull/3322. I'll merge this on Sunday to avoid blocking our CI in case there are issues with it
> chore(ci): Use large runners for all plugins on push event

- website/pages/docs/deployment/github-actions.md
Syncs the versions in the GitHub Action tutorial (also using `"` instead of `'` so the find/replace logic works)
> chore(website): Update GitHub Actions tutorial

- CODEOWNERS
This should stop tagging people to review release PRs
> chore: Set empty code owners for release PRs

- website/components/CustomErrorPage.tsx
- website/pages/404.mdx
- website/pages/_app.tsx
Fixes https://github.com/cloudquery/cloudquery-issues/issues/455 (internal issue).
Docs in https://docs.simpleanalytics.com/events
Example events in https://simpleanalytics.com/events/cloudquery.io?events=404
To see the meta data we need to export it via https://simpleanalytics.com/export?hostname=cloudquery.io.
See old 404 https://www.cloudquery.io/hello:
VS new 404 (feedback welcomed) https://cloudquery-c9lv5d0o1-cloudquery.vercel.app/hello:
> chore(website): Track 404s

- plugins/destination/postgresql/client/read.go
- plugins/destination/postgresql/client/types.go
- plugins/destination/postgresql/client/write.go
- plugins/destination/postgresql/go.mod
- plugins/destination/postgresql/go.sum
update SDK to v0.13.23
Also, This defaults unset columns to NULL. we might also want to take care of that on the SDK side given I dont think any destination want to distinguish between null and unset as it's the same thing
> fix: Update SDK to v0.13.23

- plugins/destination/csv/client/read.go
- plugins/destination/csv/go.mod
- plugins/destination/csv/go.sum
> fix: Update CSV plugin to v0.13.23

- .github/workflows/source_gcp.yml
- plugins/source/gcp/test/policy_cq_config.yml
Related https://github.com/cloudquery/cloudquery/issues/2190
> test: Add GCP policy tests

- cli/main.go
Fixes https://github.com/cloudquery/cloudquery/issues/3755, explained in https://github.com/cloudquery/cloudquery/issues/3755#issuecomment-1307114084
> fix: Silence zerolog until initialized

- plugins/source/heroku/codegen/recipes/recipes.go
connected to https://github.com/cloudquery/plugin-sdk/pull/386
> refactor(heroku): Gen using SDK structs

- plugins/source/heroku/codegen/main.go
With https://github.com/cloudquery/cloudquery/pull/4117 this option is no longer required
> refactor: Remove unsed option from Heroku code gen

- cli/cmd/testdata/dest.test.yml
- cli/cmd/testdata/source.test.yml
- plugins/source/aws/test/policy_cq_config.yml
- plugins/source/azure/test/policy_cq_config.yml
- plugins/source/gcp/test/policy_cq_config.yml
- plugins/source/k8s/test/policy_cq_config.yml
This reverts commit 57cabe84a82eca6403b7bf891651a6f38d4ec5f0.
[This update](https://github.com/cloudquery/cloudquery/pull/4066) caused our CLI CI to time out so I'm reverting it.
Our wait for all workflow didn't catch it due to a bug I'll fix later on
> test: Revert "chore(deps): Update CloudQuery monorepo modules (#4066)"

- sites/versions/v2/destination-test.json
- sites/versions/v2/source-terraform.json
- sites/versions/v2/source-test.json
I broke the plugin binaries in https://github.com/cloudquery/cloudquery/pull/3471 so I'm reverting the relevant doc changes
> chore: Revert plugin updates

- plugins/.goreleaser.template.yaml
Follow up to https://github.com/cloudquery/cloudquery/pull/4285. I missed this in https://github.com/cloudquery/cloudquery/pull/3471
> chore(release): Add missing Go releaser archives

- sites/versions/v2/destination-postgresql.json
- website/pages/blog/migrating-from-v0-to-v1.md
- website/pages/docs/deployment/github-actions.md
- website/pages/docs/quickstart.mdx
- website/pages/docs/recipes/destinations/postgresql.md
- website/pages/docs/recipes/overview.md
- website/pages/docs/reference/destination-spec.md
Reverts cloudquery/cloudquery#4283
Part of https://github.com/cloudquery/cloudquery/pull/4285
> chore: Revert "chore: Update plugin `destination-postgresql` version to v1.7.6"

- plugins/source/aws/codegen/recipes/appstream.go
- plugins/source/aws/codegen/recipes/templates/resolver_and_mock_test/describe_resources_1/fetch.go.tpl
- plugins/source/aws/resources/services/appstream/app_blocks_fetch.go
- plugins/source/aws/resources/services/appstream/directory_configs_fetch.go
- plugins/source/aws/resources/services/appstream/fleets_fetch.go
- plugins/source/aws/resources/services/appstream/image_builders_fetch.go
- plugins/source/aws/resources/services/appstream/images_fetch.go
- plugins/source/aws/resources/services/appstream/stack_user_associations_fetch.go
- plugins/source/aws/resources/services/appstream/usage_report_subscriptions_fetch.go
> feat: Increase MaxResults for appstream resources

- .github/workflows/source_azure.yml
- .github/workflows/source_gcp.yml
- .github/workflows/source_k8s.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/4402
The reason CI passed for #4402 is due to https://github.com/cloudquery/cloudquery/issues/4132 which is fixed by https://github.com/cloudquery/cloudquery/pull/4138, and also due to https://github.com/cloudquery/cloudquery/issues/2688
> test: Fix policy tests

- .github/workflows/manual_commands_triggers.yml
- plugins/source/azure/Makefile
- plugins/source/cloudflare/Makefile
- plugins/source/digitalocean/Makefile
- plugins/source/gcp/Makefile
- plugins/source/github/Makefile
- plugins/source/heroku/Makefile
- plugins/source/k8s/Makefile
- plugins/source/okta/Makefile
- plugins/source/terraform/Makefile
- plugins/source/test/Makefile
This is required for the AWS `/gen` command to work as AWS also runs `make gen-mocks`
> chore(ci): Align gen command for source plugins

- cli/cmd/sync.go
Fix error handling omissions in `cli/cmd/sync.go`
> fix: Error handling omissions

- plugins/source/aws/test/policy_cq_config.yml
- plugins/source/azure/test/policy_cq_config.yml
- plugins/source/gcp/test/policy_cq_config.yml
- plugins/source/k8s/test/policy_cq_config.yml
- sites/versions/v2/destination-postgresql.json
- website/pages/blog/migrating-from-v0-to-v1.md
- website/pages/docs/deployment/github-actions.md
- website/pages/docs/quickstart.mdx
- website/pages/docs/recipes/destinations/postgresql.md
- website/pages/docs/recipes/overview.md
- website/pages/docs/reference/destination-spec.md
Hot fix for https://github.com/cloudquery/cloudquery/issues/4489
> chore: Revert postgres plugin version in docs

- plugins/.goreleaser.template.yaml
Follow up https://github.com/cloudquery/cloudquery/pull/4402
> chore(release): Fix policies archives

- plugins/source/aws/codegen/recipes/rds.go
- plugins/source/aws/docs/tables/aws_rds_engine_versions.md
- plugins/source/aws/resources/services/rds/cluster_parameters_fetch.go
- plugins/source/aws/resources/services/rds/engine_versions.go
See individual commits please :)
> fix: RDS fixes

- website/components/pages/home.tsx
@hermanschaaf I think you mentioned this a while back
> fix(website): Point "Get Started" to Quickstart

- plugins/source/azure/CONTRIBUTING.md
Follow up to https://github.com/cloudquery/cloudquery/pull/4682
> chore(azure): Contributing guide follow up fixes

- website/components/mdx/_configure.mdx
> fix: Add filenames to quickstart

- website/pages/blog/product-updates-1.md
> chore: Product #1 bugfix

- website/pages/docs/advanced-topics/_meta.json
- website/pages/docs/advanced-topics/environment-variable-substitution.md
Updating docs to reflect https://github.com/cloudquery/plugin-sdk/pull/418
> chore: Update file substitution guide

- plugins/source/digitalocean/README.md
- website/pages/blog/announcing-cloudquery-history.md
- website/pages/blog/announcing-cloudquery-policies.md
- website/pages/blog/announcing-cloudquery-terraform-drift-detection.md
- website/pages/blog/announcing-policies-in-cloudquery-hub.md
- website/pages/blog/aws-improvements-Q1-2022.md
- website/pages/blog/aws-log4j-and-finding-unrestricted-outbound-access.md
- website/pages/blog/aws-sso-and-the-lost-iam-keys.md
- website/pages/blog/continuous-aws-iam-security-best-practices.md
- website/pages/blog/how-to-aws-cis-compliance.md
- website/pages/blog/introducing-cloudquery-sdk.md
- website/pages/blog/introducing-the-digital-ocean-cloudquery-provider.md
- website/pages/blog/introducing-the-github-cloudquery-provider.md
- website/pages/blog/open-source-cspm.md
- website/pages/blog/running-aws-foundational-security-best-practices-with-cloudquery-policies.md
- website/pages/blog/running-aws-pci-dss-with-cloudquery-policies.md
- website/pages/blog/running-nsa-and-cisa-kubernetes-hardening-tests-with-cloudquery-policies.md
> doc: Update old blogs

- plugins/source/aws/client/client.go
Closes https://github.com/cloudquery/cloudquery/issues/5028
I tested this locally using the config shown in the original ticket. If all accounts fail to auth, the CLI returns with exit code 1. If one account succeeds, an error is logged for the failing accounts. The error is not counted as part of the `Errors` count in the output, but in any case that would likely be lost in the count of resolver-related errors and quite hard to implement right now. Users will need to discover such errors through the `ERR` line in the logs, which I think is not unreasonable.
> fix: Allow sync to complete when one or more accounts fail to authenticate

- .github/workflows/dest_snowflake.yml
Im not sure what's happening  (maybe Github runners are down) but in any case I wanted to try and simplify the workflows which are starting to have a lot of know how, so going to try and play with a simple workflow for snowflake to see how it work and if it works well we can use it for all others.
> chore: Try to fix/simplify snowflake ci

- .github/workflows/dest_snowflake.yml
- .github/workflows/release_plugin_dest_snowflake.yml
- .github/workflows/wait_for_required_workflows.yml
- plugins/destination/snowflake/.goreleaser.yaml
- plugins/destination/snowflake/Makefile
Reverted https://github.com/cloudquery/cloudquery/pull/5065 and made snowflake compile similar to sqlite with golang-cross (CGO_ENABLED=1 only for windows though until https://github.com/snowflakedb/gosnowflake/issues/690 is solved).
Unrelated: Seems our github actions complexity is growing (not because they are wrong but because of underlying things like docs which I'll try to address later on)
> chore: Make snowflake compile on windows

- .release-please-manifest.json
See reasoning in https://github.com/googleapis/release-please/issues/1502 and https://www.notion.so/cloudquery/Adding-a-new-plugin-to-the-monorepo-f216b653dbe648b2b3512fb8d59a8f89#57d357ad9a79425098db19e263173829 (internal link)
> chore(release): Add Snowflake filler entry

- website/pages/docs/deployment/overview.md
The GCP repository is archived https://github.com/cloudquery/terraform-gcp-cloudquery
> fix(website): Remove GCP Terraform from deployment section

- website/pages/blog/building-cloudquery.md
Not sure why the last line shows like it was changed. I just updated from "Typing System" to "Type System" as "Typing System" is something else
> chore: Small blog update

- website/components/Integrations.tsx
- website/components/integrationsData.tsx
- website/pages/blog/aws-kms-key-grants-deep-dive.md
- website/pages/blog/cloudquery-v1-release.md
- website/vercel.json
Follow up to https://github.com/cloudquery/cloudquery/pull/5117
> fix(website): More broken links

- website/pages/blog/building-cloudquery.md
Small follow up to the blog to link directly to the overview
> fix(website): Link to destinations overview

- plugins/source/azure/codegen/main.go
Until we find a way to run it directly
> chore(azure-codegen): Add error handling to exec.Command

- plugins/destination/postgresql/client/deletestale.go
- plugins/destination/snowflake/client/deletestale.go
- plugins/destination/sqlite/client/deletestale.go
Won't compile until https://github.com/cloudquery/plugin-sdk/pull/443 is merged.
> fix: DeleteStale from relational tables as well

- website/pages/blog/how-to-find-cross-account-aws-eventbridge-usage.md
I wasn't fast enough to review https://github.com/cloudquery/cloudquery/pull/5186 😄 
This makes it look like this:
> chore: Testimonial formatting

- .github/renovate.json5
This ensures we don't updates > 4
> chore(deps): Don't update major versions for pgx

- website/components/PluginsTable.tsx
- website/pages/docs/plugins/destinations/overview.mdx
- website/pages/docs/plugins/sources/overview.mdx
This PR adds a `PluginsTable` component to make it easier to add new plugins to the Website.
At first I tried making the table generic using MDX magic, but couldn't get it to render properly so this is the best I managed.
> refactor(website): Add PluginsTable component

- plugins/source/gcp/resources/services/iam/roles_fetch.go
- plugins/source/gcp/resources/services/iam/service_accounts_fetch.go
- plugins/source/gcp/resources/services/sql/instances_fetch.go
> feat(gcp): More PageSize increases

- website/versions/cli.json
Related to https://github.com/cloudquery/cloudquery/pull/5480
> fix(website): Update CLI to latest version

- .github/workflows/release_cli.yml
Fixes a typo that caused our CI not to update the version file for the CLI
> fix(ci): Typo in release CLI

- website/components/mdx/_download-linux.mdx
- website/components/mdx/_download-macOS.mdx
- website/components/mdx/_download-windows.mdx
Extracting this from https://github.com/cloudquery/cloudquery/pull/5482 as it's a more important fix
> fix(website): Broken CLI download links

- website/components/mdx/_configure.mdx
- website/components/mdx/_download-linux.mdx
- website/components/mdx/_download-macOS.mdx
- website/components/mdx/_download-windows.mdx
- website/pages/blog/introducing-the-github-cloudquery-provider.md
- website/pages/blog/migrating-from-v0-to-v1.md
- website/pages/docs/core-concepts/configuration.md
- website/pages/docs/deployment/github-actions.md
- website/pages/docs/plugins/destinations/bigquery/overview.md
- website/pages/docs/plugins/destinations/csv/overview.md
- website/pages/docs/plugins/destinations/postgresql/overview.md
- website/pages/docs/plugins/destinations/snowflake/overview.md
- website/pages/docs/plugins/destinations/sqlite/overview.md
- website/pages/docs/plugins/sources/aws/configuration.md
- website/pages/docs/plugins/sources/azure/configuration.md
- website/pages/docs/plugins/sources/cloudflare/configuration.md
- website/pages/docs/plugins/sources/digitalocean/overview.md
- website/pages/docs/plugins/sources/gandi/configuration.md
- website/pages/docs/plugins/sources/gcp/configuration.md
- website/pages/docs/plugins/sources/github/overview.md
- website/pages/docs/plugins/sources/heroku/configuration.md
- website/pages/docs/plugins/sources/k8s/configuration.md
- website/pages/docs/plugins/sources/okta/overview.md
- website/pages/docs/plugins/sources/terraform/overview.md
- website/pages/docs/reference/destination-spec.md
- website/pages/docs/reference/source-spec.md
Fixes https://github.com/cloudquery/cloudquery/issues/5483
> fix(website): Remove copy from code blocks that have version placeholders

- website/components/mdx/_download-linux.mdx
- website/components/mdx/_download-macOS.mdx
- website/components/mdx/_download-windows.mdx
- website/next.config.mjs
- website/pages/docs/deployment/github-actions.md
The convention in Homebrew is to use `@<version>` without the `v`, so this required a bit more changes.
Instead of adding to the existing code block, we can also use a callout for it to get more visibility (I'm not sure we want that)
> feat(website): Document Homebrew specific version

- plugins/source/aws/client/client.go
> chore: Remove dead code

- plugins/source/gcp/codegen/recipes/iam.go
- plugins/source/gcp/docs/tables/gcp_iam_service_account_keys.md
- plugins/source/gcp/resources/services/iam/service_account_keys.go
Closes #3193.
Considering this non-breaking as the value is always `nil`.
> fix(gcp)!: Remove `private_key_type` field from `gcp_iam_service_account_keys`

- website/pages/docs/plugins/sources/_meta.json
Temporary until it is released.
> chore: Update _meta.json to remove Crowdstrike

- .github/workflows/wait_for_required_workflows.yml
We removed the Azure policy tests until we fix the policies to match the data synced from the new API
> fix(ci): Don't wait for Azure policy tests

- plugins/source/gcp/go.mod
- plugins/source/gcp/resources/services/kms/keyrings_fetch.go
Follow up to https://github.com/cloudquery/cloudquery/pull/5654, missed a find replace and also does https://github.com/cloudquery/cloudquery/pull/5654#pullrequestreview-1218735192
> fix(gcp): Remove error wrapping

- release-please-config.json
> chore: Add Vercel to release please

- plugins/destination/bigquery/client/spec.go
- plugins/destination/bigquery/client/write.go
- website/pages/docs/plugins/destinations/bigquery/overview.md
This brings the destination in line with Postgres to enable users to easily fine tune their writes
> feat(bigquery): Add configurable batch size

- scripts/table_diff/changes/changes.go
- scripts/table_diff/changes/changes_test.go
- scripts/table_diff/changes/testdata/pr_5636_diff.txt
This PR fixes the table diff logic to support PK changes. For example https://github.com/cloudquery/cloudquery/pull/5636#issuecomment-1351123700 is wrong.
> fix(table-diff): Support PK changes

- scripts/update-codegen.sh
Useful for https://github.com/cloudquery/cloudquery/pull/5790
> chore: Add a script to codegen for all plugins

- scripts/update-docs.sh
This is more correct as it also does the Website docs:
https://github.com/cloudquery/cloudquery/blob/91ec60b91e64b6a02b4fdd8f402ae1cf167051bf/plugins/source/aws/Makefile#L31
> chore: Use make target for root update docs script

- website/pages/blog/product-updates-2.md
> chore(website): Product update fix

- website/versions/destination-postgresql.json
Reverts cloudquery/cloudquery#5843
> chore: Revert "chore: Update plugin `destination-postgresql` version to v1.9.0"

- plugins/source/pagerduty/.goreleaser.yaml
> fix: Add goreleaser file

- plugins/source/azure/policies/queries/security/asc_automatic_provisioning_log_analytics_monitoring_agent.sql
- plugins/source/azure/policies/queries/security/auto_provisioning_monitoring_agent_enabled.sql
Update to some Azure queries based off new azure plugin and tables update
> fix: Update Azure auto provisioning queries

- plugins/source/pagerduty/client/testing.go
- plugins/source/pagerduty/docs/tables/README.md
- plugins/source/pagerduty/docs/tables/pagerduty_addons.md
- plugins/source/pagerduty/docs/tables/pagerduty_business_services.md
- plugins/source/pagerduty/docs/tables/pagerduty_escalation_policies.md
- plugins/source/pagerduty/docs/tables/pagerduty_extension_schemas.md
- plugins/source/pagerduty/docs/tables/pagerduty_extensions.md
- plugins/source/pagerduty/docs/tables/pagerduty_incident_alerts.md
- plugins/source/pagerduty/docs/tables/pagerduty_incidents.md
- plugins/source/pagerduty/docs/tables/pagerduty_maintenance_windows.md
- plugins/source/pagerduty/docs/tables/pagerduty_priorities.md
- plugins/source/pagerduty/docs/tables/pagerduty_ruleset_rules.md
- plugins/source/pagerduty/docs/tables/pagerduty_rulesets.md
- plugins/source/pagerduty/docs/tables/pagerduty_schedules.md
- plugins/source/pagerduty/docs/tables/pagerduty_service_rules.md
- plugins/source/pagerduty/docs/tables/pagerduty_services.md
- plugins/source/pagerduty/docs/tables/pagerduty_tags.md
- plugins/source/pagerduty/docs/tables/pagerduty_teams.md
- plugins/source/pagerduty/docs/tables/pagerduty_user_contact_methods.md
- plugins/source/pagerduty/docs/tables/pagerduty_user_notification_rules.md
- plugins/source/pagerduty/docs/tables/pagerduty_users.md
- plugins/source/pagerduty/docs/tables/pagerduty_vendors.md
- plugins/source/pagerduty/go.mod
- plugins/source/pagerduty/go.sum
- plugins/source/pagerduty/resources/plugin/plugin.go
- website/pages/docs/plugins/sources/pagerduty/tables.md
> fix: Update pagerduty to sdk 1.12.7

- plugins/source/tailscale/client/spec.go
- website/pages/docs/plugins/sources/tailscale/configuration.md
> chore(tailscale): Do not scan environment variables directly

- website/pages/blog/2022-may-monthly.md
To fix the broken links checker
> chore(website): Fix broken links in 2022 May update

- .github/workflows/broken_links.yml
Sorry didn't mean to auto merge https://github.com/cloudquery/cloudquery/pull/5973.
This PR should work
> fix(ci): Skip broken links checks if build is ignored on Vercel

- website/components/QueriesExamples.tsx
- website/components/pages/home.tsx
- website/content/features.ts
Some minor updates to the home page to reflect some of the new plugins & features that have been added over the last few months.
Also fixes the padding on the SQL query examples.
> chore(website): Update home page

- website/pages/docs/reference/source-spec.md
I reduced this in https://github.com/cloudquery/plugin-sdk/pull/491 and forgot to update the docs
> chore: Fix concurrency docs

- .release-please-manifest.json
Follow up to https://github.com/cloudquery/cloudquery/pull/6121
> chore: Add missing comma to release please config

- plugins/destination/gcs/client/client.go
> fix(gcs): Use empty file for permission testing

- plugins/source/cloudflare/client/client.go
- plugins/source/cloudflare/go.mod
- plugins/source/cloudflare/go.sum
> fix(cloudflare): Account Filtering

- release-please-config.json
Add azblob to release-please config and remove csv as it is deprecated
> chore: Add azblob to release please

- plugins/destination/s3/client/client_test.go
Reverts https://github.com/cloudquery/cloudquery/pull/6179/commits/356137db4191f94b500db093c7365a8dbf88c234 as we decide to exclude this bucket from the nuke process, see https://github.com/cloudquery/deployments/pull/49/files
> test(s3): Use pre-existing bucket for tests

- website/pages/docs/plugins/destinations/_meta.json
- website/pages/docs/plugins/destinations/csv/overview.md
- website/pages/docs/plugins/destinations/overview.mdx
Deprecate CSV destination plugin in the docs.
> chore(website): Deprecate CSV

- .github/workflows/source_crowdstrike.yml
We don't need a stronger machine for this plugin. Those are reserved for AWS, GCP, Azure
> fix(ci): Remove large runner from Crowdstrike

- contributing/creating_a_new_plugin.md
Update the creating_a_new_plugin page. The one link no longer exists, so I removed it. We should add more resources here soon
> chore(docs): Update creating_a_new_plugin.md

- plugins/source/aws/docs/tables/README.md
- plugins/source/aws/docs/tables/aws_organization_resource_policies.md
- plugins/source/aws/resources/plugin/tables.go
- plugins/source/aws/resources/services/organizations/resource_policies.go
- plugins/source/aws/resources/services/organizations/resource_policies_fetch.go
- plugins/source/aws/resources/services/organizations/resource_policies_mock_test.go
- website/pages/docs/plugins/sources/aws/tables.md
> feat(aws): Add Org resource policies

- plugins/source/aws/docs/tables/aws_s3_bucket_grants.md
- plugins/source/aws/resources/services/s3/bucket_grants.go
- plugins/source/aws/resources/services/s3/buckets_fetch.go
- plugins/source/aws/resources/services/s3/buckets_mock_test.go
* Add `grantee_type` column to `aws_s3_bucket_grants`
* Correctly fill in `grantee_id` column to `aws_s3_bucket_grants` based on `grantee_type`
> fix(aws): Correctly fill in `grantee_id` column to `aws_s3_bucket_grants`

- website/pages/docs/plugins/destinations/azblob/overview.md
- website/pages/docs/plugins/destinations/bigquery/overview.md
- website/pages/docs/plugins/destinations/gcs/overview.md
- website/pages/docs/plugins/destinations/mongodb/overview.md
- website/pages/docs/plugins/destinations/neo4j/overview.md
- website/pages/docs/plugins/destinations/s3/overview.md
- website/pages/docs/plugins/destinations/snowflake/overview.md
- website/pages/docs/reference/destination-spec.md
Closes https://github.com/cloudquery/cloudquery/issues/6785
> doc(website): Update documentation around batch_size and batch_size_bytes

- plugins/source/oracle/.goreleaser.yaml
> fix: Add oracle goreleaser

- .github/pr_labeler.yml
> chore: Add missing PR labeler entries

- website/pages/docs/plugins/sources/vercel/overview.md
> fix(website-vercel): Fix broken link to example

- plugins/destination/s3/client/spec_test.go
- plugins/destination/s3/client/write.go
- plugins/destination/s3/go.mod
- plugins/destination/s3/go.sum
Follow-up for https://github.com/cloudquery/cloudquery/pull/6951
> chore(s3): Refactor tests

- plugins/destination/sqlite/client/client_test.go
- plugins/destination/sqlite/client/migrate.go
- plugins/destination/sqlite/go.mod
To be merged after https://github.com/cloudquery/cloudquery/pull/6759, and needs https://github.com/cloudquery/plugin-sdk/pull/604
> feat(sqlite): Support force migration

- plugins/destination/sqlite/client/migrate.go
Some code cleanup on the SQLite destination. Removes unused context params and moves some code into functions
> refactor(sqlite): Remove unused context param, move code into functions

- release-please-config.json
These plugins are missing from our release tool configuration
> chore(release): Add missing Shopify and Stripe config

- website/pages/docs/plugins/sources/plausible/overview.md
> doc(plausible): Update plausible example to use sum instead of count

- .github/renovate.json5
- scaffold/cmd/templates/source/client/client.go.tpl
- scaffold/cmd/templates/source/go.mod.tpl
This PR updates the plugin SDK for the scaffold CLI and also ensures it's gets dependency updates automatically going forward.
There's an existing test that runs the scaffold command and verifies the code builds, so that should ensure breaking changes are handled and not auto merged
> feat(scaffold): Update SDK, add auto deps updates

- release-please-config.json
This should help us avoid rate limits, see https://github.com/googleapis/release-please/blob/8b0cc7d7d203609c95e9e7cfbef4f0faedd3f46d/docs/manifest-releaser.md.
I subscribed to https://github.com/googleapis/release-please/issues/1503 which should help as well
> fix(release): Set `sequential-calls: true` to avoid rate limits

- plugins/source/aws/docs/tables/aws_cloudtrail_trails.md
- plugins/source/aws/resources/services/cloudtrail/trails.go
Cloudtrails can span multiple regions.
The name has to be unique only in the HomeRegion.... ARN + Region ensures uniqueness
> fix(aws): Cloudtrail pks

- plugins/source/azure/docs/tables/azure_cdn_managed_rule_sets.md
- plugins/source/azure/resources/services/cdn/managed_rule_sets.go
> fix(azure)!: Add `subscription_id` to `azure_cdn_managed_rule_sets` PK

- plugins/source/azure/docs/tables/azure_authorization_role_assignments.md
- plugins/source/azure/resources/services/authorization/role_assignments.go
> fix(azure)!: Add `subscription_id` to `azure_authorization_role_assignments`

- plugins/source/azure/docs/tables/azure_cdn_edge_nodes.md
- plugins/source/azure/resources/services/cdn/edge_nodes.go
> fix(azure)!: Add `subscription_id` to `azure_cdn_edge_nodes` PK

- plugins/source/azure/docs/tables/azure_policy_data_policy_manifests.md
- plugins/source/azure/resources/services/policy/data_policy_manifests.go
> fix(azure)!: Add `subscription_id` to `azure_policy_data_policy_manifests` PK

- plugins/source/azure/docs/tables/azure_eventgrid_topic_types.md
- plugins/source/azure/resources/services/eventgrid/topic_types.go
> fix(azure)!: Add `subscription_id` to `azure_eventgrid_topic_types` PK

- plugins/source/azure/docs/tables/azure_frontdoor_managed_rule_sets.md
- plugins/source/azure/resources/services/frontdoor/managed_rule_sets.go
> fix(azure)!: Add `subscription_id` to `azure_frontdoor_managed_rule_sets` PK

- plugins/source/azure/docs/tables/azure_network_azure_firewall_fqdn_tags.md
- plugins/source/azure/resources/services/network/azure_firewall_fqdn_tags.go
> fix(azure)!: Add `subscription_id` to `azure_network_azure_firewall_fqdn_tags` PK

- plugins/source/azure/docs/tables/azure_policy_definitions.md
- plugins/source/azure/resources/services/policy/definitions.go
> fix(azure)!: Add `subscription_id` to `azure_policy_definitions` PK

- plugins/source/azure/docs/tables/azure_support_services.md
- plugins/source/azure/resources/services/support/services.go
> fix(azure)!: Add `subscription_id` to `azure_support_services` PK

- plugins/source/azure/docs/tables/azure_network_bgp_service_communities.md
- plugins/source/azure/resources/services/network/bgp_service_communities.go
> fix(azure)!: Add `subscription_id` to `azure_network_bgp_service_communities` PK

- plugins/source/azure/docs/tables/azure_reservations_reservation.md
- plugins/source/azure/resources/services/reservations/reservation.go
> fix(azure)!: Add `subscription_id` to `azure_reservations_reservation` PK

- website/pages/docs/plugins/destinations/azblob/overview.mdx
- website/pages/docs/plugins/destinations/gcs/overview.mdx
- website/pages/docs/plugins/destinations/s3/overview.mdx
> doc: Add better example for files

- plugins/source/aws/docs/tables/aws_cloudfront_cache_policies.md
- plugins/source/aws/resources/services/cloudfront/cache_policies.go
> fix: Cloudfront Policy PK

- website/pages/docs/plugins/sources/k8s/overview.mdx
Follow up to https://github.com/cloudquery/cloudquery/pull/7296 to fix some typos introduced in that PR (see failures in https://github.com/cloudquery/cloudquery/actions/runs/4036226949/jobs/6938681258)
> fix(website-k8s): Fix typos in overview

- plugins/source/azure/docs/tables/azure_advisor_recommendation_metadata.md
- plugins/source/azure/resources/services/advisor/recommendation_metadata.go
> fix(azure)!: Drop `subscription_id` column from `azure_advisor_recommendation_metadata`

- .github/workflows/lint_markdown.yml
This will ensure that new blog posts and how to guides get linted
> chore: Update lint_markdown to lint mdx

- plugins/destination/file/client/client.go
- plugins/destination/file/client/read.go
- plugins/destination/file/client/transformer.go
- plugins/destination/file/client/write.go
- plugins/destination/file/go.mod
- plugins/destination/file/go.sum
Replaces https://github.com/cloudquery/cloudquery/pull/7456
> fix(destination-file): Update to new filetypes modules

- scaffold/cmd/templates/source/.gitignore.tpl
> feat: Add *.log to gitignore template

- website/pages/how-to-guides/configuring-cloudquery-with-localstack.mdx
This link 404s, couldn't find a good replacement
> fix: Remove broken link to Localstack docs

- website/vercel.json
To catch typos in Discord link
> chore(website): Redirect Discord typos

- plugins/destination/elasticsearch/CONTRIBUTING.md
https://docs.docker.com/compose/compose-v2/
> chore(elasticsearch): Move to `docker compose` command

- plugins/destination/elasticsearch/docker-compose.yaml
https://docs.docker.com/compose/compose-file/#version-top-level-element
> chore(elasticsearch): Update docker-compose.yaml

- website/pages/how-to-guides/how-to-load-infrastructure-data-into-athena.mdx
Relates to https://github.com/cloudquery/cloudquery/issues/7639
> chore(docs): Add info about handling case sensitivity to Athena how-to guide

- plugins/source/aws/docs/tables/README.md
- plugins/source/aws/docs/tables/aws_eks_cluster_node_groups.md
- plugins/source/aws/docs/tables/aws_eks_clusters.md
- plugins/source/aws/resources/services/eks/clusters.go
- plugins/source/aws/resources/services/eks/clusters_mock_test.go
- plugins/source/aws/resources/services/eks/node_groups.go
- plugins/source/aws/resources/services/eks/node_groups_fetch.go
- website/pages/docs/plugins/sources/aws/tables.md
> feat(AWS): Add support for EKS Node Groups

- plugins/destination/postgresql/client/transformer.go
- plugins/destination/postgresql/client/transformer_test.go
> fix(postgresql): Sanitize JSONs

- website/pages/docs/plugins/destinations/snowflake/overview.mdx
> doc(snowflake): Add "?warehouse=" to snowflake docs

- plugins/source/aws/docs/tables/README.md
- plugins/source/aws/docs/tables/aws_emr_cluster_instance_fleets.md
- plugins/source/aws/docs/tables/aws_emr_cluster_instance_groups.md
- plugins/source/aws/docs/tables/aws_emr_clusters.md
- plugins/source/aws/resources/services/emr/cluster_instance_fleets.go
- plugins/source/aws/resources/services/emr/cluster_instance_fleets_fetch.go
- plugins/source/aws/resources/services/emr/cluster_instance_groups.go
- plugins/source/aws/resources/services/emr/cluster_instance_groups_fetch.go
- plugins/source/aws/resources/services/emr/clusters.go
- plugins/source/aws/resources/services/emr/clusters_mock_test.go
- website/pages/docs/plugins/sources/aws/tables.md
Fixes https://github.com/cloudquery/cloudquery/issues/7707
> feat(aws-resources): Add EMR Instance Fleets and Groups

- plugins/source/aws/docs/tables/aws_ec2_images.md
- plugins/source/aws/resources/services/ec2/images.go
> fix(aws)!: PK for `aws_ec2_images`

- plugins/source/aws/docs/tables/aws_docdb_certificates.md
- plugins/source/aws/resources/services/docdb/certificates.go
> fix(aws)!: PK for `aws_docdb_certificates`

- plugins/source/aws/docs/tables/aws_s3_bucket_grants.md
- plugins/source/aws/resources/services/s3/bucket_grants.go
> fix(aws)!: PK for `aws_s3_bucket_grants`

- plugins/destination/snowflake/client/migrate.go
Trying again to make the CI happy. Added a newline to change the commit hash
> fix: Snowflake migration

- website/pages/docs/plugins/sources/k8s/overview.mdx
> chore(website): Refactor k8s auth example

- plugins/source/aws/client/resolvers.go
- plugins/source/aws/docs/tables/README.md
- plugins/source/aws/docs/tables/aws_availability_zones.md
- plugins/source/aws/resources/plugin/tables.go
- plugins/source/aws/resources/services/ec2/azs.go
- plugins/source/aws/resources/services/ec2/azs_fetch.go
- plugins/source/aws/resources/services/ec2/azs_mock_test.go
- website/pages/docs/plugins/sources/aws/tables.md
> feat(aws): Support Availability Zones

- website/pages/docs/plugins/sources/k8s/overview.mdx
Follow up on https://github.com/cloudquery/cloudquery/pull/7298#discussion_r1101473711
> chore: K8S auth follow up

- website/pages/docs/plugins/destinations/elasticsearch/_meta.json
> fix(website): Add missing Elasticsearch `_meta.json` file

- plugins/source/aws/docs/tables/aws_securityhub_findings.md
- plugins/source/aws/resources/services/securityhub/findings.go
Closes https://github.com/cloudquery/cloudquery-issues/issues/490
> fix(aws): Add `request_account_id` & `request_region` to `aws_securityhub_findings` PK

- plugins/source/aws/docs/tables/aws_appstream_images.md
- plugins/source/aws/resources/services/appstream/images.go
Closes https://github.com/cloudquery/cloudquery-issues/issues/483
> fix(aws): Add `account_id` and `region` to `aws_appstream_images` PK

- plugins/source/github/client/columns.go
- plugins/source/github/docs/tables/github_hooks.md
- plugins/source/github/docs/tables/github_organization_dependabot_alerts.md
- plugins/source/github/docs/tables/github_organization_members.md
- plugins/source/github/docs/tables/github_organizations.md
- plugins/source/github/docs/tables/github_releases.md
- plugins/source/github/docs/tables/github_team_members.md
- plugins/source/github/resources/services/actions/workflows.go
- plugins/source/github/resources/services/billing/action.go
- plugins/source/github/resources/services/billing/package.go
- plugins/source/github/resources/services/billing/storage.go
- plugins/source/github/resources/services/external/groups.go
- plugins/source/github/resources/services/hooks/deliveries.go
- plugins/source/github/resources/services/hooks/hooks.go
- plugins/source/github/resources/services/installations/installations.go
- plugins/source/github/resources/services/issues/issues.go
- plugins/source/github/resources/services/organizations/alerts.go
- plugins/source/github/resources/services/organizations/members.go
- plugins/source/github/resources/services/organizations/organizations.go
- plugins/source/github/resources/services/organizations/secrets.go
- plugins/source/github/resources/services/repositories/alerts.go
- plugins/source/github/resources/services/repositories/assets.go
- plugins/source/github/resources/services/repositories/releases.go
- plugins/source/github/resources/services/repositories/repositories.go
- plugins/source/github/resources/services/repositories/secrets.go
- plugins/source/github/resources/services/teams/members.go
- plugins/source/github/resources/services/teams/repositories.go
- plugins/source/github/resources/services/teams/teams.go
Closes https://github.com/cloudquery/cloudquery-issues/issues/482
Based on https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28#get-a-dependabot-alert.
> fix(github)!: Change `github_organization_dependabot_alerts` PK from `(org,number)` to `(org,html_url)`
