plugins/source/aws/docs/tables/aws_ec2_managed_prefix_lists.md, plugins/source/aws/resources/services/ec2/managed_prefix_lists.go
Closes https://github.com/cloudquery/cloudquery-issues/issues/498
=> fix(aws)!: Add `arn` to `aws_ec2_managed_prefix_lists` PK

plugins/source/github/docs/tables/github_workflows.md, plugins/source/github/resources/services/actions/workflows.go
fix(github): Add `repository_id` to `github_workflows` PK
BREAKING-CHANGE: Add `repository_id` to `github_workflows` PK
feat(github): Remove `repository` column from `github_workflows`
BREAKING-CHANGE: Remove `repository` column from `github_workflows`
=> fix(github)!: Add `repository_id` to `github_workflows` PK

.github/styles/Vocab/Base/accept.txt, website/pages/docs/plugins/sources/overview.mdx
Adding links to newly added partners!
=> chore(website): Add link to partners: Scaleway, Swetrix

scripts/missing_tables/main.go
The script logic started failing with https://github.com/cloudquery/cloudquery/pull/8175. The easiest solution is to skip the test plugin as it doesn't follow other plugins conventions
=> fix(missing-tables): Skip test plugin

scripts/missing_tables/main.go
Follow up to https://github.com/cloudquery/cloudquery. We should not pollute the output as we use that for the PR comment:
https://github.com/cloudquery/cloudquery/pull/8224#issuecomment-1435986548
=> fix Don't print skipping test plugin

website/pages/blog/postgres-cdc-to-any-destination.mdx
The link to the PostgresSQL source is broken
=> fix(website): Broken link from CDC blog

plugins/destination/file/client/client_test.go, plugins/destination/file/go.mod, plugins/destination/file/go.sum
Extracted from https://github.com/cloudquery/cloudquery/pull/8156.
For file destination we can only do force for every change (we might be able to do add and remove column safely for JSON as it's simply adding/removing a new field to the JSON object which should be fine. Out of scope for this PR).
=> feat(deps): Update File plugin-sdk to v1.38.2

plugins/destination/clickhouse/client/client.go
=> fix(clickhouse): Bump minimum ClickHouse version

website/pages/docs/plugins/sources/azure/policies.mdx
Remove callout as #5830 is already closed.
=> chore(website): Remove Azure policies issue link

website/pages/blog/migration-and-history-deprecation.mdx, website/pages/docs/plugins/sources/vercel/_configuration.mdx
=> fix: Vercel integration example broken link, history deprecation broken link

plugins/source/azure/docs/tables/README.md, plugins/source/azure/docs/tables/azure_containerservice_managed_cluster_upgrade_profiles.md, plugins/source/azure/docs/tables/azure_containerservice_managed_clusters.md, plugins/source/azure/resources/services/containerservice/managed_cluster_upgrade_profiles.go, plugins/source/azure/resources/services/containerservice/managed_clusters.go, plugins/source/azure/resources/services/containerservice/managed_clusters_mock_test.go, website/pages/docs/plugins/sources/azure/tables.md
Fixes https://github.com/cloudquery/cloudquery/issues/7917
=> feat(azure-resources): Add AKS Upgrade Profile

website/pages/how-to-guides/cloud-asset-inventory-cloudquery-microsoft-power-bi.mdx
=> fix(website): Use PostgreSQL instead of PostgresSQL in `cloud-asset-inventory-cloudquery-microsoft-power-bi.mdx`

website/pages/docs/plugins/sources/overview.mdx
https://cloudquery-im5adwyc3-cloudquery.vercel.app/docs/plugins/sources/overview
=> feat(website): Link to SharePoint plugin

plugins/destination/clickhouse/client/client.go, plugins/destination/clickhouse/client/migrate.go, plugins/destination/clickhouse/client/spec.go, plugins/destination/clickhouse/queries/columns.go, plugins/destination/clickhouse/queries/columns_test.go, plugins/destination/clickhouse/queries/table.go, plugins/destination/clickhouse/queries/tables.go, plugins/destination/clickhouse/queries/tables_test.go, plugins/destination/clickhouse/queries/testdata/col_add_cluster.sql, plugins/destination/clickhouse/queries/testdata/col_drop_cluster.sql, plugins/destination/clickhouse/queries/testdata/create_table_cluster.sql, website/pages/docs/plugins/destinations/clickhouse/overview.mdx
=> feat(clickhouse): Support distributed DDL

website/components/pluginData.tsx
This is the correct capitalization
=> fix: SharePoint plugin data

website/next.config.mjs
`FutureImages` is now the default in Next.js and this option generates a warning:
```
The value at .experimental has an unexpected property, images, which is not in the list of allowed properties (adjustFontFallbacks, adjustFontFallbacksWithSizeAdjust, allowedRevalidateHeaderKeys, amp, cpus, craCompat, disableOptimizedLoading, disablePostcssPresetEnv, esmExternals, appDir, externalDir, fallbackNodePolyfills, fetchCache, forceSwcTransforms, fullySpecified, gzipSize, incrementalCacheHandlerPath, isrFlushToDisk, isrMemoryCacheSize, largePageDataBytes, legacyBrowsers, manualClientBasePath, middlewarePrefetch, newNextLinkBehavior, nextScriptWorkers, optimizeCss, optimisticClientCache, outputFileTracingRoot, outputFileTracingIgnores, pageEnv, preCompiledNextServer, proxyTimeout, runtime, …
```
=> fix(website): Remove deprecated images option

.github/styles/Vocab/Base/accept.txt, README.md
Mac and its silly non-breaking space character if you accidentally type option+space (I'm going to figure out how to disable that now once and for all)
=> chore(docs): Fix header in readme

.github/workflows/auto_sort_files.yml
So avoid manually sorting files once in a while, see:
https://github.com/cloudquery/cloudquery/pull/8734
https://github.com/cloudquery/cloudquery/pull/7223
=> chore(ci): Add workflow to auto sort some files

plugins/source/aws/docs/tables/README.md, plugins/source/aws/resources/services/ec2/image_attributes.go, plugins/source/aws/resources/services/ec2/images.go, plugins/source/aws/resources/services/ec2/images_mock_test.go, website/pages/docs/plugins/sources/aws/tables.md, website/tables/aws/aws_ec2_image_launch_permissions.md, website/tables/aws/aws_ec2_images.md
Part of https://github.com/cloudquery/cloudquery/issues/7926
=> feat(aws): Add EC2 image launch permissions resource (`aws_ec2_image_launch_permissions`)

plugins/source/aws/resources/services/organizations/delegated_admins.go, website/tables/aws/aws_organizations_delegated_administrators.md
=> fix(aws): Fix description for `aws_organizations_delegated_administrators`

.github/ISSUE_TEMPLATE/new_destination_plugin.yml
Similar to https://github.com/cloudquery/cloudquery/pull/9027/files
=> fix: Update new_destination_plugin.yml

website/pages/docs/plugins/sources/k8s/configuration.mdx, website/pages/docs/plugins/sources/pagerduty/configuration.mdx
Follow-up for https://github.com/cloudquery/cloudquery/issues/8941
=> fix(docs): Fix import in k8s and pagerduty mdx files

plugins/destination/firehose/go.mod, plugins/destination/firehose/go.sum
=> feat(firehose): Update to filetypes v1.6.0

website/pages/docs/reference/source-spec.md
=> fix(website): Improve documentation for `skip_dependent_tables`

plugins/source/azure/docs/tables/README.md, plugins/source/azure/resources/services/storage/accounts.go, plugins/source/azure/resources/services/storage/accounts_mock_test.go, plugins/source/azure/resources/services/storage/file_shares.go, plugins/source/azure/resources/services/storage/file_shares_mock_test.go, website/pages/docs/plugins/sources/azure/tables.md, website/tables/azure/azure_storage_accounts.md, website/tables/azure/azure_storage_file_shares.md
=> feat(azure): File Shares

website/pages/docs/plugins/destinations/clickhouse/overview.mdx
These links fail our broken links check as the have a permanent redirect to another link (without the `/`).
This PR updates the links so there's no extra hop for users
=> fix(clickhouse-brokenlinks): Update ClickHouse links

website/pages/docs/reference/source-spec.md
document. `deterministic_cq_id` attribute in source spec
=> chore(website): Update Docs to show information for new Source Spec option

website/components/pages/pricing.tsx
=> chore(website): Make support anually billed for now

website/pages/blog/cloudquery_tailscale.mdx
Updates the date of the Tailscale blog
=> fix(blog): Update cloudquery_tailscale.mdx

plugins/source/aws/resources/services/rds/cluster_backtracks.go
=> fix(aws): Skip backtrack fetching if backtrack is disabled for RDS cluster

website/components/PricingCard.tsx, website/components/pages/pricing.tsx
Small CSS fix and addition of line to make it clear that usage is not metered or limited.
=> chore(website): Update pricing page

website/components/PricingCard.tsx, website/components/pages/pricing.tsx
Clarify for visitors from Canada, Australia and other countries also using $ that the prices quoted are in USD.
=> chore(website): Clarify prices as being in USD

plugins/source/azure/resources/services/subscription/locations.go, plugins/source/azure/resources/services/subscription/locations_mock_test.go, plugins/source/azure/resources/services/subscription/subscription_mock_test.go
Fixes https://github.com/cloudquery/cloudquery/issues/9366
=> fix(azure-resources): Pass correct subscription ID when listing subscription locations

plugins/source/shopify/internal/shopify/shopify.go, plugins/source/shopify/resources/services/checkout/abandoned_checkouts_fetch.go, plugins/source/shopify/resources/services/customer/customers_fetch.go, plugins/source/shopify/resources/services/order/orders_fetch.go, plugins/source/shopify/resources/services/price_rule/price_rules_fetch.go, plugins/source/shopify/resources/services/product/products_fetch.go
=> fix(shopify): Pagination should not include params in following pages

plugins/source/azure/docs/tables/README.md, plugins/source/azure/resources/plugin/tables.go, plugins/source/azure/resources/services/compute/capacity_reservation_groups.go, plugins/source/azure/resources/services/compute/capacity_reservation_groups_test.go, plugins/source/azure/resources/services/compute/capacity_reservations.go, plugins/source/azure/resources/services/compute/capacity_reservations_test.go, website/pages/docs/plugins/sources/azure/tables.md, website/tables/azure/azure_compute_capacity_reservation_groups.md, website/tables/azure/azure_compute_capacity_reservations.md
Fixes https://github.com/cloudquery/cloudquery/issues/9415. Tested on real resources (with the expand bit, to list associated VMs and Scale Set VMs).
=> feat(azure-resources): Add Capacity Reservation Groups and Reservations

website/pages/how-to-guides/how-to-load-infrastructure-data-into-athena.mdx
- Add in new `region` that is now required
- For AWS source, include the `skip_tables`
=> fix(website): Update Tutorial

website/pages/docs/plugins/destinations/meilisearch/overview.mdx
=> chore(meilisearch): Update issue link

plugins/destination/clickhouse/client/spec.go
=> fix(clickhouse): Check `ca_cert` append result

website/pages/how-to-guides/cloud-asset-inventory-cloudquery-apache-superset.mdx
=> fix(website): Fix Apache Superset Broken Link

plugins/source/aws/resources/services/codebuild/projects.go, plugins/source/aws/resources/services/codepipeline/webhooks.go, plugins/source/aws/resources/services/eks/clusters.go, plugins/source/aws/resources/services/elbv2/listeners.go, plugins/source/aws/resources/services/elbv2/target_groups.go, plugins/source/aws/resources/services/emr/clusters.go, plugins/source/aws/resources/services/iam/accounts.go, plugins/source/aws/resources/services/iam/group_policies.go, plugins/source/aws/resources/services/iam/policies.go, plugins/source/aws/resources/services/iam/user_access_keys.go, plugins/source/aws/resources/services/iam/user_policies.go, plugins/source/aws/resources/services/iam/virtual_mfa_devices.go, plugins/source/aws/resources/services/kafka/cluster_operations.go, plugins/source/aws/resources/services/kafka/clusters.go, plugins/source/aws/resources/services/kafka/nodes.go, plugins/source/aws/resources/services/kinesis/streams.go, plugins/source/aws/resources/services/kinesis/streams_mock_test.go, plugins/source/aws/resources/services/ssm/instances.go, plugins/source/aws/resources/services/ssm/parameters.go, plugins/source/aws/resources/services/ssm/sessions.go, plugins/source/aws/resources/services/ssoadmin/account_assignments.go, plugins/source/aws/resources/services/ssoadmin/instances.go, plugins/source/aws/resources/services/ssoadmin/permission_sets.go, plugins/source/aws/resources/services/transfer/servers.go, plugins/source/aws/resources/services/workspaces/directories.go, plugins/source/aws/resources/services/workspaces/workspaces.go
Replace manual pagination with the Paginator object
=> chore(aws): Pagination improvements

.github/workflows/scripts_ci.yml, scripts/table_diff/main.go
Follow up to https://github.com/cloudquery/cloudquery/pull/9708
=> feat(ci): Add CI for our scripts

plugins/source/aws/resources/services/guardduty/detector_findings.go
=> fix(aws): Properly Handle Pagination for Guardduty Findings

plugins/source/googleads/client/testing.go, plugins/source/googleads/resources/ads/group_ad_labels_test.go, plugins/source/googleads/resources/ads/group_ads_test.go, plugins/source/googleads/resources/ads/group_criteria_test.go, plugins/source/googleads/resources/ads/group_criterion_labels_test.go, plugins/source/googleads/resources/ads/group_labels_test.go, plugins/source/googleads/resources/ads/groups_test.go, plugins/source/googleads/resources/campaigns/campaign_criteria_test.go, plugins/source/googleads/resources/campaigns/campaign_labels_test.go, plugins/source/googleads/resources/campaigns/campaigns_test.go, plugins/source/googleads/resources/customers/customer_labels_test.go, plugins/source/googleads/resources/customers/customers_test.go
[`maps.Copy`](https://pkg.go.dev/golang.org/x/exp/maps#Copy)
=> chore(googleads): Use `maps.Copy`

website/pages/blog/product-updates-5.mdx
=> feat: Product updates 5

plugins/destination/duckdb/client/migrate.go
Closes https://github.com/cloudquery/cloudquery/issues/9771
=> fix(duckdb): Support multiple PKs

website/pages/blog/finding-enabled-s3-acls-and-disabled-s3-block-public-access.mdx
Updating post with change now in effect.
=> chore(website): Update s3 security setting blog with change from AWS

.github/workflows/wait_for_required_workflows.yml
=> fix(ci): Revert remove duplicates from check runs in wait for all workflow

plugins/source/aws/resources/services/iot/billing_groups.go, plugins/source/aws/resources/services/iot/jobs.go, plugins/source/aws/resources/services/iot/policies.go, plugins/source/aws/resources/services/iot/security_profiles.go, plugins/source/aws/resources/services/iot/tags.go, plugins/source/aws/resources/services/iot/thing_groups.go, plugins/source/aws/resources/services/iot/thing_types.go, plugins/source/aws/resources/services/iot/topic_rules.go
use single function to make API calls rather than reimplementing for each resource
=> refactor(aws): Consolidate IoT Tag Resolvers

plugins/source/aws/resources/services/iot/topic_rules.go
Use `PreResourceResolver` to call `GetTopicRule` rather than calling sequentially
=> feat(aws): Parallelize resolution of `aws_iot_topic_rules`

plugins/source/aws/resources/services/iot/security_profiles.go
Use `PreResourceResolver` to call `DescribeSecurityProfile` rather than calling sequentially
=> feat(aws): Parallelize resolution of `aws_iot_security_profiles`

plugins/source/aws/resources/services/iot/ca_certificates.go
Use `PreResourceResolver` to call `DescribeCACertificate` rather than calling sequentially
=> feat(aws): Parallelize resolution of `aws_iot_ca_certificates`

plugins/source/aws/resources/services/iot/jobs.go
Use `PreResourceResolver` to call `DescribeJob` rather than calling sequentially
=> feat(aws): Parallelize resolution of `aws_iot_jobs`

plugins/source/aws/policies/queries/lambda/lambda_function_prohibit_public_access.sql
=> fix(aws-policies): Update Query to properly handle a string and array

plugins/source/aws/resources/services/inspector/findings.go
=> fix(aws): Inspector Classic fetch details use proper limits

.github/workflows/wait_for_required_workflows.yml
Fixes https://github.com/cloudquery/cloudquery/issues/9797. Follow up to https://github.com/cloudquery/cloudquery/pull/9793 and replaces https://github.com/cloudquery/cloudquery/pull/9813.
https://github.com/cloudquery/cloudquery/issues/9797#issuecomment-1502662486 Confirms the ID is duplicated and we can filter using it
=> fix(ci): Remove duplicated check runs

.github/workflows/source_aws.yml, .github/workflows/validate_release.yml, .github/workflows/wait_for_required_workflows.yml
=> feat(ci): Reuse `validate-release` in AWS Source plugin workflow

.github/workflows/wait_for_required_workflows.yml
Should make https://github.com/cloudquery/cloudquery/pull/9834#issuecomment-1503212583 pass
=> fix(ci): Don't fail on deleted files

plugins/source/gcp/go.mod, plugins/source/gcp/go.sum
=> fix(gcp): Update module github.com/cloudquery/plugin-sdk to v1.45.0

plugins/source/firestore/client/client.go, plugins/source/firestore/client/spec.go, plugins/source/firestore/client/sync.go, plugins/source/firestore/resources/plugin/plugin_test.go, website/components/pluginData.tsx, website/pages/docs/plugins/sources/firestore/_authentication.mdx, website/pages/docs/plugins/sources/firestore/_configuration.mdx, website/pages/docs/plugins/sources/firestore/_meta.json, website/pages/docs/plugins/sources/firestore/overview.mdx, website/pages/docs/plugins/sources/firestore/tables.md, website/public/images/logos/plugins/firestore-dark.svg, website/public/images/logos/plugins/firestore-light.svg
Follow up to https://github.com/cloudquery/cloudquery/pull/9653. I'll need some help to confirm the docs, cc @BubbaJoe 
Docs in https://cloudquery-oo1n5e8ec-cloudquery.vercel.app/docs/plugins/sources/firestore/overview
=> feat(website): Add Firestore

website/pages/docs/plugins/destinations/azblob/overview.mdx, website/pages/docs/plugins/destinations/bigquery/overview.mdx, website/pages/docs/plugins/destinations/clickhouse/overview.mdx, website/pages/docs/plugins/destinations/duckdb/overview.mdx, website/pages/docs/plugins/destinations/elasticsearch/overview.mdx, website/pages/docs/plugins/destinations/file/overview.mdx, website/pages/docs/plugins/destinations/gcs/overview.mdx, website/pages/docs/plugins/destinations/mongodb/overview.mdx, website/pages/docs/plugins/destinations/s3/overview.mdx, website/pages/docs/plugins/destinations/sqlite/overview.mdx
Im moving the destinations that we know are in use for a while to GA.
=> feat(website): Move applicable destination to GA

plugins/source/aws/policies/queries/ec2/ebs_snapshot_permissions_check.sql
=> fix(aws): Update EBS Snapshot Permissions Check Query

plugins/source/aws/client/client.go
This is a preliminary PR to make it easier to follow and understand the changes coming for #10177
=> refactor(aws): Renamed Variable In Client

plugins/source/aws/client/client.go, plugins/source/aws/client/organizations.go
More naming refactor to reduce complexity in #10177
=> refactor(aws): Naming Refactor

plugins/source/aws/client/account.go, plugins/source/aws/client/aws_sdk.go, plugins/source/aws/client/client.go
refactor to make #10177 easier to read
=> refactor(aws): Move To Separate files

plugins/source/azure/policies/queries/web/function_app_should_only_be_accessible_over_https.sql
Added missing character so the SQL statement returns the expected values.
Added missing character so that the SQL statement returns expected values.
=> fix(azure): Added missing character

plugins/source/gcp/policies/queries/compute/instances_with_shielded_vm_disabled.sql
Updating GCP Shielded VM instance policy to include Secure Boot
Link: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#enable_secure_boot
=> feat(gcp): Update GCP Instance Shielded VM Policy

website/pages/blog/product-updates-5.mdx
=> fix(website): Product update 5 link

website/pages/docs/deployment/overview.md
The product is called `Amazon ECS`
=> doc: Update deployment overview.md

plugins/destination/duckdb/json/writer.go
Missed from my CR at https://github.com/cloudquery/cloudquery/pull/10275
=> chore(duckdb): Simplify JSON writer

plugins/destination/postgresql/client/migrate.go
=> fix(postgresql): Reserved Keywords Caused Migration failure

.github/styles/Vocab/Base/accept.txt, website/pages/docs/plugins/sources/overview.mdx
Also introduces lexicographic ordering
=> doc(website): Add Onfleet to partner plugins

plugins/source/aws/policies/queries/apigateway/api_gw_xray_enabled.sql
Fixing customer reported policy issue with API Gateway.  Removing unnecessary logic.
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enabling-xraya.html
https://docs.aws.amazon.com/xray/latest/devguide/xray-services-apigateway.html
=> fix(aws-policies): Api Gateway xray tracing enabled query

plugins/source/gcp/client/client.go
Currently CQ only logs a single error (at random) from all of the projects that are discovered. This changes to ensure that all errors are logged.
=> feat(gcp): Enable Better Logging for when `enabled_services_only` fails

plugins/source/aws/docs/tables/README.md, plugins/source/aws/resources/services/cloudformation/stack_resources.go, plugins/source/aws/resources/services/cloudformation/stack_templates.go, plugins/source/aws/resources/services/cloudformation/stacks.go, plugins/source/aws/resources/services/cloudformation/stacks_mock_test.go, website/pages/docs/plugins/sources/aws/tables.md, website/tables/aws/aws_cloudformation_stack_templates.md, website/tables/aws/aws_cloudformation_stacks.md
=> feat(aws): Add Support for Cloudformation Templates

plugins/source/aws/docs/tables/README.md, plugins/source/aws/resources/plugin/tables.go, plugins/source/aws/resources/services/efs/accesspoints.go, plugins/source/aws/resources/services/efs/accesspoints_mock_test.go, website/pages/docs/plugins/sources/aws/tables.md, website/tables/aws/aws_efs_access_points.md, website/tables/aws/aws_efs_accesspoints.md
Closes https://github.com/cloudquery/cloudquery/issues/10459
=> feat(aws): Add support for EFS Access Point

plugins/destination/test/client/client.go, plugins/destination/test/go.mod, plugins/destination/test/go.sum, plugins/destination/test/main.go
=> feat(test destination): Upgrade to SDK v3

plugins/destination/snowflake/CHANGELOG.md, plugins/destination/snowflake/CONTRIBUTING.md, plugins/destination/snowflake/client/client.go, plugins/destination/snowflake/client/client_test.go, plugins/destination/snowflake/client/deletestale.go, plugins/destination/snowflake/client/metrics.go, plugins/destination/snowflake/client/migrate.go, plugins/destination/snowflake/client/read.go, plugins/destination/snowflake/client/types.go, plugins/destination/snowflake/client/write.go, plugins/destination/snowflake/go.mod, plugins/destination/snowflake/go.sum, plugins/destination/snowflake/main.go
Closes https://github.com/cloudquery/cloudquery/issues/10729
=> feat(snowflake): Migrate to SDK V3 native arrow

plugins/destination/postgresql/client/client.go, plugins/destination/postgresql/client/client_test.go, plugins/destination/postgresql/client/deletestale.go, plugins/destination/postgresql/client/metrics.go, plugins/destination/postgresql/client/migrate.go, plugins/destination/postgresql/client/read.go, plugins/destination/postgresql/client/read_cockroach.go, plugins/destination/postgresql/client/transformer.go, plugins/destination/postgresql/client/types_cockroach.go, plugins/destination/postgresql/client/types_pg.go, plugins/destination/postgresql/client/write.go, plugins/destination/postgresql/go.mod, plugins/destination/postgresql/go.sum, plugins/destination/postgresql/main.go
Closes https://github.com/cloudquery/cloudquery/issues/10727
=> feat(postgresql): Update PG to SDK V3 native arrow support

cli/internal/plugin/manageddestination/plugin.go, cli/internal/plugin/managedsource/plugin.go
Reported on discord. It was introduced when we moved code from SDK to CLI.
=> fix(cli): Regression support 100MB msgs

plugins/source/okta/client/client.go, plugins/source/okta/client/spec.go, plugins/source/okta/client/transformers.go, website/pages/docs/plugins/sources/okta/overview.mdx
=> feat(okta): Add rate limiter config

plugins/source/hubspot/client/spec.go, plugins/source/hubspot/resources/services/crm/companies.go, plugins/source/hubspot/resources/services/crm/companies_fetch.go, plugins/source/hubspot/resources/services/crm/contacts.go, plugins/source/hubspot/resources/services/crm/contacts_fetch.go, plugins/source/hubspot/resources/services/crm/deals.go, plugins/source/hubspot/resources/services/crm/deals_fetch.go, plugins/source/hubspot/resources/services/crm/line_items.go, plugins/source/hubspot/resources/services/crm/line_items_fetch.go, plugins/source/hubspot/resources/services/crm/products.go, plugins/source/hubspot/resources/services/crm/products_fetch.go, plugins/source/hubspot/resources/services/crm/quotes.go, plugins/source/hubspot/resources/services/crm/quotes_fetch.go, plugins/source/hubspot/resources/services/crm/tickets.go, plugins/source/hubspot/resources/services/crm/tickets_fetch.go, website/pages/docs/plugins/sources/hubspot/_configuration.mdx, website/pages/docs/plugins/sources/hubspot/overview.mdx, website/tables/hubspot/hubspot_crm_companies.md, website/tables/hubspot/hubspot_crm_contacts.md, website/tables/hubspot/hubspot_crm_deals.md, website/tables/hubspot/hubspot_crm_line_items.md, website/tables/hubspot/hubspot_crm_products.md, website/tables/hubspot/hubspot_crm_quotes.md, website/tables/hubspot/hubspot_crm_tickets.md
Extracts the HubSpot objects associations and adds their JSON content as a column in the extracted table
Relates to https://github.com/cloudquery/cloudquery/issues/10915
=> feat(hubspot): Extract associations

plugins/destination/duckdb/go.mod, plugins/destination/duckdb/go.sum
=> chore(deps): Update duckdb to sdk v3.6.3

plugins/destination/mongodb/go.mod, plugins/destination/mongodb/go.sum
=> chore(mongodb): Update to SDK v3.6.3

plugins/destination/mssql/go.mod, plugins/destination/mssql/go.sum
=> feat(mssql): Update to SDK V363

plugins/destination/mysql/go.mod, plugins/destination/mysql/go.sum
=> feat(mysql): Update to SDK v3.6.3

plugins/destination/test/go.mod, plugins/destination/test/go.sum
=> feat(test): Update to sdk v3.6.3

scripts/table_diff/changes/changes_test.go, scripts/table_diff/changes/testdata/pr_10797_diff.txt, scripts/table_diff/changes/types.go
Inspired by https://github.com/cloudquery/cloudquery/pull/10797#issuecomment-1562966623
=> chore(diff): Handle list types

plugins/destination/neo4j/client/client_test.go, plugins/destination/neo4j/client/transformer.go, plugins/destination/neo4j/go.mod, plugins/destination/neo4j/go.sum
=> feat(neo4j): Update to SDK v3.6.3

plugins/source/gitlab/docs/tables/README.md, plugins/source/gitlab/resources/services/groups/billable_members.go, plugins/source/gitlab/resources/services/groups/groups.go, plugins/source/gitlab/resources/services/groups/groups_mock_test.go, plugins/source/gitlab/resources/services/groups/members.go, plugins/source/gitlab/resources/services/projects/branches.go, plugins/source/gitlab/resources/services/projects/members.go, plugins/source/gitlab/resources/services/projects/projects.go, plugins/source/gitlab/resources/services/projects/releases.go, plugins/source/gitlab/resources/services/users/users.go, website/pages/docs/plugins/sources/gitlab/tables.md, website/tables/gitlab/gitlab_group_billable_members.md, website/tables/gitlab/gitlab_groups.md
=> feat(gitbal): Add `gitlab_group_billable_members` table

plugins/source/azure/docs/tables/README.md, plugins/source/azure/resources/services/dns/record_sets.go, plugins/source/azure/resources/services/dns/zones.go, plugins/source/azure/resources/services/dns/zones_mock_test.go, website/pages/docs/plugins/sources/azure/tables.md, website/tables/azure/azure_dns_record_sets.md, website/tables/azure/azure_dns_zones.md
Fixes https://github.com/cloudquery/cloudquery/issues/10847
=> feat(azure-resources): Add DNS Record Sets

website/components/_app.tsx
We don't use plausible analytics (we just use simpleanalytics)
=> chore(website): Remove plausible analytics

plugins/destination/duckdb/client/client.go, plugins/destination/duckdb/client/delete_stale.go, plugins/destination/duckdb/client/migrate.go, plugins/destination/duckdb/client/read.go, plugins/destination/duckdb/client/transform.go, plugins/destination/duckdb/client/types.go, plugins/destination/duckdb/client/write.go
It's an effort to shorten #11116 diff
=> chore(duckdb): Refactor

plugins/destination/duckdb/client/client.go, plugins/destination/duckdb/client/delete_stale.go, plugins/destination/duckdb/client/metrics.go, plugins/destination/duckdb/client/migrate.go, plugins/destination/duckdb/client/read.go, plugins/destination/duckdb/client/types.go, plugins/destination/duckdb/client/write.go
=> chore(refactor): Refactor DuckDB

plugins/source/gcp/go.mod, plugins/source/gcp/go.sum
=> fix(gcp): Update module github.com/cloudquery/plugin-sdk/v3 to v3.10.2

website/pages/blog/finding-enabled-s3-acls-and-disabled-s3-block-public-access.mdx
Updating table links to direct to website and not Github
=> chore(website): Update links to tables in S3 Blog Post

website/pages/blog/aws-kms-key-grants-deep-dive.mdx
Update CQ resource links (tables) to point to website and not github.
=> chore(website): Update links for AWS KMS Grants and Access blog

website/pages/docs/advanced-topics/environment-variable-substitution.md
Not sure about the wording or if we should include recommendations for older versions.
=> fix(website): External content import notes

website/pages/blog/product-updates-6.mdx
=> chore(website): Product Updates #6

website/pages/docs/developers/creating-new-plugin.md
=> doc(website): Fix scaffold command

website/pages/docs/deployment/google-cloud-vm.mdx, website/theme.config.tsx
This adds the ability to use additional Open Graph tags on pages that can use them.
=> chore(website): Add optional og:title and og:video meta tags to header

website/versions/source-firestore.json
Versions >= v2 of the Firestore source plugin are currently broken due to an issue with v3 of the plugins SDK. See https://github.com/cloudquery/cloudquery/pull/11452
=> chore(website-firestore): Revert to last working version

.github/workflows/pr_labeler.yml
Woops 🤦  follow up to https://github.com/cloudquery/cloudquery/pull/11494
=> fix(ci): Put `continue-on-error: true` in the right level

plugins/source/oracledb/client/list_tables.go
Fixes https://github.com/cloudquery/cloudquery/issues/10964#issuecomment-1590962768
=> fix: Filter out invisible columns

.github/workflows/clean_actions_cache.yml
Testing if clearing the actions cache solves the failures in https://github.com/cloudquery/cloudquery/pull/11473 (changes to `go.sum`)
=> feat(ci): Add workflow to clean GitHub Actions caches

cli/cmd/sync_v3.go
Update for v4 to set SkipDependentTables and DeterministicCqId
=> fix(cli): Set SkipDependentTables, DeterministicCqId

website/pages/docs/advanced-topics/_meta.json
Follow up to https://github.com/cloudquery/cloudquery/pull/10371
=> fix: Remove docker link from advanced topics

plugins/source/aws/resources/services/eks/clusters_mock_test.go, plugins/source/aws/resources/services/support/services_test.go
=> refactor(aws): Linting

plugins/source/aws/resources/services/apprunner/tag_fetch.go
Closes: https://github.com/cloudquery/cloudquery/issues/11785
=> fix(aws): AppRunner Tag errors

cli/cmd/migrate.go
we were exiting instead of continuing on migrating for multiple sources. Introduced here https://github.com/cloudquery/cloudquery/pull/11655
=> fix(CLI): Multiple migrations

website/pages/docs/plugins/sources/aws/configuration.md, website/pages/docs/plugins/sources/aws/multi-account.mdx
followup to https://github.com/cloudquery/cloudquery/pull/11441
=> doc(website): Add `concurrency` to example configs

plugins/source/aws/client/account.go, plugins/source/aws/client/client.go, plugins/source/aws/resources/services/timestream/databases.go
Workaround for https://github.com/aws/aws-sdk-go-v2/issues/2163
=> fix(aws): Fix Timestream Regional issue

plugins/source/aws/resources/services/codebuild/source_credentials_mock_test.go
=> fix(aws): Fix CodeBuild SourceCredentials Mock Test

plugins/destination/snowflake/client/client.go, plugins/destination/snowflake/client/client_test.go, plugins/destination/snowflake/client/deletestale.go, plugins/destination/snowflake/client/migrate.go, plugins/destination/snowflake/client/read.go, plugins/destination/snowflake/client/write.go, plugins/destination/snowflake/go.mod, plugins/destination/snowflake/go.sum
=> fix(snowflake): Update to SDK v4.1.0-rc1

cli/cmd/sync_v3.go, cli/go.mod, cli/go.sum
This requires additional update in plugin-pb-go. For delete stale we actually don't want the schema but just the name of the table
=> fix(cli): Fix sync in protov3

plugins/destination/snowflake/client/deletestale.go, plugins/destination/snowflake/client/migrate.go, plugins/destination/snowflake/client/write.go, plugins/destination/snowflake/go.mod, plugins/destination/snowflake/go.sum
SDK Release: https://github.com/cloudquery/plugin-sdk/releases/tag/v4.4.0-rc1
=> fix(snowflake): Update to SDK v4.4.0-rc1

plugins/destination/sqlite/client/deletestale.go, plugins/destination/sqlite/client/write.go, plugins/destination/sqlite/go.mod, plugins/destination/sqlite/go.sum
Update: https://github.com/cloudquery/plugin-sdk/releases/tag/v4.4.0-rc1
=> feat(sqlite): Update to SDK V4.4.0-rc1

plugins/destination/mongodb/client/deletestale.go, plugins/destination/mongodb/client/migrate.go, plugins/destination/mongodb/client/write.go, plugins/destination/mongodb/go.mod, plugins/destination/mongodb/go.sum
SDK Release: https://github.com/cloudquery/plugin-sdk/releases/tag/v4.4.0-rc1
=> fix(mongodb): Update SDK to v4.4.0-rc1

plugins/destination/meilisearch/go.mod, plugins/destination/meilisearch/go.sum
SDK Release: https://github.com/cloudquery/plugin-sdk/releases/tag/v4.4.0-rc1
=> fix(meilisearch): Update SDK to v4.4.0-rc1

plugins/destination/duckdb/client/delete_stale.go, plugins/destination/duckdb/client/migrate.go, plugins/destination/duckdb/client/write.go, plugins/destination/duckdb/go.mod, plugins/destination/duckdb/go.sum
SDK Release: https://github.com/cloudquery/plugin-sdk/releases/tag/v4.4.0-rc1
=> fix(duckdb): Update SDK to v4.4.0-rc1

plugins/destination/gremlin/client/deletestale.go, plugins/destination/gremlin/client/migrate.go, plugins/destination/gremlin/client/write.go, plugins/destination/gremlin/go.mod, plugins/destination/gremlin/go.sum
Update: https://github.com/cloudquery/plugin-sdk/releases/tag/v4.4.0-rc1
=> fix(gremlin): Update to SDK v4.4.1-rc1

plugins/destination/duckdb/go.mod, plugins/destination/duckdb/go.sum, plugins/destination/gremlin/go.mod, plugins/destination/gremlin/go.sum, plugins/destination/meilisearch/go.mod, plugins/destination/meilisearch/go.sum, plugins/destination/mongodb/go.mod, plugins/destination/mongodb/go.sum, plugins/destination/neo4j/go.mod, plugins/destination/neo4j/go.sum, plugins/destination/snowflake/go.mod, plugins/destination/snowflake/go.sum, plugins/destination/sqlite/go.mod, plugins/destination/sqlite/go.sum
=> fix: Update destinations to v4.4.2-rc1

plugins/destination/mysql/main.go
=> fix(mysql): Fix main serve function

plugins/destination/clickhouse/client/spec.go
=> chore: Fix comment

cli/cmd/sync_v3.go, cli/go.mod, cli/go.sum
Depends on https://github.com/cloudquery/plugin-pb-go/pull/57
=> feat: Handle State backends in CLI for v3 protocol

website/pages/how-to-guides/update-plugins-using-renovate.mdx
Add missing colon in `renovate.json` code block
=> doc: Add missing colon in code block

plugins/destination/elasticsearch/main.go
=> fix(elasticsearch): Fix serve

plugins/destination/clickhouse/client/client.go, plugins/destination/clickhouse/client/spec.go, plugins/destination/clickhouse/go.mod, plugins/destination/clickhouse/go.sum, plugins/destination/meilisearch/client/client.go, plugins/destination/meilisearch/client/spec.go, plugins/destination/meilisearch/go.mod, plugins/destination/meilisearch/go.sum, plugins/destination/mssql/client/client.go, plugins/destination/mssql/client/spec.go, plugins/destination/mssql/go.mod, plugins/destination/mssql/go.sum, website/pages/docs/plugins/destinations/meilisearch/_configuration.mdx, website/pages/docs/plugins/destinations/meilisearch/overview.mdx
Same as #11939 but for:
* ClickHouse
* Meilisearch
* MSSQL
=> fix: Use `configtype.Duration`

plugins/source/tailscale/client/client.go, plugins/source/tailscale/client/resolvers.go, plugins/source/tailscale/client/spec.go, plugins/source/tailscale/client/testing.go, plugins/source/tailscale/client/transformers.go, plugins/source/tailscale/go.mod, plugins/source/tailscale/go.sum, plugins/source/tailscale/main.go, plugins/source/tailscale/resources/plugin/plugin.go, plugins/source/tailscale/resources/plugin/tables.go, plugins/source/tailscale/resources/services/acl/acls.go, plugins/source/tailscale/resources/services/acl/acls_mock_test.go, plugins/source/tailscale/resources/services/device/devices.go, plugins/source/tailscale/resources/services/device/devices_mock_test.go, plugins/source/tailscale/resources/services/dns/nameservers.go, plugins/source/tailscale/resources/services/dns/nameservers_mock_test.go, plugins/source/tailscale/resources/services/dns/preferences.go, plugins/source/tailscale/resources/services/dns/preferences_mock_test.go, plugins/source/tailscale/resources/services/dns/searchpaths.go, plugins/source/tailscale/resources/services/dns/searchpaths_mock_test.go, plugins/source/tailscale/resources/services/key/keys.go, plugins/source/tailscale/resources/services/key/keys_mock_test.go, website/tables/tailscale/tailscale_acls.md, website/tables/tailscale/tailscale_devices.md, website/tables/tailscale/tailscale_dns_nameservers.md, website/tables/tailscale/tailscale_dns_preferences.md, website/tables/tailscale/tailscale_dns_searchpaths.md, website/tables/tailscale/tailscale_keys.md
Closes https://github.com/cloudquery/cloudquery/issues/11950
=> feat(tailscale): Update to SDK v4

plugins/destination/postgresql/client/client.go
=> fix(postgresql): Rerun release please

.release-please-manifest.json
=> chore: Update .release-please-manifest.json

release-please-config.json
=> chore: Update release-please-config.json

plugins/source/azure/resources/plugin/client.go, plugins/source/azure/resources/plugin/plugin.go, plugins/source/azure/resources/plugin/tables.go, plugins/source/hubspot/resources/plugin/plugin.go
Azure and a tiny one in Hubspot
=> chore: More table fixes

website/pages/docs/plugins/sources/jira/overview.mdx
=> chore(website): Update jira pricing

website/pages/docs/core-concepts/policies.md, website/vercel.json
=> chore(website): Add premium policy for Azure CIS v1.3.0 for snowflake

plugins/destination/duckdb/main.go
=> fix(duckdb): Support V0/V1 syncs

website/pages/how-to-guides/open-source-cspm.mdx
Updated a few outdated links on How to CSPM Guide
=> chore(website): Update Links on How To CSPM Guide

cli/cmd/migrate.go, cli/cmd/sync.go
Fixes https://github.com/cloudquery/cloudquery/issues/12139#issuecomment-1632712486
See https://github.com/cloudquery/cloudquery/issues/12139#issuecomment-1633707056
=> fix: Improve version mismatch errors to include plugin type

website/pages/docs/plugins/sources/jira/overview.mdx
=> fix(website): Update link to Jira integration

cli/cmd/migrate_v3.go, cli/go.mod, cli/go.sum
Goes with https://github.com/cloudquery/plugin-sdk/pull/1092 and https://github.com/cloudquery/plugin-pb-go/pull/62.
This ensures the `cloudquery migrate` command does not require authentication to AWS, GCP, Azure, etc.
=> fix(cmd-migrate): Set `NoConnection` to true

plugins/source/alicloud/client/testing.go, plugins/source/aws/client/testing.go, plugins/source/azure/client/testing.go, plugins/source/cloudflare/client/testing.go, plugins/source/datadog/client/testing.go, plugins/source/digitalocean/client/testing.go, plugins/source/fastly/client/testing.go, plugins/source/gcp/client/testing.go, plugins/source/github/client/testing.go, plugins/source/gitlab/client/testing.go, plugins/source/hackernews/client/testing.go, plugins/source/homebrew/client/testing.go, plugins/source/k8s/client/testing.go, plugins/source/okta/client/testing.go, plugins/source/pagerduty/client/testing.go, plugins/source/salesforce/client/testing.go, plugins/source/shopify/client/testing.go, plugins/source/snyk/client/testing.go, plugins/source/stripe/client/testing.go
~Some plugins _may_ have issues with PKs, will be fixed in future commits.~
=> test: Validate all source plugin tables

website/pages/_meta.json, website/vercel.json
=> chore(website): Add register for CQ Cloud

website/components/BlogHeader.tsx, website/components/CaseStudyHeader.tsx, website/components/HowToGuideHeader.tsx, website/components/Title.tsx
Same fix as https://github.com/cloudquery/cloudquery/pull/12184 just for how to guides.
I removed some code duplication so the fix is now in a single component instead of 3.
=> chore(website): Fix styles for How to guides

website/pages/solutions/open-source-cspm.mdx
Some of the links in this page were moved to our how to guides, so we should link to them instead of the blog to avoid the extra redirect
=> chore(wesbite): Fix links in Open Source CSPM page

scaffold/cmd/templates/source/client/client.go.tpl, scaffold/cmd/templates/source/go.mod.tpl, scaffold/cmd/templates/source/main.go.tpl, scaffold/cmd/templates/source/plugin/plugin.go.tpl, scaffold/cmd/templates/source/resources/table.go.tpl
Fixes https://github.com/cloudquery/cloudquery/issues/11743
=> feat(scaffold): Update to `plugin-sdk` v4

.github/renovate.json5
Similar to https://github.com/cloudquery/cloudquery/pull/7115. This tells renovate to auto update GitHub actions in template files, such as https://github.com/cloudquery/cloudquery/tree/fe7ed1ff29a4da9db3ca5c1b87bdc8977bb5f73d/scaffold/cmd/templates/source/.github/workflows
=> feat(ci-deps): Match github actions dependencies in template files

.github/renovate.json5
Follow up to https://github.com/cloudquery/cloudquery/commit/ec3156f374bb189256f3b8c2a42ff71012409442
=> fix: Renovate config

release-please-config.json
We didn't remove it from the monorepo (see https://github.com/cloudquery/cloudquery/pull/11988 closed and not merged), but [removed it from release please](https://github.com/cloudquery/cloudquery/pull/12049/files#diff-c55d4dcb68c348b2c06d263819702fbce72eeeb35b662956d02049a5a18fcf2bL25).
This PR brings it back so we can release new versions
=> chore: Bring back release please firehose configuration

plugins/source/github/client/mocks/mock_repositories.go, plugins/source/github/client/services.go, plugins/source/github/docs/tables/README.md, plugins/source/github/resources/services/repositories/keys.go, plugins/source/github/resources/services/repositories/repositories.go, plugins/source/github/resources/services/repositories/repositories_test.go, website/pages/docs/plugins/sources/github/tables.md, website/tables/github/github_repositories.md, website/tables/github/github_repository_keys.md
Fixes https://github.com/cloudquery/cloudquery/issues/12403
=> feat(resources): Add Repository Keys

website/components/pages/home.tsx, website/vercel.json
Added Button + changed to typeform which is nicer then google forms, I think might help conversion as well.
=> chore(website): Signup for cloud button

plugins/source/aws/resources/plugin/client.go, plugins/source/azure/resources/plugin/client.go, plugins/source/cloudflare/resources/plugin/plugin.go, plugins/source/facebookmarketing/resources/plugin/plugin.go, plugins/source/fastly/resources/plugin/plugin.go, plugins/source/gcp/resources/plugin/client.go, plugins/source/gitlab/resources/plugin/plugin.go, plugins/source/hubspot/resources/plugin/plugin.go, plugins/source/k8s/resources/plugin/plugin.go
Fixes https://github.com/cloudquery/cloudquery/issues/12421
Did a sweep on all sources to add this option. Will look into adding a test for it in the SDK
=> fix(sync): Pass `DeterministicCQID` option to scheduler

website/vercel.json
=> chore(website): Use typeform instead of Google for for support

plugins/source/aws/resources/services/s3/buckets.go, plugins/source/aws/resources/services/s3/models/s3.go
Should help with [12393](https://github.com/cloudquery/cloudquery/issues/12393)
=> fix(aws): Make `aws_s3_buckets` properties nullable to clarify successful resolver results

plugins/destination/bigquery/CONTRIBUTING.md, plugins/destination/bigquery/client/client.go, plugins/destination/bigquery/client/spec.go, website/pages/docs/plugins/destinations/bigquery/overview.mdx
=> feat(bigquery): Add `endpoint` for local testing

plugins/source/aws/resources/services/acm/certificates.go, plugins/source/aws/resources/services/acm/certificates_mock_test.go
Fixes https://github.com/cloudquery/cloudquery/issues/12416
=> fix(resources-acm-certificates): Filter by all key usages

contributing/development_environment.md, website/pages/blog/aws-priv-esc-identity-center.mdx, website/pages/blog/guide-aws-org-delegation.mdx, website/pages/how-to-guides/attack-surface-management-with-graph.mdx, website/pages/how-to-guides/simple-analytics-to-bigquery.mdx, website/pages/how-to-guides/update-plugins-using-renovate.mdx
update to make versions use latest
=> chore(website): Update plugin versions in blogs and how-to-guides

plugins/source/aws/resources/services/s3/buckets.go
=> fix: Resolve attributes for S3 buckets with no policy status

website/pages/docs/plugins/sources/aws/configuration.md
Add more large tables to skip to existing list
=> doc(website): Update Skip Tables for AWS

plugins/source/aws/docs/tables/README.md, plugins/source/aws/resources/plugin/tables.go, plugins/source/aws/resources/services/s3/multi_region_access_points.go, plugins/source/aws/resources/services/s3/multi_region_access_points_mock_test.go, website/pages/docs/plugins/sources/aws/tables.md, website/tables/aws/aws_s3_multi_region_access_points.md
=> feat(resources-s3): Add support for S3 Multi Region Access Points

website/pages/docs/reference/destination-spec.md
Related to https://github.com/cloudquery/cloudquery/issues/12526#issuecomment-1651384771
=> chore(docs-spec): Add `write_mode`, `migrate_mode` clarifications

cli/internal/specs/v0/source.go
Didn't want to add these to `Source.Validate()` to error out just yet.
=> feat(source-spec): Warn if ineffective options are detected

plugins/source/aws/docs/tables/README.md, plugins/source/aws/resources/plugin/tables.go, plugins/source/aws/resources/services/emr/studio_session_mapping.go, plugins/source/aws/resources/services/emr/studios.go, plugins/source/aws/resources/services/emr/studios_test.go, website/pages/docs/plugins/sources/aws/tables.md, website/tables/aws/aws_emr_studio_session_mapping.md, website/tables/aws/aws_emr_studio_session_mappings.md, website/tables/aws/aws_emr_studios.md
Fixes: https://github.com/cloudquery/cloudquery/issues/12528
=> feat(resources): Add additional emr resources for studio and studio session mapping

plugins/source/aws/client/testing.go
Another codification of a rule that came up during onboarding
=> test: Ensure SDK Metadata column(s) are properly skipped

website/pages/docs/core-concepts/policies.md
=> feat: Add cost dashboard to policies section

.github/workflows/release_plugin_source_test.yml, .release-please-manifest.json, plugins/source/test/CHANGELOG.md
Put the `Add Docker builder` in the correct place
=> chore: Fix test release workflow

.release-please-manifest.json, plugins/source/test/.goreleaser.yaml, plugins/source/test/CHANGELOG.md, plugins/source/test/Dockerfile.windows.goreleaser
=> chore: Disable docker Windows image for source-test

website/pages/_meta.json
=> chore: Move policies to main navbar

.github/workflows/validate_pr_title.yml
We usually use these for `chore` PRs for clarity
=> chore: Add some more scopes to PR validator

.github/workflows/broken_links.yml
Our broken links checker is not happy about this link for some reason. Follow up to https://github.com/cloudquery/cloudquery/pull/12689
=> chore(website): Exclude Shopify link

plugins/destination/mssql/queries/values.go, plugins/destination/mssql/queries/values_test.go
Follow-up for #12645.
See https://github.com/cloudquery/cloudquery/pull/12645/files#r1280845493 for more details
=> fix: Bring chunk traversal back

plugins/source/aws/client/spec.go
This option was never used. Marked as `chore` as it's non breaking (we will still parse the spec successfully without it)
=> chore: Remove scheduler from spec

.github/workflows/source_square.yml, plugins/source/square/Makefile, plugins/source/square/plugin/plugin.py, plugins/source/square/requirements.txt, plugins/source/square/tests/plugin/test_plugin.py
=> chore(ci): Add square CI

.github/workflows/source_square.yml
=> chore: Fix typo in `source_square.yml`

.github/workflows/release_plugin.yml
Should fix the `unknown/unknown` arch here:
https://github.com/cloudquery/cloudquery/pkgs/container/cq-source-square
More in https://github.com/orgs/community/discussions/45969
=> fix(ci): Disable attestations

website/pages/blog/proto-v3.mdx
Versions are required so the example won't work without them
=> chore: Add missing versions to blog example

CONTRIBUTING.md
To make it easier to discover it
=> chore: Link to the `adding a plugin the monorepo` guide in contributing docs

contributing/adding_a_new_plugin_to_cq_monorepo.md
=> chore: Add missing `a` in contributing guide

.github/workflows/release_pr.yml, release-please-config.json
Trying to fix the extra files configuration
=> chore: Pin release please version

.github/workflows/release_pr.yml, release-please-config.json
=> chore: Fix typeform release

.github/workflows/release_pr.yml, plugins/source/square/Makefile, plugins/source/square/README.md, plugins/source/square/plugin/plugin.py, plugins/source/square/plugin/tables/bookings.py, plugins/source/square/plugin/tables/disputes.py, plugins/source/square/plugin/tables/invoices.py, plugins/source/square/plugin/tables/locations.py, plugins/source/square/plugin/tables/merchants.py, plugins/source/square/plugin/tables/payments.py, plugins/source/square/plugin/tables/payouts.py, plugins/source/square/plugin/tables/refunds.py, website/pages/docs/plugins/sources/square/_authentication.mdx, website/pages/docs/plugins/sources/square/_configuration.mdx, website/pages/docs/plugins/sources/square/_meta.json, website/pages/docs/plugins/sources/square/overview.mdx, website/pages/docs/plugins/sources/square/tables.md, website/pages/docs/plugins/sources/square/tables/[table].mdx, website/tables/square/square_bookings.md, website/tables/square/square_disputes.md, website/tables/square/square_invoices.md, website/tables/square/square_locations.md, website/tables/square/square_merchants.md, website/tables/square/square_payments.md, website/tables/square/square_payouts.md, website/tables/square/square_refunds.md
Most things mindlessly copied from typeform example.
=> chore: Add Square plugin docs

plugins/destination/postgresql/client/transformer.go
Fixes https://github.com/cloudquery/cloudquery/issues/12754
=> fix: Strip NUL bytes in JSON

plugins/source/gcp/client/transformers.go, website/tables/gcp/gcp_aiplatform_operations.md, website/tables/gcp/gcp_appengine_versions.md, website/tables/gcp/gcp_artifactregistry_repositories.md, website/tables/gcp/gcp_bigtableadmin_app_profiles.md, website/tables/gcp/gcp_binaryauthorization_assertors.md, website/tables/gcp/gcp_certificatemanager_certificate_map_entries.md, website/tables/gcp/gcp_certificatemanager_certificates.md, website/tables/gcp/gcp_clouddeploy_delivery_pipelines.md, website/tables/gcp/gcp_clouddeploy_job_runs.md, website/tables/gcp/gcp_clouddeploy_targets.md, website/tables/gcp/gcp_cloudscheduler_jobs.md, website/tables/gcp/gcp_containeranalysis_occurrences.md, website/tables/gcp/gcp_functions_functions.md, website/tables/gcp/gcp_kms_crypto_keys.md, website/tables/gcp/gcp_logging_sinks.md, website/tables/gcp/gcp_secretmanager_secrets.md, website/tables/gcp/gcp_translate_glossaries.md, website/tables/gcp/gcp_videotranscoder_jobs.md, website/tables/gcp/gcp_vmmigration_source_migrating_vm_clone_jobs.md, website/tables/gcp/gcp_vmmigration_source_migrating_vm_cutover_jobs.md, website/tables/gcp/gcp_vmmigration_source_migrating_vms.md, website/tables/gcp/gcp_vmmigration_sources.md, website/tables/gcp/gcp_workflows_workflows.md
Closes https://github.com/cloudquery/cloudquery/issues/12759
=> fix(resources): Handle previously missing interface fields

.release-please-manifest.json, release-please-config.json
To help with https://github.com/cloudquery/cloudquery/pull/12782
=> chore: Add Jira release please config

plugins/source/jira/.goreleaser.yaml
=> chore: Add Jira go releaser file

website/components/_app.tsx
=> chore(website): Add GTAG

.github/styles/Vocab/Base/accept.txt, website/pages/docs/plugins/sources/jira/_configuration.mdx, website/pages/docs/plugins/sources/jira/overview.mdx, website/pages/docs/plugins/sources/jira/tables.md
=> chore(website): Move Jira to open core

.github/workflows/broken_links_scheduled.yml
I read the wrong docs earlier 🤦
=> chore: Fix Slack notifications

.github/workflows/source_azuredevops.yml, plugins/source/azuredevops/Makefile, plugins/source/azuredevops/test/config.yml, website/tables/azuredevops/azuredevops_core_projects.md
=> chore: Use CLI tables command to generate docs

release-please-config.json
This makes the JSON file syntax valid
=> chore: Fix `release-please-config.json` syntax

plugins/source/azure/dashboards/grafana/asset_inventory.json, plugins/source/azure/dashboards/grafana/compliance.json
Utilize `$__timeFilter` properly & exclude extra columns when building board
=> fix: Azure dashboards

plugins/source/airtable/package-lock.json, plugins/source/airtable/package.json, plugins/source/airtable/src/plugin.ts, plugins/source/airtable/src/tables.ts
Better logging for the discovery phase so it doesn't seem the CLI hangs during that phase.
=> feat: Improve logging of discovery phase

plugins/source/aws/client/account.go, plugins/source/aws/client/aws_sdk.go, plugins/source/aws/client/client.go, plugins/source/aws/client/organizations.go, plugins/source/aws/client/testing.go
Expose functions to other packages for increased testing
=> chore: Internal refactor

website/components/pluginData.tsx
Updates Airtable availability (other changes are formatting since we sometime use single quotes and sometimes double quotes)
=> chore: Update Airtable availability

plugins/source/aws/resources/services/codecommit/repositories.go, plugins/source/aws/resources/services/codecommit/repositories_mock_test.go
Closes https://github.com/cloudquery/cloudquery-issues/issues/584
=> fix: Panic while fetching `aws_codecommit_repositories`

plugins/destination/clickhouse/go.mod, plugins/destination/clickhouse/go.sum, plugins/destination/clickhouse/typeconv/ch/values/values_test.go
Extracted from https://github.com/cloudquery/cloudquery/pull/13262/
=> chore(deps): Update `github.com/cloudquery/plugin-sdk/v4` to v4.5.3

plugins/destination/snowflake/client/migrate.go
Fixes https://github.com/cloudquery/cloudquery/issues/13266.
Tested locally (local registry/path).
=> fix: List columns using current schema during migration

plugins/source/mysql/go.mod, plugins/source/mysql/go.sum, plugins/source/mysql/resources/plugin/plugin_test.go, plugins/source/oracledb/go.mod, plugins/source/oracledb/go.sum, plugins/source/oracledb/resources/plugin/plugin_test.go, plugins/source/test/go.mod, plugins/source/test/go.sum, plugins/source/test/resources/services/testdata.go
Extracted from https://github.com/cloudquery/cloudquery/pull/13262
Part of https://github.com/cloudquery/cloudquery/issues/13153
=> fix(deps): Update `github.com/cloudquery/plugin-sdk/v4` to v4.5.3

plugins/source/aws/policies/cis_v1.5.0/section_1.sql, plugins/source/aws/policies/queries/accessanalyzer/regions_with_no_accessanalyzers.sql, website/tables/aws/aws_accessanalyzer_analyzers.md, website/tables/aws/aws_regions.md
I have implemented CIS AWS v1.5.0 Section 1.16 and 1.20
- Section 1.16
- I use existing one.
- Section 1.20
- I fixed existing query for the current table definition.
=> feat: Implement CIS AWS v1.5.0 Section 1.16 and 1.20

plugins/destination/meilisearch/go.mod, plugins/destination/meilisearch/go.sum
Extracted from https://github.com/cloudquery/cloudquery/pull/13262
Part of https://github.com/cloudquery/cloudquery/issues/13153
=> fix(deps): Update `github.com/cloudquery/plugin-sdk/v4` to v4.5.5

cli/cmd/sync_v3.go
Fixes https://github.com/cloudquery/cloudquery/issues/13281
=> fix: Send delete stale when `--no-migrate` is used

plugins/destination/postgresql/CHANGELOG.md
This was removed in https://github.com/cloudquery/cloudquery/pull/13341
=> chore: Bring back postgres changelog

plugins/source/aws/client/account.go, plugins/source/aws/client/client.go, plugins/source/aws/client/services.go, plugins/source/aws/client/testing.go, plugins/source/aws/resources/services/timestream/databases.go
=> fix: Store AWS config per account

plugins/source/shopify/resources/plugin/client.go
This ensures that the backend state is persisted between syncs
=> fix: Flush state backend so that state is persisted

plugins/destination/s3/client/client.go, plugins/destination/s3/client/spec.go, website/pages/docs/plugins/destinations/s3/_configuration.mdx, website/pages/docs/plugins/destinations/s3/overview.mdx
=> feat: Add `use_path_style`

.github/workflows/scaffold.yml, scaffold/cmd/templates/source/go.mod.tpl, scaffold/go.mod, scaffold/go.sum
Extracted from https://github.com/cloudquery/cloudquery/pull/13492
=> fix(deps): Update `github.com/cloudquery/plugin-sdk/v4` to `v4.6.1`

plugins/destination/elasticsearch/client/delete_stale.go, plugins/destination/elasticsearch/client/write.go
Extracted from https://github.com/cloudquery/cloudquery/pull/13553
=> feat: Bulk all messages in a batch into a single bulk write

plugins/destination/elasticsearch/client/client.go
See https://pkg.go.dev/time#pkg-constants
=> chore: Use predefined format constant

plugins/source/aws/docs/tables/README.md, plugins/source/aws/resources/services/s3/bucket_notification_configurations.go, plugins/source/aws/resources/services/s3/buckets.go, plugins/source/aws/resources/services/s3/buckets_mock_test.go, website/pages/docs/plugins/sources/aws/tables.md, website/tables/aws/aws_s3_bucket_notification_configurations.md, website/tables/aws/aws_s3_buckets.md
Closes https://github.com/cloudquery/cloudquery/issues/13605
=> feat: Add `aws_s3_bucket_notification_configurations` table

plugins/source/aws/docs/tables/README.md, plugins/source/aws/resources/services/s3/bucket_object_lock_configurations.go, plugins/source/aws/resources/services/s3/buckets.go, plugins/source/aws/resources/services/s3/buckets_mock_test.go, website/pages/docs/plugins/sources/aws/tables.md, website/tables/aws/aws_s3_bucket_object_lock_configurations.md, website/tables/aws/aws_s3_buckets.md
=> feat: Add `aws_s3_bucket_object_lock_configurations` table

website/components/_app.tsx
This doesn't need to be behind the cookie consent
=> chore: Bring back simple analytics

plugins/source/postgresql/resources/plugin/plugin_test.go
Adding further test coverage for complex SQL query. The additional coverage covers:
- Adding additional constraints to primary key
- Adding custom primary key constraint name
- Adding additional columns with contraints
=> test: Adding more tests for list tables query

plugins/source/aws/policies/queries/lambda/functions_with_public_egress.sql, website/tables/aws/aws_ec2_route_tables.md, website/tables/aws/aws_lambda_functions.md
Reported on Discord https://discord.com/channels/872925471417962546/1148149878615187456/1148501029386735677
=> fix: Don't reference public schema in policies

website/pages/blog/announcing-cloudquery-aws-event-based-sync-beta.mdx, website/pages/blog/announcing-cloudquery-java-sdk.mdx
fixed the actual publication dates on the most recent blog posts to make them appear in the right order.
=> doc: Fix blog post dates

website/pages/docs/plugins/destinations/mysql/overview.mdx
=> doc: Explicitly note MariaDB incompatability

website/pages/blog/announcing-cloudquery-aws-event-based-sync-beta.mdx, website/pages/docs/plugins/sources/aws/event-based-sync.mdx
=> doc: Update supported events

plugins/source/gcp/resources/services/iam/roles_fetch.go
=> fix: Include `IncludedPermissions` in `gcp_iam_roles`

website/pages/blog/announcing-cloudquery-aws-event-based-sync-beta.mdx
Similar to https://github.com/cloudquery/cloudquery/pull/13820/files/c3f1789a43d168e4322ded2ebaa164c8c70e731b#diff-fe361eb56cbcd18a6ee9c2191da67c0ba0e3177ed4fdbc8578bb8eb296a41320
=> chore: Update announcing-cloudquery-aws-event-based-sync-beta.mdx

plugins/source/aws/policies/queries/secretsmanager/secrets_should_be_rotated_within_a_specified_number_of_days.sql, website/tables/aws/aws_secretsmanager_secrets.md
flipped < sign in the status column
#13774
=> fix: Flipped condition in query for SecretsManager.4

plugins/source/aws/policies/queries/secretsmanager/remove_unused_secrets_manager_secrets.sql, website/tables/aws/aws_secretsmanager_secrets.md
=> fix: Flipped condition on secrets manager policy

.github/workflows/publish_plugin_to_hub.yml
Fixes https://github.com/cloudquery/cloud/issues/303 (internal issue).
=> chore: Add publish to Hub CI workflow

.github/workflows/publish_plugin_to_hub.yml, plugins/source/test/README.md
Woops, fixes https://github.com/cloudquery/cloudquery/actions/runs/6248143505/job/16962157306
=> fix: Save token to file

.github/workflows/publish_plugin_to_hub.yml, plugins/source/test/README.md
=> fix: Create token directory before creating file

.github/workflows/publish_plugin_to_hub.yml
=> chore: Publish plugins to Hub as non drafts

.github/workflows/publish_plugin_to_hub.yml
Follow up to https://github.com/cloudquery/plugin-sdk/pull/1238
=> chore(ci): Pass plugin kind to package command

.github/workflows/publish_plugin_to_hub.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/13997
=> chore(ci): Update CI to support new publish API

plugins/source/aws/docs/tables/README.md, plugins/source/aws/resources/plugin/tables.go, plugins/source/aws/resources/services/ec2/vpc_endpoint_connections.go, plugins/source/aws/resources/services/ec2/vpc_endpoint_connections_mock_test.go, website/pages/docs/plugins/sources/aws/tables.md, website/tables/aws/aws_ec2_vpc_endpoint_connections.md
=> feat: Add support for AWS EC2 VPC Endpoint Connections

.github/workflows/publish_plugin_to_hub.yml
Trying to fix publishing to the Hub https://github.com/cloudquery/cloudquery/actions/runs/6309661411/job/17169664291#step:8:10
=> chore: Update CLI version in Hub publishing

.github/workflows/publish_plugin_to_hub.yml
This should fix source publishing in our CI
=> chore: Update CLI when in Hub publishing

.github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml
Fixes https://github.com/cloudquery/cloud/issues/394 (internal issue).
I didn't add `GO111MODULE=on` as that's the default in newer Go versions
=> chore: Add cross compile Hub publishing workflows

plugins/source/googleanalytics/client/client.go
Same as https://github.com/cloudquery/cloudquery/pull/14115
Required for the package command to work
=> fix: Handle NoConnection

plugins/source/datadog/client/mocks/dashboards_api.go, plugins/source/datadog/client/mocks/monitors_api.go, plugins/source/datadog/client/mocks/notebooks_api.go, plugins/source/datadog/client/mocks/service_level_objective_corrections_api.go, plugins/source/datadog/client/mocks/service_level_objectives_api.go, plugins/source/datadog/client/mocks/synthetics_api.go, plugins/source/datadog/client/mocks/users_api.go, plugins/source/datadog/client/services/dashboards_api.go, plugins/source/datadog/client/services/monitors_api.go, plugins/source/datadog/client/services/notebooks_api.go, plugins/source/datadog/client/services/service_level_objective_corrections_api.go, plugins/source/datadog/client/services/service_level_objectives_api.go, plugins/source/datadog/client/services/synthetics_api.go, plugins/source/datadog/client/services/users_api.go, plugins/source/datadog/go.mod, plugins/source/datadog/go.sum, plugins/source/datadog/resources/services/users/users.go, plugins/source/datadog/resources/services/users/users_mock_test.go, website/tables/datadog/datadog_monitors.md
fixes: https://github.com/cloudquery/cloudquery/issues/14187
=> fix!: Add pagination support for list users

website/pages/blog/creating-a-new-js-plugin.mdx
This fixes a typo in the blog post title
=> chore: Fix typo

website/pages/docs/plugins/destinations/sqlite/_configuration.mdx, website/pages/docs/plugins/sources/hackernews/_configuration.mdx, website/pages/docs/plugins/sources/homebrew/_configuration.mdx
Testing using:
```yaml
kind: source
spec:
name: "homebrew"
path: "cloudquery/homebrew"
registry: cloudquery
version: "v3.0.10"
tables: ["*"]
destinations: [sqlite]
---
kind: source
spec:
name: "hackernews"
path: "cloudquery/hackernews"
registry: cloudquery
version: "v3.0.12"
tables: ["*"]
destinations: [sqlite]
---
spec:
name: sqlite
path: cloudquery/sqlite
registry: cloudquery
version: v2.4.11
spec:
connection_string: ./db.sql
```
=> chore: Change hackernews, homebrew, sqlite to cloudquery registry

plugins/source/gcp/client/spec/spec.go
=> chore: Remove comment

.github/workflows/publish_plugin_to_hub.yml, .github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/14437. Renovate wasn't too happy about the double quotes
=> chore: Fix CLI version in Hub workflows

.github/workflows/clean_actions_cache.yml
Related to https://github.com/cloudquery/cloudquery/issues/14464
=> chore: Use `cq-bot` token in cache cleanup

plugins/source/aws/client/spec/schema.json, plugins/source/aws/go.mod, plugins/source/aws/go.sum, plugins/source/gcp/go.mod, plugins/source/gcp/go.sum, plugins/source/oracle/go.mod, plugins/source/oracle/go.sum
https://github.com/cloudquery/codegen/pull/51
=> chore: Use `-` for clashing names in JSON schema

plugins/destination/snowflake/client/client.go, plugins/destination/snowflake/client/write.go
Shouldn't attempt to `CREATE STAGE` and `CREATE FORMAT` before migrate starts so we can have `cloudquery migrate` with fewer permissions required.
=> fix: Late setup for format and stage

plugins/source/googleanalytics/Makefile, plugins/source/googleanalytics/client/client.go, plugins/source/googleanalytics/client/fetch.go, plugins/source/googleanalytics/client/metric.go, plugins/source/googleanalytics/client/metric_test.go, plugins/source/googleanalytics/client/oauth.go, plugins/source/googleanalytics/client/oauth_test.go, plugins/source/googleanalytics/client/report.go, plugins/source/googleanalytics/client/report_test.go, plugins/source/googleanalytics/client/schema.json, plugins/source/googleanalytics/client/schemagen/main.go, plugins/source/googleanalytics/client/spec.go, plugins/source/googleanalytics/client/spec_test.go, plugins/source/googleanalytics/go.mod, plugins/source/googleanalytics/go.sum
Closes #14451
See related https://github.com/cloudquery/jsonschema/pull/7
=> feat: Add JSON schema

README.md
*Safe to merge PR*  
added `license`, `go report`, `ci` and `latest release` status badges to readme to improve docs quality.  
Take a look at the edited readme in [my fork](https://github.com/R3DRUN3/cloudquery/blob/main/README.md).
=> doc: Status badges to readme

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/new_destination_plugin.yml, .github/ISSUE_TEMPLATE/new_resource.yml, .github/ISSUE_TEMPLATE/new_source_plugin.yml, .github/pr_labeler.yml
Part of https://github.com/cloudquery/cloudquery/issues/14545
=> chore: Update labels

plugins/source/azure/Makefile, plugins/source/azure/client/client.go, plugins/source/azure/client/spec/gen/main.go, plugins/source/azure/client/spec/schema.json, plugins/source/azure/client/spec/spec.go, plugins/source/azure/client/spec/spec_test.go, plugins/source/azure/client/testing.go, plugins/source/azure/go.mod, plugins/source/azure/go.sum, plugins/source/azure/resources/plugin/client.go, plugins/source/azure/resources/plugin/plugin.go
Closes #14553
Note [`uniqueItems`](https://json-schema.org/draft/2020-12/json-schema-validation#section-6.4.3) feature that's useful for the `subscriptions` & `skip_subscriptions` validation.
=> feat: Add JSON schema for plugin spec

website/theme.config.tsx
=> chore: Add missing install Slack app link

plugins/source/k8s/resources/plugin/plugin.go
Follow-up to https://github.com/cloudquery/cloudquery/pull/14715
=> fix: Fix k8s plugin metadata

plugins/destination/clickhouse/client/spec/engine.go, plugins/destination/clickhouse/client/spec/gen/main.go, plugins/destination/clickhouse/client/spec/schema.json, plugins/destination/clickhouse/client/spec/spec.go, plugins/destination/clickhouse/go.mod, plugins/destination/clickhouse/go.sum, website/pages/docs/plugins/destinations/clickhouse/overview.md
Closes https://github.com/cloudquery/cloudquery/issues/14616
=> fix: Update `engine.parameters` validation

website/pages/docs/developers/creating-new-plugin/python-source.mdx
Updates the Python Source Plugin page to add the Youtube Video and links to the Template Repo
=> doc: Python Plugin video and template links

.github/workflows/source_square.yml
Same as https://github.com/cloudquery/plugin-pb-python/pull/31
=> chore: Pin Python version to 3.11

website/tables/slack/slack_conversation_bookmarks.md, website/tables/slack/slack_conversation_histories.md, website/tables/slack/slack_conversation_members.md, website/tables/slack/slack_conversation_replies.md, website/tables/slack/slack_conversations.md, website/tables/slack/slack_files.md, website/tables/slack/slack_teams.md, website/tables/slack/slack_user_presences.md, website/tables/slack/slack_users.md
Discovered while working on https://github.com/cloudquery/cloudquery-issues/issues/597 (internal issue).
The Slack plugin tables we out of date
=> chore: Update Slack tables

website/tables/gandi/gandi_certificate_packages.md, website/tables/gandi/gandi_certificates.md, website/tables/gandi/gandi_domain_dnssec_keys.md, website/tables/gandi/gandi_domain_glue_records.md, website/tables/gandi/gandi_domain_livedns.md, website/tables/gandi/gandi_domain_web_redirections.md, website/tables/gandi/gandi_domains.md, website/tables/gandi/gandi_livedns_domain_snapshots.md, website/tables/gandi/gandi_livedns_domains.md, website/tables/gandi/gandi_simplehosting_instance_vhosts.md, website/tables/gandi/gandi_simplehosting_instances.md
Same as https://github.com/cloudquery/cloudquery/pull/15049 for Gandi
=> chore: Update Gandi tables

website/tables/mixpanel/mixpanel_annotations.md, website/tables/mixpanel/mixpanel_cohort_members.md, website/tables/mixpanel/mixpanel_cohorts.md, website/tables/mixpanel/mixpanel_engage_revenues.md, website/tables/mixpanel/mixpanel_export_events.md, website/tables/mixpanel/mixpanel_funnel_reports.md, website/tables/mixpanel/mixpanel_funnels.md
Same as https://github.com/cloudquery/cloudquery/pull/15049 for Mixpanel
=> chore: Update Mixpanel tables

plugins/destination/snowflake/client/spec.go, plugins/destination/snowflake/client/write.go, website/pages/docs/plugins/destinations/snowflake/overview.md
Should help with https://github.com/cloudquery/cloudquery/issues/15041
=> feat: Add option to leave files `leave_stage_files` after PUT

website/pages/blog/announcing-cloudquery-new-hub.mdx
Updated the Hub announcement based on the latest notes in Notion
=> doc: Update wording about previous plugin versions

plugins/source/jira/resources/boards/boards.go, plugins/source/jira/resources/issues/issues.go
Fixes pagination of issues and boards reported on Discord
=> fix: Fix pagination of Jira Issues and Boards

.github/styles/Vocab/Base/accept.txt, website/pages/docs/developers/_meta.json, website/pages/docs/developers/publishing-a-plugin-to-the-hub.md
Formalizes https://github.com/koltyakov/cq-source-sharepoint/issues/26#issuecomment-1788007192
Fixes cloudquery/cloudquery-issues#609 (internal issue)
=> feat: Add docs on how to publish plugins to the Hub

website/pages/blog/product-updates-9.mdx
Adding utm tags for the latest campaign to the hub and signup form links.
=> doc: Add utm tags to the most important links in the November 2023 newsletter

website/pages/docs/developers/publishing-a-plugin-to-the-hub.md
=> doc: Update publishing-a-plugin-to-the-hub.md

plugins/source/oracle/client/client.go, plugins/source/oracle/client/multiplex.go
Fixes https://github.com/cloudquery/cloudquery/issues/14279
=> fix: Set global retry policy to `common.DefaultRetryPolicy`

website/pages/docs/plugins/sources/googleads/configuration.md
=> doc: Update configuration.md to fix broken link

website/pages/blog/aws-kms-key-grants-deep-dive.mdx, website/pages/blog/aws-priv-esc-identity-center.mdx, website/pages/blog/finding-enabled-s3-acls-and-disabled-s3-block-public-access.mdx, website/pages/blog/migrating-from-v0-to-v1.mdx, website/pages/blog/product-updates-6.mdx, website/pages/docs/glossary/what-is-infrastructure-data-lake.mdx, website/pages/how-to-guides/aws-resource-limits-and-service-quotas.mdx, website/pages/how-to-guides/how-to-load-infrastructure-data-into-athena.mdx
Fixes https://github.com/cloudquery/cloudquery/actions/runs/6754698378/job/18362442381.
Follow up to https://github.com/cloudquery/cloudquery/pull/15124.
Uses direct links to the Hub instead of relying on the redirects. This should have users the additional hop and make our broken links checker happy
=> chore: Update table links to link to the Hub directly

cli/cmd/addon_publish.go, cli/cmd/plugin_publish.go, website/pages/docs/reference/cli/cloudquery_addon_publish.md, website/pages/docs/reference/cli/cloudquery_plugin_publish.md
Extracted from https://github.com/cloudquery/cloudquery/pull/15177
=> fix: Better publish command messages

.github/pr_labeler.yml, release-please-config.json
refs: https://github.com/cloudquery/cloudquery/pull/15194
refs: https://github.com/cloudquery/cloudquery/pull/15192
refs: https://github.com/cloudquery/cloudquery/pull/15191
refs: https://github.com/cloudquery/cloudquery/pull/15190
=> chore: Cleanup pr_labeler and release please

website/components/pluginData.tsx, website/vercel.json
=> chore: Update vercel.json redirects

website/vercel.json
We're missing this redirect. I'll go over the 404 report from our analytics to see if something else comes up
=> fix: Add missing launchdarkly redirects

cli/cmd/addon_download.go, cli/internal/auth/team.go
follow up to https://github.com/cloudquery/cloudquery/pull/15278
=> fix: Simplify `addon download` team reading

.github/workflows/release_summary.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/15266
=> chore: Fix Release summary workflow

plugins/source/aws/docs/event-based-sync.md
Closes https://github.com/cloudquery/cloudquery-issues/issues/900
=> fix: Event-based sync doc

plugins/source/aws/resources/plugin/plugin.go, plugins/source/aws/resources/plugin/tables.go
=> feat: Single title transformation pass

website/pages/blog/aws-log4j-and-finding-unrestricted-outbound-access.mdx
GovCert removed the blogs from their Website and archived them on GitHub. See https://www.ncsc.admin.ch/govcert
=> chore: Fix broken link to govcert blog

CODE_OF_CONDUCT.md, README.md
Closes https://github.com/cloudquery/cloudquery-issues/issues/913
=> chore: Update contribution guide

cli/internal/auth/logout.go
Closes https://github.com/cloudquery/cloudquery/issues/15392
=> fix: Logout should unset team

website/vercel.json
Part of the move to the new landing page. This moves some redirects we had in Cloudflare to `vercel.json`
=> chore: Migrate cloudflare redirects

plugins/source/aws/test/policy_cq_config.yml, plugins/source/azure/test/policy_cq_config.yml, plugins/source/gcp/test/policy_cq_config.yml, plugins/source/k8s/test/policy_cq_config.yml
Kind of related to https://github.com/cloudquery/plugin-pb-go/pull/165 since these tests are broken at the moment
=> chore: Update policy tests to use `cloudquery` registry

website/vercel.json
Looks like we missed those in the migration
=> chore: Add missing redirects

release-please-config.json
Removes releases for the test plugin in preparation to make that plugin open core
=> chore: Disable publishing for open source test plugin

website/components/_app.tsx
Should fix https://github.com/cloudquery/cloudquery/actions/runs/6995413963/job/19030234156#step:4:258
=> chore: Fix canonical URLs

.github/workflows/publish_plugin_to_hub.yml
=> chore: Don't publish tables file with docs

website/pages/blog/announcing-cloudquery-marketplace.mdx
@pilvikala for your review - I want to start early registration for folks that want to sell on our Hub (marketplace).
=> chore: Announce CQ Marketplace

release-please-config.json
Preparing to release this plugin as open core
=> chore: Disable publishing for open source AWS plugin

release-please-config.json
Same as https://github.com/cloudquery/cloudquery/pull/15500 for GCP
=> chore: Disable publishing for open source GCP plugin

website/pages/blog/product-updates-10.mdx
Updating bitlinks - used incorrect ones in the previous commit (incorrect utm tags)
=> doc: Fix links in the newsletter

.github/workflows/broken_links_scheduled.yml
Fixes https://github.com/cloudquery/cloudquery/actions/runs/7100474819/job/19326636971#step:4:289
=> chore: Update `broken_links_scheduled.yml`

plugins/source/bitbucket/app/build.gradle
For Bitbucket this should fix the error message when launching.
Should fix https://github.com/cloudquery/cloudquery/issues/15546
=> fix: Upgrade SDK

cli/go.mod, cli/go.sum
Needed so the code in https://github.com/cloudquery/cloudquery/blob/4e2ffc1a11af9505049429d332657938e097e991/cli/cmd/plugin_publish.go#L214 picks up the `is_paid` field
=> feat: Include `is_paid` field when publishing tables to the Hub

.github/workflows/broken_links.yml, .github/workflows/broken_links_scheduled.yml, website/components/Footer.tsx, website/pages/_meta.json, website/vercel.json
=> chore: Add redirect for blog

.github/renovate.json5
This should help us avoid most `git` conflicts with the private source version.
We can still update manually if we need it for a specific case.
=> chore: Ignore Go mod automatic dependencies updates for AWS, Azure, GCP

.github/workflows/broken_links_scheduled.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/15580
=> chore: Add missing `\` to broken links check

plugins/source/github/client/client.go, plugins/source/github/client/spec.go, plugins/source/github/docs/_configuration.md, plugins/source/github/docs/overview.md
Fixes https://github.com/cloudquery/cloudquery/issues/15399
Somehow related to https://github.com/cloudquery/cloudquery/issues/13304 which would be a bigger effort.
Added this with a default of `false` to avoid a breaking change. We might want to change the default to `true` at some point
=> feat: Add option to skip archived repositories

plugins/source/aws/resources/services/iam/last_accessed_details.go
=> feat: Improve backoff between requests for `ServiceLastAccessedDetails`

plugins/source/azure/docs/_authentication.md, plugins/source/azure/docs/overview.md
This has been popping up in Discord recently quite a bit. Fixes https://github.com/cloudquery/cloudquery/issues/13192
=> chore: Reference all auth methods in Azure docs

website/pages/_meta.json
Avoids the extra redirect from `https://cloudquery.io` to `https://www.cloudquery.io`
=> chore: Link to www instead of top level domain

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
Adds more information on the open-core model
=> chore: Add open-core notes in PR template and contributing guide

.github/workflows/source_airtable.yml, plugins/source/airtable/.dockerignore, plugins/source/airtable/.gitignore, plugins/source/airtable/Dockerfile, plugins/source/airtable/README.md, plugins/source/airtable/docs/_authentication.md, plugins/source/airtable/docs/_configuration.md, plugins/source/airtable/docs/overview.md, plugins/source/airtable/package-lock.json, plugins/source/airtable/package.json, plugins/source/airtable/src/main.ts, plugins/source/airtable/src/plugin.ts, plugins/source/airtable/src/serve.test.ts, plugins/source/airtable/src/serve.ts, plugins/source/airtable/tsconfig.json
Updates the JavaScript SDK for the Airtable plugin and adds package command support. This is a breaking changes since it requires Node.js 20
feat: Add package command
chore: Require Node.js 20
BREAKING-CHANGE: Require Node.js 20
=> feat: Add package command

plugins/source/cloudflare/go.mod, plugins/source/cloudflare/go.sum
Follow up to https://github.com/cloudquery/cloudquery/pull/15777
=> chore: Update SDK

cli/internal/specs/v0/destination.go, cli/internal/specs/v0/destination_test.go, cli/internal/specs/v0/metadata.go, cli/internal/specs/v0/source.go, cli/internal/specs/v0/source_test.go, cli/internal/specs/v0/spec_reader_test.go
Extracted from https://github.com/cloudquery/cloudquery/pull/15998
=> refactor: Extract common plugin spec fields into metadata struct

.github/renovate.json5
With the current configuration renovate groups JavaScript Plugin SDK updates with Website updates. This PR fixes it
=> chore: Fix Website dependency grouping

plugins/source/gcp/CONTRIBUTING.md
removes references to codegen.
closes: #11636
=> doc: Update CONTRIBUTING guide

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/new_destination_plugin.yml, .github/ISSUE_TEMPLATE/new_resource.yml, .github/ISSUE_TEMPLATE/new_source_plugin.yml
Update templates to reflect current status of accepting PRs
=> chore: Update templates

cli/cmd/install.go, cli/go.mod, cli/go.sum
Needs https://github.com/cloudquery/plugin-pb-go/pull/218
=> fix: Handle Docker no-login or no-team errors

cli/cmd/addon_download.go, cli/cmd/addon_publish.go, cli/cmd/analytics.go, cli/cmd/login.go, cli/cmd/plugin_docs_download.go, cli/cmd/plugin_docs_upload.go, cli/cmd/plugin_publish.go, cli/cmd/root.go, cli/cmd/switch.go, cli/internal/api/client.go, cli/internal/env/env.go, cli/internal/team/team.go
Follow up to https://github.com/cloudquery/cloudquery/pull/16230 with some more cleanup
=> refactor: Remove duplication for getting API env variable value

.github/workflows/cli.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/16231
=> chore: Add buildx to validate release

.github/workflows/cli.yml, .github/workflows/release_cli.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/16303
=> chore: Setup QEMU

.github/ISSUE_TEMPLATE/new_resource.yml
This template is broken at the moment since the YAML is not valid, see 
https://github.com/cloudquery/cloudquery/blob/a8d71793ee2e392e306f3156f5b8b5b8cd6ca80c/.github/ISSUE_TEMPLATE/new_resource.yml
=> chore: Fix `new_resource.yml` issue template

.github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml, .github/workflows/release_plugin_dest_duckdb.yml, .github/workflows/release_plugin_dest_snowflake.yml, .github/workflows/release_plugin_dest_sqlite.yml, plugins/destination/duckdb/.goreleaser.yaml, plugins/destination/duckdb/go.mod, plugins/destination/duckdb/go.sum, plugins/destination/duckdb/main.go, plugins/destination/snowflake/.goreleaser.yaml, plugins/destination/snowflake/go.mod, plugins/destination/snowflake/go.sum, plugins/destination/snowflake/main.go, plugins/destination/sqlite/.goreleaser.yaml, plugins/destination/sqlite/go.mod, plugins/destination/sqlite/go.sum, plugins/destination/sqlite/main.go
Fixes https://github.com/cloudquery/cloudquery-issues/issues/966
Requires https://github.com/cloudquery/plugin-sdk/pull/1492
=> fix: Don't use `CGO` unless specifically selected to

.github/ISSUE_TEMPLATE/new_destination_plugin.yml
The indentation for this issue template was broken
=> chore: Fix new destination plugin issue template

plugins/source/alicloud/Makefile, plugins/source/alicloud/client/schema.json, plugins/source/alicloud/client/spec.go, plugins/source/alicloud/client/spec/gen/main.go, plugins/source/alicloud/client/spec_test.go, plugins/source/alicloud/go.mod, plugins/source/alicloud/go.sum, plugins/source/alicloud/resources/plugin/plugin.go
- Add `gen-spec-schema` to Makfile
- Adding spec generation code
- Adding test cases
- Configure plugin to use JSON schema
fixes: https://github.com/cloudquery/cloudquery/issues/16334
=> feat: Adding JSON schema for alibaba source plugin

plugins/source/cloudflare/Makefile, plugins/source/cloudflare/client/schema.json, plugins/source/cloudflare/client/spec.go, plugins/source/cloudflare/client/spec/gen/main.go, plugins/source/cloudflare/client/spec_test.go, plugins/source/cloudflare/go.mod, plugins/source/cloudflare/go.sum, plugins/source/cloudflare/resources/plugin/plugin.go
fixes: https://github.com/cloudquery/cloudquery/issues/16335
=> feat: Adding JSON Schema support to Cloudflare

plugins/source/cloudflare/Makefile, plugins/source/datadog/Makefile, plugins/source/datadog/client/schema.json, plugins/source/datadog/client/spec.go, plugins/source/datadog/client/spec/gen/main.go, plugins/source/datadog/client/spec_test.go, plugins/source/datadog/go.mod, plugins/source/datadog/go.sum, plugins/source/datadog/resources/plugin/plugin.go
fixes: https://github.com/cloudquery/cloudquery/issues/16336
=> feat: Add JSON schema support to Datadog source plugin

plugins/destination/test/Makefile, plugins/destination/test/client/schema.json, plugins/destination/test/client/spec.go, plugins/destination/test/client/spec/gen/main.go, plugins/destination/test/client/spec_test.go, plugins/destination/test/go.mod, plugins/destination/test/go.sum, plugins/destination/test/main.go
Implements https://github.com/cloudquery/cloudquery/issues/16352
=> feat: Add JSON Schema to Test destination plugin

.github/workflows/dest_neo4j.yml, plugins/destination/neo4j/Makefile, plugins/destination/neo4j/client/schema.json, plugins/destination/neo4j/client/spec.go, plugins/destination/neo4j/client/spec/gen/main.go, plugins/destination/neo4j/client/spec_test.go, plugins/destination/neo4j/go.mod, plugins/destination/neo4j/go.sum, plugins/destination/neo4j/main.go
Implements https://github.com/cloudquery/cloudquery/issues/16351
=> feat: Add JSON schema to Neo4J destination plugin

cli/cmd/plugin_publish.go, cli/go.mod, cli/go.sum, cli/internal/publish/plugins.go
~~Goes with https://github.com/cloudquery/cloudquery-api-go/pull/114~~
=> feat: Support adding a spec json schema to plugin versions

plugins/destination/sqlite/client/migrate.go
Update migration to skip unique constraint changes
=> fix: Update migration to skip unique constraint changes

plugins/source/gitlab/Makefile, plugins/source/gitlab/client/schema.json, plugins/source/gitlab/client/spec.go, plugins/source/gitlab/client/spec/gen/main.go, plugins/source/gitlab/client/spec_test.go, plugins/source/gitlab/go.mod, plugins/source/gitlab/go.sum, plugins/source/gitlab/resources/plugin/plugin.go
fixes: https://github.com/cloudquery/cloudquery/issues/16361
=> feat: Add JSON schema support for GitLab

.github/workflows/dest_elasticsearch.yml, plugins/destination/elasticsearch/Makefile, plugins/destination/elasticsearch/client/schema.json, plugins/destination/elasticsearch/client/spec.go, plugins/destination/elasticsearch/client/spec/gen/main.go, plugins/destination/elasticsearch/client/spec_test.go, plugins/destination/elasticsearch/go.mod, plugins/destination/elasticsearch/go.sum, plugins/destination/elasticsearch/main.go
Closes https://github.com/cloudquery/cloudquery/issues/16448
=> feat: Add JSON schema to `elasticsearch` destination

.github/workflows/dest_bigquery.yml, plugins/destination/bigquery/Makefile, plugins/destination/bigquery/client/schema.json, plugins/destination/bigquery/client/spec.go, plugins/destination/bigquery/client/spec/gen/main.go, plugins/destination/bigquery/client/spec_test.go, plugins/destination/bigquery/go.mod, plugins/destination/bigquery/go.sum, plugins/destination/bigquery/main.go
Closes https://github.com/cloudquery/cloudquery/issues/16447
=> feat: Add JSON schema to bigquery destination

website/pages/docs/advanced-topics/rate-limiting.md
=> fix: Update rate-limiting.md

plugins/destination/postgresql/client/migrate.go
Prior to this PR if a user was migrating from component PKs to `_cq_id` the `NOT NULL` on the old PKs would remain... This would mean that the next migration would find a diff that is unable to be migrated
=> fix: Remove `NOT NULL` when moving to `_cq_id`

plugins/source/bitbucket/app/build.gradle
Follow-up for package renaming
=> fix: Use `io.cloudquery:plugin-sdk-java`

website/pages/how-to-guides/open-source-cspm.mdx
This is an update for our Open Source CSPM "How To" guide that reflects the recent changes to policies.
=> doc: Updated how-to for open source CSPM

plugins/source/aws/docs/tables/aws_ssm_parameters.md, plugins/source/aws/resources/services/ssm/parameters.go, plugins/source/aws/resources/services/ssm/parameters_mock_test.go
Add tags for AWS Systems Manager Parameters
=> feat: Add tags for AWS Systems Manager Parameters

cli/go.mod
Not sure why our bot did this in https://github.com/cloudquery/cloudquery/pull/16539/files, but we don't need it
=> chore: Revert toolchain update

website/pages/how-to-guides/open-source-cspm.mdx
Should fix https://github.com/cloudquery/cloudquery/actions/runs/7829313019
=> chore: Use redirect target to avoid the extra hop in dbt installation link

plugins/source/bitbucket/app/build.gradle, plugins/source/bitbucket/app/src/main/java/bitbucket/BitbucketPlugin.java, plugins/source/bitbucket/app/src/main/java/bitbucket/client/configuration/Spec.java
Closes https://github.com/cloudquery/cloudquery/issues/16374
=> feat: Add JSON schema to `bitbucket` source plugin

.github/styles/config/vocabularies/Base/accept.txt, website/pages/privacy.mdx
Added Posthog to our Privacy Policy
=> doc: Add Posthog to privacy policy

plugins/source/typeform/docs/overview.md, plugins/source/typeform/plugin/client/client.py, plugins/source/typeform/plugin/plugin.py
Closes https://github.com/cloudquery/cloudquery/issues/16460
=> feat: Add JSON Schema to `typeform` source plugin

plugins/source/square/docs/overview.md, plugins/source/square/plugin/client/client.py, plugins/source/square/plugin/plugin.py
Closes https://github.com/cloudquery/cloudquery/issues/16458
=> feat: Add JSON schema to `square` source plugin spec

plugins/destination/duckdb/client/client.go, plugins/destination/duckdb/client/write.go
Fixes https://github.com/cloudquery/cloudquery/issues/15551
=> feat: Add user agent if MotherDuck connection

plugins/destination/bigquery/go.mod, plugins/destination/clickhouse/go.mod, plugins/destination/duckdb/go.mod, plugins/destination/elasticsearch/go.mod, plugins/destination/gremlin/go.mod, plugins/destination/meilisearch/go.mod, plugins/destination/mongodb/go.mod, plugins/destination/mysql/go.mod, plugins/destination/neo4j/go.mod, plugins/destination/sqlite/go.mod, plugins/destination/test/go.mod, plugins/source/alicloud/go.mod, plugins/source/awspricing/go.mod, plugins/source/cloudflare/go.mod, plugins/source/datadog/go.mod, plugins/source/digitalocean/go.mod, plugins/source/firestore/go.mod, plugins/source/github/go.mod, plugins/source/gitlab/go.mod, plugins/source/hackernews/go.mod, plugins/source/hubspot/go.mod, plugins/source/k8s/go.mod, plugins/source/notion/go.mod, plugins/source/okta/go.mod, plugins/source/oracle/go.mod, plugins/source/pagerduty/go.mod, plugins/source/test/go.mod
This was done as a part of https://github.com/cloudquery/cloudquery/pull/16669/files and not needed.
I'll check why we started seeing this
=> chore: Revert Go toolchain

plugins/source/gcp/docs/tables/gcp_compute_projects.md, plugins/source/gcp/resources/services/compute/projects.go
Currently the GCP projects have no description, so updating this to match other resources
=> fix(resources): Link to gcp project description

cli/cmd/root.go, website/pages/docs/reference/cli/cloudquery.md, website/pages/docs/reference/cli/cloudquery_addon.md, website/pages/docs/reference/cli/cloudquery_addon_download.md, website/pages/docs/reference/cli/cloudquery_addon_publish.md, website/pages/docs/reference/cli/cloudquery_login.md, website/pages/docs/reference/cli/cloudquery_logout.md, website/pages/docs/reference/cli/cloudquery_migrate.md, website/pages/docs/reference/cli/cloudquery_plugin.md, website/pages/docs/reference/cli/cloudquery_plugin_install.md, website/pages/docs/reference/cli/cloudquery_plugin_publish.md, website/pages/docs/reference/cli/cloudquery_switch.md, website/pages/docs/reference/cli/cloudquery_sync.md, website/pages/docs/reference/cli/cloudquery_tables.md
=> fix: Document log levels

.release-please-manifest.json, plugins/destination/motherduck/CHANGELOG.md
Reverts cloudquery/cloudquery#16807
=> chore: Revert "chore(main): Release plugins-destination-motherduck v1.0.0"

.github/workflows/publish_plugin_to_hub.yml, .github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_motherduck.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml
=> chore: Motherduck publish workflow

.github/renovate.json5
We should handle this update manually
=> chore: Don't update duckdb client for motherduck dest

plugins/destination/motherduck/go.mod, plugins/destination/motherduck/go.sum
Reverts cloudquery/cloudquery#16810
=> chore: Revert "fix(deps): Update module github.com/marcboeker/go-duckdb to v1.6.1"

plugins/destination/motherduck/client/schema.json, plugins/destination/motherduck/client/spec.go, plugins/destination/motherduck/docs/_configuration.md
Iterate on _configuration.md and json schema.
=> chore: MotherDuck config updates

plugins/source/okta/client/client.go, plugins/source/okta/client/errors.go, plugins/source/okta/client/testing.go, plugins/source/okta/client/transformers.go, plugins/source/okta/docs/_configuration.md, plugins/source/okta/docs/tables/okta_users.md, plugins/source/okta/go.mod, plugins/source/okta/go.sum, plugins/source/okta/resources/plugin/client.go, plugins/source/okta/resources/services/applications/applications.go, plugins/source/okta/resources/services/applications/applications_mock_test.go, plugins/source/okta/resources/services/applications/group_assignments.go, plugins/source/okta/resources/services/applications/users.go, plugins/source/okta/resources/services/fakes/group.go, plugins/source/okta/resources/services/fakes/user.go, plugins/source/okta/resources/services/groups/groups.go, plugins/source/okta/resources/services/groups/groups_mock_test.go, plugins/source/okta/resources/services/groups/users.go, plugins/source/okta/resources/services/users/users.go, plugins/source/okta/resources/services/users/users_mock_test.go
instead of: https://github.com/cloudquery/cloudquery/pull/16831
=> feat: Upgrade Okta SDK to v4

website/pages/docs/developers/creating-new-plugin/javascript-source.mdx
Fixes https://github.com/cloudquery/cloudquery/actions/runs/8037794424/job/21953042758#step:4:122
=> chore: Update link to Node.js starting guide

.github/renovate.json5
We should handle this manually with coordination with MotherDuck support
=> chore: Disable automatic updates for DuckDB lib

plugins/destination/gcs/client/client.go, plugins/destination/gcs/client/spec/schema.json, plugins/destination/gcs/client/spec/spec.go
Otherwise we can't use this plugin in managed syncs.
=> feat: Support authenticating via `service_account_key_json`

plugins/destination/neo4j/docs/_configuration.md
Adding environment variables to guide the managed sync creation workflow.
=> fix: Adding environment variables to config

plugins/source/gitlab/docs/_configuration.md
Similar to https://github.com/cloudquery/cloudquery/pull/16944
=> fix: Use env var replacement in example configuration

cli/internal/transformer/transformer.go
=> refactor: Improve performance by reducing allocations

.github/workflows/deps_trigger_gen.yml
Current code has a syntax error https://github.com/cloudquery/cloudquery-private/actions/runs/8109948590/job/22166179264#step:3:25
Follow up to https://github.com/cloudquery/cloudquery/pull/16891
=> fix: Get dirname using path module

.release-please-manifest.json, plugins/source/typeform/CHANGELOG.md, plugins/source/typeform/plugin/plugin.py
Reverts cloudquery/cloudquery#16993
Similar to https://github.com/cloudquery/cloudquery/pull/17025
=> chore: Revert "chore(main): Release plugins-source-typeform v1.3.2"

.release-please-manifest.json, plugins/source/square/CHANGELOG.md
Reverts cloudquery/cloudquery#16992
Similar to https://github.com/cloudquery/cloudquery/pull/17025
=> chore: Revert "chore(main): Release plugins-source-square v1.2.2"

cli/internal/publish/plugins.go
Similar to https://github.com/cloudquery/plugin-pb-go/pull/272
=> fix: Enable docker API negotiation

website/pages/docs/advanced-topics/_meta.json, website/pages/docs/advanced-topics/using-an-offline-license.md
https://docs-7psf8b120-cloudquery.vercel.app/docs/advanced-topics/using-an-offline-license
=> feat: Document how to use an offline license

plugins/destination/postgresql/client/migrate.go
=> chore: Remove repetitive word

.github/workflows/publish_plugin_to_hub.yml
Closes https://github.com/cloudquery/cloudquery-issues/issues/1396
=> fix: Replace dashes with underscores during publish

website/pages/how-to-guides/attack-surface-management-with-graph.mdx, website/pages/how-to-guides/open-source-cspm.mdx
I have updated our most visited how-to guides with a mention of the Managed Syncs.
=> doc: Mention managed syncs on the most visited how-to guides

.github/workflows/publish_plugin_to_hub.yml
=> fix(ci): Split tag properly

.github/workflows/publish_plugin_to_hub.yml
=> fix(ci): Undash every plugin type

website/pages/_meta.json
follow up on #17230 - the top navigation URL did not get updated
=> fix: Update top navigation CTA

plugins/source/oracle/client/configProvider.go
Follow up to https://github.com/cloudquery/cloudquery/pull/17242#discussion_r1534019195 🙈
=> fix: Env var reference

plugins/destination/s3/docs/_authentication.md
Update _authentication.md docs
=> fix: Update `_authentication.md` docs

plugins/source/aws/docs/tables/aws_rds_option_groups.md, plugins/source/aws/docs/tables/aws_rds_subnet_groups.md, plugins/source/aws/resources/services/rds/cluster_parameter_groups.go, plugins/source/aws/resources/services/rds/cluster_snapshots.go, plugins/source/aws/resources/services/rds/clusters.go, plugins/source/aws/resources/services/rds/db_parameter_groups.go, plugins/source/aws/resources/services/rds/db_proxies.go, plugins/source/aws/resources/services/rds/db_security_groups.go, plugins/source/aws/resources/services/rds/db_snapshots.go, plugins/source/aws/resources/services/rds/event_subscriptions.go, plugins/source/aws/resources/services/rds/fetch_rds_tags.go, plugins/source/aws/resources/services/rds/instances.go, plugins/source/aws/resources/services/rds/mock_test.go, plugins/source/aws/resources/services/rds/option_groups.go, plugins/source/aws/resources/services/rds/option_groups_mock_test.go, plugins/source/aws/resources/services/rds/reserved_instances.go, plugins/source/aws/resources/services/rds/subnet_groups.go
Add support for resolving tags for AWS RDS DBSubnetGroup and OptionGroup
=> feat: Add support for resolving tags for AWS RDS DBSubnetGroup and OptionGroup

plugins/destination/snowflake/client/client.go
Fail on Init with incorrect credentials
=> feat: Fail on Init with incorrect credentials

.release-please-manifest.json, plugins/source/bitbucket/CHANGELOG.md
Reverts cloudquery/cloudquery#17340
Need to do this again since the publish failed
=> chore: Revert "chore(main): Release plugins-source-bitbucket v1.2.0"

website/pages/docs/deployment/docker.mdx
Update Docker docs to reflect login requirement
=> fix: Update Docker docs to reflect login requirement

website/pages/docs/deployment/github-actions.md
Fixes https://github.com/cloudquery/cloudquery/issues/17420
=> chore: Add API key to GitHub Actions deployment

website/pages/docs/deployment/kestra.mdx
Fixes https://github.com/cloudquery/cloudquery/issues/17424
=> chore: Add API Key docs to Kestra

website/pages/docs/deployment/kubernetes.mdx
Fixes https://github.com/cloudquery/cloudquery/issues/17423
=> chore: Add API Key docs to k8s deployment

website/pages/docs/deployment/google-cloud-vm.mdx
Fixes https://github.com/cloudquery/cloudquery/issues/17422
=> chore: Add API Key docs to Google VM deployment

website/pages/docs/deployment/docker.mdx
=> doc: Update docker example to remove typo

website/pages/docs/deployment/docker.mdx
Fixes https://github.com/cloudquery/cloudquery/issues/17531#issuecomment-2041030361
=> chore: Fix docker pull argument in deployment guides

cli/cmd/plugin_docs_upload.go, website/pages/docs/advanced-topics/monitoring.md, website/pages/docs/reference/destination-spec.md, website/pages/docs/reference/source-spec.md
=> chore: Fix some typos in comments

plugins/source/awspricing/docs/overview.md
Update Connection information for AWS Pricing
=> fix: Update Connection information for AWS Pricing

cli/cmd/addon_download_test.go, cli/cmd/tables.go, cli/cmd/tables_test.go, cli/cmd/tables_v3.go, cli/cmd/testdata/cloudflare-tables-with-spec-filter.yml, website/pages/docs/reference/cli/cloudquery_tables.md
Instead of https://github.com/cloudquery/cloudquery/pull/17551
=> feat: Add filter flag to tables command

cli/cmd/addon_download_test.go
Fixes https://github.com/cloudquery/cloudquery/issues/17585 ~~(hopefully)~~.
Not sure how this works for concurrent tests. If they in separate processes probably ok, but in separate Go routines probably not
=> test: Don't override test stdout

plugins/source/airtable/docs/overview.md, plugins/source/bitbucket/docs/overview.md, plugins/source/square/docs/overview.md, plugins/source/typeform/docs/overview.md
So it's easier to discover the guide when working with the plugins. At some point it might make sense to have this built-in in the Hub but not urgent
=> feat: Add reference to running in a Containerized Environment doc

cli/internal/auth/team.go
Follow up to https://github.com/cloudquery/cloudquery/pull/17580.
We should check the status code otherwise we would panic
=> fix: Don't panic on invalid API key

plugins/destination/sqlite/.goreleaser.yaml, plugins/destination/sqlite/main.go
Closes https://github.com/cloudquery/cloudquery/issues/13878
=> feat: Publish `linux/arm64` build

plugins/destination/elasticsearch/client/schema.json, plugins/destination/elasticsearch/client/spec.go, plugins/destination/elasticsearch/docs/overview.md
Closes https://github.com/cloudquery/cloudquery/issues/14932
=> doc: Document `cloud_id` being mutually exclusive with `addresses`

plugins/destination/sqlite/main.go
Partial revertion of https://github.com/cloudquery/cloudquery/pull/17673
=> fix: Re-enable CGO in build

plugins/destination/sqlite/main.go
Until we can figure out why it's failing https://github.com/cloudquery/cloudquery/actions/runs/8742512711/job/23990955224#step:11:112
=> chore: Disable building linux arm64

plugins/destination/sqlite/gencc.sh, plugins/destination/sqlite/gencpp.sh, plugins/destination/sqlite/main.go
Fixes https://github.com/cloudquery/cloudquery/issues/13878
=> fix: Add proper `linux/arm64` value for compilation

release-please-config.json
Move some plugins to be published from the private repository
=> chore: Move some plugins to publish from the private repo

cli/cmd/addon_download.go, website/pages/docs/reference/cli/cloudquery_addon_download.md
Fixes https://github.com/cloudquery/cloudquery/issues/17772
=> feat: Updating addon_download cli cmd docs

website/components/Footer.tsx
Follow up to https://github.com/cloudquery/cloudquery/pull/17784
=> chore: Use direct links to private and terms

.github/styles/config/vocabularies/Base/accept.txt, plugins/destination/kafka/client/spec/schema.json, plugins/destination/kafka/client/spec/schema_test.go, plugins/destination/kafka/client/spec/spec.go, plugins/destination/kafka/client/write.go, plugins/destination/kafka/docs/overview.md
This PR adds supports for overwriting the topic details via spec config options
=> feat: Expose Kafka Topic Details in spec

plugins/destination/kafka/client/spec/schema.json, plugins/destination/kafka/client/spec/spec.go, plugins/destination/kafka/docs/_configuration.md, plugins/destination/kafka/docs/overview.md
Follow-up for https://github.com/cloudquery/cloudquery/pull/17910
=> chore: Add default

website/pages/docs/deployment/overview.md
Removes links to archived projects that are no longer supported
=> doc: Update deployment overview

plugins/source/bitbucket/docs/_configuration.md, plugins/source/bitbucket/docs/overview.md
Fixes https://github.com/cloudquery/cloudquery/issues/18162
=> fix: Update BitBucket configuration

plugins/destination/kafka/client/spec/spec.go, plugins/destination/kafka/client/write.go
int64 from https://github.com/cloudquery/cloudquery/pull/18338
=> fix: Properly handle multiple rows in a record

cli/cmd/root.go, cli/internal/analytics/client.go
These events burn through our quota and we don't need the data yet
=> fix: Remove tracking of start and end of each command

cli/internal/analytics/client.go
In order to fix the issue described here: https://github.com/cloudquery/cloudquery-issues/issues/1911#issuecomment-2191820570
I'm caching the event details in a global variable except on `LoginSuccess` as suggested by @erezrokah.
Testing:
Successful sync
Cmd+C during sync
=> fix: Cache sync event details to track Cmd+C.

cli/internal/publish/images/images.go
> max-control-nesting: control flow nesting exceeds 5 (revive)
=> chore: Fix linter issue with image parser

.github/workflows/publish_plugin_to_hub.yml, .github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml
Part of https://github.com/cloudquery/cloudquery-issues/issues/1864 (internal issue)
=> chore: Update publish workflows to include `cloud-config-ui`

plugins/source/k8s/resources/plugin/plugin.go
Follow up to https://github.com/cloudquery/cloudquery/pull/18510#discussion_r1672127784
=> chore: Split scheduler options to multiple lines

cli/cmd/sync.go, website/pages/docs/reference/cli/cloudquery_sync.md
Small clarification to the command
=> fix: Improve `--tables-metrics-location` reference docs

website/pages/docs/advanced-topics/performance-tuning.mdx
Follow up to https://github.com/cloudquery/cloudquery/pull/18701
=> chore: Update performance-tuning.mdx

contributing/adding_a_new_plugin_to_cq_monorepo.md
GCP plugin is now private so the link was broken
=> chore: Update adding_a_new_plugin_to_cq_monorepo.md

.github/workflows/publish_plugin_to_hub.yml
=> chore: Update CI for Config UI

cli/.golangci.yml, plugins/.golangci.yml, plugins/destination/clickhouse/typeconv/arrow/values/unwrap.go
=> chore: Add more govet lint rules

plugins/destination/azblob/docs/_configuration.md, plugins/destination/azblob/docs/overview.md, plugins/destination/file/docs/_configuration.md, plugins/destination/file/docs/overview.md, plugins/destination/gcs/docs/_configuration.md, plugins/destination/gcs/docs/overview.md, plugins/destination/kafka/docs/_configuration.md, plugins/destination/kafka/docs/overview.md, plugins/destination/s3/docs/_configuration.md, plugins/destination/s3/docs/overview.md
Fixes https://github.com/cloudquery/cloudquery-issues/issues/2106.
Documents the new Parquet options added via https://github.com/cloudquery/cloudquery/pull/18917 and https://github.com/cloudquery/filetypes/pull/567
=> feat: Document new parquet options

website/pages/docs/billing-and-usage/overview.md
I updated the CloudQuery documentation to include information about purchasing CloudQuery through the AWS marketplace. 
I also made some minor updates to grammar and copy to improve clarity.
=> chore: Update Billing and Usage docs with AWS Marketplace info

website/pages/docs/advanced-topics/_meta.json, website/pages/docs/advanced-topics/monitoring/_meta.json, website/pages/docs/advanced-topics/monitoring/otel-datadog.md, website/pages/docs/advanced-topics/monitoring/overview.md, website/vercel.json
This PR organizes our monitoring docs a bit so it's easier to add a separate section on Prometheus and Grafana.
=> chore: Organize monitoring docs

.github/workflows/publish_ui_dir.yml
Similar to https://github.com/cloudquery/cloudquery-private/pull/4051
=> chore: Add UI changes publishing workflow

website/public/assets/datadog-dashboard.json
Found this while working on https://github.com/cloudquery/cloudquery/pull/18971
=> chore: Fix Datadog dashboard p95 formula

plugins/destination/mysql/client/client.go, plugins/destination/mysql/client/test_connection.go, plugins/destination/mysql/client/test_connection_test.go
~Still not great, but a small improvement to get more error codes out.~ I think this should cover most cases now.
=> fix: Better test connection error codes

plugins/destination/mysql/client/client.go
Follow-up to https://github.com/cloudquery/cloudquery/pull/18985
After preparing https://github.com/cloudquery/cloudquery-issues/issues/2326 (internal issue) I noticed some of the error codes are unnecessary, this PR cleans them up a little.
`chore` because the previous update isn't released yet.
=> chore: Clean up MySQL init error codes

.github/renovate.json5
Make UI updates a `chore:` and groups the updates into a single PR. Similar to this internal PR https://github.com/cloudquery/cloudquery-private/pull/4107 (if the duplication starts bothering us I might create another shared config in https://github.com/cloudquery/.github/tree/main/.github)
=> chore: Make UI updates a `chore:`

plugins/destination/mysql/cloud-config-ui/package-lock.json, plugins/destination/mysql/cloud-config-ui/package.json, plugins/destination/mysql/cloud-config-ui/src/form/index.tsx, plugins/destination/postgresql/cloud-config-ui/package-lock.json, plugins/destination/postgresql/cloud-config-ui/package.json, plugins/destination/postgresql/cloud-config-ui/src/form/index.tsx, plugins/source/hackernews/cloud-config-ui/package-lock.json, plugins/source/hackernews/cloud-config-ui/package.json, plugins/source/hackernews/cloud-config-ui/src/form/index.tsx, plugins/source/xkcd/cloud-config-ui/package-lock.json, plugins/source/xkcd/cloud-config-ui/package.json, plugins/source/xkcd/cloud-config-ui/src/form/index.tsx
=> chore: UI FormWrapper

plugins/source/hackernews/cloud-config-ui/package-lock.json, plugins/source/hackernews/cloud-config-ui/package.json, plugins/source/xkcd/cloud-config-ui/package-lock.json, plugins/source/xkcd/cloud-config-ui/package.json
=> chore: XKCD & Hacker News tables

plugins/source/hackernews/cloud-config-ui/src/utils/formSchema.ts
=> chore: Hacker News state props update

website/components/mdx/_configure.mdx
This guide is going to be revamped soon but until we do it this PR fixes one 404 link and another outdated one
=> chore: Update links in quick start guide

website/components/mdx/_configure.mdx
Follow up to https://github.com/cloudquery/cloudquery/pull/19111. Probably good to have some next steps/action items at the end of the guide.
Feedback welcomed
=> fix: Add next steps to quick start guide

plugins/destination/test/client/client.go, plugins/destination/test/client/schema.json, plugins/destination/test/client/spec.go, plugins/destination/test/go.mod, plugins/destination/test/go.sum
Adds `error_on_migrate`, `error_on_insert`, `batch_writer` and batch writer options.
=> feat: Add batching and more error options to test destination

.github/workflows/publish_plugin_to_hub_duckdb.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml
The checkout step was missing from https://github.com/cloudquery/cloudquery/pull/18537 so the GitHub action script failed to list the files in the plugin's directory https://github.com/cloudquery/cloudquery/actions/runs/10924144967/job/30329954149
=> chore: Add missing checkout steps

.release-please-manifest.json, plugins/destination/snowflake/CHANGELOG.md
Reverts cloudquery/cloudquery#19177 so we can re-do the release
=> chore: Revert "chore(main): Release plugins-destination-snowflake v4.3.0"

plugins/source/hackernews/resources/plugin/client.go, plugins/source/test/resources/plugin/client.go, plugins/source/xkcd/resources/plugin/client.go
Follow up to https://github.com/cloudquery/plugin-sdk/pull/1891
=> feat: Add sharding support

website/pages/docs/reference/source-spec.md
=> chore: Improve documentation for `tables` in source spec

scripts/workflows/wait_for_required_workflows.js
Similar to this https://github.com/cloudquery/cloudquery-private/pull/4714 internal PR to allow skipped workflows
=> chore: Allow skipped workflows

scripts/workflows/wait_for_required_workflows.js
Woops, erased this line by mistake in https://github.com/cloudquery/cloudquery/pull/19273/files
=> chore: Update wait_for_required_workflows.js

.github/workflows/broken_links_scheduled.yml
Follow up to https://github.com/cloudquery/cloudquery/pull/19281
=> chore: Update broken_links_scheduled.yml

website/pages/docs/index.mdx
Fixes https://github.com/cloudquery/cloudquery/actions/runs/11179640686/job/31079706889
We should use relative links where possible to avoid them opening in a new page/redirecting.
This PR also updates `https://www.cloudquery.io/how-to-guides/attack-surface-management-with-graph` to as `https://www.cloudquery.io/how-to-guides/attack-surface-management-with-graph` redirects to `https://www.cloudquery.io/blog/attack-surface-management-with-graph` anyways
Follow up to https://github.com/cloudquery/cloudquery/pull/19281
=> fix: Use relative links instead of absolute ones

plugins/destination/s3/cloud-config-ui/package-lock.json, plugins/destination/s3/cloud-config-ui/package.json, plugins/destination/s3/cloud-config-ui/src/hooks/useConfig.tsx, plugins/destination/s3/cloud-config-ui/src/utils/authSubmitGuard.ts
=> chore: S3 plugin UI prevent reauthentication of connector

.github/pr_labeler.yml, plugins/destination/test/client/client.go, plugins/destination/test/main.go, plugins/source/test/resources/plugin/client.go, plugins/source/test/resources/plugin/plugin.go
Should help with https://github.com/cloudquery/cloudquery/pull/19349
=> feat: Add test connection handling

cli/cmd/sync.go
If someone uses the `--tables-metrics-location` flag with `otel_endpoint` the flag silenlty doesn't work at the moment.
This PR changes it so it reports and error, at least until we support both https://github.com/cloudquery/cloudquery-issues/issues/2455 (internal issue)
=> fix: Fail if both `--table-metrics-location` and `otel_endpoint` are configured

website/pages/docs/glossary/what-is-infrastructure-data-lake.mdx
PR head links to several blog posts that no longer exist in their location, and while I was in there, I also updated some language to be more active and direct.
=> chore(main): Update what-is-infrastructure-data-lake.mdx

cli/cmd/summary.go, cli/cmd/sync_test.go, cli/cmd/sync_v3.go, cli/cmd/tables_v3.go, cli/cmd/testdata/with-destination-summary-with-sync-group-id-and-shard.yml, cli/cmd/testdata/with-sync-group-id.yml
Fixes https://github.com/cloudquery/cloudquery-issues/issues/2590
=> feat: Add source tables, sync group ID, shard to sync summary

plugins/transformer/jsonflattener/docs/overview.md
=> chore: Show latest Postgres version in docs

.github/workflows/publish_plugin_to_hub_fips.yml, plugins/source/test/README.md
Forgot the actual publishing part in https://github.com/cloudquery/cloudquery/pull/19676, everything else worked https://github.com/cloudquery/cloudquery/actions/runs/12014258222/job/33489640405
Did an invisible change to the readme to trigger a new release
=> fix: Update readme

plugins/source/typeform/docs/overview.md
Adding a deprecation message to Typeform plugin. See https://github.com/cloudquery/cloudquery-issues/issues/2812
=> chore: Add a deprecation message to typeform plugin

.github/workflows/cli.yml, .github/workflows/release_cli.yml, cli/Makefile, cli/docs/reference/cloudquery.md, cli/docs/reference/cloudquery_addon.md, cli/docs/reference/cloudquery_addon_download.md, cli/docs/reference/cloudquery_addon_publish.md, cli/docs/reference/cloudquery_init.md, cli/docs/reference/cloudquery_login.md, cli/docs/reference/cloudquery_logout.md, cli/docs/reference/cloudquery_migrate.md, cli/docs/reference/cloudquery_plugin.md, cli/docs/reference/cloudquery_plugin_install.md, cli/docs/reference/cloudquery_plugin_publish.md, cli/docs/reference/cloudquery_switch.md, cli/docs/reference/cloudquery_sync.md, cli/docs/reference/cloudquery_tables.md, cli/docs/reference/cloudquery_test-connection.md, cli/docs/reference/cloudquery_validate-config.md
Needed because of https://github.com/cloudquery/cloudquery/pull/19697
=> chore: Fix CLI docs generation

.github/workflows/release_scaffold.yml, scaffold/.goreleaser.prerelease.yaml, scaffold/cmd/source.go, scaffold/go.mod, scaffold/main.go
Same as https://github.com/cloudquery/cloudquery/pull/19806 and https://github.com/cloudquery/cloudquery/pull/19805 for the Scaffold tool
=> fix: Correct major version in `go.mod`

plugins/destination/clickhouse/cloud-config-ui/src/utils/prepareSubmitValues.ts
Fixes https://github.com/cloudquery/cloudquery/security/code-scanning/8
=> chore: Remove connection fields logging

plugins/destination/postgresql/pgarrow/to_arrow.go
Fixes https://github.com/cloudquery/cloudquery/security/code-scanning/7
Fixes https://github.com/cloudquery/cloudquery/security/code-scanning/6
=> fix: Correctly handle integer conversion

plugins/destination/kafka/client/client.go, plugins/destination/kafka/client/spec/schema.json, plugins/destination/kafka/client/spec/spec.go, plugins/destination/kafka/docs/overview.md
Fixes https://github.com/cloudquery/cloudquery/security/code-scanning/1.
Couldn't think of a better way to handle that issue
=> feat: Allow to enforce TLS verification

plugins/source/test/go.mod, plugins/source/test/go.sum
Upgrades the test source plugin to use SDK improvement.
=> fix: Upgrade the test source plugin to use SDK improvement.

plugins/destination/s3/client/client.go, plugins/destination/s3/client/spec/schema.json, plugins/destination/s3/client/spec/spec.go, plugins/destination/s3/docs/_authentication.md, plugins/destination/s3/docs/overview.md
closes https://github.com/cloudquery/cloudquery-issues/issues/2465
=> feat: Add possibility to set local profile to use in S3 Destination spec

.github/workflows/release_cli.yml, .github/workflows/release_scaffold.yml
Fixes https://github.com/cloudquery/cloudquery/actions/runs/12276143711/job/34252716519#step:16:7 and https://github.com/cloudquery/cloudquery/actions/runs/12275531988/job/34250776017#step:13:7 since the directory structure had changed in the Frontend repo
=> chore: Update versions update workflows

cli/cmd/sync_test.go, cli/cmd/testdata/multiple-destinations-multiple-batching-writers.yml
Adds multiple batch writers to E2E tests.
=> chore: Add multiple batch writers to E2E tests.

plugins/transformer/jsonflattener/client/schemaupdater/schema_updater.go
I think we want all columns to be snake case for consistency. Also helps with https://github.com/cloudquery/plugin-sdk/pull/2011
=> fix!: ToSnake flattened columns

cli/internal/api/client.go
`resp.JSON200 == nil` is covered in the next block
=> chore: Remove duplicated code

cli/.golangci.yml, cli/cmd/addon_download_test.go, cli/cmd/addon_publish_test.go, cli/cmd/init_test.go, cli/cmd/plugin_publish_test.go, cli/cmd/switch_test.go, cli/internal/publish/plugins.go, plugins/.golangci.yml, plugins/destination/mongodb/client/uint64.go, scripts/lint.sh
This should fix the lint errors seen on https://github.com/cloudquery/cloudquery/pull/20243 and on other PRs
=> chore: Fix Go linting

plugins/destination/firehose/client/client.go, plugins/destination/firehose/client/test_connection.go, plugins/destination/firehose/client/test_connection_test.go, plugins/destination/firehose/main.go
=> feat: Add connection test to AWS Firehose destination

.github/workflows/deps_trigger_gen.yml
This PR replaces another changed files actions we were using (https://github.com/Ana06/get-changed-files)
=> chore: Replace another changed files action

plugins/destination/s3/client/client.go, plugins/destination/s3/client/spec/schema.json, plugins/destination/s3/client/spec/spec.go, plugins/destination/s3/client/spec/spec_test.go, plugins/destination/s3/client/write.go, plugins/destination/s3/docs/_configuration.md
This PR aligns configuration options to reflect options avilable for s3 source plugin.
=> feat: Allow configuring retries and multipart body size

.github/renovate.json5
So we can get the update PRs for versions below 2.1.0 including
=> chore: Allow DuckDB upgrades

.github/workflows/dest_kafka.yml, cli/cmd/sync_v3.go, plugins/destination/kafka/client/client.go, plugins/destination/kafka/client/spec/schema.json, plugins/destination/kafka/client/spec/spec.go
=> fix: SSL Config

plugins/transformer/basic/docs/overview.md
=> doc: Document obfuscating JSON arrays behaviour

cli/cmd/login.go
Adds post login step guide to the CLI
=> feat: Add post login steps in the CLI

.github/workflows/publish_plugin_to_hub_duckdb.yml
=> chore: Change publish image for duckdb

.github/renovate.json5, .github/workflows/publish_plugin_to_hub_fips.yml, .github/workflows/publish_plugin_to_hub_snowflake.yml, .github/workflows/publish_plugin_to_hub_sqlite.yml, .github/workflows/source_test.yml
This PR replaces cq golang-cross image with maintained version.
=> chore: Replace all golang-cross images with maintained version

cli/cmd/sync_v3.go
Should fix the data race in https://github.com/cloudquery/cloudquery/pull/21116. Instead of using the `Done()` channel we can call the debounced function one last time.
The data race is a known issue in the package, see https://github.com/vnteamopen/godebouncer/pull/28
=> fix: Data race when reporting progress

plugins/destination/mysql/client/migrate.go
Similar to https://github.com/cloudquery/cloudquery/pull/21165
=> feat: Better summary of schema changes

release-please-config.json
Reverts cloudquery/cloudquery#20138
=> chore: Bring back Airtable plugin

cli/cmd/data/tables_queries.yml, cli/cmd/sync_v3.go
This PR moves the CLI example queries to a YAML so it's easier to add new tables, destinations and queries cc @pilvikala
=> chore: Move example queries to YAML file

cli/cmd/data/tables_queries.yml, cli/cmd/sync_v3.go
Adding more example queries to display after the first sync.
These are based on the most popular tables synced by new users.
=> feat: Adding more example queries

plugins/destination/snowflake/client/types.go
Follow-up to https://github.com/cloudquery/cloudquery/pull/21277
=> fix: Use Decimal128 for NUMBER(38,0)

plugins/destination/bigquery/client/migrate.go, plugins/destination/bigquery/client/schema.json, plugins/destination/bigquery/client/spec.go, plugins/destination/bigquery/docs/_configuration.md
These can be useful when using expiration intervals introduced in https://github.com/cloudquery/cloudquery/pull/21391
=> feat: Add monthly/yearly partitioning
